# 03 — In Season Feature Engineering

This notebook creates the weekly performance features used by the in season projection layer.

It does not modify the original preseason notebooks or their outputs.

The purpose of this notebook is to convert completed regular season games into team level offensive and defensive performance features that can later be blended with the frozen preseason model.

For a selected target week, the notebook:

- Loads only completed games from weeks before the target week
- Builds team level scoring and margin summaries
- Separates offense and defense
- Adds simple opponent adjusted performance features
- Applies early season shrinkage to reduce overreaction to small samples
- Saves a clean feature table for the weekly team strength notebook

This notebook is intentionally conservative after Week 1. One game should inform the model, not redefine it.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the outputs created by:

`02_Weekly_Data_Update.ipynb`

The only value that normally changes week to week is `TARGET_WEEK`.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 4
PRIOR_WEEK = TARGET_WEEK - 1

completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

prior_strength_path = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

print("Using completed games:", completed_games_path)
print("Using entering ratings:", prior_strength_path)

Using completed games: ..\..\data\processed\weekly\week_04_completed_games.parquet
Using entering ratings: ..\..\data\processed\weekly\week_03_sequential_team_strength.parquet

# Load Completed Games

Only games completed before the target week should exist in this file.

That leakage rule was enforced in `02_Weekly_Data_Update.ipynb`.

In [3]:
completed_games = pd.read_parquet(
    completed_games_path
)

completed_games = completed_games.sort_values(
    ["week", "gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Completed games available before Week {TARGET_WEEK}:",
    len(completed_games)
)

display(
    completed_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Completed games available before Week 4: 48

    week     gameday away_team  away_score home_team  home_score
0      1  2026-09-09        NE        10.0       SEA        13.0
1      1  2026-09-10        SF        27.0        LA         7.0
2      1  2026-09-13       ARI        26.0       LAC        14.0
3      1  2026-09-13       ATL        13.0       PIT        20.0
4      1  2026-09-13       BAL        41.0       IND        23.0
5      1  2026-09-13       BUF        36.0       HOU        31.0
6      1  2026-09-13       CHI        59.0       CAR        37.0
7      1  2026-09-13       CLE        10.0       JAX        34.0
8      1  2026-09-13       DAL        20.0       NYG        28.0
9      1  2026-09-13        GB        22.0       MIN        39.0
10     1  2026-09-13       MIA        13.0        LV        27.0
11     1  2026-09-13        NO        30.0       DET        31.0
12     1  2026-09-13       NYJ        23.0       TEN        10.0
13     1  2026-09-13        TB        27.0       CIN        33.0
14     1  2026-09-13       WAS        22.0       PHI        24.0
15     1  2026-09-14       DEN        10.0        KC        31.0
16     2  2026-09-17       DET        31.0       BUF        41.0
17     2  2026-09-20       CAR        34.0       ATL         3.0
18     2  2026-09-20       CIN        20.0       HOU         6.0
19     2  2026-09-20       CLE        23.0        TB        19.0
20     2  2026-09-20        GB        20.0       NYJ        17.0
21     2  2026-09-20       IND        30.0        KC        33.0
22     2  2026-09-20       JAX        13.0       DEN        20.0
23     2  2026-09-20        LV        26.0       LAC        14.0
24     2  2026-09-20       MIA        13.0        SF        35.0
25     2  2026-09-20       MIN         9.0       CHI         3.0
26     2  2026-09-20        NO        24.0       BAL        17.0
27     2  2026-09-20       PHI        24.0       TEN        20.0
28     2  2026-09-20       PIT         3.0        NE        20.0
29     2  2026-09-20       SEA        31.0       ARI         7.0
30     2  2026-09-20       WAS        20.0       DAL        37.0
31     2  2026-09-21       NYG         6.0        LA        28.0
32     3  2026-09-24       ATL        35.0        GB        14.0
33     3  2026-09-27       ARI        30.0        SF        36.0
34     3  2026-09-27       BAL        34.0       DAL        31.0
35     3  2026-09-27       CAR        18.0       CLE        21.0
36     3  2026-09-27       CIN        27.0       PIT        30.0
37     3  2026-09-27       HOU        17.0       IND        19.0
38     3  2026-09-27        KC        24.0       MIA        10.0
39     3  2026-09-27       LAC        16.0       BUF        24.0
40     3  2026-09-27        LA        26.0       DEN        30.0
41     3  2026-09-27        LV        35.0        NO        27.0
42     3  2026-09-27       MIN        23.0        TB        16.0
43     3  2026-09-27        NE         6.0       JAX        35.0
44     3  2026-09-27       NYJ        24.0       DET        31.0
45     3  2026-09-27       SEA        31.0       WAS        33.0
46     3  2026-09-27       TEN         7.0       NYG        12.0
47     3  2026-09-28       PHI         7.0       CHI        27.0

In [4]:
update_games = completed_games[
    completed_games["week"] == PRIOR_WEEK
].copy()

update_games = update_games.sort_values(
    ["gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Week {PRIOR_WEEK} games used to update "
    f"Week {TARGET_WEEK} ratings:",
    len(update_games)
)

display(
    update_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Week 3 games used to update Week 4 ratings: 16

    week     gameday away_team  away_score home_team  home_score
0      3  2026-09-24       ATL        35.0        GB        14.0
1      3  2026-09-27       ARI        30.0        SF        36.0
2      3  2026-09-27       BAL        34.0       DAL        31.0
3      3  2026-09-27       CAR        18.0       CLE        21.0
4      3  2026-09-27       CIN        27.0       PIT        30.0
5      3  2026-09-27       HOU        17.0       IND        19.0
6      3  2026-09-27        KC        24.0       MIA        10.0
7      3  2026-09-27       LAC        16.0       BUF        24.0
8      3  2026-09-27        LA        26.0       DEN        30.0
9      3  2026-09-27        LV        35.0        NO        27.0
10     3  2026-09-27       MIN        23.0        TB        16.0
11     3  2026-09-27        NE         6.0       JAX        35.0
12     3  2026-09-27       NYJ        24.0       DET        31.0
13     3  2026-09-27       SEA        31.0       WAS        33.0
14     3  2026-09-27       TEN         7.0       NYG        12.0
15     3  2026-09-28       PHI         7.0       CHI        27.0

# Convert Prior Week Games to Team Game Rows

Only the most recently completed week is used for the new weekly update.

For Week 3:

- Week 2 team strength is the entering prior
- Week 2 game performance is the new evidence
- Week 1 is not counted again because it is already reflected in the Week 2 ratings

Each game becomes two rows:

- one from the home team's perspective
- one from the away team's perspective

In [5]:
home_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["home_team"],
        "opponent": update_games["away_team"],
        "is_home": 1,
        "points_for": update_games["home_score"],
        "points_against": update_games["away_score"]
    }
)

away_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["away_team"],
        "opponent": update_games["home_team"],
        "is_home": 0,
        "points_for": update_games["away_score"],
        "points_against": update_games["home_score"]
    }
)

team_games = pd.concat(
    [home_rows, away_rows],
    ignore_index=True
)

team_games["point_margin"] = (
    team_games["points_for"]
    - team_games["points_against"]
)

team_games = team_games.sort_values(
    ["team", "game_id"]
).reset_index(drop=True)

print("Team-game rows:", len(team_games))

display(team_games)

Team-game rows: 32

,game_id,week,team,opponent,is_home,points_for,points_against,point_margin
0,2026_03_ARI_SF,3,ARI,SF,0,30.0,36.0,-6.0
1,2026_03_ATL_GB,3,ATL,GB,0,35.0,14.0,21.0
2,2026_03_BAL_DAL,3,BAL,DAL,0,34.0,31.0,3.0
3,2026_03_LAC_BUF,3,BUF,LAC,1,24.0,16.0,8.0
4,2026_03_CAR_CLE,3,CAR,CLE,0,18.0,21.0,-3.0
5,2026_03_PHI_CHI,3,CHI,PHI,1,27.0,7.0,20.0
6,2026_03_CIN_PIT,3,CIN,PIT,0,27.0,30.0,-3.0
7,2026_03_CAR_CLE,3,CLE,CAR,1,21.0,18.0,3.0
8,2026_03_BAL_DAL,3,DAL,BAL,1,31.0,34.0,-3.0
9,2026_03_LA_DEN,3,DEN,LA,1,30.0,26.0,4.0
10,2026_03_NYJ_DET,3,DET,NYJ,1,31.0,24.0,7.0
11,2026_03_ATL_GB,3,GB,ATL,1,14.0,35.0,-21.0
12,2026_03_HOU_IND,3,HOU,IND,0,17.0,19.0,-2.0
13,2026_03_HOU_IND,3,IND,HOU,1,19.0,17.0,2.0
14,2026_03_NE_JAX,3,JAX,NE,1,35.0,6.0,29.0
15,2026_03_KC_MIA,3,KC,MIA,0,24.0,10.0,14.0
16,2026_03_LA_DEN,3,LA,DEN,0,26.0,30.0,-4.0
17,2026_03_LAC_BUF,3,LAC,BUF,0,16.0,24.0,-8.0
18,2026_03_LV_NO,3,LV,NO,0,35.0,27.0,8.0
19,2026_03_KC_MIA,3,MIA,KC,1,10.0,24.0,-14.0
20,2026_03_MIN_TB,3,MIN,TB,0,23.0,16.0,7.0
21,2026_03_NE_JAX,3,NE,JAX,0,6.0,35.0,-29.0
22,2026_03_LV_NO,3,NO,LV,1,27.0,35.0,-8.0
23,2026_03_TEN_NYG,3,NYG,TEN,1,12.0,7.0,5.0
24,2026_03_NYJ_DET,3,NYJ,DET,0,24.0,31.0,-7.0
25,2026_03_PHI_CHI,3,PHI,CHI,0,7.0,27.0,-20.0
26,2026_03_CIN_PIT,3,PIT,CIN,1,30.0,27.0,3.0
27,2026_03_SEA_WAS,3,SEA,WAS,0,31.0,33.0,-2.0
28,2026_03_ARI_SF,3,SF,ARI,1,36.0,30.0,6.0
29,2026_03_MIN_TB,3,TB,MIN,1,16.0,23.0,-7.0
30,2026_03_TEN_NYG,3,TEN,NYG,0,7.0,12.0,-5.0
31,2026_03_SEA_WAS,3,WAS,SEA,1,33.0,31.0,2.0

# Attach Entering Team and Opponent Strength

Each team's performance is evaluated relative to what the model believed before the game was played.

For Week 3 projections, Week 2 ratings represent the information available entering Week 2.

This prevents the opponent adjustment from using future information or the same results that are currently being evaluated.

In [6]:
prior_strength = pd.read_parquet(
    prior_strength_path
).copy()

required_prior_columns = [
    "team",
    "weekly_team_strength",
    "weekly_strength_rank"
]

missing_prior_columns = [
    col
    for col in required_prior_columns
    if col not in prior_strength.columns
]

if missing_prior_columns:
    raise KeyError(
        "Missing prior-week strength columns: "
        + ", ".join(missing_prior_columns)
    )

prior_strength = prior_strength[
    required_prior_columns
].rename(
    columns={
        "weekly_team_strength": "entering_team_strength",
        "weekly_strength_rank": "entering_strength_rank"
    }
)

print(
    f"Week {PRIOR_WEEK} entering ratings loaded:",
    len(prior_strength)
)

display(
    prior_strength.sort_values(
        "entering_strength_rank"
    )
)

Week 3 entering ratings loaded: 32

   team  entering_team_strength  entering_strength_rank
0   BUF                5.941307                       1
1   SEA                5.532084                       2
2    SF                4.807611                       3
3    LA                4.510074                       4
4   BAL                3.194678                       5
5    NE                3.153263                       6
6   DEN                2.823203                       7
7   DET                2.748511                       8
8   MIN                2.458757                       9
9    KC                2.458286                      10
10  JAX                2.328442                      11
11  PHI                1.582449                      12
12   GB                1.131145                      13
13  CIN                1.122452                      14
14  HOU                1.025111                      15
15  CHI                0.551141                      16
16   NO                0.223504                      17
17  DAL               -0.076385                      18
18  PIT               -0.215758                      19
19  IND               -0.520573                      20
20   TB               -0.961835                      21
21  LAC               -1.669265                      22
22  WAS               -2.745448                      23
23  ATL               -3.169388                      24
24   LV               -3.206077                      25
25  ARI               -3.679974                      26
26  NYG               -3.713683                      27
27  CAR               -4.369019                      28
28  CLE               -4.391506                      29
29  NYJ               -4.654697                      30
30  MIA               -4.705708                      31
31  TEN               -7.456672                      32

In [7]:
team_games = team_games.merge(
    prior_strength[
        [
            "team",
            "entering_team_strength",
            "entering_strength_rank"
        ]
    ],
    on="team",
    how="left",
    validate="many_to_one"
)

opponent_strength = prior_strength[
    [
        "team",
        "entering_team_strength",
        "entering_strength_rank"
    ]
].rename(
    columns={
        "team": "opponent",
        "entering_team_strength": "opponent_entering_strength",
        "entering_strength_rank": "opponent_entering_rank"
    }
)

team_games = team_games.merge(
    opponent_strength,
    on="opponent",
    how="left",
    validate="many_to_one"
)

display(
    team_games[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "opponent",
            "opponent_entering_rank",
            "opponent_entering_strength",
            "points_for",
            "points_against",
            "point_margin"
        ]
    ].sort_values(
        "entering_strength_rank"
    )
)

,team,entering_strength_rank,entering_team_strength,opponent,opponent_entering_rank,opponent_entering_strength,points_for,points_against,point_margin
3,BUF,1,5.941307,LAC,22,-1.669265,24.0,16.0,8.0
27,SEA,2,5.532084,WAS,23,-2.745448,31.0,33.0,-2.0
28,SF,3,4.807611,ARI,26,-3.679974,36.0,30.0,6.0
16,LA,4,4.510074,DEN,7,2.823203,26.0,30.0,-4.0
2,BAL,5,3.194678,DAL,18,-0.076385,34.0,31.0,3.0
21,NE,6,3.153263,JAX,11,2.328442,6.0,35.0,-29.0
9,DEN,7,2.823203,LA,4,4.510074,30.0,26.0,4.0
10,DET,8,2.748511,NYJ,30,-4.654697,31.0,24.0,7.0
20,MIN,9,2.458757,TB,21,-0.961835,23.0,16.0,7.0
15,KC,10,2.458286,MIA,31,-4.705708,24.0,10.0,14.0
14,JAX,11,2.328442,NE,6,3.153263,35.0,6.0,29.0
25,PHI,12,1.582449,CHI,16,0.551141,7.0,27.0,-20.0
11,GB,13,1.131145,ATL,24,-3.169388,14.0,35.0,-21.0
6,CIN,14,1.122452,PIT,19,-0.215758,27.0,30.0,-3.0
12,HOU,15,1.025111,IND,20,-0.520573,17.0,19.0,-2.0
5,CHI,16,0.551141,PHI,12,1.582449,27.0,7.0,20.0
22,NO,17,0.223504,LV,25,-3.206077,27.0,35.0,-8.0
8,DAL,18,-0.076385,BAL,5,3.194678,31.0,34.0,-3.0
26,PIT,19,-0.215758,CIN,14,1.122452,30.0,27.0,3.0
13,IND,20,-0.520573,HOU,15,1.025111,19.0,17.0,2.0
29,TB,21,-0.961835,MIN,9,2.458757,16.0,23.0,-7.0
17,LAC,22,-1.669265,BUF,1,5.941307,16.0,24.0,-8.0
31,WAS,23,-2.745448,SEA,2,5.532084,33.0,31.0,2.0
1,ATL,24,-3.169388,GB,13,1.131145,35.0,14.0,21.0
18,LV,25,-3.206077,NO,17,0.223504,35.0,27.0,8.0
0,ARI,26,-3.679974,SF,3,4.807611,30.0,36.0,-6.0
23,NYG,27,-3.713683,TEN,32,-7.456672,12.0,7.0,5.0
4,CAR,28,-4.369019,CLE,29,-4.391506,18.0,21.0,-3.0
7,CLE,29,-4.391506,CAR,28,-4.369019,21.0,18.0,3.0
24,NYJ,30,-4.654697,DET,8,2.748511,24.0,31.0,-7.0
19,MIA,31,-4.705708,KC,10,2.458286,10.0,24.0,-14.0
30,TEN,32,-7.456672,NYG,27,-3.713683,7.0,12.0,-5.0

# Expected Margin and Opponent-Adjusted Performance

The weekly update is based on how a team performed relative to expectation.

For each team game:

`performance residual = actual margin - expected margin`

Expected margin uses the difference between the two teams' entering strength ratings plus home field advantage.

This means beating a strong opponent is more informative than producing the same result against a weak opponent.

In [8]:
HOME_FIELD_POINTS = 1.5

team_games["expected_margin"] = (
    team_games["entering_team_strength"]
    - team_games["opponent_entering_strength"]
    + np.where(
        team_games["is_home"] == 1,
        HOME_FIELD_POINTS,
        -HOME_FIELD_POINTS
    )
)

team_games["performance_residual"] = (
    team_games["point_margin"]
    - team_games["expected_margin"]
)

display(
    team_games[
        [
            "team",
            "opponent",
            "entering_team_strength",
            "opponent_entering_strength",
            "point_margin",
            "expected_margin",
            "performance_residual"
        ]
    ].sort_values(
        "performance_residual",
        ascending=False
    )
)

,team,opponent,entering_team_strength,opponent_entering_strength,point_margin,expected_margin,performance_residual
14,JAX,NE,2.328442,3.153263,29.0,0.675179,28.324821
1,ATL,GB,-3.169388,1.131145,21.0,-5.800533,26.800533
5,CHI,PHI,0.551141,1.582449,20.0,0.468692,19.531308
18,LV,NO,-3.206077,0.223504,8.0,-4.929581,12.929581
31,WAS,SEA,-2.745448,5.532084,2.0,-6.777532,8.777532
15,KC,MIA,2.458286,-4.705708,14.0,5.663995,8.336005
20,MIN,TB,2.458757,-0.961835,7.0,1.920592,5.079408
9,DEN,LA,2.823203,4.510074,4.0,-0.186871,4.186871
0,ARI,SF,-3.679974,4.807611,-6.0,-9.987585,3.987585
26,PIT,CIN,-0.215758,1.122452,3.0,0.161790,2.838210
13,IND,HOU,-0.520573,1.025111,2.0,-0.045684,2.045684
24,NYJ,DET,-4.654697,2.748511,-7.0,-8.903207,1.903207
7,CLE,CAR,-4.391506,-4.369019,3.0,1.477513,1.522487
2,BAL,DAL,3.194678,-0.076385,3.0,1.771063,1.228937
17,LAC,BUF,-1.669265,5.941307,-8.0,-9.110572,1.110572
30,TEN,NYG,-7.456672,-3.713683,-5.0,-5.242989,0.242989
23,NYG,TEN,-3.713683,-7.456672,5.0,5.242989,-0.242989
3,BUF,LAC,5.941307,-1.669265,8.0,9.110572,-1.110572
8,DAL,BAL,-0.076385,3.194678,-3.0,-1.771063,-1.228937
4,CAR,CLE,-4.369019,-4.391506,-3.0,-1.477513,-1.522487
10,DET,NYJ,2.748511,-4.654697,7.0,8.903207,-1.903207
12,HOU,IND,1.025111,-0.520573,-2.0,0.045684,-2.045684
6,CIN,PIT,1.122452,-0.215758,-3.0,-0.161790,-2.838210
28,SF,ARI,4.807611,-3.679974,6.0,9.987585,-3.987585
16,LA,DEN,4.510074,2.823203,-4.0,0.186871,-4.186871
29,TB,MIN,-0.961835,2.458757,-7.0,-1.920592,-5.079408
19,MIA,KC,-4.705708,2.458286,-14.0,-5.663995,-8.336005
27,SEA,WAS,5.532084,-2.745448,-2.0,6.777532,-8.777532
22,NO,LV,0.223504,-3.206077,-8.0,4.929581,-12.929581
25,PHI,CHI,1.582449,0.551141,-20.0,-0.468692,-19.531308
11,GB,ATL,1.131145,-3.169388,-21.0,5.800533,-26.800533
21,NE,JAX,3.153263,2.328442,-29.0,-0.675179,-28.324821

# Control Extreme Single-Game Results

NFL game margins contain substantial single-game noise.

A blowout should affect team strength, but one extreme result should not completely redefine the team's rating.

Performance residuals are therefore capped before the weekly learning rate is applied.

In [9]:
RESIDUAL_SCALE = 14.0
MAX_WEEKLY_UPDATE = 1.5

team_games["weekly_strength_update"] = (
    MAX_WEEKLY_UPDATE
    * np.tanh(
        team_games["performance_residual"]
        / RESIDUAL_SCALE
    )
)

display(
    team_games[
        [
            "team",
            "opponent",
            "point_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,opponent,point_margin,expected_margin,performance_residual,weekly_strength_update
14,JAX,NE,29.0,0.675179,28.324821,1.448446
1,ATL,GB,21.0,-5.800533,26.800533,1.436171
5,CHI,PHI,20.0,0.468692,19.531308,1.326430
18,LV,NO,8.0,-4.929581,12.929581,1.091353
31,WAS,SEA,2.0,-6.777532,8.777532,0.833940
15,KC,MIA,14.0,5.663995,8.336005,0.800683
20,MIN,TB,7.0,1.920592,5.079408,0.521537
9,DEN,LA,4.0,-0.186871,4.186871,0.435681
0,ARI,SF,-6.0,-9.987585,3.987585,0.416051
26,PIT,CIN,3.0,0.161790,2.838210,0.299995
13,IND,HOU,2.0,-0.045684,2.045684,0.217634
24,NYJ,DET,-7.0,-8.903207,1.903207,0.202668
7,CLE,CAR,3.0,1.477513,1.522487,0.162484
2,BAL,DAL,3.0,1.771063,1.228937,0.131335
17,LAC,BUF,-8.0,-9.110572,1.110572,0.118741
30,TEN,NYG,-5.0,-5.242989,0.242989,0.026032
23,NYG,TEN,5.0,5.242989,-0.242989,-0.026032
3,BUF,LAC,8.0,9.110572,-1.110572,-0.118741
8,DAL,BAL,-3.0,-1.771063,-1.228937,-0.131335
4,CAR,CLE,-3.0,-1.477513,-1.522487,-0.162484
10,DET,NYJ,7.0,8.903207,-1.903207,-0.202668
12,HOU,IND,-2.0,0.045684,-2.045684,-0.217634
6,CIN,PIT,-3.0,-0.161790,-2.838210,-0.299995
28,SF,ARI,6.0,9.987585,-3.987585,-0.416051
16,LA,DEN,-4.0,0.186871,-4.186871,-0.435681
29,TB,MIN,-7.0,-1.920592,-5.079408,-0.521537
19,MIA,KC,-14.0,-5.663995,-8.336005,-0.800683
27,SEA,WAS,-2.0,6.777532,-8.777532,-0.833940
22,NO,LV,-8.0,4.929581,-12.929581,-1.091353
25,PHI,CHI,-20.0,-0.468692,-19.531308,-1.326430
11,GB,ATL,-21.0,5.800533,-26.800533,-1.436171
21,NE,JAX,-29.0,-0.675179,-28.324821,-1.448446

# Offensive and Defensive Weekly Signals

Overall team strength uses the opponent adjusted margin residual.

We also preserve separate offensive and defensive signals because the weekly game projection model needs scoring information.

These are weekly updates, not cumulative season averages.

Opponent entering strength is used conservatively as context until separate entering offensive and defensive strength ratings are maintained.

In [10]:
league_points_per_team_game = (
    team_games["points_for"].mean()
)

OPPONENT_CONTEXT_RATE = 0.25
OFFENSE_DEFENSE_UPDATE_RATE = 0.15

team_games["raw_offense_performance"] = (
    team_games["points_for"]
    - league_points_per_team_game
)

team_games["raw_defense_performance"] = (
    league_points_per_team_game
    - team_games["points_against"]
)

team_games["adjusted_offense_performance"] = (
    team_games["raw_offense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["adjusted_defense_performance"] = (
    team_games["raw_defense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["weekly_offense_adjustment"] = (
    team_games["adjusted_offense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

team_games["weekly_defense_adjustment"] = (
    team_games["adjusted_defense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

display(
    team_games[
        [
            "team",
            "opponent",
            "points_for",
            "points_against",
            "opponent_entering_strength",
            "raw_offense_performance",
            "adjusted_offense_performance",
            "weekly_offense_adjustment",
            "raw_defense_performance",
            "adjusted_defense_performance",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "team"
    )
)

,team,opponent,points_for,points_against,opponent_entering_strength,raw_offense_performance,adjusted_offense_performance,weekly_offense_adjustment,raw_defense_performance,adjusted_defense_performance,weekly_defense_adjustment
0,ARI,SF,30.0,36.0,4.807611,6.375,7.576903,1.136535,-12.375,-11.173097,-1.675965
1,ATL,GB,35.0,14.0,1.131145,11.375,11.657786,1.748668,9.625,9.907786,1.486168
2,BAL,DAL,34.0,31.0,-0.076385,10.375,10.355904,1.553386,-7.375,-7.394096,-1.109114
3,BUF,LAC,24.0,16.0,-1.669265,0.375,-0.042316,-0.006347,7.625,7.207684,1.081153
4,CAR,CLE,18.0,21.0,-4.391506,-5.625,-6.722877,-1.008431,2.625,1.527123,0.229069
5,CHI,PHI,27.0,7.0,1.582449,3.375,3.770612,0.565592,16.625,17.020612,2.553092
6,CIN,PIT,27.0,30.0,-0.215758,3.375,3.321060,0.498159,-6.375,-6.428940,-0.964341
7,CLE,CAR,21.0,18.0,-4.369019,-2.625,-3.717255,-0.557588,5.625,4.532745,0.679912
8,DAL,BAL,31.0,34.0,3.194678,7.375,8.173669,1.226050,-10.375,-9.576331,-1.436450
9,DEN,LA,30.0,26.0,4.510074,6.375,7.502518,1.125378,-2.375,-1.247482,-0.187122
10,DET,NYJ,31.0,24.0,-4.654697,7.375,6.211326,0.931699,-0.375,-1.538674,-0.230801
11,GB,ATL,14.0,35.0,-3.169388,-9.625,-10.417347,-1.562602,-11.375,-12.167347,-1.825102
12,HOU,IND,17.0,19.0,-0.520573,-6.625,-6.755143,-1.013271,4.625,4.494857,0.674229
13,IND,HOU,19.0,17.0,1.025111,-4.625,-4.368722,-0.655308,6.625,6.881278,1.032192
14,JAX,NE,35.0,6.0,3.153263,11.375,12.163316,1.824497,17.625,18.413316,2.761997
15,KC,MIA,24.0,10.0,-4.705708,0.375,-0.801427,-0.120214,13.625,12.448573,1.867286
16,LA,DEN,26.0,30.0,2.823203,2.375,3.080801,0.462120,-6.375,-5.669199,-0.850380
17,LAC,BUF,16.0,24.0,5.941307,-7.625,-6.139673,-0.920951,-0.375,1.110327,0.166549
18,LV,NO,35.0,27.0,0.223504,11.375,11.430876,1.714631,-3.375,-3.319124,-0.497869
19,MIA,KC,10.0,24.0,2.458286,-13.625,-13.010428,-1.951564,-0.375,0.239572,0.035936
20,MIN,TB,23.0,16.0,-0.961835,-0.625,-0.865459,-0.129819,7.625,7.384541,1.107681
21,NE,JAX,6.0,35.0,2.328442,-17.625,-17.042889,-2.556433,-11.375,-10.792889,-1.618933
22,NO,LV,27.0,35.0,-3.206077,3.375,2.573481,0.386022,-11.375,-12.176519,-1.826478
23,NYG,TEN,12.0,7.0,-7.456672,-11.625,-13.489168,-2.023375,16.625,14.760832,2.214125
24,NYJ,DET,24.0,31.0,2.748511,0.375,1.062128,0.159319,-7.375,-6.687872,-1.003181
25,PHI,CHI,7.0,27.0,0.551141,-16.625,-16.487215,-2.473082,-3.375,-3.237215,-0.485582
26,PIT,CIN,30.0,27.0,1.122452,6.375,6.655613,0.998342,-3.375,-3.094387,-0.464158
27,SEA,WAS,31.0,33.0,-2.745448,7.375,6.688638,1.003296,-9.375,-10.061362,-1.509204
28,SF,ARI,36.0,30.0,-3.679974,12.375,11.455006,1.718251,-6.375,-7.294994,-1.094249
29,TB,MIN,16.0,23.0,2.458757,-7.625,-7.010311,-1.051547,0.625,1.239689,0.185953
30,TEN,NYG,7.0,12.0,-3.713683,-16.625,-17.553421,-2.633013,11.625,10.696579,1.604487
31,WAS,SEA,33.0,31.0,5.532084,9.375,10.758021,1.613703,-7.375,-5.991979,-0.898797

# Build Week-Level Feature Table

The final feature table contains only the new evidence that should move the prior week's ratings.

For Week 3:

`Week 3 strength = Week 2 strength + Week 2 performance update`

The previous week's rating therefore acts as the prior, and older games are not counted again.

In [11]:
team_features = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_in_update=("game_id", "count"),

        entering_team_strength=(
            "entering_team_strength",
            "first"
        ),

        entering_strength_rank=(
            "entering_strength_rank",
            "first"
        ),

        average_opponent_strength=(
            "opponent_entering_strength",
            "mean"
        ),

        average_opponent_rank=(
            "opponent_entering_rank",
            "mean"
        ),

        actual_margin=(
            "point_margin",
            "mean"
        ),

        expected_margin=(
            "expected_margin",
            "mean"
        ),

        performance_residual=(
            "performance_residual",
            "mean"
        ),

        weekly_strength_update=(
            "weekly_strength_update",
            "mean"
        ),

        weekly_offense_adjustment=(
            "weekly_offense_adjustment",
            "mean"
        ),

        weekly_defense_adjustment=(
            "weekly_defense_adjustment",
            "mean"
        )
    )
)

display(
    team_features[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "average_opponent_rank",
            "average_opponent_strength",
            "actual_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,entering_strength_rank,entering_team_strength,average_opponent_rank,average_opponent_strength,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
14,JAX,11,2.328442,6.0,3.153263,29.0,0.675179,28.324821,1.448446,1.824497,2.761997
1,ATL,24,-3.169388,13.0,1.131145,21.0,-5.800533,26.800533,1.436171,1.748668,1.486168
5,CHI,16,0.551141,12.0,1.582449,20.0,0.468692,19.531308,1.326430,0.565592,2.553092
18,LV,25,-3.206077,17.0,0.223504,8.0,-4.929581,12.929581,1.091353,1.714631,-0.497869
31,WAS,23,-2.745448,2.0,5.532084,2.0,-6.777532,8.777532,0.833940,1.613703,-0.898797
15,KC,10,2.458286,31.0,-4.705708,14.0,5.663995,8.336005,0.800683,-0.120214,1.867286
20,MIN,9,2.458757,21.0,-0.961835,7.0,1.920592,5.079408,0.521537,-0.129819,1.107681
9,DEN,7,2.823203,4.0,4.510074,4.0,-0.186871,4.186871,0.435681,1.125378,-0.187122
0,ARI,26,-3.679974,3.0,4.807611,-6.0,-9.987585,3.987585,0.416051,1.136535,-1.675965
26,PIT,19,-0.215758,14.0,1.122452,3.0,0.161790,2.838210,0.299995,0.998342,-0.464158
13,IND,20,-0.520573,15.0,1.025111,2.0,-0.045684,2.045684,0.217634,-0.655308,1.032192
24,NYJ,30,-4.654697,8.0,2.748511,-7.0,-8.903207,1.903207,0.202668,0.159319,-1.003181
7,CLE,29,-4.391506,28.0,-4.369019,3.0,1.477513,1.522487,0.162484,-0.557588,0.679912
2,BAL,5,3.194678,18.0,-0.076385,3.0,1.771063,1.228937,0.131335,1.553386,-1.109114
17,LAC,22,-1.669265,1.0,5.941307,-8.0,-9.110572,1.110572,0.118741,-0.920951,0.166549
30,TEN,32,-7.456672,27.0,-3.713683,-5.0,-5.242989,0.242989,0.026032,-2.633013,1.604487
23,NYG,27,-3.713683,32.0,-7.456672,5.0,5.242989,-0.242989,-0.026032,-2.023375,2.214125
3,BUF,1,5.941307,22.0,-1.669265,8.0,9.110572,-1.110572,-0.118741,-0.006347,1.081153
8,DAL,18,-0.076385,5.0,3.194678,-3.0,-1.771063,-1.228937,-0.131335,1.226050,-1.436450
4,CAR,28,-4.369019,29.0,-4.391506,-3.0,-1.477513,-1.522487,-0.162484,-1.008431,0.229069
10,DET,8,2.748511,30.0,-4.654697,7.0,8.903207,-1.903207,-0.202668,0.931699,-0.230801
12,HOU,15,1.025111,20.0,-0.520573,-2.0,0.045684,-2.045684,-0.217634,-1.013271,0.674229
6,CIN,14,1.122452,19.0,-0.215758,-3.0,-0.161790,-2.838210,-0.299995,0.498159,-0.964341
28,SF,3,4.807611,26.0,-3.679974,6.0,9.987585,-3.987585,-0.416051,1.718251,-1.094249
16,LA,4,4.510074,7.0,2.823203,-4.0,0.186871,-4.186871,-0.435681,0.462120,-0.850380
29,TB,21,-0.961835,9.0,2.458757,-7.0,-1.920592,-5.079408,-0.521537,-1.051547,0.185953
19,MIA,31,-4.705708,10.0,2.458286,-14.0,-5.663995,-8.336005,-0.800683,-1.951564,0.035936
27,SEA,2,5.532084,23.0,-2.745448,-2.0,6.777532,-8.777532,-0.833940,1.003296,-1.509204
22,NO,17,0.223504,25.0,-3.206077,-8.0,4.929581,-12.929581,-1.091353,0.386022,-1.826478
25,PHI,12,1.582449,16.0,0.551141,-20.0,-0.468692,-19.531308,-1.326430,-2.473082,-0.485582
11,GB,13,1.131145,24.0,-3.169388,-21.0,5.800533,-26.800533,-1.436171,-1.562602,-1.825102
21,NE,6,3.153263,11.0,2.328442,-29.0,-0.675179,-28.324821,-1.448446,-2.556433,-1.618933

# Sanity Checks

Before saving, verify that:

- all 32 teams are represented
- every team has an entering Week 2 rating
- every opponent has an entering Week 2 rating
- no Week 3 game results were used
- weekly strength updates remain within the intended cap

In [12]:
print("Teams in feature table:", len(team_features))
print(
    "Unique teams:",
    team_features["team"].nunique()
)

print(
    "Missing entering team strengths:",
    team_features[
        "entering_team_strength"
    ].isna().sum()
)

print(
    "Missing opponent strengths:",
    team_features[
        "average_opponent_strength"
    ].isna().sum()
)

print(
    "Largest positive weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].max(),
        3
    )
)

print(
    "Largest negative weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].min(),
        3
    )
)

if (
    completed_games["week"] >= TARGET_WEEK
).any():
    raise ValueError(
        "DATA LEAKAGE: target-week results "
        "were found in completed games."
    )

if len(team_features) != 32:
    print()
    print(
        "WARNING: Feature table does not "
        "contain all 32 teams."
    )

Teams in feature table: 32
Unique teams: 32
Missing entering team strengths: 0
Missing opponent strengths: 0
Largest positive weekly update: 1.448
Largest negative weekly update: -1.448

# Save In Season Feature Table

This output will be consumed by:

`04_Weekly_Team_Strength.ipynb`

The file contains only the new in season evidence. It does not overwrite or replace the preseason team strength table.

In [13]:
output_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

team_features = team_features.sort_values(
    "team"
).reset_index(drop=True)

team_features.to_parquet(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: ..\..\data\processed\weekly\week_04_inseason_features.parquet

# Interpretation

The weekly model is now sequential.

For Week 3:

1. Week 2 team strength is treated as the entering prior.
2. Only Week 2 game results provide new evidence.
3. Performance is evaluated relative to the opponent's entering strength.
4. Extreme single game residuals are capped.
5. A conservative learning rate determines the weekly rating movement.
6. The resulting update will be added to the Week 2 rating in `04_Weekly_Team_Strength.ipynb`.

This prevents older games from being counted repeatedly and makes strength of opponent part of every weekly update.

The frozen preseason model remains unchanged.