# 03 — In Season Feature Engineering

This notebook creates the weekly performance features used by the in season projection layer.

It does not modify the original preseason notebooks or their outputs.

The purpose of this notebook is to convert completed regular season games into team level offensive and defensive performance features that can later be blended with the frozen preseason model.

For a selected target week, the notebook:

- Loads only completed games from weeks before the target week
- Builds team level scoring and margin summaries
- Separates offense and defense
- Adds simple opponent adjusted performance features
- Applies early season shrinkage to reduce overreaction to small samples
- Saves a clean feature table for the weekly team strength notebook

This notebook is intentionally conservative after Week 1. One game should inform the model, not redefine it.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the outputs created by:

`02_Weekly_Data_Update.ipynb`

The only value that normally changes week to week is `TARGET_WEEK`.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 5
PRIOR_WEEK = TARGET_WEEK - 1

completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

prior_strength_path = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

print("Using completed games:", completed_games_path)
print("Using entering ratings:", prior_strength_path)

Using completed games: ..\..\data\processed\weekly\week_05_completed_games.parquet
Using entering ratings: ..\..\data\processed\weekly\week_04_sequential_team_strength.parquet

# Load Completed Games

Only games completed before the target week should exist in this file.

That leakage rule was enforced in `02_Weekly_Data_Update.ipynb`.

In [3]:
completed_games = pd.read_parquet(
    completed_games_path
)

completed_games = completed_games.sort_values(
    ["week", "gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Completed games available before Week {TARGET_WEEK}:",
    len(completed_games)
)

display(
    completed_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Completed games available before Week 5: 64

    week     gameday away_team  away_score home_team  home_score
0      1  2026-09-09        NE        10.0       SEA        13.0
1      1  2026-09-10        SF        27.0        LA         7.0
2      1  2026-09-13       ARI        26.0       LAC        14.0
3      1  2026-09-13       ATL        13.0       PIT        20.0
4      1  2026-09-13       BAL        41.0       IND        23.0
..   ...         ...       ...         ...       ...         ...
59     4  2026-10-04       MIA        10.0       MIN        15.0
60     4  2026-10-04        NE        29.0       BUF        26.0
61     4  2026-10-04       NYJ        12.0       CHI        23.0
62     4  2026-10-04       TEN        18.0       BAL        24.0
63     4  2026-10-05       ATL        45.0        NO        24.0

[64 rows x 6 columns]

In [4]:
update_games = completed_games[
    completed_games["week"] == PRIOR_WEEK
].copy()

update_games = update_games.sort_values(
    ["gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Week {PRIOR_WEEK} games used to update "
    f"Week {TARGET_WEEK} ratings:",
    len(update_games)
)

display(
    update_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Week 4 games used to update Week 5 ratings: 16

    week     gameday away_team  away_score home_team  home_score
0      4  2026-10-01       PIT        24.0       CLE        27.0
1      4  2026-10-04       ARI        24.0       NYG        36.0
2      4  2026-10-04       DAL        34.0       HOU        30.0
3      4  2026-10-04       DEN        14.0        SF        24.0
4      4  2026-10-04       DET        26.0       CAR        32.0
5      4  2026-10-04        GB        17.0        TB        14.0
6      4  2026-10-04       IND        30.0       WAS        13.0
7      4  2026-10-04       JAX        22.0       CIN        17.0
8      4  2026-10-04        KC        30.0        LV        27.0
9      4  2026-10-04       LAC        23.0       SEA        30.0
10     4  2026-10-04        LA        24.0       PHI        20.0
11     4  2026-10-04       MIA        10.0       MIN        15.0
12     4  2026-10-04        NE        29.0       BUF        26.0
13     4  2026-10-04       NYJ        12.0       CHI        23.0
14     4  2026-10-04       TEN        18.0       BAL        24.0
15     4  2026-10-05       ATL        45.0        NO        24.0

# Convert Prior Week Games to Team Game Rows

Only the most recently completed week is used for the new weekly update.

For Week 3:

- Week 2 team strength is the entering prior
- Week 2 game performance is the new evidence
- Week 1 is not counted again because it is already reflected in the Week 2 ratings

Each game becomes two rows:

- one from the home team's perspective
- one from the away team's perspective

In [5]:
home_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["home_team"],
        "opponent": update_games["away_team"],
        "is_home": 1,
        "points_for": update_games["home_score"],
        "points_against": update_games["away_score"]
    }
)

away_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["away_team"],
        "opponent": update_games["home_team"],
        "is_home": 0,
        "points_for": update_games["away_score"],
        "points_against": update_games["home_score"]
    }
)

team_games = pd.concat(
    [home_rows, away_rows],
    ignore_index=True
)

team_games["point_margin"] = (
    team_games["points_for"]
    - team_games["points_against"]
)

team_games = team_games.sort_values(
    ["team", "game_id"]
).reset_index(drop=True)

print("Team-game rows:", len(team_games))

display(team_games)

Team-game rows: 32

,game_id,week,team,opponent,is_home,points_for,points_against,point_margin
0,2026_04_ARI_NYG,4,ARI,NYG,0,24.0,36.0,-12.0
1,2026_04_ATL_NO,4,ATL,NO,0,45.0,24.0,21.0
2,2026_04_TEN_BAL,4,BAL,TEN,1,24.0,18.0,6.0
3,2026_04_NE_BUF,4,BUF,NE,1,26.0,29.0,-3.0
4,2026_04_DET_CAR,4,CAR,DET,1,32.0,26.0,6.0
5,2026_04_NYJ_CHI,4,CHI,NYJ,1,23.0,12.0,11.0
6,2026_04_JAX_CIN,4,CIN,JAX,1,17.0,22.0,-5.0
7,2026_04_PIT_CLE,4,CLE,PIT,1,27.0,24.0,3.0
8,2026_04_DAL_HOU,4,DAL,HOU,0,34.0,30.0,4.0
9,2026_04_DEN_SF,4,DEN,SF,0,14.0,24.0,-10.0
10,2026_04_DET_CAR,4,DET,CAR,0,26.0,32.0,-6.0
11,2026_04_GB_TB,4,GB,TB,0,17.0,14.0,3.0
12,2026_04_DAL_HOU,4,HOU,DAL,1,30.0,34.0,-4.0
13,2026_04_IND_WAS,4,IND,WAS,0,30.0,13.0,17.0
14,2026_04_JAX_CIN,4,JAX,CIN,0,22.0,17.0,5.0
15,2026_04_KC_LV,4,KC,LV,0,30.0,27.0,3.0
16,2026_04_LA_PHI,4,LA,PHI,0,24.0,20.0,4.0
17,2026_04_LAC_SEA,4,LAC,SEA,0,23.0,30.0,-7.0
18,2026_04_KC_LV,4,LV,KC,1,27.0,30.0,-3.0
19,2026_04_MIA_MIN,4,MIA,MIN,0,10.0,15.0,-5.0
20,2026_04_MIA_MIN,4,MIN,MIA,1,15.0,10.0,5.0
21,2026_04_NE_BUF,4,NE,BUF,0,29.0,26.0,3.0
22,2026_04_ATL_NO,4,NO,ATL,1,24.0,45.0,-21.0
23,2026_04_ARI_NYG,4,NYG,ARI,1,36.0,24.0,12.0
24,2026_04_NYJ_CHI,4,NYJ,CHI,0,12.0,23.0,-11.0
25,2026_04_LA_PHI,4,PHI,LA,1,20.0,24.0,-4.0
26,2026_04_PIT_CLE,4,PIT,CLE,0,24.0,27.0,-3.0
27,2026_04_LAC_SEA,4,SEA,LAC,1,30.0,23.0,7.0
28,2026_04_DEN_SF,4,SF,DEN,1,24.0,14.0,10.0
29,2026_04_GB_TB,4,TB,GB,1,14.0,17.0,-3.0
30,2026_04_TEN_BAL,4,TEN,BAL,0,18.0,24.0,-6.0
31,2026_04_IND_WAS,4,WAS,IND,1,13.0,30.0,-17.0

# Attach Entering Team and Opponent Strength

Each team's performance is evaluated relative to what the model believed before the game was played.

For Week 3 projections, Week 2 ratings represent the information available entering Week 2.

This prevents the opponent adjustment from using future information or the same results that are currently being evaluated.

In [6]:
prior_strength = pd.read_parquet(
    prior_strength_path
).copy()

required_prior_columns = [
    "team",
    "weekly_team_strength",
    "weekly_strength_rank"
]

missing_prior_columns = [
    col
    for col in required_prior_columns
    if col not in prior_strength.columns
]

if missing_prior_columns:
    raise KeyError(
        "Missing prior-week strength columns: "
        + ", ".join(missing_prior_columns)
    )

prior_strength = prior_strength[
    required_prior_columns
].rename(
    columns={
        "weekly_team_strength": "entering_team_strength",
        "weekly_strength_rank": "entering_strength_rank"
    }
)

print(
    f"Week {PRIOR_WEEK} entering ratings loaded:",
    len(prior_strength)
)

display(
    prior_strength.sort_values(
        "entering_strength_rank"
    )
)

Week 4 entering ratings loaded: 32

   team  entering_team_strength  entering_strength_rank
0   BUF                5.822566                       1
1   SEA                4.698144                       2
2    SF                4.391561                       3
3    LA                4.074393                       4
4   JAX                3.776888                       5
5   BAL                3.326012                       6
6    KC                3.258970                       7
7   DEN                3.258884                       8
8   MIN                2.980293                       9
9   DET                2.545843                      10
10  CHI                1.877571                      11
11   NE                1.704818                      12
12  CIN                0.822457                      13
13  HOU                0.807477                      14
14  PHI                0.256019                      15
15  PIT                0.084237                      16
16  DAL               -0.207720                      17
17  IND               -0.302939                      18
18   GB               -0.305026                      19
19   NO               -0.867849                      20
20   TB               -1.483372                      21
21  LAC               -1.550525                      22
22  ATL               -1.733218                      23
23  WAS               -1.911508                      24
24   LV               -2.114724                      25
25  ARI               -3.263923                      26
26  NYG               -3.739715                      27
27  CLE               -4.229023                      28
28  NYJ               -4.452029                      29
29  CAR               -4.531503                      30
30  MIA               -5.506392                      31
31  TEN               -7.430640                      32

In [7]:
team_games = team_games.merge(
    prior_strength[
        [
            "team",
            "entering_team_strength",
            "entering_strength_rank"
        ]
    ],
    on="team",
    how="left",
    validate="many_to_one"
)

opponent_strength = prior_strength[
    [
        "team",
        "entering_team_strength",
        "entering_strength_rank"
    ]
].rename(
    columns={
        "team": "opponent",
        "entering_team_strength": "opponent_entering_strength",
        "entering_strength_rank": "opponent_entering_rank"
    }
)

team_games = team_games.merge(
    opponent_strength,
    on="opponent",
    how="left",
    validate="many_to_one"
)

display(
    team_games[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "opponent",
            "opponent_entering_rank",
            "opponent_entering_strength",
            "points_for",
            "points_against",
            "point_margin"
        ]
    ].sort_values(
        "entering_strength_rank"
    )
)

,team,entering_strength_rank,entering_team_strength,opponent,opponent_entering_rank,opponent_entering_strength,points_for,points_against,point_margin
3,BUF,1,5.822566,NE,12,1.704818,26.0,29.0,-3.0
27,SEA,2,4.698144,LAC,22,-1.550525,30.0,23.0,7.0
28,SF,3,4.391561,DEN,8,3.258884,24.0,14.0,10.0
16,LA,4,4.074393,PHI,15,0.256019,24.0,20.0,4.0
14,JAX,5,3.776888,CIN,13,0.822457,22.0,17.0,5.0
2,BAL,6,3.326012,TEN,32,-7.430640,24.0,18.0,6.0
15,KC,7,3.258970,LV,25,-2.114724,30.0,27.0,3.0
9,DEN,8,3.258884,SF,3,4.391561,14.0,24.0,-10.0
20,MIN,9,2.980293,MIA,31,-5.506392,15.0,10.0,5.0
10,DET,10,2.545843,CAR,30,-4.531503,26.0,32.0,-6.0
5,CHI,11,1.877571,NYJ,29,-4.452029,23.0,12.0,11.0
21,NE,12,1.704818,BUF,1,5.822566,29.0,26.0,3.0
6,CIN,13,0.822457,JAX,5,3.776888,17.0,22.0,-5.0
12,HOU,14,0.807477,DAL,17,-0.207720,30.0,34.0,-4.0
25,PHI,15,0.256019,LA,4,4.074393,20.0,24.0,-4.0
26,PIT,16,0.084237,CLE,28,-4.229023,24.0,27.0,-3.0
8,DAL,17,-0.207720,HOU,14,0.807477,34.0,30.0,4.0
13,IND,18,-0.302939,WAS,24,-1.911508,30.0,13.0,17.0
11,GB,19,-0.305026,TB,21,-1.483372,17.0,14.0,3.0
22,NO,20,-0.867849,ATL,23,-1.733218,24.0,45.0,-21.0
29,TB,21,-1.483372,GB,19,-0.305026,14.0,17.0,-3.0
17,LAC,22,-1.550525,SEA,2,4.698144,23.0,30.0,-7.0
1,ATL,23,-1.733218,NO,20,-0.867849,45.0,24.0,21.0
31,WAS,24,-1.911508,IND,18,-0.302939,13.0,30.0,-17.0
18,LV,25,-2.114724,KC,7,3.258970,27.0,30.0,-3.0
0,ARI,26,-3.263923,NYG,27,-3.739715,24.0,36.0,-12.0
23,NYG,27,-3.739715,ARI,26,-3.263923,36.0,24.0,12.0
7,CLE,28,-4.229023,PIT,16,0.084237,27.0,24.0,3.0
24,NYJ,29,-4.452029,CHI,11,1.877571,12.0,23.0,-11.0
4,CAR,30,-4.531503,DET,10,2.545843,32.0,26.0,6.0
19,MIA,31,-5.506392,MIN,9,2.980293,10.0,15.0,-5.0
30,TEN,32,-7.430640,BAL,6,3.326012,18.0,24.0,-6.0

# Expected Margin and Opponent-Adjusted Performance

The weekly update is based on how a team performed relative to expectation.

For each team game:

`performance residual = actual margin - expected margin`

Expected margin uses the difference between the two teams' entering strength ratings plus home field advantage.

This means beating a strong opponent is more informative than producing the same result against a weak opponent.

In [8]:
HOME_FIELD_POINTS = 1.5

team_games["expected_margin"] = (
    team_games["entering_team_strength"]
    - team_games["opponent_entering_strength"]
    + np.where(
        team_games["is_home"] == 1,
        HOME_FIELD_POINTS,
        -HOME_FIELD_POINTS
    )
)

team_games["performance_residual"] = (
    team_games["point_margin"]
    - team_games["expected_margin"]
)

display(
    team_games[
        [
            "team",
            "opponent",
            "entering_team_strength",
            "opponent_entering_strength",
            "point_margin",
            "expected_margin",
            "performance_residual"
        ]
    ].sort_values(
        "performance_residual",
        ascending=False
    )
)

,team,opponent,entering_team_strength,opponent_entering_strength,point_margin,expected_margin,performance_residual
1,ATL,NO,-1.733218,-0.867849,21.0,-2.365369,23.365369
13,IND,WAS,-0.302939,-1.911508,17.0,0.108569,16.891431
4,CAR,DET,-4.531503,2.545843,6.0,-5.577346,11.577346
23,NYG,ARI,-3.739715,-3.263923,12.0,1.024209,10.975791
21,NE,BUF,1.704818,5.822566,3.0,-5.617748,8.617748
28,SF,DEN,4.391561,3.258884,10.0,2.632676,7.367324
8,DAL,HOU,-0.207720,0.807477,4.0,-2.515197,6.515197
30,TEN,BAL,-7.430640,3.326012,-6.0,-12.256652,6.256652
7,CLE,PIT,-4.229023,0.084237,3.0,-2.813260,5.813260
19,MIA,MIN,-5.506392,2.980293,-5.0,-9.986685,4.986685
14,JAX,CIN,3.776888,0.822457,5.0,1.454432,3.545568
11,GB,TB,-0.305026,-1.483372,3.0,-0.321654,3.321654
5,CHI,NYJ,1.877571,-4.452029,11.0,7.829600,3.170400
16,LA,PHI,4.074393,0.256019,4.0,2.318373,1.681627
18,LV,KC,-2.114724,3.258970,-3.0,-3.873694,0.873694
17,LAC,SEA,-1.550525,4.698144,-7.0,-7.748669,0.748669
27,SEA,LAC,4.698144,-1.550525,7.0,7.748669,-0.748669
15,KC,LV,3.258970,-2.114724,3.0,3.873694,-0.873694
25,PHI,LA,0.256019,4.074393,-4.0,-2.318373,-1.681627
24,NYJ,CHI,-4.452029,1.877571,-11.0,-7.829600,-3.170400
29,TB,GB,-1.483372,-0.305026,-3.0,0.321654,-3.321654
6,CIN,JAX,0.822457,3.776888,-5.0,-1.454432,-3.545568
20,MIN,MIA,2.980293,-5.506392,5.0,9.986685,-4.986685
26,PIT,CLE,0.084237,-4.229023,-3.0,2.813260,-5.813260
2,BAL,TEN,3.326012,-7.430640,6.0,12.256652,-6.256652
12,HOU,DAL,0.807477,-0.207720,-4.0,2.515197,-6.515197
9,DEN,SF,3.258884,4.391561,-10.0,-2.632676,-7.367324
3,BUF,NE,5.822566,1.704818,-3.0,5.617748,-8.617748
0,ARI,NYG,-3.263923,-3.739715,-12.0,-1.024209,-10.975791
10,DET,CAR,2.545843,-4.531503,-6.0,5.577346,-11.577346
31,WAS,IND,-1.911508,-0.302939,-17.0,-0.108569,-16.891431
22,NO,ATL,-0.867849,-1.733218,-21.0,2.365369,-23.365369

# Control Extreme Single-Game Results

NFL game margins contain substantial single-game noise.

A blowout should affect team strength, but one extreme result should not completely redefine the team's rating.

Performance residuals are therefore capped before the weekly learning rate is applied.

In [9]:
RESIDUAL_SCALE = 14.0
MAX_WEEKLY_UPDATE = 1.5

team_games["weekly_strength_update"] = (
    MAX_WEEKLY_UPDATE
    * np.tanh(
        team_games["performance_residual"]
        / RESIDUAL_SCALE
    )
)

display(
    team_games[
        [
            "team",
            "opponent",
            "point_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,opponent,point_margin,expected_margin,performance_residual,weekly_strength_update
1,ATL,NO,21.0,-2.365369,23.365369,1.397120
13,IND,WAS,17.0,0.108569,16.891431,1.253454
4,CAR,DET,6.0,-5.577346,11.577346,1.018255
23,NYG,ARI,12.0,1.024209,10.975791,0.982482
21,NE,BUF,3.0,-5.617748,8.617748,0.822037
28,SF,DEN,10.0,2.632676,7.367324,0.723750
8,DAL,HOU,4.0,-2.515197,6.515197,0.651678
30,TEN,BAL,-6.0,-12.256652,6.256652,0.629026
7,CLE,PIT,3.0,-2.813260,5.813260,0.589360
19,MIA,MIN,-5.0,-9.986685,4.986685,0.512783
14,JAX,CIN,5.0,1.454432,3.545568,0.371964
11,GB,TB,3.0,-0.321654,3.321654,0.349360
5,CHI,NYJ,11.0,7.829600,3.170400,0.333996
16,LA,PHI,4.0,2.318373,1.681627,0.179313
18,LV,KC,-3.0,-3.873694,0.873694,0.093489
17,LAC,SEA,-7.0,-7.748669,0.748669,0.080138
27,SEA,LAC,7.0,7.748669,-0.748669,-0.080138
15,KC,LV,3.0,3.873694,-0.873694,-0.093489
25,PHI,LA,-4.0,-2.318373,-1.681627,-0.179313
24,NYJ,CHI,-11.0,-7.829600,-3.170400,-0.333996
29,TB,GB,-3.0,0.321654,-3.321654,-0.349360
6,CIN,JAX,-5.0,-1.454432,-3.545568,-0.371964
20,MIN,MIA,5.0,9.986685,-4.986685,-0.512783
26,PIT,CLE,-3.0,2.813260,-5.813260,-0.589360
2,BAL,TEN,6.0,12.256652,-6.256652,-0.629026
12,HOU,DAL,-4.0,2.515197,-6.515197,-0.651678
9,DEN,SF,-10.0,-2.632676,-7.367324,-0.723750
3,BUF,NE,-3.0,5.617748,-8.617748,-0.822037
0,ARI,NYG,-12.0,-1.024209,-10.975791,-0.982482
10,DET,CAR,-6.0,5.577346,-11.577346,-1.018255
31,WAS,IND,-17.0,-0.108569,-16.891431,-1.253454
22,NO,ATL,-21.0,2.365369,-23.365369,-1.397120

# Offensive and Defensive Weekly Signals

Overall team strength uses the opponent adjusted margin residual.

We also preserve separate offensive and defensive signals because the weekly game projection model needs scoring information.

These are weekly updates, not cumulative season averages.

Opponent entering strength is used conservatively as context until separate entering offensive and defensive strength ratings are maintained.

In [10]:
league_points_per_team_game = (
    team_games["points_for"].mean()
)

OPPONENT_CONTEXT_RATE = 0.25
OFFENSE_DEFENSE_UPDATE_RATE = 0.15

team_games["raw_offense_performance"] = (
    team_games["points_for"]
    - league_points_per_team_game
)

team_games["raw_defense_performance"] = (
    league_points_per_team_game
    - team_games["points_against"]
)

team_games["adjusted_offense_performance"] = (
    team_games["raw_offense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["adjusted_defense_performance"] = (
    team_games["raw_defense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["weekly_offense_adjustment"] = (
    team_games["adjusted_offense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

team_games["weekly_defense_adjustment"] = (
    team_games["adjusted_defense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

display(
    team_games[
        [
            "team",
            "opponent",
            "points_for",
            "points_against",
            "opponent_entering_strength",
            "raw_offense_performance",
            "adjusted_offense_performance",
            "weekly_offense_adjustment",
            "raw_defense_performance",
            "adjusted_defense_performance",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "team"
    )
)

,team,opponent,points_for,points_against,opponent_entering_strength,raw_offense_performance,adjusted_offense_performance,weekly_offense_adjustment,raw_defense_performance,adjusted_defense_performance,weekly_defense_adjustment
0,ARI,NYG,24.0,36.0,-3.739715,0.125,-0.809929,-0.121489,-12.125,-13.059929,-1.958989
1,ATL,NO,45.0,24.0,-0.867849,21.125,20.908038,3.136206,-0.125,-0.341962,-0.051294
2,BAL,TEN,24.0,18.0,-7.430640,0.125,-1.732660,-0.259899,5.875,4.017340,0.602601
3,BUF,NE,26.0,29.0,1.704818,2.125,2.551204,0.382681,-5.125,-4.698796,-0.704819
4,CAR,DET,32.0,26.0,2.545843,8.125,8.761461,1.314219,-2.125,-1.488539,-0.223281
5,CHI,NYJ,23.0,12.0,-4.452029,-0.875,-1.988007,-0.298201,11.875,10.761993,1.614299
6,CIN,JAX,17.0,22.0,3.776888,-6.875,-5.930778,-0.889617,1.875,2.819222,0.422883
7,CLE,PIT,27.0,24.0,0.084237,3.125,3.146059,0.471909,-0.125,-0.103941,-0.015591
8,DAL,HOU,34.0,30.0,0.807477,10.125,10.326869,1.549030,-6.125,-5.923131,-0.888470
9,DEN,SF,14.0,24.0,4.391561,-9.875,-8.777110,-1.316566,-0.125,0.972890,0.145934
10,DET,CAR,26.0,32.0,-4.531503,2.125,0.992124,0.148819,-8.125,-9.257876,-1.388681
11,GB,TB,17.0,14.0,-1.483372,-6.875,-7.245843,-1.086876,9.875,9.504157,1.425624
12,HOU,DAL,30.0,34.0,-0.207720,6.125,6.073070,0.910960,-10.125,-10.176930,-1.526540
13,IND,WAS,30.0,13.0,-1.911508,6.125,5.647123,0.847068,10.875,10.397123,1.559568
14,JAX,CIN,22.0,17.0,0.822457,-1.875,-1.669386,-0.250408,6.875,7.080614,1.062092
15,KC,LV,30.0,27.0,-2.114724,6.125,5.596319,0.839448,-3.125,-3.653681,-0.548052
16,LA,PHI,24.0,20.0,0.256019,0.125,0.189005,0.028351,3.875,3.939005,0.590851
17,LAC,SEA,23.0,30.0,4.698144,-0.875,0.299536,0.044930,-6.125,-4.950464,-0.742570
18,LV,KC,27.0,30.0,3.258970,3.125,3.939742,0.590961,-6.125,-5.310258,-0.796539
19,MIA,MIN,10.0,15.0,2.980293,-13.875,-13.129927,-1.969489,8.875,9.620073,1.443011
20,MIN,MIA,15.0,10.0,-5.506392,-8.875,-10.251598,-1.537740,13.875,12.498402,1.874760
21,NE,BUF,29.0,26.0,5.822566,5.125,6.580641,0.987096,-2.125,-0.669359,-0.100404
22,NO,ATL,24.0,45.0,-1.733218,0.125,-0.308304,-0.046246,-21.125,-21.558304,-3.233746
23,NYG,ARI,36.0,24.0,-3.263923,12.125,11.309019,1.696353,-0.125,-0.940981,-0.141147
24,NYJ,CHI,12.0,23.0,1.877571,-11.875,-11.405607,-1.710841,0.875,1.344393,0.201659
25,PHI,LA,20.0,24.0,4.074393,-3.875,-2.856402,-0.428460,-0.125,0.893598,0.134040
26,PIT,CLE,24.0,27.0,-4.229023,0.125,-0.932256,-0.139838,-3.125,-4.182256,-0.627338
27,SEA,LAC,30.0,23.0,-1.550525,6.125,5.737369,0.860605,0.875,0.487369,0.073105
28,SF,DEN,24.0,14.0,3.258884,0.125,0.939721,0.140958,9.875,10.689721,1.603458
29,TB,GB,14.0,17.0,-0.305026,-9.875,-9.951256,-1.492688,6.875,6.798744,1.019812
30,TEN,BAL,18.0,24.0,3.326012,-5.875,-5.043497,-0.756525,-0.125,0.706503,0.105975
31,WAS,IND,13.0,30.0,-0.302939,-10.875,-10.950735,-1.642610,-6.125,-6.200735,-0.930110

# Build Week-Level Feature Table

The final feature table contains only the new evidence that should move the prior week's ratings.

For Week 3:

`Week 3 strength = Week 2 strength + Week 2 performance update`

The previous week's rating therefore acts as the prior, and older games are not counted again.

In [11]:
team_features = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_in_update=("game_id", "count"),

        entering_team_strength=(
            "entering_team_strength",
            "first"
        ),

        entering_strength_rank=(
            "entering_strength_rank",
            "first"
        ),

        average_opponent_strength=(
            "opponent_entering_strength",
            "mean"
        ),

        average_opponent_rank=(
            "opponent_entering_rank",
            "mean"
        ),

        actual_margin=(
            "point_margin",
            "mean"
        ),

        expected_margin=(
            "expected_margin",
            "mean"
        ),

        performance_residual=(
            "performance_residual",
            "mean"
        ),

        weekly_strength_update=(
            "weekly_strength_update",
            "mean"
        ),

        weekly_offense_adjustment=(
            "weekly_offense_adjustment",
            "mean"
        ),

        weekly_defense_adjustment=(
            "weekly_defense_adjustment",
            "mean"
        )
    )
)

display(
    team_features[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "average_opponent_rank",
            "average_opponent_strength",
            "actual_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,entering_strength_rank,entering_team_strength,average_opponent_rank,average_opponent_strength,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
1,ATL,23,-1.733218,20.0,-0.867849,21.0,-2.365369,23.365369,1.397120,3.136206,-0.051294
13,IND,18,-0.302939,24.0,-1.911508,17.0,0.108569,16.891431,1.253454,0.847068,1.559568
4,CAR,30,-4.531503,10.0,2.545843,6.0,-5.577346,11.577346,1.018255,1.314219,-0.223281
23,NYG,27,-3.739715,26.0,-3.263923,12.0,1.024209,10.975791,0.982482,1.696353,-0.141147
21,NE,12,1.704818,1.0,5.822566,3.0,-5.617748,8.617748,0.822037,0.987096,-0.100404
28,SF,3,4.391561,8.0,3.258884,10.0,2.632676,7.367324,0.723750,0.140958,1.603458
8,DAL,17,-0.207720,14.0,0.807477,4.0,-2.515197,6.515197,0.651678,1.549030,-0.888470
30,TEN,32,-7.430640,6.0,3.326012,-6.0,-12.256652,6.256652,0.629026,-0.756525,0.105975
7,CLE,28,-4.229023,16.0,0.084237,3.0,-2.813260,5.813260,0.589360,0.471909,-0.015591
19,MIA,31,-5.506392,9.0,2.980293,-5.0,-9.986685,4.986685,0.512783,-1.969489,1.443011
14,JAX,5,3.776888,13.0,0.822457,5.0,1.454432,3.545568,0.371964,-0.250408,1.062092
11,GB,19,-0.305026,21.0,-1.483372,3.0,-0.321654,3.321654,0.349360,-1.086876,1.425624
5,CHI,11,1.877571,29.0,-4.452029,11.0,7.829600,3.170400,0.333996,-0.298201,1.614299
16,LA,4,4.074393,15.0,0.256019,4.0,2.318373,1.681627,0.179313,0.028351,0.590851
18,LV,25,-2.114724,7.0,3.258970,-3.0,-3.873694,0.873694,0.093489,0.590961,-0.796539
17,LAC,22,-1.550525,2.0,4.698144,-7.0,-7.748669,0.748669,0.080138,0.044930,-0.742570
27,SEA,2,4.698144,22.0,-1.550525,7.0,7.748669,-0.748669,-0.080138,0.860605,0.073105
15,KC,7,3.258970,25.0,-2.114724,3.0,3.873694,-0.873694,-0.093489,0.839448,-0.548052
25,PHI,15,0.256019,4.0,4.074393,-4.0,-2.318373,-1.681627,-0.179313,-0.428460,0.134040
24,NYJ,29,-4.452029,11.0,1.877571,-11.0,-7.829600,-3.170400,-0.333996,-1.710841,0.201659
29,TB,21,-1.483372,19.0,-0.305026,-3.0,0.321654,-3.321654,-0.349360,-1.492688,1.019812
6,CIN,13,0.822457,5.0,3.776888,-5.0,-1.454432,-3.545568,-0.371964,-0.889617,0.422883
20,MIN,9,2.980293,31.0,-5.506392,5.0,9.986685,-4.986685,-0.512783,-1.537740,1.874760
26,PIT,16,0.084237,28.0,-4.229023,-3.0,2.813260,-5.813260,-0.589360,-0.139838,-0.627338
2,BAL,6,3.326012,32.0,-7.430640,6.0,12.256652,-6.256652,-0.629026,-0.259899,0.602601
12,HOU,14,0.807477,17.0,-0.207720,-4.0,2.515197,-6.515197,-0.651678,0.910960,-1.526540
9,DEN,8,3.258884,3.0,4.391561,-10.0,-2.632676,-7.367324,-0.723750,-1.316566,0.145934
3,BUF,1,5.822566,12.0,1.704818,-3.0,5.617748,-8.617748,-0.822037,0.382681,-0.704819
0,ARI,26,-3.263923,27.0,-3.739715,-12.0,-1.024209,-10.975791,-0.982482,-0.121489,-1.958989
10,DET,10,2.545843,30.0,-4.531503,-6.0,5.577346,-11.577346,-1.018255,0.148819,-1.388681
31,WAS,24,-1.911508,18.0,-0.302939,-17.0,-0.108569,-16.891431,-1.253454,-1.642610,-0.930110
22,NO,20,-0.867849,23.0,-1.733218,-21.0,2.365369,-23.365369,-1.397120,-0.046246,-3.233746

# Sanity Checks

Before saving, verify that:

- all 32 teams are represented
- every team has an entering Week 2 rating
- every opponent has an entering Week 2 rating
- no Week 3 game results were used
- weekly strength updates remain within the intended cap

In [12]:
print("Teams in feature table:", len(team_features))
print(
    "Unique teams:",
    team_features["team"].nunique()
)

print(
    "Missing entering team strengths:",
    team_features[
        "entering_team_strength"
    ].isna().sum()
)

print(
    "Missing opponent strengths:",
    team_features[
        "average_opponent_strength"
    ].isna().sum()
)

print(
    "Largest positive weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].max(),
        3
    )
)

print(
    "Largest negative weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].min(),
        3
    )
)

if (
    completed_games["week"] >= TARGET_WEEK
).any():
    raise ValueError(
        "DATA LEAKAGE: target-week results "
        "were found in completed games."
    )

if len(team_features) != 32:
    print()
    print(
        "WARNING: Feature table does not "
        "contain all 32 teams."
    )

Teams in feature table: 32
Unique teams: 32
Missing entering team strengths: 0
Missing opponent strengths: 0
Largest positive weekly update: 1.397
Largest negative weekly update: -1.397

# Save In Season Feature Table

This output will be consumed by:

`04_Weekly_Team_Strength.ipynb`

The file contains only the new in season evidence. It does not overwrite or replace the preseason team strength table.

In [13]:
output_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

team_features = team_features.sort_values(
    "team"
).reset_index(drop=True)

team_features.to_parquet(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: ..\..\data\processed\weekly\week_05_inseason_features.parquet

# Interpretation

The weekly model is now sequential.

For Week 3:

1. Week 2 team strength is treated as the entering prior.
2. Only Week 2 game results provide new evidence.
3. Performance is evaluated relative to the opponent's entering strength.
4. Extreme single game residuals are capped.
5. A conservative learning rate determines the weekly rating movement.
6. The resulting update will be added to the Week 2 rating in `04_Weekly_Team_Strength.ipynb`.

This prevents older games from being counted repeatedly and makes strength of opponent part of every weekly update.

The frozen preseason model remains unchanged.