# 03 — In Season Feature Engineering

This notebook creates the weekly performance features used by the in season projection layer.

It does not modify the original preseason notebooks or their outputs.

The purpose of this notebook is to convert completed regular season games into team level offensive and defensive performance features that can later be blended with the frozen preseason model.

For a selected target week, the notebook:

- Loads only completed games from weeks before the target week
- Builds team level scoring and margin summaries
- Separates offense and defense
- Adds simple opponent adjusted performance features
- Applies early season shrinkage to reduce overreaction to small samples
- Saves a clean feature table for the weekly team strength notebook

This notebook is intentionally conservative after Week 1. One game should inform the model, not redefine it.

In [14]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the outputs created by:

`02_Weekly_Data_Update.ipynb`

The only value that normally changes week to week is `TARGET_WEEK`.

In [15]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 7
PRIOR_WEEK = TARGET_WEEK - 1

completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

prior_strength_path = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

print("Using completed games:", completed_games_path)
print("Using entering ratings:", prior_strength_path)

Using completed games: ..\..\data\processed\weekly\week_07_completed_games.parquet
Using entering ratings: ..\..\data\processed\weekly\week_06_sequential_team_strength.parquet

# Load Completed Games

Only games completed before the target week should exist in this file.

That leakage rule was enforced in `02_Weekly_Data_Update.ipynb`.

In [16]:
completed_games = pd.read_parquet(
    completed_games_path
)

completed_games = completed_games.sort_values(
    ["week", "gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Completed games available before Week {TARGET_WEEK}:",
    len(completed_games)
)

display(
    completed_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Completed games available before Week 7: 93

    week     gameday away_team  away_score home_team  home_score
0      1  2026-09-09        NE        10.0       SEA        13.0
1      1  2026-09-10        SF        27.0        LA         7.0
2      1  2026-09-13       ARI        26.0       LAC        14.0
3      1  2026-09-13       ATL        13.0       PIT        20.0
4      1  2026-09-13       BAL        41.0       IND        23.0
..   ...         ...       ...         ...       ...         ...
88     6  2026-10-18        NO        34.0       NYG        27.0
89     6  2026-10-18       NYJ        19.0        NE        26.0
90     6  2026-10-18       PIT        26.0        TB        19.0
91     6  2026-10-18       TEN        26.0       IND        20.0
92     6  2026-10-19       WAS        17.0        SF        23.0

[93 rows x 6 columns]

In [17]:
update_games = completed_games[
    completed_games["week"] == PRIOR_WEEK
].copy()

update_games = update_games.sort_values(
    ["gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Week {PRIOR_WEEK} games used to update "
    f"Week {TARGET_WEEK} ratings:",
    len(update_games)
)

display(
    update_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Week 6 games used to update Week 7 ratings: 14

    week     gameday away_team  away_score home_team  home_score
0      6  2026-10-15       SEA        14.0       DEN        17.0
1      6  2026-10-18       ARI        18.0        LA        16.0
2      6  2026-10-18       BAL        10.0       CLE        13.0
3      6  2026-10-18       BUF        33.0        LV        30.0
4      6  2026-10-18       CAR        25.0       PHI        14.0
5      6  2026-10-18       CHI        31.0       ATL        23.0
6      6  2026-10-18       DAL        13.0        GB        23.0
7      6  2026-10-18       HOU        34.0       JAX        31.0
8      6  2026-10-18       LAC         6.0        KC        22.0
9      6  2026-10-18        NO        34.0       NYG        27.0
10     6  2026-10-18       NYJ        19.0        NE        26.0
11     6  2026-10-18       PIT        26.0        TB        19.0
12     6  2026-10-18       TEN        26.0       IND        20.0
13     6  2026-10-19       WAS        17.0        SF        23.0

# Convert Prior Week Games to Team Game Rows

Only the most recently completed week is used for the new weekly update.

For Week 3:

- Week 2 team strength is the entering prior
- Week 2 game performance is the new evidence
- Week 1 is not counted again because it is already reflected in the Week 2 ratings

Each game becomes two rows:

- one from the home team's perspective
- one from the away team's perspective

In [18]:
home_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["home_team"],
        "opponent": update_games["away_team"],
        "is_home": 1,
        "points_for": update_games["home_score"],
        "points_against": update_games["away_score"]
    }
)

away_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["away_team"],
        "opponent": update_games["home_team"],
        "is_home": 0,
        "points_for": update_games["away_score"],
        "points_against": update_games["home_score"]
    }
)

team_games = pd.concat(
    [home_rows, away_rows],
    ignore_index=True
)

team_games["point_margin"] = (
    team_games["points_for"]
    - team_games["points_against"]
)

team_games = team_games.sort_values(
    ["team", "game_id"]
).reset_index(drop=True)

print("Team-game rows:", len(team_games))

display(team_games)

Team-game rows: 28

,game_id,week,team,opponent,is_home,points_for,points_against,point_margin
0,2026_06_ARI_LA,6,ARI,LA,0,18.0,16.0,2.0
1,2026_06_CHI_ATL,6,ATL,CHI,1,23.0,31.0,-8.0
2,2026_06_BAL_CLE,6,BAL,CLE,0,10.0,13.0,-3.0
3,2026_06_BUF_LV,6,BUF,LV,0,33.0,30.0,3.0
4,2026_06_CAR_PHI,6,CAR,PHI,0,25.0,14.0,11.0
5,2026_06_CHI_ATL,6,CHI,ATL,0,31.0,23.0,8.0
6,2026_06_BAL_CLE,6,CLE,BAL,1,13.0,10.0,3.0
7,2026_06_DAL_GB,6,DAL,GB,0,13.0,23.0,-10.0
8,2026_06_SEA_DEN,6,DEN,SEA,1,17.0,14.0,3.0
9,2026_06_DAL_GB,6,GB,DAL,1,23.0,13.0,10.0
10,2026_06_HOU_JAX,6,HOU,JAX,0,34.0,31.0,3.0
11,2026_06_TEN_IND,6,IND,TEN,1,20.0,26.0,-6.0
12,2026_06_HOU_JAX,6,JAX,HOU,1,31.0,34.0,-3.0
13,2026_06_LAC_KC,6,KC,LAC,1,22.0,6.0,16.0
14,2026_06_ARI_LA,6,LA,ARI,1,16.0,18.0,-2.0
15,2026_06_LAC_KC,6,LAC,KC,0,6.0,22.0,-16.0
16,2026_06_BUF_LV,6,LV,BUF,1,30.0,33.0,-3.0
17,2026_06_NYJ_NE,6,NE,NYJ,1,26.0,19.0,7.0
18,2026_06_NO_NYG,6,NO,NYG,0,34.0,27.0,7.0
19,2026_06_NO_NYG,6,NYG,NO,1,27.0,34.0,-7.0
20,2026_06_NYJ_NE,6,NYJ,NE,0,19.0,26.0,-7.0
21,2026_06_CAR_PHI,6,PHI,CAR,1,14.0,25.0,-11.0
22,2026_06_PIT_TB,6,PIT,TB,0,26.0,19.0,7.0
23,2026_06_SEA_DEN,6,SEA,DEN,0,14.0,17.0,-3.0
24,2026_06_WAS_SF,6,SF,WAS,1,23.0,17.0,6.0
25,2026_06_PIT_TB,6,TB,PIT,1,19.0,26.0,-7.0
26,2026_06_TEN_IND,6,TEN,IND,0,26.0,20.0,6.0
27,2026_06_WAS_SF,6,WAS,SF,0,17.0,23.0,-6.0

# Attach Entering Team and Opponent Strength

Each team's performance is evaluated relative to what the model believed before the game was played.

For Week 3 projections, Week 2 ratings represent the information available entering Week 2.

This prevents the opponent adjustment from using future information or the same results that are currently being evaluated.

In [19]:
prior_strength = pd.read_parquet(
    prior_strength_path
).copy()

required_prior_columns = [
    "team",
    "weekly_team_strength",
    "weekly_strength_rank"
]

missing_prior_columns = [
    col
    for col in required_prior_columns
    if col not in prior_strength.columns
]

if missing_prior_columns:
    raise KeyError(
        "Missing prior-week strength columns: "
        + ", ".join(missing_prior_columns)
    )

prior_strength = prior_strength[
    required_prior_columns
].rename(
    columns={
        "weekly_team_strength": "entering_team_strength",
        "weekly_strength_rank": "entering_strength_rank"
    }
)

print(
    f"Week {PRIOR_WEEK} entering ratings loaded:",
    len(prior_strength)
)

display(
    prior_strength.sort_values(
        "entering_strength_rank"
    )
)

Week 6 entering ratings loaded: 32

   team  entering_team_strength  entering_strength_rank
0    SF                5.532855                       1
1   BUF                5.393291                       2
2   SEA                4.200461                       3
3    NE                3.901913                       4
4    LA                3.860944                       5
5   JAX                3.774217                       6
6   BAL                3.254665                       7
7    KC                3.165481                       8
8   MIN                3.140947                       9
9   DEN                2.901957                      10
10  DET                2.858510                      11
11   GB                1.458414                      12
12  HOU                1.429501                      13
13  CHI                0.797487                      14
14  CIN                0.772808                      15
15  PIT                0.534587                      16
16  PHI                0.451342                      17
17  IND               -0.089195                      18
18  DAL               -0.585702                      19
19   TB               -0.803072                      20
20  ATL               -0.893777                      21
21  LAC               -1.837208                      22
22  NYG               -2.640440                      23
23   NO               -2.938405                      24
24  WAS               -3.281754                      25
25   LV               -3.396294                      26
26  CAR               -3.513248                      27
27  CLE               -4.119980                      28
28  NYJ               -4.305707                      29
29  MIA               -5.315924                      30
30  ARI               -5.577328                      31
31  TEN               -8.075316                      32

In [20]:
team_games = team_games.merge(
    prior_strength[
        [
            "team",
            "entering_team_strength",
            "entering_strength_rank"
        ]
    ],
    on="team",
    how="left",
    validate="many_to_one"
)

opponent_strength = prior_strength[
    [
        "team",
        "entering_team_strength",
        "entering_strength_rank"
    ]
].rename(
    columns={
        "team": "opponent",
        "entering_team_strength": "opponent_entering_strength",
        "entering_strength_rank": "opponent_entering_rank"
    }
)

team_games = team_games.merge(
    opponent_strength,
    on="opponent",
    how="left",
    validate="many_to_one"
)

display(
    team_games[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "opponent",
            "opponent_entering_rank",
            "opponent_entering_strength",
            "points_for",
            "points_against",
            "point_margin"
        ]
    ].sort_values(
        "entering_strength_rank"
    )
)

,team,entering_strength_rank,entering_team_strength,opponent,opponent_entering_rank,opponent_entering_strength,points_for,points_against,point_margin
24,SF,1,5.532855,WAS,25,-3.281754,23.0,17.0,6.0
3,BUF,2,5.393291,LV,26,-3.396294,33.0,30.0,3.0
23,SEA,3,4.200461,DEN,10,2.901957,14.0,17.0,-3.0
17,NE,4,3.901913,NYJ,29,-4.305707,26.0,19.0,7.0
14,LA,5,3.860944,ARI,31,-5.577328,16.0,18.0,-2.0
12,JAX,6,3.774217,HOU,13,1.429501,31.0,34.0,-3.0
2,BAL,7,3.254665,CLE,28,-4.119980,10.0,13.0,-3.0
13,KC,8,3.165481,LAC,22,-1.837208,22.0,6.0,16.0
8,DEN,10,2.901957,SEA,3,4.200461,17.0,14.0,3.0
9,GB,12,1.458414,DAL,19,-0.585702,23.0,13.0,10.0
10,HOU,13,1.429501,JAX,6,3.774217,34.0,31.0,3.0
5,CHI,14,0.797487,ATL,21,-0.893777,31.0,23.0,8.0
22,PIT,16,0.534587,TB,20,-0.803072,26.0,19.0,7.0
21,PHI,17,0.451342,CAR,27,-3.513248,14.0,25.0,-11.0
11,IND,18,-0.089195,TEN,32,-8.075316,20.0,26.0,-6.0
7,DAL,19,-0.585702,GB,12,1.458414,13.0,23.0,-10.0
25,TB,20,-0.803072,PIT,16,0.534587,19.0,26.0,-7.0
1,ATL,21,-0.893777,CHI,14,0.797487,23.0,31.0,-8.0
15,LAC,22,-1.837208,KC,8,3.165481,6.0,22.0,-16.0
19,NYG,23,-2.640440,NO,24,-2.938405,27.0,34.0,-7.0
18,NO,24,-2.938405,NYG,23,-2.640440,34.0,27.0,7.0
27,WAS,25,-3.281754,SF,1,5.532855,17.0,23.0,-6.0
16,LV,26,-3.396294,BUF,2,5.393291,30.0,33.0,-3.0
4,CAR,27,-3.513248,PHI,17,0.451342,25.0,14.0,11.0
6,CLE,28,-4.119980,BAL,7,3.254665,13.0,10.0,3.0
20,NYJ,29,-4.305707,NE,4,3.901913,19.0,26.0,-7.0
0,ARI,31,-5.577328,LA,5,3.860944,18.0,16.0,2.0
26,TEN,32,-8.075316,IND,18,-0.089195,26.0,20.0,6.0

# Expected Margin and Opponent-Adjusted Performance

The weekly update is based on how a team performed relative to expectation.

For each team game:

`performance residual = actual margin - expected margin`

Expected margin uses the difference between the two teams' entering strength ratings plus home field advantage.

This means beating a strong opponent is more informative than producing the same result against a weak opponent.

In [21]:
HOME_FIELD_POINTS = 1.5

team_games["expected_margin"] = (
    team_games["entering_team_strength"]
    - team_games["opponent_entering_strength"]
    + np.where(
        team_games["is_home"] == 1,
        HOME_FIELD_POINTS,
        -HOME_FIELD_POINTS
    )
)

team_games["performance_residual"] = (
    team_games["point_margin"]
    - team_games["expected_margin"]
)

display(
    team_games[
        [
            "team",
            "opponent",
            "entering_team_strength",
            "opponent_entering_strength",
            "point_margin",
            "expected_margin",
            "performance_residual"
        ]
    ].sort_values(
        "performance_residual",
        ascending=False
    )
)

,team,opponent,entering_team_strength,opponent_entering_strength,point_margin,expected_margin,performance_residual
4,CAR,PHI,-3.513248,0.451342,11.0,-5.464590,16.464590
26,TEN,IND,-8.075316,-0.089195,6.0,-9.486120,15.486120
0,ARI,LA,-5.577328,3.860944,2.0,-10.938272,12.938272
13,KC,LAC,3.165481,-1.837208,16.0,6.502689,9.497311
6,CLE,BAL,-4.119980,3.254665,3.0,-5.874645,8.874645
18,NO,NYG,-2.938405,-2.640440,7.0,-1.797965,8.797965
5,CHI,ATL,0.797487,-0.893777,8.0,0.191264,7.808736
22,PIT,TB,0.534587,-0.803072,7.0,-0.162341,7.162341
10,HOU,JAX,1.429501,3.774217,3.0,-3.844716,6.844716
9,GB,DAL,1.458414,-0.585702,10.0,3.544117,6.455883
27,WAS,SF,-3.281754,5.532855,-6.0,-10.314609,4.314609
16,LV,BUF,-3.396294,5.393291,-3.0,-7.289585,4.289585
8,DEN,SEA,2.901957,4.200461,3.0,0.201495,2.798505
20,NYJ,NE,-4.305707,3.901913,-7.0,-9.707620,2.707620
17,NE,NYJ,3.901913,-4.305707,7.0,9.707620,-2.707620
23,SEA,DEN,4.200461,2.901957,-3.0,-0.201495,-2.798505
3,BUF,LV,5.393291,-3.396294,3.0,7.289585,-4.289585
24,SF,WAS,5.532855,-3.281754,6.0,10.314609,-4.314609
7,DAL,GB,-0.585702,1.458414,-10.0,-3.544117,-6.455883
12,JAX,HOU,3.774217,1.429501,-3.0,3.844716,-6.844716
25,TB,PIT,-0.803072,0.534587,-7.0,0.162341,-7.162341
1,ATL,CHI,-0.893777,0.797487,-8.0,-0.191264,-7.808736
19,NYG,NO,-2.640440,-2.938405,-7.0,1.797965,-8.797965
2,BAL,CLE,3.254665,-4.119980,-3.0,5.874645,-8.874645
15,LAC,KC,-1.837208,3.165481,-16.0,-6.502689,-9.497311
14,LA,ARI,3.860944,-5.577328,-2.0,10.938272,-12.938272
11,IND,TEN,-0.089195,-8.075316,-6.0,9.486120,-15.486120
21,PHI,CAR,0.451342,-3.513248,-11.0,5.464590,-16.464590

# Control Extreme Single-Game Results

NFL game margins contain substantial single-game noise.

A blowout should affect team strength, but one extreme result should not completely redefine the team's rating.

Performance residuals are therefore capped before the weekly learning rate is applied.

In [22]:
RESIDUAL_SCALE = 14.0
MAX_WEEKLY_UPDATE = 1.5

team_games["weekly_strength_update"] = (
    MAX_WEEKLY_UPDATE
    * np.tanh(
        team_games["performance_residual"]
        / RESIDUAL_SCALE
    )
)

display(
    team_games[
        [
            "team",
            "opponent",
            "point_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,opponent,point_margin,expected_margin,performance_residual,weekly_strength_update
4,CAR,PHI,11.0,-5.464590,16.464590,1.239299
26,TEN,IND,6.0,-9.486120,15.486120,1.204047
0,ARI,LA,2.0,-10.938272,12.938272,1.091791
13,KC,LAC,16.0,6.502689,9.497311,0.885697
6,CLE,BAL,3.0,-5.874645,8.874645,0.841101
18,NO,NYG,7.0,-1.797965,8.797965,0.835451
5,CHI,ATL,8.0,0.191264,7.808736,0.759478
22,PIT,TB,7.0,-0.162341,7.162341,0.706781
10,HOU,JAX,3.0,-3.844716,6.844716,0.680024
9,GB,DAL,10.0,3.544117,6.455883,0.646513
27,WAS,SF,-6.0,-10.314609,4.314609,0.448179
16,LV,BUF,-3.0,-7.289585,4.289585,0.445736
8,DEN,SEA,3.0,0.201495,2.798505,0.295909
20,NYJ,NE,-7.0,-9.707620,2.707620,0.286538
17,NE,NYJ,7.0,9.707620,-2.707620,-0.286538
23,SEA,DEN,-3.0,-0.201495,-2.798505,-0.295909
3,BUF,LV,3.0,7.289585,-4.289585,-0.445736
24,SF,WAS,6.0,10.314609,-4.314609,-0.448179
7,DAL,GB,-10.0,-3.544117,-6.455883,-0.646513
12,JAX,HOU,-3.0,3.844716,-6.844716,-0.680024
25,TB,PIT,-7.0,0.162341,-7.162341,-0.706781
1,ATL,CHI,-8.0,-0.191264,-7.808736,-0.759478
19,NYG,NO,-7.0,1.797965,-8.797965,-0.835451
2,BAL,CLE,-3.0,5.874645,-8.874645,-0.841101
15,LAC,KC,-16.0,-6.502689,-9.497311,-0.885697
14,LA,ARI,-2.0,10.938272,-12.938272,-1.091791
11,IND,TEN,-6.0,9.486120,-15.486120,-1.204047
21,PHI,CAR,-11.0,5.464590,-16.464590,-1.239299

# Offensive and Defensive Weekly Signals

Overall team strength uses the opponent adjusted margin residual.

We also preserve separate offensive and defensive signals because the weekly game projection model needs scoring information.

These are weekly updates, not cumulative season averages.

Opponent entering strength is used conservatively as context until separate entering offensive and defensive strength ratings are maintained.

In [23]:
league_points_per_team_game = (
    team_games["points_for"].mean()
)

OPPONENT_CONTEXT_RATE = 0.25
OFFENSE_DEFENSE_UPDATE_RATE = 0.15

team_games["raw_offense_performance"] = (
    team_games["points_for"]
    - league_points_per_team_game
)

team_games["raw_defense_performance"] = (
    league_points_per_team_game
    - team_games["points_against"]
)

team_games["adjusted_offense_performance"] = (
    team_games["raw_offense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["adjusted_defense_performance"] = (
    team_games["raw_defense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["weekly_offense_adjustment"] = (
    team_games["adjusted_offense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

team_games["weekly_defense_adjustment"] = (
    team_games["adjusted_defense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

display(
    team_games[
        [
            "team",
            "opponent",
            "points_for",
            "points_against",
            "opponent_entering_strength",
            "raw_offense_performance",
            "adjusted_offense_performance",
            "weekly_offense_adjustment",
            "raw_defense_performance",
            "adjusted_defense_performance",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "team"
    )
)

,team,opponent,points_for,points_against,opponent_entering_strength,raw_offense_performance,adjusted_offense_performance,weekly_offense_adjustment,raw_defense_performance,adjusted_defense_performance,weekly_defense_adjustment
0,ARI,LA,18.0,16.0,3.860944,-3.785714,-2.820478,-0.423072,5.785714,6.750950,1.012643
1,ATL,CHI,23.0,31.0,0.797487,1.214286,1.413657,0.212049,-9.214286,-9.014914,-1.352237
2,BAL,CLE,10.0,13.0,-4.119980,-11.785714,-12.815709,-1.922356,8.785714,7.755719,1.163358
3,BUF,LV,33.0,30.0,-3.396294,11.214286,10.365212,1.554782,-8.214286,-9.063359,-1.359504
4,CAR,PHI,25.0,14.0,0.451342,3.214286,3.327121,0.499068,7.785714,7.898550,1.184782
5,CHI,ATL,31.0,23.0,-0.893777,9.214286,8.990842,1.348626,-1.214286,-1.437730,-0.215659
6,CLE,BAL,13.0,10.0,3.254665,-8.785714,-7.972048,-1.195807,11.785714,12.599381,1.889907
7,DAL,GB,13.0,23.0,1.458414,-8.785714,-8.421111,-1.263167,-1.214286,-0.849682,-0.127452
8,DEN,SEA,17.0,14.0,4.200461,-4.785714,-3.735599,-0.560340,7.785714,8.835830,1.325374
9,GB,DAL,23.0,13.0,-0.585702,1.214286,1.067860,0.160179,8.785714,8.639289,1.295893
10,HOU,JAX,34.0,31.0,3.774217,12.214286,13.157840,1.973676,-9.214286,-8.270731,-1.240610
11,IND,TEN,20.0,26.0,-8.075316,-1.785714,-3.804543,-0.570681,-4.214286,-6.233115,-0.934967
12,JAX,HOU,31.0,34.0,1.429501,9.214286,9.571661,1.435749,-12.214286,-11.856910,-1.778537
13,KC,LAC,22.0,6.0,-1.837208,0.214286,-0.245016,-0.036752,15.785714,15.326412,2.298962
14,LA,ARI,16.0,18.0,-5.577328,-5.785714,-7.180046,-1.077007,3.785714,2.391382,0.358707
15,LAC,KC,6.0,22.0,3.165481,-15.785714,-14.994344,-2.249152,-0.214286,0.577085,0.086563
16,LV,BUF,30.0,33.0,5.393291,8.214286,9.562608,1.434391,-11.214286,-9.865963,-1.479894
17,NE,NYJ,26.0,19.0,-4.305707,4.214286,3.137859,0.470679,2.785714,1.709288,0.256393
18,NO,NYG,34.0,27.0,-2.640440,12.214286,11.554176,1.733126,-5.214286,-5.874396,-0.881159
19,NYG,NO,27.0,34.0,-2.938405,5.214286,4.479684,0.671953,-12.214286,-12.948887,-1.942333
20,NYJ,NE,19.0,26.0,3.901913,-2.785714,-1.810236,-0.271535,-4.214286,-3.238807,-0.485821
21,PHI,CAR,14.0,25.0,-3.513248,-7.785714,-8.664026,-1.299604,-3.214286,-4.092598,-0.613890
22,PIT,TB,26.0,19.0,-0.803072,4.214286,4.013518,0.602028,2.785714,2.584946,0.387742
23,SEA,DEN,14.0,17.0,2.901957,-7.785714,-7.060225,-1.059034,4.785714,5.511203,0.826681
24,SF,WAS,23.0,17.0,-3.281754,1.214286,0.393847,0.059077,4.785714,3.965276,0.594791
25,TB,PIT,19.0,26.0,0.534587,-2.785714,-2.652068,-0.397810,-4.214286,-4.080639,-0.612096
26,TEN,IND,26.0,20.0,-0.089195,4.214286,4.191987,0.628798,1.785714,1.763415,0.264512
27,WAS,SF,17.0,23.0,5.532855,-4.785714,-3.402501,-0.510375,-1.214286,0.168928,0.025339

# Build Week-Level Feature Table

The final feature table contains only the new evidence that should move the prior week's ratings.

For Week 3:

`Week 3 strength = Week 2 strength + Week 2 performance update`

The previous week's rating therefore acts as the prior, and older games are not counted again.

In [24]:
team_features = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_in_update=("game_id", "count"),

        entering_team_strength=(
            "entering_team_strength",
            "first"
        ),

        entering_strength_rank=(
            "entering_strength_rank",
            "first"
        ),

        average_opponent_strength=(
            "opponent_entering_strength",
            "mean"
        ),

        average_opponent_rank=(
            "opponent_entering_rank",
            "mean"
        ),

        actual_margin=(
            "point_margin",
            "mean"
        ),

        expected_margin=(
            "expected_margin",
            "mean"
        ),

        performance_residual=(
            "performance_residual",
            "mean"
        ),

        weekly_strength_update=(
            "weekly_strength_update",
            "mean"
        ),

        weekly_offense_adjustment=(
            "weekly_offense_adjustment",
            "mean"
        ),

        weekly_defense_adjustment=(
            "weekly_defense_adjustment",
            "mean"
        )
    )
)

display(
    team_features[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "average_opponent_rank",
            "average_opponent_strength",
            "actual_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,entering_strength_rank,entering_team_strength,average_opponent_rank,average_opponent_strength,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
4,CAR,27,-3.513248,17.0,0.451342,11.0,-5.464590,16.464590,1.239299,0.499068,1.184782
26,TEN,32,-8.075316,18.0,-0.089195,6.0,-9.486120,15.486120,1.204047,0.628798,0.264512
0,ARI,31,-5.577328,5.0,3.860944,2.0,-10.938272,12.938272,1.091791,-0.423072,1.012643
13,KC,8,3.165481,22.0,-1.837208,16.0,6.502689,9.497311,0.885697,-0.036752,2.298962
6,CLE,28,-4.119980,7.0,3.254665,3.0,-5.874645,8.874645,0.841101,-1.195807,1.889907
18,NO,24,-2.938405,23.0,-2.640440,7.0,-1.797965,8.797965,0.835451,1.733126,-0.881159
5,CHI,14,0.797487,21.0,-0.893777,8.0,0.191264,7.808736,0.759478,1.348626,-0.215659
22,PIT,16,0.534587,20.0,-0.803072,7.0,-0.162341,7.162341,0.706781,0.602028,0.387742
10,HOU,13,1.429501,6.0,3.774217,3.0,-3.844716,6.844716,0.680024,1.973676,-1.240610
9,GB,12,1.458414,19.0,-0.585702,10.0,3.544117,6.455883,0.646513,0.160179,1.295893
27,WAS,25,-3.281754,1.0,5.532855,-6.0,-10.314609,4.314609,0.448179,-0.510375,0.025339
16,LV,26,-3.396294,2.0,5.393291,-3.0,-7.289585,4.289585,0.445736,1.434391,-1.479894
8,DEN,10,2.901957,3.0,4.200461,3.0,0.201495,2.798505,0.295909,-0.560340,1.325374
20,NYJ,29,-4.305707,4.0,3.901913,-7.0,-9.707620,2.707620,0.286538,-0.271535,-0.485821
17,NE,4,3.901913,29.0,-4.305707,7.0,9.707620,-2.707620,-0.286538,0.470679,0.256393
23,SEA,3,4.200461,10.0,2.901957,-3.0,-0.201495,-2.798505,-0.295909,-1.059034,0.826681
3,BUF,2,5.393291,26.0,-3.396294,3.0,7.289585,-4.289585,-0.445736,1.554782,-1.359504
24,SF,1,5.532855,25.0,-3.281754,6.0,10.314609,-4.314609,-0.448179,0.059077,0.594791
7,DAL,19,-0.585702,12.0,1.458414,-10.0,-3.544117,-6.455883,-0.646513,-1.263167,-0.127452
12,JAX,6,3.774217,13.0,1.429501,-3.0,3.844716,-6.844716,-0.680024,1.435749,-1.778537
25,TB,20,-0.803072,16.0,0.534587,-7.0,0.162341,-7.162341,-0.706781,-0.397810,-0.612096
1,ATL,21,-0.893777,14.0,0.797487,-8.0,-0.191264,-7.808736,-0.759478,0.212049,-1.352237
19,NYG,23,-2.640440,24.0,-2.938405,-7.0,1.797965,-8.797965,-0.835451,0.671953,-1.942333
2,BAL,7,3.254665,28.0,-4.119980,-3.0,5.874645,-8.874645,-0.841101,-1.922356,1.163358
15,LAC,22,-1.837208,8.0,3.165481,-16.0,-6.502689,-9.497311,-0.885697,-2.249152,0.086563
14,LA,5,3.860944,31.0,-5.577328,-2.0,10.938272,-12.938272,-1.091791,-1.077007,0.358707
11,IND,18,-0.089195,32.0,-8.075316,-6.0,9.486120,-15.486120,-1.204047,-0.570681,-0.934967
21,PHI,17,0.451342,27.0,-3.513248,-11.0,5.464590,-16.464590,-1.239299,-1.299604,-0.613890

# Sanity Checks

Before saving, verify that:

- all 32 teams are represented
- every team has an entering Week 2 rating
- every opponent has an entering Week 2 rating
- no Week 3 game results were used
- weekly strength updates remain within the intended cap

In [25]:
print("Teams in feature table:", len(team_features))
print(
    "Unique teams:",
    team_features["team"].nunique()
)

print(
    "Missing entering team strengths:",
    team_features[
        "entering_team_strength"
    ].isna().sum()
)

print(
    "Missing opponent strengths:",
    team_features[
        "average_opponent_strength"
    ].isna().sum()
)

print(
    "Largest positive weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].max(),
        3
    )
)

print(
    "Largest negative weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].min(),
        3
    )
)

if (
    completed_games["week"] >= TARGET_WEEK
).any():
    raise ValueError(
        "DATA LEAKAGE: target-week results "
        "were found in completed games."
    )

if len(team_features) != 32:
    print()
    print(
        "WARNING: Feature table does not "
        "contain all 32 teams."
    )

Teams in feature table: 28
Unique teams: 28
Missing entering team strengths: 0
Missing opponent strengths: 0
Largest positive weekly update: 1.239
Largest negative weekly update: -1.239

WARNING: Feature table does not contain all 32 teams.

# Save In Season Feature Table

This output will be consumed by:

`04_Weekly_Team_Strength.ipynb`

The file contains only the new in season evidence. It does not overwrite or replace the preseason team strength table.

In [26]:
output_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

team_features = team_features.sort_values(
    "team"
).reset_index(drop=True)

team_features.to_parquet(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: ..\..\data\processed\weekly\week_07_inseason_features.parquet

# Interpretation

The weekly model is now sequential.

For Week 3:

1. Week 2 team strength is treated as the entering prior.
2. Only Week 2 game results provide new evidence.
3. Performance is evaluated relative to the opponent's entering strength.
4. Extreme single game residuals are capped.
5. A conservative learning rate determines the weekly rating movement.
6. The resulting update will be added to the Week 2 rating in `04_Weekly_Team_Strength.ipynb`.

This prevents older games from being counted repeatedly and makes strength of opponent part of every weekly update.

The frozen preseason model remains unchanged.