# 03 — In Season Feature Engineering

This notebook creates the weekly performance features used by the in season projection layer.

It does not modify the original preseason notebooks or their outputs.

The purpose of this notebook is to convert completed regular season games into team level offensive and defensive performance features that can later be blended with the frozen preseason model.

For a selected target week, the notebook:

- Loads only completed games from weeks before the target week
- Builds team level scoring and margin summaries
- Separates offense and defense
- Adds simple opponent adjusted performance features
- Applies early season shrinkage to reduce overreaction to small samples
- Saves a clean feature table for the weekly team strength notebook

This notebook is intentionally conservative after Week 1. One game should inform the model, not redefine it.

In [27]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the outputs created by:

`02_Weekly_Data_Update.ipynb`

The only value that normally changes week to week is `TARGET_WEEK`.

In [28]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 6
PRIOR_WEEK = TARGET_WEEK - 1

completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

prior_strength_path = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

print("Using completed games:", completed_games_path)
print("Using entering ratings:", prior_strength_path)

Using completed games: ..\..\data\processed\weekly\week_06_completed_games.parquet
Using entering ratings: ..\..\data\processed\weekly\week_05_sequential_team_strength.parquet

# Load Completed Games

Only games completed before the target week should exist in this file.

That leakage rule was enforced in `02_Weekly_Data_Update.ipynb`.

In [29]:
completed_games = pd.read_parquet(
    completed_games_path
)

completed_games = completed_games.sort_values(
    ["week", "gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Completed games available before Week {TARGET_WEEK}:",
    len(completed_games)
)

display(
    completed_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Completed games available before Week 6: 79

    week     gameday away_team  away_score home_team  home_score
0      1  2026-09-09        NE        10.0       SEA        13.0
1      1  2026-09-10        SF        27.0        LA         7.0
2      1  2026-09-13       ARI        26.0       LAC        14.0
3      1  2026-09-13       ATL        13.0       PIT        20.0
4      1  2026-09-13       BAL        41.0       IND        23.0
..   ...         ...       ...         ...       ...         ...
74     5  2026-10-11       MIN        23.0        NO        13.0
75     5  2026-10-11       NYG        27.0       WAS        27.0
76     5  2026-10-11       PHI        17.0       JAX        19.0
77     5  2026-10-11        SF        32.0       SEA        29.0
78     5  2026-10-12       BUF        37.0        LA        34.0

[79 rows x 6 columns]

In [30]:
update_games = completed_games[
    completed_games["week"] == PRIOR_WEEK
].copy()

update_games = update_games.sort_values(
    ["gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Week {PRIOR_WEEK} games used to update "
    f"Week {TARGET_WEEK} ratings:",
    len(update_games)
)

display(
    update_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Week 5 games used to update Week 6 ratings: 15

    week     gameday away_team  away_score home_team  home_score
0      5  2026-10-08        TB        24.0       DAL        16.0
1      5  2026-10-11       BAL        30.0       ATL        23.0
2      5  2026-10-11       CHI         7.0        GB        31.0
3      5  2026-10-11       CIN        31.0       MIA        24.0
4      5  2026-10-11       CLE        12.0       NYJ        17.0
5      5  2026-10-11       DEN        23.0       LAC        17.0
6      5  2026-10-11       DET        45.0       ARI        21.0
7      5  2026-10-11       HOU        26.0       TEN         3.0
8      5  2026-10-11       IND        22.0       PIT        34.0
9      5  2026-10-11        LV        17.0        NE        45.0
10     5  2026-10-11       MIN        23.0        NO        13.0
11     5  2026-10-11       NYG        27.0       WAS        27.0
12     5  2026-10-11       PHI        17.0       JAX        19.0
13     5  2026-10-11        SF        32.0       SEA        29.0
14     5  2026-10-12       BUF        37.0        LA        34.0

# Convert Prior Week Games to Team Game Rows

Only the most recently completed week is used for the new weekly update.

For Week 3:

- Week 2 team strength is the entering prior
- Week 2 game performance is the new evidence
- Week 1 is not counted again because it is already reflected in the Week 2 ratings

Each game becomes two rows:

- one from the home team's perspective
- one from the away team's perspective

In [31]:
home_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["home_team"],
        "opponent": update_games["away_team"],
        "is_home": 1,
        "points_for": update_games["home_score"],
        "points_against": update_games["away_score"]
    }
)

away_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["away_team"],
        "opponent": update_games["home_team"],
        "is_home": 0,
        "points_for": update_games["away_score"],
        "points_against": update_games["home_score"]
    }
)

team_games = pd.concat(
    [home_rows, away_rows],
    ignore_index=True
)

team_games["point_margin"] = (
    team_games["points_for"]
    - team_games["points_against"]
)

team_games = team_games.sort_values(
    ["team", "game_id"]
).reset_index(drop=True)

print("Team-game rows:", len(team_games))

display(team_games)

Team-game rows: 30

,game_id,week,team,opponent,is_home,points_for,points_against,point_margin
0,2026_05_DET_ARI,5,ARI,DET,1,21.0,45.0,-24.0
1,2026_05_BAL_ATL,5,ATL,BAL,1,23.0,30.0,-7.0
2,2026_05_BAL_ATL,5,BAL,ATL,0,30.0,23.0,7.0
3,2026_05_BUF_LA,5,BUF,LA,0,37.0,34.0,3.0
4,2026_05_CHI_GB,5,CHI,GB,0,7.0,31.0,-24.0
5,2026_05_CIN_MIA,5,CIN,MIA,0,31.0,24.0,7.0
6,2026_05_CLE_NYJ,5,CLE,NYJ,0,12.0,17.0,-5.0
7,2026_05_TB_DAL,5,DAL,TB,1,16.0,24.0,-8.0
8,2026_05_DEN_LAC,5,DEN,LAC,0,23.0,17.0,6.0
9,2026_05_DET_ARI,5,DET,ARI,0,45.0,21.0,24.0
10,2026_05_CHI_GB,5,GB,CHI,1,31.0,7.0,24.0
11,2026_05_HOU_TEN,5,HOU,TEN,0,26.0,3.0,23.0
12,2026_05_IND_PIT,5,IND,PIT,0,22.0,34.0,-12.0
13,2026_05_PHI_JAX,5,JAX,PHI,1,19.0,17.0,2.0
14,2026_05_BUF_LA,5,LA,BUF,1,34.0,37.0,-3.0
15,2026_05_DEN_LAC,5,LAC,DEN,1,17.0,23.0,-6.0
16,2026_05_LV_NE,5,LV,NE,0,17.0,45.0,-28.0
17,2026_05_CIN_MIA,5,MIA,CIN,1,24.0,31.0,-7.0
18,2026_05_MIN_NO,5,MIN,NO,0,23.0,13.0,10.0
19,2026_05_LV_NE,5,NE,LV,1,45.0,17.0,28.0
20,2026_05_MIN_NO,5,NO,MIN,1,13.0,23.0,-10.0
21,2026_05_NYG_WAS,5,NYG,WAS,0,27.0,27.0,0.0
22,2026_05_CLE_NYJ,5,NYJ,CLE,1,17.0,12.0,5.0
23,2026_05_PHI_JAX,5,PHI,JAX,0,17.0,19.0,-2.0
24,2026_05_IND_PIT,5,PIT,IND,1,34.0,22.0,12.0
25,2026_05_SF_SEA,5,SEA,SF,1,29.0,32.0,-3.0
26,2026_05_SF_SEA,5,SF,SEA,0,32.0,29.0,3.0
27,2026_05_TB_DAL,5,TB,DAL,0,24.0,16.0,8.0
28,2026_05_HOU_TEN,5,TEN,HOU,1,3.0,26.0,-23.0
29,2026_05_NYG_WAS,5,WAS,NYG,1,27.0,27.0,0.0

# Attach Entering Team and Opponent Strength

Each team's performance is evaluated relative to what the model believed before the game was played.

For Week 3 projections, Week 2 ratings represent the information available entering Week 2.

This prevents the opponent adjustment from using future information or the same results that are currently being evaluated.

In [32]:
prior_strength = pd.read_parquet(
    prior_strength_path
).copy()

required_prior_columns = [
    "team",
    "weekly_team_strength",
    "weekly_strength_rank"
]

missing_prior_columns = [
    col
    for col in required_prior_columns
    if col not in prior_strength.columns
]

if missing_prior_columns:
    raise KeyError(
        "Missing prior-week strength columns: "
        + ", ".join(missing_prior_columns)
    )

prior_strength = prior_strength[
    required_prior_columns
].rename(
    columns={
        "weekly_team_strength": "entering_team_strength",
        "weekly_strength_rank": "entering_strength_rank"
    }
)

print(
    f"Week {PRIOR_WEEK} entering ratings loaded:",
    len(prior_strength)
)

display(
    prior_strength.sort_values(
        "entering_strength_rank"
    )
)

Week 5 entering ratings loaded: 32

   team  entering_team_strength  entering_strength_rank
0    SF                5.115310                       1
1   BUF                5.000529                       2
2   SEA                4.618006                       3
3    LA                4.253705                       4
4   JAX                4.148852                       5
5    KC                3.165481                       6
6   BAL                2.696986                       7
7   DEN                2.535135                       8
8    NE                2.526854                       9
9   MIN                2.467510                      10
10  CHI                2.211567                      11
11  DET                1.527588                      12
12  IND                0.950515                      13
13  CIN                0.450493                      14
14  DAL                0.443958                      15
15  HOU                0.155800                      16
16  PHI                0.076707                      17
17   GB                0.044335                      18
18  ATL               -0.336098                      19
19  PIT               -0.505123                      20
20  LAC               -1.470386                      21
21   TB               -1.832732                      22
22   LV               -2.021235                      23
23   NO               -2.264969                      24
24  NYG               -2.757233                      25
25  WAS               -3.164962                      26
26  CAR               -3.513248                      27
27  CLE               -3.639662                      28
28  ARI               -4.246405                      29
29  NYJ               -4.786024                      30
30  MIA               -4.993609                      31
31  TEN               -6.801614                      32

In [33]:
team_games = team_games.merge(
    prior_strength[
        [
            "team",
            "entering_team_strength",
            "entering_strength_rank"
        ]
    ],
    on="team",
    how="left",
    validate="many_to_one"
)

opponent_strength = prior_strength[
    [
        "team",
        "entering_team_strength",
        "entering_strength_rank"
    ]
].rename(
    columns={
        "team": "opponent",
        "entering_team_strength": "opponent_entering_strength",
        "entering_strength_rank": "opponent_entering_rank"
    }
)

team_games = team_games.merge(
    opponent_strength,
    on="opponent",
    how="left",
    validate="many_to_one"
)

display(
    team_games[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "opponent",
            "opponent_entering_rank",
            "opponent_entering_strength",
            "points_for",
            "points_against",
            "point_margin"
        ]
    ].sort_values(
        "entering_strength_rank"
    )
)

,team,entering_strength_rank,entering_team_strength,opponent,opponent_entering_rank,opponent_entering_strength,points_for,points_against,point_margin
26,SF,1,5.115310,SEA,3,4.618006,32.0,29.0,3.0
3,BUF,2,5.000529,LA,4,4.253705,37.0,34.0,3.0
25,SEA,3,4.618006,SF,1,5.115310,29.0,32.0,-3.0
14,LA,4,4.253705,BUF,2,5.000529,34.0,37.0,-3.0
13,JAX,5,4.148852,PHI,17,0.076707,19.0,17.0,2.0
2,BAL,7,2.696986,ATL,19,-0.336098,30.0,23.0,7.0
8,DEN,8,2.535135,LAC,21,-1.470386,23.0,17.0,6.0
19,NE,9,2.526854,LV,23,-2.021235,45.0,17.0,28.0
18,MIN,10,2.467510,NO,24,-2.264969,23.0,13.0,10.0
4,CHI,11,2.211567,GB,18,0.044335,7.0,31.0,-24.0
9,DET,12,1.527588,ARI,29,-4.246405,45.0,21.0,24.0
12,IND,13,0.950515,PIT,20,-0.505123,22.0,34.0,-12.0
5,CIN,14,0.450493,MIA,31,-4.993609,31.0,24.0,7.0
7,DAL,15,0.443958,TB,22,-1.832732,16.0,24.0,-8.0
11,HOU,16,0.155800,TEN,32,-6.801614,26.0,3.0,23.0
23,PHI,17,0.076707,JAX,5,4.148852,17.0,19.0,-2.0
10,GB,18,0.044335,CHI,11,2.211567,31.0,7.0,24.0
1,ATL,19,-0.336098,BAL,7,2.696986,23.0,30.0,-7.0
24,PIT,20,-0.505123,IND,13,0.950515,34.0,22.0,12.0
15,LAC,21,-1.470386,DEN,8,2.535135,17.0,23.0,-6.0
27,TB,22,-1.832732,DAL,15,0.443958,24.0,16.0,8.0
16,LV,23,-2.021235,NE,9,2.526854,17.0,45.0,-28.0
20,NO,24,-2.264969,MIN,10,2.467510,13.0,23.0,-10.0
21,NYG,25,-2.757233,WAS,26,-3.164962,27.0,27.0,0.0
29,WAS,26,-3.164962,NYG,25,-2.757233,27.0,27.0,0.0
6,CLE,28,-3.639662,NYJ,30,-4.786024,12.0,17.0,-5.0
0,ARI,29,-4.246405,DET,12,1.527588,21.0,45.0,-24.0
22,NYJ,30,-4.786024,CLE,28,-3.639662,17.0,12.0,5.0
17,MIA,31,-4.993609,CIN,14,0.450493,24.0,31.0,-7.0
28,TEN,32,-6.801614,HOU,16,0.155800,3.0,26.0,-23.0

# Expected Margin and Opponent-Adjusted Performance

The weekly update is based on how a team performed relative to expectation.

For each team game:

`performance residual = actual margin - expected margin`

Expected margin uses the difference between the two teams' entering strength ratings plus home field advantage.

This means beating a strong opponent is more informative than producing the same result against a weak opponent.

In [34]:
HOME_FIELD_POINTS = 1.5

team_games["expected_margin"] = (
    team_games["entering_team_strength"]
    - team_games["opponent_entering_strength"]
    + np.where(
        team_games["is_home"] == 1,
        HOME_FIELD_POINTS,
        -HOME_FIELD_POINTS
    )
)

team_games["performance_residual"] = (
    team_games["point_margin"]
    - team_games["expected_margin"]
)

display(
    team_games[
        [
            "team",
            "opponent",
            "entering_team_strength",
            "opponent_entering_strength",
            "point_margin",
            "expected_margin",
            "performance_residual"
        ]
    ].sort_values(
        "performance_residual",
        ascending=False
    )
)

,team,opponent,entering_team_strength,opponent_entering_strength,point_margin,expected_margin,performance_residual
10,GB,CHI,0.044335,2.211567,24.0,-0.667232,24.667232
19,NE,LV,2.526854,-2.021235,28.0,6.048089,21.951911
9,DET,ARI,1.527588,-4.246405,24.0,4.273993,19.726007
11,HOU,TEN,0.155800,-6.801614,23.0,5.457414,17.542586
24,PIT,IND,-0.505123,0.950515,12.0,0.044362,11.955638
27,TB,DAL,-1.832732,0.443958,8.0,-3.776690,11.776690
18,MIN,NO,2.467510,-2.264969,10.0,3.232479,6.767521
2,BAL,ATL,2.696986,-0.336098,7.0,1.533084,5.466916
22,NYJ,CLE,-4.786024,-3.639662,5.0,0.353638,4.646362
26,SF,SEA,5.115310,4.618006,3.0,-1.002696,4.002696
3,BUF,LA,5.000529,4.253705,3.0,-0.753176,3.753176
23,PHI,JAX,0.076707,4.148852,-2.0,-5.572145,3.572145
8,DEN,LAC,2.535135,-1.470386,6.0,2.505521,3.494479
5,CIN,MIA,0.450493,-4.993609,7.0,3.944102,3.055898
21,NYG,WAS,-2.757233,-3.164962,0.0,-1.092271,1.092271
29,WAS,NYG,-3.164962,-2.757233,0.0,1.092271,-1.092271
17,MIA,CIN,-4.993609,0.450493,-7.0,-3.944102,-3.055898
15,LAC,DEN,-1.470386,2.535135,-6.0,-2.505521,-3.494479
13,JAX,PHI,4.148852,0.076707,2.0,5.572145,-3.572145
14,LA,BUF,4.253705,5.000529,-3.0,0.753176,-3.753176
25,SEA,SF,4.618006,5.115310,-3.0,1.002696,-4.002696
6,CLE,NYJ,-3.639662,-4.786024,-5.0,-0.353638,-4.646362
1,ATL,BAL,-0.336098,2.696986,-7.0,-1.533084,-5.466916
20,NO,MIN,-2.264969,2.467510,-10.0,-3.232479,-6.767521
7,DAL,TB,0.443958,-1.832732,-8.0,3.776690,-11.776690
12,IND,PIT,0.950515,-0.505123,-12.0,-0.044362,-11.955638
28,TEN,HOU,-6.801614,0.155800,-23.0,-5.457414,-17.542586
0,ARI,DET,-4.246405,1.527588,-24.0,-4.273993,-19.726007
16,LV,NE,-2.021235,2.526854,-28.0,-6.048089,-21.951911
4,CHI,GB,2.211567,0.044335,-24.0,0.667232,-24.667232

# Control Extreme Single-Game Results

NFL game margins contain substantial single-game noise.

A blowout should affect team strength, but one extreme result should not completely redefine the team's rating.

Performance residuals are therefore capped before the weekly learning rate is applied.

In [35]:
RESIDUAL_SCALE = 14.0
MAX_WEEKLY_UPDATE = 1.5

team_games["weekly_strength_update"] = (
    MAX_WEEKLY_UPDATE
    * np.tanh(
        team_games["performance_residual"]
        / RESIDUAL_SCALE
    )
)

display(
    team_games[
        [
            "team",
            "opponent",
            "point_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,opponent,point_margin,expected_margin,performance_residual,weekly_strength_update
10,GB,CHI,24.0,-0.667232,24.667232,1.414080
19,NE,LV,28.0,6.048089,21.951911,1.375059
9,DET,ARI,24.0,4.273993,19.726007,1.330923
11,HOU,TEN,23.0,5.457414,17.542586,1.273702
24,PIT,IND,12.0,0.044362,11.955638,1.039710
27,TB,DAL,8.0,-3.776690,11.776690,1.029660
18,MIN,NO,10.0,3.232479,6.767521,0.673437
2,BAL,ATL,7.0,1.533084,5.466916,0.557679
22,NYJ,CLE,5.0,0.353638,4.646362,0.480318
26,SF,SEA,3.0,-1.002696,4.002696,0.417545
3,BUF,LA,3.0,-0.753176,3.753176,0.392762
23,PHI,JAX,-2.0,-5.572145,3.572145,0.374635
8,DEN,LAC,6.0,2.505521,3.494479,0.366822
5,CIN,MIA,7.0,3.944102,3.055898,0.322315
21,NYG,WAS,0.0,-1.092271,1.092271,0.116792
29,WAS,NYG,0.0,1.092271,-1.092271,-0.116792
17,MIA,CIN,-7.0,-3.944102,-3.055898,-0.322315
15,LAC,DEN,-6.0,-2.505521,-3.494479,-0.366822
13,JAX,PHI,2.0,5.572145,-3.572145,-0.374635
14,LA,BUF,-3.0,0.753176,-3.753176,-0.392762
25,SEA,SF,-3.0,1.002696,-4.002696,-0.417545
6,CLE,NYJ,-5.0,-0.353638,-4.646362,-0.480318
1,ATL,BAL,-7.0,-1.533084,-5.466916,-0.557679
20,NO,MIN,-10.0,-3.232479,-6.767521,-0.673437
7,DAL,TB,-8.0,3.776690,-11.776690,-1.029660
12,IND,PIT,-12.0,-0.044362,-11.955638,-1.039710
28,TEN,HOU,-23.0,-5.457414,-17.542586,-1.273702
0,ARI,DET,-24.0,-4.273993,-19.726007,-1.330923
16,LV,NE,-28.0,-6.048089,-21.951911,-1.375059
4,CHI,GB,-24.0,0.667232,-24.667232,-1.414080

# Offensive and Defensive Weekly Signals

Overall team strength uses the opponent adjusted margin residual.

We also preserve separate offensive and defensive signals because the weekly game projection model needs scoring information.

These are weekly updates, not cumulative season averages.

Opponent entering strength is used conservatively as context until separate entering offensive and defensive strength ratings are maintained.

In [23]:
league_points_per_team_game = (
    team_games["points_for"].mean()
)

OPPONENT_CONTEXT_RATE = 0.25
OFFENSE_DEFENSE_UPDATE_RATE = 0.15

team_games["raw_offense_performance"] = (
    team_games["points_for"]
    - league_points_per_team_game
)

team_games["raw_defense_performance"] = (
    league_points_per_team_game
    - team_games["points_against"]
)

team_games["adjusted_offense_performance"] = (
    team_games["raw_offense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["adjusted_defense_performance"] = (
    team_games["raw_defense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["weekly_offense_adjustment"] = (
    team_games["adjusted_offense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

team_games["weekly_defense_adjustment"] = (
    team_games["adjusted_defense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

display(
    team_games[
        [
            "team",
            "opponent",
            "points_for",
            "points_against",
            "opponent_entering_strength",
            "raw_offense_performance",
            "adjusted_offense_performance",
            "weekly_offense_adjustment",
            "raw_defense_performance",
            "adjusted_defense_performance",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "team"
    )
)

,team,opponent,points_for,points_against,opponent_entering_strength,raw_offense_performance,adjusted_offense_performance,weekly_offense_adjustment,raw_defense_performance,adjusted_defense_performance,weekly_defense_adjustment
0,ARI,DET,21.0,45.0,1.527588,-3.2,-2.818103,-0.422715,-20.8,-20.418103,-3.062715
1,ATL,BAL,23.0,30.0,2.696986,-1.2,-0.525753,-0.078863,-5.8,-5.125753,-0.768863
2,BAL,ATL,30.0,23.0,-0.336098,5.8,5.715976,0.857396,1.2,1.115976,0.167396
3,BUF,LA,37.0,34.0,4.253705,12.8,13.863426,2.079514,-9.8,-8.736574,-1.310486
4,CHI,GB,7.0,31.0,0.044335,-17.2,-17.188916,-2.578337,-6.8,-6.788916,-1.018337
5,CIN,MIA,31.0,24.0,-4.993609,6.8,5.551598,0.832740,0.2,-1.048402,-0.157260
6,CLE,NYJ,12.0,17.0,-4.786024,-12.2,-13.396506,-2.009476,7.2,6.003494,0.900524
7,DAL,TB,16.0,24.0,-1.832732,-8.2,-8.658183,-1.298727,0.2,-0.258183,-0.038727
8,DEN,LAC,23.0,17.0,-1.470386,-1.2,-1.567597,-0.235139,7.2,6.832403,1.024861
9,DET,ARI,45.0,21.0,-4.246405,20.8,19.738399,2.960760,3.2,2.138399,0.320760
10,GB,CHI,31.0,7.0,2.211567,6.8,7.352892,1.102934,17.2,17.752892,2.662934
11,HOU,TEN,26.0,3.0,-6.801614,1.8,0.099596,0.014939,21.2,19.499596,2.924939
12,IND,PIT,22.0,34.0,-0.505123,-2.2,-2.326281,-0.348942,-9.8,-9.926281,-1.488942
13,JAX,PHI,19.0,17.0,0.076707,-5.2,-5.180823,-0.777123,7.2,7.219177,1.082877
14,LA,BUF,34.0,37.0,5.000529,9.8,11.050132,1.657520,-12.8,-11.549868,-1.732480
15,LAC,DEN,17.0,23.0,2.535135,-7.2,-6.566216,-0.984932,1.2,1.833784,0.275068
16,LV,NE,17.0,45.0,2.526854,-7.2,-6.568286,-0.985243,-20.8,-20.168286,-3.025243
17,MIA,CIN,24.0,31.0,0.450493,-0.2,-0.087377,-0.013107,-6.8,-6.687377,-1.003107
18,MIN,NO,23.0,13.0,-2.264969,-1.2,-1.766242,-0.264936,11.2,10.633758,1.595064
19,NE,LV,45.0,17.0,-2.021235,20.8,20.294691,3.044204,7.2,6.694691,1.004204
20,NO,MIN,13.0,23.0,2.467510,-11.2,-10.583122,-1.587468,1.2,1.816878,0.272532
21,NYG,WAS,27.0,27.0,-3.164962,2.8,2.008760,0.301314,-2.8,-3.591240,-0.538686
22,NYJ,CLE,17.0,12.0,-3.639662,-7.2,-8.109916,-1.216487,12.2,11.290084,1.693513
23,PHI,JAX,17.0,19.0,4.148852,-7.2,-6.162787,-0.924418,5.2,6.237213,0.935582
24,PIT,IND,34.0,22.0,0.950515,9.8,10.037629,1.505644,2.2,2.437629,0.365644
25,SEA,SF,29.0,32.0,5.115310,4.8,6.078828,0.911824,-7.8,-6.521172,-0.978176
26,SF,SEA,32.0,29.0,4.618006,7.8,8.954502,1.343175,-4.8,-3.645498,-0.546825
27,TB,DAL,24.0,16.0,0.443958,-0.2,-0.089011,-0.013352,8.2,8.310989,1.246648
28,TEN,HOU,3.0,26.0,0.155800,-21.2,-21.161050,-3.174158,-1.8,-1.761050,-0.264158
29,WAS,NYG,27.0,27.0,-2.757233,2.8,2.110692,0.316604,-2.8,-3.489308,-0.523396

# Build Week-Level Feature Table

The final feature table contains only the new evidence that should move the prior week's ratings.

For Week 3:

`Week 3 strength = Week 2 strength + Week 2 performance update`

The previous week's rating therefore acts as the prior, and older games are not counted again.

In [24]:
team_features = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_in_update=("game_id", "count"),

        entering_team_strength=(
            "entering_team_strength",
            "first"
        ),

        entering_strength_rank=(
            "entering_strength_rank",
            "first"
        ),

        average_opponent_strength=(
            "opponent_entering_strength",
            "mean"
        ),

        average_opponent_rank=(
            "opponent_entering_rank",
            "mean"
        ),

        actual_margin=(
            "point_margin",
            "mean"
        ),

        expected_margin=(
            "expected_margin",
            "mean"
        ),

        performance_residual=(
            "performance_residual",
            "mean"
        ),

        weekly_strength_update=(
            "weekly_strength_update",
            "mean"
        ),

        weekly_offense_adjustment=(
            "weekly_offense_adjustment",
            "mean"
        ),

        weekly_defense_adjustment=(
            "weekly_defense_adjustment",
            "mean"
        )
    )
)

display(
    team_features[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "average_opponent_rank",
            "average_opponent_strength",
            "actual_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,entering_strength_rank,entering_team_strength,average_opponent_rank,average_opponent_strength,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
10,GB,18,0.044335,11.0,2.211567,24.0,-0.667232,24.667232,1.414080,1.102934,2.662934
19,NE,9,2.526854,23.0,-2.021235,28.0,6.048089,21.951911,1.375059,3.044204,1.004204
9,DET,12,1.527588,29.0,-4.246405,24.0,4.273993,19.726007,1.330923,2.960760,0.320760
11,HOU,16,0.155800,32.0,-6.801614,23.0,5.457414,17.542586,1.273702,0.014939,2.924939
24,PIT,20,-0.505123,13.0,0.950515,12.0,0.044362,11.955638,1.039710,1.505644,0.365644
27,TB,22,-1.832732,15.0,0.443958,8.0,-3.776690,11.776690,1.029660,-0.013352,1.246648
18,MIN,10,2.467510,24.0,-2.264969,10.0,3.232479,6.767521,0.673437,-0.264936,1.595064
2,BAL,7,2.696986,19.0,-0.336098,7.0,1.533084,5.466916,0.557679,0.857396,0.167396
22,NYJ,30,-4.786024,28.0,-3.639662,5.0,0.353638,4.646362,0.480318,-1.216487,1.693513
26,SF,1,5.115310,3.0,4.618006,3.0,-1.002696,4.002696,0.417545,1.343175,-0.546825
3,BUF,2,5.000529,4.0,4.253705,3.0,-0.753176,3.753176,0.392762,2.079514,-1.310486
23,PHI,17,0.076707,5.0,4.148852,-2.0,-5.572145,3.572145,0.374635,-0.924418,0.935582
8,DEN,8,2.535135,21.0,-1.470386,6.0,2.505521,3.494479,0.366822,-0.235139,1.024861
5,CIN,14,0.450493,31.0,-4.993609,7.0,3.944102,3.055898,0.322315,0.832740,-0.157260
21,NYG,25,-2.757233,26.0,-3.164962,0.0,-1.092271,1.092271,0.116792,0.301314,-0.538686
29,WAS,26,-3.164962,25.0,-2.757233,0.0,1.092271,-1.092271,-0.116792,0.316604,-0.523396
17,MIA,31,-4.993609,14.0,0.450493,-7.0,-3.944102,-3.055898,-0.322315,-0.013107,-1.003107
15,LAC,21,-1.470386,8.0,2.535135,-6.0,-2.505521,-3.494479,-0.366822,-0.984932,0.275068
13,JAX,5,4.148852,17.0,0.076707,2.0,5.572145,-3.572145,-0.374635,-0.777123,1.082877
14,LA,4,4.253705,2.0,5.000529,-3.0,0.753176,-3.753176,-0.392762,1.657520,-1.732480
25,SEA,3,4.618006,1.0,5.115310,-3.0,1.002696,-4.002696,-0.417545,0.911824,-0.978176
6,CLE,28,-3.639662,30.0,-4.786024,-5.0,-0.353638,-4.646362,-0.480318,-2.009476,0.900524
1,ATL,19,-0.336098,7.0,2.696986,-7.0,-1.533084,-5.466916,-0.557679,-0.078863,-0.768863
20,NO,24,-2.264969,10.0,2.467510,-10.0,-3.232479,-6.767521,-0.673437,-1.587468,0.272532
7,DAL,15,0.443958,22.0,-1.832732,-8.0,3.776690,-11.776690,-1.029660,-1.298727,-0.038727
12,IND,13,0.950515,20.0,-0.505123,-12.0,-0.044362,-11.955638,-1.039710,-0.348942,-1.488942
28,TEN,32,-6.801614,16.0,0.155800,-23.0,-5.457414,-17.542586,-1.273702,-3.174158,-0.264158
0,ARI,29,-4.246405,12.0,1.527588,-24.0,-4.273993,-19.726007,-1.330923,-0.422715,-3.062715
16,LV,23,-2.021235,9.0,2.526854,-28.0,-6.048089,-21.951911,-1.375059,-0.985243,-3.025243
4,CHI,11,2.211567,18.0,0.044335,-24.0,0.667232,-24.667232,-1.414080,-2.578337,-1.018337

# Sanity Checks

Before saving, verify that:

- all 32 teams are represented
- every team has an entering Week 2 rating
- every opponent has an entering Week 2 rating
- no Week 3 game results were used
- weekly strength updates remain within the intended cap

In [25]:
print("Teams in feature table:", len(team_features))
print(
    "Unique teams:",
    team_features["team"].nunique()
)

print(
    "Missing entering team strengths:",
    team_features[
        "entering_team_strength"
    ].isna().sum()
)

print(
    "Missing opponent strengths:",
    team_features[
        "average_opponent_strength"
    ].isna().sum()
)

print(
    "Largest positive weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].max(),
        3
    )
)

print(
    "Largest negative weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].min(),
        3
    )
)

if (
    completed_games["week"] >= TARGET_WEEK
).any():
    raise ValueError(
        "DATA LEAKAGE: target-week results "
        "were found in completed games."
    )

if len(team_features) != 32:
    print()
    print(
        "WARNING: Feature table does not "
        "contain all 32 teams."
    )

Teams in feature table: 30
Unique teams: 30
Missing entering team strengths: 0
Missing opponent strengths: 0
Largest positive weekly update: 1.414
Largest negative weekly update: -1.414

WARNING: Feature table does not contain all 32 teams.

# Save In Season Feature Table

This output will be consumed by:

`04_Weekly_Team_Strength.ipynb`

The file contains only the new in season evidence. It does not overwrite or replace the preseason team strength table.

In [26]:
output_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

team_features = team_features.sort_values(
    "team"
).reset_index(drop=True)

team_features.to_parquet(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: ..\..\data\processed\weekly\week_06_inseason_features.parquet

# Interpretation

The weekly model is now sequential.

For Week 3:

1. Week 2 team strength is treated as the entering prior.
2. Only Week 2 game results provide new evidence.
3. Performance is evaluated relative to the opponent's entering strength.
4. Extreme single game residuals are capped.
5. A conservative learning rate determines the weekly rating movement.
6. The resulting update will be added to the Week 2 rating in `04_Weekly_Team_Strength.ipynb`.

This prevents older games from being counted repeatedly and makes strength of opponent part of every weekly update.

The frozen preseason model remains unchanged.