# 03 — In Season Feature Engineering

This notebook creates the weekly performance features used by the in season projection layer.

It does not modify the original preseason notebooks or their outputs.

The purpose of this notebook is to convert completed regular season games into team level offensive and defensive performance features that can later be blended with the frozen preseason model.

For a selected target week, the notebook:

- Loads only completed games from weeks before the target week
- Builds team level scoring and margin summaries
- Separates offense and defense
- Adds simple opponent adjusted performance features
- Applies early season shrinkage to reduce overreaction to small samples
- Saves a clean feature table for the weekly team strength notebook

This notebook is intentionally conservative after Week 1. One game should inform the model, not redefine it.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the outputs created by:

`02_Weekly_Data_Update.ipynb`

The only value that normally changes week to week is `TARGET_WEEK`.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 8
PRIOR_WEEK = TARGET_WEEK - 1

completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

prior_strength_path = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

print("Using completed games:", completed_games_path)
print("Using entering ratings:", prior_strength_path)

Using completed games: ..\..\data\processed\weekly\week_08_completed_games.parquet
Using entering ratings: ..\..\data\processed\weekly\week_07_sequential_team_strength.parquet

# Load Completed Games

Only games completed before the target week should exist in this file.

That leakage rule was enforced in `02_Weekly_Data_Update.ipynb`.

In [3]:
completed_games = pd.read_parquet(
    completed_games_path
)

completed_games = completed_games.sort_values(
    ["week", "gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Completed games available before Week {TARGET_WEEK}:",
    len(completed_games)
)

display(
    completed_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Completed games available before Week 8: 107

     week     gameday away_team  away_score home_team  home_score
0       1  2026-09-09        NE        10.0       SEA        13.0
1       1  2026-09-10        SF        27.0        LA         7.0
2       1  2026-09-13       ARI        26.0       LAC        14.0
3       1  2026-09-13       ATL        13.0       PIT        20.0
4       1  2026-09-13       BAL        41.0       IND        23.0
..    ...         ...       ...         ...       ...         ...
102     7  2026-10-25       NYG        27.0       HOU        21.0
103     7  2026-10-25       PIT        16.0        NO        10.0
104     7  2026-10-25        SF        20.0       ATL        29.0
105     7  2026-10-25        TB        43.0       CAR        13.0
106     7  2026-10-26       DAL        38.0       PHI        21.0

[107 rows x 6 columns]

In [4]:
update_games = completed_games[
    completed_games["week"] == PRIOR_WEEK
].copy()

update_games = update_games.sort_values(
    ["gameday", "game_id"]
).reset_index(drop=True)

print(
    f"Week {PRIOR_WEEK} games used to update "
    f"Week {TARGET_WEEK} ratings:",
    len(update_games)
)

display(
    update_games[
        [
            "week",
            "gameday",
            "away_team",
            "away_score",
            "home_team",
            "home_score"
        ]
    ]
)

Week 7 games used to update Week 8 ratings: 14

    week     gameday away_team  away_score home_team  home_score
0      7  2026-10-22        NE        24.0       CHI        30.0
1      7  2026-10-25       CIN        35.0       BAL        13.0
2      7  2026-10-25       CLE        27.0       TEN        24.0
3      7  2026-10-25       DEN        30.0       ARI        16.0
4      7  2026-10-25        GB        17.0       DET        20.0
5      7  2026-10-25       IND        10.0       MIN        16.0
6      7  2026-10-25        KC         3.0       SEA        20.0
7      7  2026-10-25        LA        35.0        LV        21.0
8      7  2026-10-25       MIA        28.0       NYJ        25.0
9      7  2026-10-25       NYG        27.0       HOU        21.0
10     7  2026-10-25       PIT        16.0        NO        10.0
11     7  2026-10-25        SF        20.0       ATL        29.0
12     7  2026-10-25        TB        43.0       CAR        13.0
13     7  2026-10-26       DAL        38.0       PHI        21.0

# Convert Prior Week Games to Team Game Rows

Only the most recently completed week is used for the new weekly update.

For Week 3:

- Week 2 team strength is the entering prior
- Week 2 game performance is the new evidence
- Week 1 is not counted again because it is already reflected in the Week 2 ratings

Each game becomes two rows:

- one from the home team's perspective
- one from the away team's perspective

In [5]:
home_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["home_team"],
        "opponent": update_games["away_team"],
        "is_home": 1,
        "points_for": update_games["home_score"],
        "points_against": update_games["away_score"]
    }
)

away_rows = pd.DataFrame(
    {
        "game_id": update_games["game_id"],
        "week": update_games["week"],
        "team": update_games["away_team"],
        "opponent": update_games["home_team"],
        "is_home": 0,
        "points_for": update_games["away_score"],
        "points_against": update_games["home_score"]
    }
)

team_games = pd.concat(
    [home_rows, away_rows],
    ignore_index=True
)

team_games["point_margin"] = (
    team_games["points_for"]
    - team_games["points_against"]
)

team_games = team_games.sort_values(
    ["team", "game_id"]
).reset_index(drop=True)

print("Team-game rows:", len(team_games))

display(team_games)

Team-game rows: 28

,game_id,week,team,opponent,is_home,points_for,points_against,point_margin
0,2026_07_DEN_ARI,7,ARI,DEN,1,16.0,30.0,-14.0
1,2026_07_SF_ATL,7,ATL,SF,1,29.0,20.0,9.0
2,2026_07_CIN_BAL,7,BAL,CIN,1,13.0,35.0,-22.0
3,2026_07_TB_CAR,7,CAR,TB,1,13.0,43.0,-30.0
4,2026_07_NE_CHI,7,CHI,NE,1,30.0,24.0,6.0
5,2026_07_CIN_BAL,7,CIN,BAL,0,35.0,13.0,22.0
6,2026_07_CLE_TEN,7,CLE,TEN,0,27.0,24.0,3.0
7,2026_07_DAL_PHI,7,DAL,PHI,0,38.0,21.0,17.0
8,2026_07_DEN_ARI,7,DEN,ARI,0,30.0,16.0,14.0
9,2026_07_GB_DET,7,DET,GB,1,20.0,17.0,3.0
10,2026_07_GB_DET,7,GB,DET,0,17.0,20.0,-3.0
11,2026_07_NYG_HOU,7,HOU,NYG,1,21.0,27.0,-6.0
12,2026_07_IND_MIN,7,IND,MIN,0,10.0,16.0,-6.0
13,2026_07_KC_SEA,7,KC,SEA,0,3.0,20.0,-17.0
14,2026_07_LA_LV,7,LA,LV,0,35.0,21.0,14.0
15,2026_07_LA_LV,7,LV,LA,1,21.0,35.0,-14.0
16,2026_07_MIA_NYJ,7,MIA,NYJ,0,28.0,25.0,3.0
17,2026_07_IND_MIN,7,MIN,IND,1,16.0,10.0,6.0
18,2026_07_NE_CHI,7,NE,CHI,0,24.0,30.0,-6.0
19,2026_07_PIT_NO,7,NO,PIT,1,10.0,16.0,-6.0
20,2026_07_NYG_HOU,7,NYG,HOU,0,27.0,21.0,6.0
21,2026_07_MIA_NYJ,7,NYJ,MIA,1,25.0,28.0,-3.0
22,2026_07_DAL_PHI,7,PHI,DAL,1,21.0,38.0,-17.0
23,2026_07_PIT_NO,7,PIT,NO,0,16.0,10.0,6.0
24,2026_07_KC_SEA,7,SEA,KC,1,20.0,3.0,17.0
25,2026_07_SF_ATL,7,SF,ATL,0,20.0,29.0,-9.0
26,2026_07_TB_CAR,7,TB,CAR,0,43.0,13.0,30.0
27,2026_07_CLE_TEN,7,TEN,CLE,1,24.0,27.0,-3.0

# Attach Entering Team and Opponent Strength

Each team's performance is evaluated relative to what the model believed before the game was played.

For Week 3 projections, Week 2 ratings represent the information available entering Week 2.

This prevents the opponent adjustment from using future information or the same results that are currently being evaluated.

In [6]:
prior_strength = pd.read_parquet(
    prior_strength_path
).copy()

required_prior_columns = [
    "team",
    "weekly_team_strength",
    "weekly_strength_rank"
]

missing_prior_columns = [
    col
    for col in required_prior_columns
    if col not in prior_strength.columns
]

if missing_prior_columns:
    raise KeyError(
        "Missing prior-week strength columns: "
        + ", ".join(missing_prior_columns)
    )

prior_strength = prior_strength[
    required_prior_columns
].rename(
    columns={
        "weekly_team_strength": "entering_team_strength",
        "weekly_strength_rank": "entering_strength_rank"
    }
)

print(
    f"Week {PRIOR_WEEK} entering ratings loaded:",
    len(prior_strength)
)

display(
    prior_strength.sort_values(
        "entering_strength_rank"
    )
)

Week 7 entering ratings loaded: 32

   team  entering_team_strength  entering_strength_rank
0    SF                5.084675                       1
1   BUF                4.947555                       2
2    KC                4.051178                       3
3   SEA                3.904552                       4
4    NE                3.615375                       5
5   DEN                3.197866                       6
6   MIN                3.140947                       7
7   JAX                3.094193                       8
8   DET                2.858510                       9
9    LA                2.769153                      10
10  BAL                2.413564                      11
11  HOU                2.109526                      12
12   GB                2.104927                      13
13  CHI                1.556965                      14
14  PIT                1.241368                      15
15  CIN                0.772808                      16
16  PHI               -0.787958                      17
17  DAL               -1.232215                      18
18  IND               -1.293242                      19
19   TB               -1.509854                      20
20  ATL               -1.653255                      21
21   NO               -2.102954                      22
22  CAR               -2.273949                      23
23  LAC               -2.722905                      24
24  WAS               -2.833574                      25
25   LV               -2.950558                      26
26  CLE               -3.278879                      27
27  NYG               -3.475892                      28
28  NYJ               -4.019168                      29
29  ARI               -4.485537                      30
30  MIA               -5.315924                      31
31  TEN               -6.871269                      32

In [7]:
team_games = team_games.merge(
    prior_strength[
        [
            "team",
            "entering_team_strength",
            "entering_strength_rank"
        ]
    ],
    on="team",
    how="left",
    validate="many_to_one"
)

opponent_strength = prior_strength[
    [
        "team",
        "entering_team_strength",
        "entering_strength_rank"
    ]
].rename(
    columns={
        "team": "opponent",
        "entering_team_strength": "opponent_entering_strength",
        "entering_strength_rank": "opponent_entering_rank"
    }
)

team_games = team_games.merge(
    opponent_strength,
    on="opponent",
    how="left",
    validate="many_to_one"
)

display(
    team_games[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "opponent",
            "opponent_entering_rank",
            "opponent_entering_strength",
            "points_for",
            "points_against",
            "point_margin"
        ]
    ].sort_values(
        "entering_strength_rank"
    )
)

,team,entering_strength_rank,entering_team_strength,opponent,opponent_entering_rank,opponent_entering_strength,points_for,points_against,point_margin
25,SF,1,5.084675,ATL,21,-1.653255,20.0,29.0,-9.0
13,KC,3,4.051178,SEA,4,3.904552,3.0,20.0,-17.0
24,SEA,4,3.904552,KC,3,4.051178,20.0,3.0,17.0
18,NE,5,3.615375,CHI,14,1.556965,24.0,30.0,-6.0
8,DEN,6,3.197866,ARI,30,-4.485537,30.0,16.0,14.0
17,MIN,7,3.140947,IND,19,-1.293242,16.0,10.0,6.0
9,DET,9,2.858510,GB,13,2.104927,20.0,17.0,3.0
14,LA,10,2.769153,LV,26,-2.950558,35.0,21.0,14.0
2,BAL,11,2.413564,CIN,16,0.772808,13.0,35.0,-22.0
11,HOU,12,2.109526,NYG,28,-3.475892,21.0,27.0,-6.0
10,GB,13,2.104927,DET,9,2.858510,17.0,20.0,-3.0
4,CHI,14,1.556965,NE,5,3.615375,30.0,24.0,6.0
23,PIT,15,1.241368,NO,22,-2.102954,16.0,10.0,6.0
5,CIN,16,0.772808,BAL,11,2.413564,35.0,13.0,22.0
22,PHI,17,-0.787958,DAL,18,-1.232215,21.0,38.0,-17.0
7,DAL,18,-1.232215,PHI,17,-0.787958,38.0,21.0,17.0
12,IND,19,-1.293242,MIN,7,3.140947,10.0,16.0,-6.0
26,TB,20,-1.509854,CAR,23,-2.273949,43.0,13.0,30.0
1,ATL,21,-1.653255,SF,1,5.084675,29.0,20.0,9.0
19,NO,22,-2.102954,PIT,15,1.241368,10.0,16.0,-6.0
3,CAR,23,-2.273949,TB,20,-1.509854,13.0,43.0,-30.0
15,LV,26,-2.950558,LA,10,2.769153,21.0,35.0,-14.0
6,CLE,27,-3.278879,TEN,32,-6.871269,27.0,24.0,3.0
20,NYG,28,-3.475892,HOU,12,2.109526,27.0,21.0,6.0
21,NYJ,29,-4.019168,MIA,31,-5.315924,25.0,28.0,-3.0
0,ARI,30,-4.485537,DEN,6,3.197866,16.0,30.0,-14.0
16,MIA,31,-5.315924,NYJ,29,-4.019168,28.0,25.0,3.0
27,TEN,32,-6.871269,CLE,27,-3.278879,24.0,27.0,-3.0

# Expected Margin and Opponent-Adjusted Performance

The weekly update is based on how a team performed relative to expectation.

For each team game:

`performance residual = actual margin - expected margin`

Expected margin uses the difference between the two teams' entering strength ratings plus home field advantage.

This means beating a strong opponent is more informative than producing the same result against a weak opponent.

In [8]:
HOME_FIELD_POINTS = 1.5

team_games["expected_margin"] = (
    team_games["entering_team_strength"]
    - team_games["opponent_entering_strength"]
    + np.where(
        team_games["is_home"] == 1,
        HOME_FIELD_POINTS,
        -HOME_FIELD_POINTS
    )
)

team_games["performance_residual"] = (
    team_games["point_margin"]
    - team_games["expected_margin"]
)

display(
    team_games[
        [
            "team",
            "opponent",
            "entering_team_strength",
            "opponent_entering_strength",
            "point_margin",
            "expected_margin",
            "performance_residual"
        ]
    ].sort_values(
        "performance_residual",
        ascending=False
    )
)

,team,opponent,entering_team_strength,opponent_entering_strength,point_margin,expected_margin,performance_residual
26,TB,CAR,-1.509854,-2.273949,30.0,-0.735905,30.735905
5,CIN,BAL,0.772808,2.413564,22.0,-3.140757,25.140757
7,DAL,PHI,-1.232215,-0.787958,17.0,-1.944257,18.944257
24,SEA,KC,3.904552,4.051178,17.0,1.353374,15.646626
1,ATL,SF,-1.653255,5.084675,9.0,-5.237930,14.237930
20,NYG,HOU,-3.475892,2.109526,6.0,-7.085417,13.085417
14,LA,LV,2.769153,-2.950558,14.0,4.219711,9.780289
8,DEN,ARI,3.197866,-4.485537,14.0,6.183403,7.816597
4,CHI,NE,1.556965,3.615375,6.0,-0.558410,6.558410
16,MIA,NYJ,-5.315924,-4.019168,3.0,-2.796755,5.796755
23,PIT,NO,1.241368,-2.102954,6.0,1.844322,4.155678
6,CLE,TEN,-3.278879,-6.871269,3.0,2.092390,0.907610
9,DET,GB,2.858510,2.104927,3.0,2.253583,0.746417
17,MIN,IND,3.140947,-1.293242,6.0,5.934189,0.065811
12,IND,MIN,-1.293242,3.140947,-6.0,-5.934189,-0.065811
10,GB,DET,2.104927,2.858510,-3.0,-2.253583,-0.746417
27,TEN,CLE,-6.871269,-3.278879,-3.0,-2.092390,-0.907610
19,NO,PIT,-2.102954,1.241368,-6.0,-1.844322,-4.155678
21,NYJ,MIA,-4.019168,-5.315924,-3.0,2.796755,-5.796755
18,NE,CHI,3.615375,1.556965,-6.0,0.558410,-6.558410
0,ARI,DEN,-4.485537,3.197866,-14.0,-6.183403,-7.816597
15,LV,LA,-2.950558,2.769153,-14.0,-4.219711,-9.780289
11,HOU,NYG,2.109526,-3.475892,-6.0,7.085417,-13.085417
25,SF,ATL,5.084675,-1.653255,-9.0,5.237930,-14.237930
13,KC,SEA,4.051178,3.904552,-17.0,-1.353374,-15.646626
22,PHI,DAL,-0.787958,-1.232215,-17.0,1.944257,-18.944257
2,BAL,CIN,2.413564,0.772808,-22.0,3.140757,-25.140757
3,CAR,TB,-2.273949,-1.509854,-30.0,0.735905,-30.735905

# Control Extreme Single-Game Results

NFL game margins contain substantial single-game noise.

A blowout should affect team strength, but one extreme result should not completely redefine the team's rating.

Performance residuals are therefore capped before the weekly learning rate is applied.

In [9]:
RESIDUAL_SCALE = 14.0
MAX_WEEKLY_UPDATE = 1.5

team_games["weekly_strength_update"] = (
    MAX_WEEKLY_UPDATE
    * np.tanh(
        team_games["performance_residual"]
        / RESIDUAL_SCALE
    )
)

display(
    team_games[
        [
            "team",
            "opponent",
            "point_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,opponent,point_margin,expected_margin,performance_residual,weekly_strength_update
26,TB,CAR,30.0,-0.735905,30.735905,1.463284
5,CIN,BAL,22.0,-3.140757,25.140757,1.419549
7,DAL,PHI,17.0,-1.944257,18.944257,1.312196
24,SEA,KC,17.0,1.353374,15.646626,1.210107
1,ATL,SF,9.0,-5.237930,14.237930,1.152960
20,NYG,HOU,6.0,-7.085417,13.085417,1.099148
14,LA,LV,14.0,4.219711,9.780289,0.905210
8,DEN,ARI,14.0,6.183403,7.816597,0.760104
4,CHI,NE,6.0,-0.558410,6.558410,0.655429
16,MIA,NYJ,3.0,-2.796755,5.796755,0.587864
23,PIT,NO,6.0,1.844322,4.155678,0.432619
6,CLE,TEN,3.0,2.092390,0.907610,0.097108
9,DET,GB,3.0,2.253583,0.746417,0.079898
17,MIN,IND,6.0,5.934189,0.065811,0.007051
12,IND,MIN,-6.0,-5.934189,-0.065811,-0.007051
10,GB,DET,-3.0,-2.253583,-0.746417,-0.079898
27,TEN,CLE,-3.0,-2.092390,-0.907610,-0.097108
19,NO,PIT,-6.0,-1.844322,-4.155678,-0.432619
21,NYJ,MIA,-3.0,2.796755,-5.796755,-0.587864
18,NE,CHI,-6.0,0.558410,-6.558410,-0.655429
0,ARI,DEN,-14.0,-6.183403,-7.816597,-0.760104
15,LV,LA,-14.0,-4.219711,-9.780289,-0.905210
11,HOU,NYG,-6.0,7.085417,-13.085417,-1.099148
25,SF,ATL,-9.0,5.237930,-14.237930,-1.152960
13,KC,SEA,-17.0,-1.353374,-15.646626,-1.210107
22,PHI,DAL,-17.0,1.944257,-18.944257,-1.312196
2,BAL,CIN,-22.0,3.140757,-25.140757,-1.419549
3,CAR,TB,-30.0,0.735905,-30.735905,-1.463284

# Offensive and Defensive Weekly Signals

Overall team strength uses the opponent adjusted margin residual.

We also preserve separate offensive and defensive signals because the weekly game projection model needs scoring information.

These are weekly updates, not cumulative season averages.

Opponent entering strength is used conservatively as context until separate entering offensive and defensive strength ratings are maintained.

In [10]:
league_points_per_team_game = (
    team_games["points_for"].mean()
)

OPPONENT_CONTEXT_RATE = 0.25
OFFENSE_DEFENSE_UPDATE_RATE = 0.15

team_games["raw_offense_performance"] = (
    team_games["points_for"]
    - league_points_per_team_game
)

team_games["raw_defense_performance"] = (
    league_points_per_team_game
    - team_games["points_against"]
)

team_games["adjusted_offense_performance"] = (
    team_games["raw_offense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["adjusted_defense_performance"] = (
    team_games["raw_defense_performance"]
    + (
        OPPONENT_CONTEXT_RATE
        * team_games["opponent_entering_strength"]
    )
)

team_games["weekly_offense_adjustment"] = (
    team_games["adjusted_offense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

team_games["weekly_defense_adjustment"] = (
    team_games["adjusted_defense_performance"]
    * OFFENSE_DEFENSE_UPDATE_RATE
)

display(
    team_games[
        [
            "team",
            "opponent",
            "points_for",
            "points_against",
            "opponent_entering_strength",
            "raw_offense_performance",
            "adjusted_offense_performance",
            "weekly_offense_adjustment",
            "raw_defense_performance",
            "adjusted_defense_performance",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "team"
    )
)

,team,opponent,points_for,points_against,opponent_entering_strength,raw_offense_performance,adjusted_offense_performance,weekly_offense_adjustment,raw_defense_performance,adjusted_defense_performance,weekly_defense_adjustment
0,ARI,DEN,16.0,30.0,3.197866,-6.571429,-5.771962,-0.865794,-7.428571,-6.629105,-0.994366
1,ATL,SF,29.0,20.0,5.084675,6.428571,7.699740,1.154961,2.571429,3.842597,0.576390
2,BAL,CIN,13.0,35.0,0.772808,-9.571429,-9.378227,-1.406734,-12.428571,-12.235369,-1.835305
3,CAR,TB,13.0,43.0,-1.509854,-9.571429,-9.948892,-1.492334,-20.428571,-20.806035,-3.120905
4,CHI,NE,30.0,24.0,3.615375,7.428571,8.332415,1.249862,-1.428571,-0.524728,-0.078709
5,CIN,BAL,35.0,13.0,2.413564,12.428571,13.031963,1.954794,9.571429,10.174820,1.526223
6,CLE,TEN,27.0,24.0,-6.871269,4.428571,2.710754,0.406613,-1.428571,-3.146389,-0.471958
7,DAL,PHI,38.0,21.0,-0.787958,15.428571,15.231582,2.284737,1.571429,1.374439,0.206166
8,DEN,ARI,30.0,16.0,-4.485537,7.428571,6.307187,0.946078,6.571429,5.450044,0.817507
9,DET,GB,20.0,17.0,2.104927,-2.571429,-2.045197,-0.306780,5.571429,6.097660,0.914649
10,GB,DET,17.0,20.0,2.858510,-5.571429,-4.856801,-0.728520,2.571429,3.286056,0.492908
11,HOU,NYG,21.0,27.0,-3.475892,-1.571429,-2.440401,-0.366060,-4.428571,-5.297544,-0.794632
12,IND,MIN,10.0,16.0,3.140947,-12.571429,-11.786192,-1.767929,6.571429,7.356665,1.103500
13,KC,SEA,3.0,20.0,3.904552,-19.571429,-18.595290,-2.789294,2.571429,3.547567,0.532135
14,LA,LV,35.0,21.0,-2.950558,12.428571,11.690932,1.753640,1.571429,0.833789,0.125068
15,LV,LA,21.0,35.0,2.769153,-1.571429,-0.879140,-0.131871,-12.428571,-11.736283,-1.760442
16,MIA,NYJ,28.0,25.0,-4.019168,5.428571,4.423779,0.663567,-2.428571,-3.433363,-0.515005
17,MIN,IND,16.0,10.0,-1.293242,-6.571429,-6.894739,-1.034211,12.571429,12.248118,1.837218
18,NE,CHI,24.0,30.0,1.556965,1.428571,1.817813,0.272672,-7.428571,-7.039330,-1.055900
19,NO,PIT,10.0,16.0,1.241368,-12.571429,-12.261087,-1.839163,6.571429,6.881771,1.032266
20,NYG,HOU,27.0,21.0,2.109526,4.428571,4.955953,0.743393,1.571429,2.098810,0.314821
21,NYJ,MIA,25.0,28.0,-5.315924,2.428571,1.099591,0.164939,-5.428571,-6.757552,-1.013633
22,PHI,DAL,21.0,38.0,-1.232215,-1.571429,-1.879482,-0.281922,-15.428571,-15.736625,-2.360494
23,PIT,NO,16.0,10.0,-2.102954,-6.571429,-7.097167,-1.064575,12.571429,12.045690,1.806854
24,SEA,KC,20.0,3.0,4.051178,-2.571429,-1.558634,-0.233795,19.571429,20.584223,3.087633
25,SF,ATL,20.0,29.0,-1.653255,-2.571429,-2.984742,-0.447711,-6.428571,-6.841885,-1.026283
26,TB,CAR,43.0,13.0,-2.273949,20.428571,19.860084,2.979013,9.571429,9.002941,1.350441
27,TEN,CLE,24.0,27.0,-3.278879,1.428571,0.608852,0.091328,-4.428571,-5.248291,-0.787244

# Build Week-Level Feature Table

The final feature table contains only the new evidence that should move the prior week's ratings.

For Week 3:

`Week 3 strength = Week 2 strength + Week 2 performance update`

The previous week's rating therefore acts as the prior, and older games are not counted again.

In [11]:
team_features = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_in_update=("game_id", "count"),

        entering_team_strength=(
            "entering_team_strength",
            "first"
        ),

        entering_strength_rank=(
            "entering_strength_rank",
            "first"
        ),

        average_opponent_strength=(
            "opponent_entering_strength",
            "mean"
        ),

        average_opponent_rank=(
            "opponent_entering_rank",
            "mean"
        ),

        actual_margin=(
            "point_margin",
            "mean"
        ),

        expected_margin=(
            "expected_margin",
            "mean"
        ),

        performance_residual=(
            "performance_residual",
            "mean"
        ),

        weekly_strength_update=(
            "weekly_strength_update",
            "mean"
        ),

        weekly_offense_adjustment=(
            "weekly_offense_adjustment",
            "mean"
        ),

        weekly_defense_adjustment=(
            "weekly_defense_adjustment",
            "mean"
        )
    )
)

display(
    team_features[
        [
            "team",
            "entering_strength_rank",
            "entering_team_strength",
            "average_opponent_rank",
            "average_opponent_strength",
            "actual_margin",
            "expected_margin",
            "performance_residual",
            "weekly_strength_update",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment"
        ]
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

,team,entering_strength_rank,entering_team_strength,average_opponent_rank,average_opponent_strength,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
26,TB,20,-1.509854,23.0,-2.273949,30.0,-0.735905,30.735905,1.463284,2.979013,1.350441
5,CIN,16,0.772808,11.0,2.413564,22.0,-3.140757,25.140757,1.419549,1.954794,1.526223
7,DAL,18,-1.232215,17.0,-0.787958,17.0,-1.944257,18.944257,1.312196,2.284737,0.206166
24,SEA,4,3.904552,3.0,4.051178,17.0,1.353374,15.646626,1.210107,-0.233795,3.087633
1,ATL,21,-1.653255,1.0,5.084675,9.0,-5.237930,14.237930,1.152960,1.154961,0.576390
20,NYG,28,-3.475892,12.0,2.109526,6.0,-7.085417,13.085417,1.099148,0.743393,0.314821
14,LA,10,2.769153,26.0,-2.950558,14.0,4.219711,9.780289,0.905210,1.753640,0.125068
8,DEN,6,3.197866,30.0,-4.485537,14.0,6.183403,7.816597,0.760104,0.946078,0.817507
4,CHI,14,1.556965,5.0,3.615375,6.0,-0.558410,6.558410,0.655429,1.249862,-0.078709
16,MIA,31,-5.315924,29.0,-4.019168,3.0,-2.796755,5.796755,0.587864,0.663567,-0.515005
23,PIT,15,1.241368,22.0,-2.102954,6.0,1.844322,4.155678,0.432619,-1.064575,1.806854
6,CLE,27,-3.278879,32.0,-6.871269,3.0,2.092390,0.907610,0.097108,0.406613,-0.471958
9,DET,9,2.858510,13.0,2.104927,3.0,2.253583,0.746417,0.079898,-0.306780,0.914649
17,MIN,7,3.140947,19.0,-1.293242,6.0,5.934189,0.065811,0.007051,-1.034211,1.837218
12,IND,19,-1.293242,7.0,3.140947,-6.0,-5.934189,-0.065811,-0.007051,-1.767929,1.103500
10,GB,13,2.104927,9.0,2.858510,-3.0,-2.253583,-0.746417,-0.079898,-0.728520,0.492908
27,TEN,32,-6.871269,27.0,-3.278879,-3.0,-2.092390,-0.907610,-0.097108,0.091328,-0.787244
19,NO,22,-2.102954,15.0,1.241368,-6.0,-1.844322,-4.155678,-0.432619,-1.839163,1.032266
21,NYJ,29,-4.019168,31.0,-5.315924,-3.0,2.796755,-5.796755,-0.587864,0.164939,-1.013633
18,NE,5,3.615375,14.0,1.556965,-6.0,0.558410,-6.558410,-0.655429,0.272672,-1.055900
0,ARI,30,-4.485537,6.0,3.197866,-14.0,-6.183403,-7.816597,-0.760104,-0.865794,-0.994366
15,LV,26,-2.950558,10.0,2.769153,-14.0,-4.219711,-9.780289,-0.905210,-0.131871,-1.760442
11,HOU,12,2.109526,28.0,-3.475892,-6.0,7.085417,-13.085417,-1.099148,-0.366060,-0.794632
25,SF,1,5.084675,21.0,-1.653255,-9.0,5.237930,-14.237930,-1.152960,-0.447711,-1.026283
13,KC,3,4.051178,4.0,3.904552,-17.0,-1.353374,-15.646626,-1.210107,-2.789294,0.532135
22,PHI,17,-0.787958,18.0,-1.232215,-17.0,1.944257,-18.944257,-1.312196,-0.281922,-2.360494
2,BAL,11,2.413564,16.0,0.772808,-22.0,3.140757,-25.140757,-1.419549,-1.406734,-1.835305
3,CAR,23,-2.273949,20.0,-1.509854,-30.0,0.735905,-30.735905,-1.463284,-1.492334,-3.120905

# Sanity Checks

Before saving, verify that:

- all 32 teams are represented
- every team has an entering Week 2 rating
- every opponent has an entering Week 2 rating
- no Week 3 game results were used
- weekly strength updates remain within the intended cap

In [12]:
print("Teams in feature table:", len(team_features))
print(
    "Unique teams:",
    team_features["team"].nunique()
)

print(
    "Missing entering team strengths:",
    team_features[
        "entering_team_strength"
    ].isna().sum()
)

print(
    "Missing opponent strengths:",
    team_features[
        "average_opponent_strength"
    ].isna().sum()
)

print(
    "Largest positive weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].max(),
        3
    )
)

print(
    "Largest negative weekly update:",
    round(
        team_features[
            "weekly_strength_update"
        ].min(),
        3
    )
)

if (
    completed_games["week"] >= TARGET_WEEK
).any():
    raise ValueError(
        "DATA LEAKAGE: target-week results "
        "were found in completed games."
    )

if len(team_features) != 32:
    print()
    print(
        "WARNING: Feature table does not "
        "contain all 32 teams."
    )

Teams in feature table: 28
Unique teams: 28
Missing entering team strengths: 0
Missing opponent strengths: 0
Largest positive weekly update: 1.463
Largest negative weekly update: -1.463

WARNING: Feature table does not contain all 32 teams.

# Save In Season Feature Table

This output will be consumed by:

`04_Weekly_Team_Strength.ipynb`

The file contains only the new in season evidence. It does not overwrite or replace the preseason team strength table.

In [13]:
output_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

team_features = team_features.sort_values(
    "team"
).reset_index(drop=True)

team_features.to_parquet(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: ..\..\data\processed\weekly\week_08_inseason_features.parquet

# Interpretation

The weekly model is now sequential.

For Week 3:

1. Week 2 team strength is treated as the entering prior.
2. Only Week 2 game results provide new evidence.
3. Performance is evaluated relative to the opponent's entering strength.
4. Extreme single game residuals are capped.
5. A conservative learning rate determines the weekly rating movement.
6. The resulting update will be added to the Week 2 rating in `04_Weekly_Team_Strength.ipynb`.

This prevents older games from being counted repeatedly and makes strength of opponent part of every weekly update.

The frozen preseason model remains unchanged.