# 04 — Weekly Team Strength

This notebook updates team strength sequentially using the new in season evidence created in `03_Inseason_Feature_Engineering.ipynb`.

The original preseason model remains unchanged.

The weekly model follows a sequential principle:

> The previous week's team strength is the prior. The most recently completed week provides new evidence.

For each target week, this notebook:

- Loads the frozen preseason ratings for reference
- Loads the previous week's team strength state
- Loads the target week's new in season feature table
- Applies the opponent adjusted weekly strength update
- Preserves separate offensive and defensive weekly signals
- Calculates current weekly rankings
- Compares rank and strength movement to the previous week
- Saves a separate weekly team strength file

No original preseason file or prior weekly file is overwritten.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the output from:

`03_Inseason_Feature_Engineering.ipynb`

For Week 3:

- `TARGET_WEEK = 3`
- `PRIOR_WEEK = 2`

The Week 2 team strength file becomes the entering prior for Week 3.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 6
PRIOR_WEEK = TARGET_WEEK - 1

PRESEASON_STRENGTH_PATH = (
    PROCESSED_DIR
    / "2026_team_strength.parquet"
)

PRIOR_WEEK_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

INSEASON_FEATURES_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

OUTPUT_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_sequential_team_strength.parquet"
)

print("Preseason ratings:", PRESEASON_STRENGTH_PATH)
print("Prior-week ratings:", PRIOR_WEEK_STRENGTH_PATH)
print("New in-season features:", INSEASON_FEATURES_PATH)
print("Weekly output:", OUTPUT_PATH)

Preseason ratings: ..\..\data\processed\2026_team_strength.parquet
Prior-week ratings: ..\..\data\processed\weekly\week_05_sequential_team_strength.parquet
New in-season features: ..\..\data\processed\weekly\week_06_inseason_features.parquet
Weekly output: ..\..\data\processed\weekly\week_06_sequential_team_strength.parquet

# Load Frozen Preseason Team Strength

The preseason team strength file is the final output of the original `05_Team_Strength_Model.ipynb`.

Its `team_strength` value is already expressed in point differential terms, so it can serve directly as the prior for weekly updates.

We immediately rename the important preseason columns so it is impossible to confuse the original ratings with the new weekly ratings.

In [3]:
preseason = pd.read_parquet(
    PRESEASON_STRENGTH_PATH
).copy()

required_preseason_columns = [
    "team",
    "team_strength",
    "baseline_team_strength",
    "personnel_adjustment",
    "personnel_strength",
    "roster_continuity",
    "roster_continuity_adjustment"
]

missing_preseason = [
    column
    for column in required_preseason_columns
    if column not in preseason.columns
]

if missing_preseason:
    raise KeyError(
        "Missing required preseason columns: "
        + ", ".join(missing_preseason)
    )

preseason = preseason.rename(
    columns={
        "strength_rank": "preseason_strength_rank",
        "team_strength": "preseason_team_strength",
        "baseline_team_strength": "preseason_baseline_team_strength",
        "personnel_adjustment": "preseason_personnel_adjustment",
        "personnel_strength": "preseason_personnel_strength",
        "roster_continuity": "preseason_roster_continuity",
        "roster_continuity_adjustment": "preseason_roster_continuity_adjustment"
    }
)

print("Preseason teams:", len(preseason))
print("Unique teams:", preseason["team"].nunique())

display(
    preseason[
        [
            "preseason_strength_rank",
            "team",
            "preseason_team_strength",
            "preseason_baseline_team_strength",
            "preseason_personnel_adjustment",
            "preseason_roster_continuity_adjustment"
        ]
    ].sort_values(
        "preseason_strength_rank"
    )
)

Preseason teams: 32
Unique teams: 32

,preseason_strength_rank,team,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_roster_continuity_adjustment
0,1,BUF,4.816514,4.125764,0.934506,0.260091
1,2,LA,4.762452,3.257133,2.100811,0.489665
2,3,SEA,4.363421,3.515976,0.635683,0.932073
3,4,DET,4.018565,3.374644,1.041923,0.037533
4,5,DEN,3.569507,2.355154,0.979753,1.253003
5,6,BAL,3.074111,2.710864,0.636254,-0.037012
6,7,HOU,2.810133,2.193179,1.173833,-0.174691
7,8,GB,2.536317,1.718369,0.882628,0.576742
8,9,PHI,2.451919,2.324982,0.264690,-0.063756
9,10,SF,2.366788,1.805709,0.692939,0.290631
10,11,NE,1.910188,1.605622,0.906186,-0.478291
11,12,JAX,1.713136,1.746953,-0.223729,0.200841
12,13,KC,1.302244,1.484935,-0.187743,-0.140090
13,14,LAC,0.910681,1.089525,-0.382598,0.101429
14,15,TB,0.601026,0.449564,0.167912,0.101429
15,16,PIT,0.543902,0.359049,0.304322,0.004521
16,17,IND,0.532226,0.543256,-0.167564,0.179017
17,18,MIN,0.475040,0.919610,-0.620638,-0.144374
18,19,CHI,-0.051934,-0.069709,0.002783,0.032209
19,20,DAL,-0.386396,-0.773189,0.640887,0.004521
20,21,CIN,-0.739434,-1.268642,0.286293,0.714864
21,22,ATL,-1.331272,-1.430617,0.664859,-0.599141
22,23,NO,-1.556053,-1.584652,-0.112569,0.192281
23,24,WAS,-2.001869,-1.962594,0.021167,-0.103950
24,25,MIA,-2.443254,-1.116195,-0.947865,-1.516681
25,26,NYG,-3.455862,-2.902685,-0.687303,-0.281590
26,27,ARI,-3.678016,-2.961441,-1.166618,-0.033208
27,28,CLE,-4.150395,-3.147236,-1.385118,-0.344177
28,29,CAR,-4.533242,-3.703033,-1.322770,-0.073094
29,30,LV,-5.693342,-4.625655,-1.325021,-0.545348
30,31,NYJ,-5.933726,-4.805098,-1.734836,-0.175452
31,32,TEN,-6.747344,-5.173512,-2.073057,-0.659994

# Load Prior-Week Team Strength

The previous week's team strength file is the starting point for the new weekly update.

For Week 3, the model begins with the Week 2 ratings.

This prevents older games from being counted repeatedly and creates a true sequential rating system.

In [4]:
prior_week = pd.read_parquet(
    PRIOR_WEEK_STRENGTH_PATH
).copy()

required_prior_columns = [
    "team",
    "weekly_strength_rank",
    "weekly_team_strength",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment"
]

missing_prior = [
    column
    for column in required_prior_columns
    if column not in prior_week.columns
]

if missing_prior:
    raise KeyError(
        "Missing required prior-week columns: "
        + ", ".join(missing_prior)
    )

prior_week = prior_week[
    required_prior_columns
].rename(
    columns={
        "weekly_strength_rank":
            "prior_week_strength_rank",
        "weekly_team_strength":
            "prior_week_team_strength",
        "cumulative_offense_adjustment":
            "prior_cumulative_offense_adjustment",
        "cumulative_defense_adjustment":
            "prior_cumulative_defense_adjustment"
    }
)

print(
    f"Week {PRIOR_WEEK} teams:",
    len(prior_week)
)

print(
    "Unique teams:",
    prior_week["team"].nunique()
)

display(
    prior_week.sort_values(
        "prior_week_strength_rank"
    )
)

Week 5 teams: 32
Unique teams: 32

,team,prior_week_strength_rank,prior_week_team_strength,prior_cumulative_offense_adjustment,prior_cumulative_defense_adjustment
0,SF,1,5.115310,4.460402,4.291652
1,BUF,2,5.000529,5.417927,-1.950823
2,SEA,3,4.618006,1.705610,2.736860
3,LA,4,4.253705,-1.008286,1.522964
4,JAX,5,4.148852,1.810413,5.991663
5,KC,6,3.165481,3.685027,2.166277
6,BAL,7,2.696986,3.238326,-0.830424
7,DEN,8,2.535135,-2.272381,0.258869
8,NE,9,2.526854,-3.612686,2.818564
9,MIN,10,2.467510,-1.065500,6.115750
10,CHI,11,2.211567,2.722068,3.903318
11,DET,12,1.527588,3.780570,-5.388180
12,IND,13,0.950515,1.616517,-1.552233
13,CIN,14,0.450493,0.927425,1.358675
14,DAL,15,0.443958,4.396241,-2.972509
15,HOU,16,0.155800,-1.118753,-2.337503
16,PHI,17,0.076707,-2.813018,-0.281768
17,GB,18,0.044335,-3.252049,-2.220799
18,ATL,19,-0.336098,0.345129,-0.123621
19,PIT,20,-0.505123,-2.405536,0.725714
20,LAC,21,-1.470386,-3.722919,-1.941669
21,TB,22,-1.832732,-2.614585,-0.683335
22,LV,23,-2.021235,3.408868,1.290118
23,NO,24,-2.264969,2.012524,-5.206226
24,NYG,25,-2.757233,-1.855386,1.725864
25,WAS,26,-3.164962,-0.424784,-4.193534
26,CAR,27,-3.513248,4.150041,-2.618709
27,CLE,28,-3.639662,-1.810816,-0.479566
28,ARI,29,-4.246405,-0.582677,-3.451427
29,NYJ,30,-4.786024,-2.497546,1.233704
30,MIA,31,-4.993609,-6.834583,-1.153333
31,TEN,32,-6.801614,-5.777180,1.254070

# Load New Weekly In-Season Features

These features contain the new evidence generated in notebook `03`.

For Week 3, they describe each team's Week 2 performance relative to its entering Week 2 expectation.

The primary values used here are:

- `weekly_strength_update`
- `weekly_offense_adjustment`
- `weekly_defense_adjustment`

The overall strength update is opponent adjusted and uses diminishing returns for extreme single game results.

In [5]:
inseason = pd.read_parquet(
    INSEASON_FEATURES_PATH
).copy()

required_inseason_columns = [
    "team",
    "games_in_update",
    "entering_team_strength",
    "entering_strength_rank",
    "average_opponent_strength",
    "average_opponent_rank",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

missing_inseason = [
    column
    for column in required_inseason_columns
    if column not in inseason.columns
]

if missing_inseason:
    raise KeyError(
        "Missing required in-season columns: "
        + ", ".join(missing_inseason)
    )

print("In-season teams:", len(inseason))
print(
    "Unique teams:",
    inseason["team"].nunique()
)

display(
    inseason[
        required_inseason_columns
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

In-season teams: 30
Unique teams: 30

,team,games_in_update,entering_team_strength,entering_strength_rank,average_opponent_strength,average_opponent_rank,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
10,GB,1,0.044335,18,2.211567,11.0,24.0,-0.667232,24.667232,1.414080,1.102934,2.662934
19,NE,1,2.526854,9,-2.021235,23.0,28.0,6.048089,21.951911,1.375059,3.044204,1.004204
9,DET,1,1.527588,12,-4.246405,29.0,24.0,4.273993,19.726007,1.330923,2.960760,0.320760
11,HOU,1,0.155800,16,-6.801614,32.0,23.0,5.457414,17.542586,1.273702,0.014939,2.924939
24,PIT,1,-0.505123,20,0.950515,13.0,12.0,0.044362,11.955638,1.039710,1.505644,0.365644
27,TB,1,-1.832732,22,0.443958,15.0,8.0,-3.776690,11.776690,1.029660,-0.013352,1.246648
18,MIN,1,2.467510,10,-2.264969,24.0,10.0,3.232479,6.767521,0.673437,-0.264936,1.595064
2,BAL,1,2.696986,7,-0.336098,19.0,7.0,1.533084,5.466916,0.557679,0.857396,0.167396
22,NYJ,1,-4.786024,30,-3.639662,28.0,5.0,0.353638,4.646362,0.480318,-1.216487,1.693513
26,SF,1,5.115310,1,4.618006,3.0,3.0,-1.002696,4.002696,0.417545,1.343175,-0.546825
3,BUF,1,5.000529,2,4.253705,4.0,3.0,-0.753176,3.753176,0.392762,2.079514,-1.310486
23,PHI,1,0.076707,17,4.148852,5.0,-2.0,-5.572145,3.572145,0.374635,-0.924418,0.935582
8,DEN,1,2.535135,8,-1.470386,21.0,6.0,2.505521,3.494479,0.366822,-0.235139,1.024861
5,CIN,1,0.450493,14,-4.993609,31.0,7.0,3.944102,3.055898,0.322315,0.832740,-0.157260
21,NYG,1,-2.757233,25,-3.164962,26.0,0.0,-1.092271,1.092271,0.116792,0.301314,-0.538686
29,WAS,1,-3.164962,26,-2.757233,25.0,0.0,1.092271,-1.092271,-0.116792,0.316604,-0.523396
17,MIA,1,-4.993609,31,0.450493,14.0,-7.0,-3.944102,-3.055898,-0.322315,-0.013107,-1.003107
15,LAC,1,-1.470386,21,2.535135,8.0,-6.0,-2.505521,-3.494479,-0.366822,-0.984932,0.275068
13,JAX,1,4.148852,5,0.076707,17.0,2.0,5.572145,-3.572145,-0.374635,-0.777123,1.082877
14,LA,1,4.253705,4,5.000529,2.0,-3.0,0.753176,-3.753176,-0.392762,1.657520,-1.732480
25,SEA,1,4.618006,3,5.115310,1.0,-3.0,1.002696,-4.002696,-0.417545,0.911824,-0.978176
6,CLE,1,-3.639662,28,-4.786024,30.0,-5.0,-0.353638,-4.646362,-0.480318,-2.009476,0.900524
1,ATL,1,-0.336098,19,2.696986,7.0,-7.0,-1.533084,-5.466916,-0.557679,-0.078863,-0.768863
20,NO,1,-2.264969,24,2.467510,10.0,-10.0,-3.232479,-6.767521,-0.673437,-1.587468,0.272532
7,DAL,1,0.443958,15,-1.832732,22.0,-8.0,3.776690,-11.776690,-1.029660,-1.298727,-0.038727
12,IND,1,0.950515,13,-0.505123,20.0,-12.0,-0.044362,-11.955638,-1.039710,-0.348942,-1.488942
28,TEN,1,-6.801614,32,0.155800,16.0,-23.0,-5.457414,-17.542586,-1.273702,-3.174158,-0.264158
0,ARI,1,-4.246405,29,1.527588,12.0,-24.0,-4.273993,-19.726007,-1.330923,-0.422715,-3.062715
16,LV,1,-2.021235,23,2.526854,9.0,-28.0,-6.048089,-21.951911,-1.375059,-0.985243,-3.025243
4,CHI,1,2.211567,11,0.044335,18.0,-24.0,0.667232,-24.667232,-1.414080,-2.578337,-1.018337

# Merge Prior Week State with New Evidence

The weekly model now combines three pieces of information:

1. Frozen preseason information for long term reference
2. Previous week's team strength as the current prior
3. Most recent week's opponent adjusted performance as new evidence

All 32 teams must remain in the table.

In [6]:
weekly_strength = (
    preseason
    .merge(
        prior_week,
        on="team",
        how="left",
        validate="one_to_one"
    )
    .merge(
        inseason,
        on="team",
        how="left",
        validate="one_to_one"
    )
)

weekly_fill_columns = [
    "games_in_update",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

weekly_strength[
    weekly_fill_columns
] = (
    weekly_strength[
        weekly_fill_columns
    ]
    .fillna(0.0)
)

print("Merged teams:", len(weekly_strength))
print(
    "Unique teams:",
    weekly_strength["team"].nunique()
)

print(
    "Missing prior-week strengths:",
    weekly_strength[
        "prior_week_team_strength"
    ].isna().sum()
)

Merged teams: 32
Unique teams: 32
Missing prior-week strengths: 0

# Sequential Weekly Rating Update

The previous week's team strength is the starting point.

The current week's opponent adjusted performance update is then applied:

`weekly_team_strength = prior_week_team_strength + weekly_strength_update`

Therefore, for Week 3:

`Week 3 Strength = Week 2 Strength + Week 2 Performance Update`

Older results remain embedded in the prior week rating and are not counted again.

The offensive and defensive weekly adjustments remain available separately for the weekly scoring model.

In [7]:
weekly_strength["team_strength_change"] = (
    weekly_strength["weekly_strength_update"]
)

weekly_strength["weekly_team_strength"] = (
    weekly_strength["prior_week_team_strength"]
    + weekly_strength["team_strength_change"]
)

display(
    weekly_strength[
        [
            "team",
            "prior_week_team_strength",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment",
            "team_strength_change",
            "weekly_team_strength"
        ]
    ].sort_values(
        "weekly_team_strength",
        ascending=False
    )
)

,team,prior_week_team_strength,weekly_offense_adjustment,weekly_defense_adjustment,team_strength_change,weekly_team_strength
9,SF,5.115310,1.343175,-0.546825,0.417545,5.532855
0,BUF,5.000529,2.079514,-1.310486,0.392762,5.393291
2,SEA,4.618006,0.911824,-0.978176,-0.417545,4.200461
10,NE,2.526854,3.044204,1.004204,1.375059,3.901913
1,LA,4.253705,1.657520,-1.732480,-0.392762,3.860944
11,JAX,4.148852,-0.777123,1.082877,-0.374635,3.774217
5,BAL,2.696986,0.857396,0.167396,0.557679,3.254665
12,KC,3.165481,0.000000,0.000000,0.000000,3.165481
17,MIN,2.467510,-0.264936,1.595064,0.673437,3.140947
4,DEN,2.535135,-0.235139,1.024861,0.366822,2.901957
3,DET,1.527588,2.960760,0.320760,1.330923,2.858510
7,GB,0.044335,1.102934,2.662934,1.414080,1.458414
6,HOU,0.155800,0.014939,2.924939,1.273702,1.429501
18,CHI,2.211567,-2.578337,-1.018337,-1.414080,0.797487
20,CIN,0.450493,0.832740,-0.157260,0.322315,0.772808
15,PIT,-0.505123,1.505644,0.365644,1.039710,0.534587
8,PHI,0.076707,-0.924418,0.935582,0.374635,0.451342
16,IND,0.950515,-0.348942,-1.488942,-1.039710,-0.089195
19,DAL,0.443958,-1.298727,-0.038727,-1.029660,-0.585702
14,TB,-1.832732,-0.013352,1.246648,1.029660,-0.803072
21,ATL,-0.336098,-0.078863,-0.768863,-0.557679,-0.893777
13,LAC,-1.470386,-0.984932,0.275068,-0.366822,-1.837208
25,NYG,-2.757233,0.301314,-0.538686,0.116792,-2.640440
22,NO,-2.264969,-1.587468,0.272532,-0.673437,-2.938405
23,WAS,-3.164962,0.316604,-0.523396,-0.116792,-3.281754
29,LV,-2.021235,-0.985243,-3.025243,-1.375059,-3.396294
28,CAR,-3.513248,0.000000,0.000000,0.000000,-3.513248
27,CLE,-3.639662,-2.009476,0.900524,-0.480318,-4.119980
30,NYJ,-4.786024,-1.216487,1.693513,0.480318,-4.305707
24,MIA,-4.993609,-0.013107,-1.003107,-0.322315,-5.315924
26,ARI,-4.246405,-0.422715,-3.062715,-1.330923,-5.577328
31,TEN,-6.801614,-3.174158,-0.264158,-1.273702,-8.075316

In [8]:
weekly_strength["cumulative_offense_adjustment"] = (
    weekly_strength["prior_cumulative_offense_adjustment"]
    + weekly_strength["weekly_offense_adjustment"]
)

weekly_strength["cumulative_defense_adjustment"] = (
    weekly_strength["prior_cumulative_defense_adjustment"]
    + weekly_strength["weekly_defense_adjustment"]
)

assert weekly_strength[
    "cumulative_offense_adjustment"
].notna().all()

assert weekly_strength[
    "cumulative_defense_adjustment"
].notna().all()

# Updated Weekly Rankings

The current weekly rank is based on `weekly_team_strength`.

Ranking movement is now measured relative to the immediately previous week rather than the preseason ranking.

A positive `rank_change` means the team moved up.

For example:

- Week 2 rank = 8
- Week 3 rank = 5
- Rank change = +3

In [9]:
weekly_strength = weekly_strength.sort_values(
    [
        "weekly_team_strength",
        "prior_week_team_strength"
    ],
    ascending=[False, False]
).reset_index(drop=True)

weekly_strength["weekly_strength_rank"] = (
    np.arange(
        1,
        len(weekly_strength) + 1
    )
)

weekly_strength["rank_change"] = (
    weekly_strength["prior_week_strength_rank"]
    - weekly_strength["weekly_strength_rank"]
)

weekly_comparison_table = (
    weekly_strength[
        [
            "weekly_strength_rank",
            "team",
            "weekly_team_strength",
            "prior_week_strength_rank",
            "prior_week_team_strength",
            "team_strength_change",
            "rank_change"
        ]
    ]
    .copy()
)

display(weekly_comparison_table)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change
0,1,SF,5.532855,1,5.115310,0.417545,0
1,2,BUF,5.393291,2,5.000529,0.392762,0
2,3,SEA,4.200461,3,4.618006,-0.417545,0
3,4,NE,3.901913,9,2.526854,1.375059,5
4,5,LA,3.860944,4,4.253705,-0.392762,-1
5,6,JAX,3.774217,5,4.148852,-0.374635,-1
6,7,BAL,3.254665,7,2.696986,0.557679,0
7,8,KC,3.165481,6,3.165481,0.000000,-2
8,9,MIN,3.140947,10,2.467510,0.673437,1
9,10,DEN,2.901957,8,2.535135,0.366822,-2
10,11,DET,2.858510,12,1.527588,1.330923,1
11,12,GB,1.458414,18,0.044335,1.414080,6
12,13,HOU,1.429501,16,0.155800,1.273702,3
13,14,CHI,0.797487,11,2.211567,-1.414080,-3
14,15,CIN,0.772808,14,0.450493,0.322315,-1
15,16,PIT,0.534587,20,-0.505123,1.039710,4
16,17,PHI,0.451342,17,0.076707,0.374635,0
17,18,IND,-0.089195,13,0.950515,-1.039710,-5
18,19,DAL,-0.585702,15,0.443958,-1.029660,-4
19,20,TB,-0.803072,22,-1.832732,1.029660,2
20,21,ATL,-0.893777,19,-0.336098,-0.557679,-2
21,22,LAC,-1.837208,21,-1.470386,-0.366822,-1
22,23,NYG,-2.640440,25,-2.757233,0.116792,2
23,24,NO,-2.938405,24,-2.264969,-0.673437,0
24,25,WAS,-3.281754,26,-3.164962,-0.116792,1
25,26,LV,-3.396294,23,-2.021235,-1.375059,-3
26,27,CAR,-3.513248,27,-3.513248,0.000000,0
27,28,CLE,-4.119980,28,-3.639662,-0.480318,0
28,29,NYJ,-4.305707,30,-4.786024,0.480318,1
29,30,MIA,-5.315924,31,-4.993609,-0.322315,1
30,31,ARI,-5.577328,29,-4.246405,-1.330923,-2
31,32,TEN,-8.075316,32,-6.801614,-1.273702,0

# Biggest Weekly Movers

This table is diagnostic only.

It shows which teams experienced the largest overall rating changes from the previous week to the current week.

The underlying projection model still retains the full preseason, offense, defense, opponent and weekly information.

In [10]:
mover_columns = [
    "team",
    "prior_week_team_strength",
    "team_strength_change",
    "weekly_team_strength",
    "prior_week_strength_rank",
    "weekly_strength_rank",
    "rank_change"
]

biggest_risers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=False
    )
    .head(10)
)

biggest_fallers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=True
    )
    .head(10)
)

print("BIGGEST RISERS")
display(biggest_risers)

print()
print("BIGGEST FALLERS")
display(biggest_fallers)

BIGGEST RISERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
11,GB,0.044335,1.414080,1.458414,18,12,6
3,NE,2.526854,1.375059,3.901913,9,4,5
10,DET,1.527588,1.330923,2.858510,12,11,1
12,HOU,0.155800,1.273702,1.429501,16,13,3
15,PIT,-0.505123,1.039710,0.534587,20,16,4
19,TB,-1.832732,1.029660,-0.803072,22,20,2
8,MIN,2.467510,0.673437,3.140947,10,9,1
6,BAL,2.696986,0.557679,3.254665,7,7,0
28,NYJ,-4.786024,0.480318,-4.305707,30,29,1
0,SF,5.115310,0.417545,5.532855,1,1,0

BIGGEST FALLERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
13,CHI,2.211567,-1.414080,0.797487,11,14,-3
25,LV,-2.021235,-1.375059,-3.396294,23,26,-3
30,ARI,-4.246405,-1.330923,-5.577328,29,31,-2
31,TEN,-6.801614,-1.273702,-8.075316,32,32,0
17,IND,0.950515,-1.039710,-0.089195,13,18,-5
18,DAL,0.443958,-1.029660,-0.585702,15,19,-4
23,NO,-2.264969,-0.673437,-2.938405,24,24,0
20,ATL,-0.336098,-0.557679,-0.893777,19,21,-2
27,CLE,-3.639662,-0.480318,-4.119980,28,28,0
2,SEA,4.618006,-0.417545,4.200461,3,3,0

# Update Diagnostics

These diagnostics check the size and distribution of the sequential weekly update.

The comparison is now:

`Prior Week Strength → Current Week Strength`

rather than:

`Preseason Strength → Current Week Strength`

In [11]:
movement = (
    weekly_strength[
        "team_strength_change"
    ].abs()
)

print(
    f"WEEK {PRIOR_WEEK} → "
    f"WEEK {TARGET_WEEK} TEAM-STRENGTH MOVEMENT"
)

print(
    weekly_strength[
        "team_strength_change"
    ]
    .describe()
    .round(3)
)

print()

print(
    "Mean absolute movement:",
    round(
        movement.mean(),
        3
    )
)

print(
    "Maximum absolute movement:",
    round(
        movement.max(),
        3
    )
)

print(
    "Team with largest movement:",
    weekly_strength.loc[
        movement.idxmax(),
        "team"
    ]
)

print()
print("RATING DISTRIBUTIONS")

distribution_check = pd.DataFrame(
    {
        "metric": [
            f"Week {PRIOR_WEEK} Team Strength",
            f"Week {TARGET_WEEK} Team Strength"
        ],
        "mean": [
            weekly_strength[
                "prior_week_team_strength"
            ].mean(),
            weekly_strength[
                "weekly_team_strength"
            ].mean()
        ],
        "std": [
            weekly_strength[
                "prior_week_team_strength"
            ].std(),
            weekly_strength[
                "weekly_team_strength"
            ].std()
        ],
        "min": [
            weekly_strength[
                "prior_week_team_strength"
            ].min(),
            weekly_strength[
                "weekly_team_strength"
            ].min()
        ],
        "max": [
            weekly_strength[
                "prior_week_team_strength"
            ].max(),
            weekly_strength[
                "weekly_team_strength"
            ].max()
        ]
    }
)

display(
    distribution_check.round(3)
)

WEEK 5 → WEEK 6 TEAM-STRENGTH MOVEMENT
count    32.000
mean      0.000
std       0.848
min      -1.414
25%      -0.500
50%       0.000
75%       0.500
max       1.414
Name: team_strength_change, dtype: float64

Mean absolute movement: 0.698
Maximum absolute movement: 1.414
Team with largest movement: GB

RATING DISTRIBUTIONS

                 metric   mean    std    min    max
0  Week 5 Team Strength  0.002  3.228 -6.802  5.115
1  Week 6 Team Strength  0.002  3.548 -8.075  5.533

# Sanity Checks

These checks verify the sequential weekly update.

The weekly file should:

- contain exactly 32 unique teams
- preserve the frozen preseason information
- contain a valid prior week rating for every team
- contain no missing current weekly strength values
- have `team_strength_change` equal to the new opponent adjusted weekly update
- calculate current strength as prior week strength plus the weekly update
- never overwrite the preseason or prior week files

In [12]:
assert len(weekly_strength) == 32, (
    "Expected 32 teams in weekly strength table."
)

assert (
    weekly_strength["team"].nunique()
    == 32
), (
    "Expected 32 unique teams."
)

assert weekly_strength[
    "preseason_team_strength"
].notna().all(), (
    "Missing frozen preseason ratings."
)

assert weekly_strength[
    "prior_week_team_strength"
].notna().all(), (
    "Missing prior-week ratings."
)

assert weekly_strength[
    "weekly_team_strength"
].notna().all(), (
    "Missing current weekly ratings."
)

assert np.allclose(
    weekly_strength[
        "team_strength_change"
    ],
    weekly_strength[
        "weekly_strength_update"
    ]
), (
    "Team-strength change does not match "
    "the opponent-adjusted weekly update."
)

assert np.allclose(
    weekly_strength[
        "weekly_team_strength"
    ],
    (
        weekly_strength[
            "prior_week_team_strength"
        ]
        + weekly_strength[
            "team_strength_change"
        ]
    )
), (
    "Sequential weekly strength formula "
    "is inconsistent."
)

played_mask = weekly_strength["games_in_update"] > 0

assert np.allclose(
    weekly_strength.loc[
        played_mask, "entering_team_strength"
    ],
    weekly_strength.loc[
        played_mask, "prior_week_team_strength"
    ]
), (
    "Notebook 03 entering strength does not match "
    "the prior-week team strength."
)

bye_mask = ~played_mask

assert np.allclose(
    weekly_strength.loc[
        bye_mask, "weekly_team_strength"
    ],
    weekly_strength.loc[
        bye_mask, "prior_week_team_strength"
    ]
), "Bye-week teams did not retain their previous strength."

print(
    "All sequential weekly team-strength "
    "sanity checks passed."
)

All sequential weekly team-strength sanity checks passed.

# Final Weekly Team Strength Table

The saved file contains the full state needed by the weekly projection pipeline.

This includes:

- current weekly strength and rank
- previous week's strength and rank
- week to week movement
- frozen preseason information
- opponent adjusted performance information
- separate offensive and defensive weekly signals

The compact ranking table shown earlier is only for interpretation. The saved dataset retains the additional model information.

In [13]:
final_columns = [
    "weekly_strength_rank",
    "team",
    "weekly_team_strength",

    "prior_week_strength_rank",
    "prior_week_team_strength",
    "team_strength_change",
    "rank_change",

    "games_in_update",
    "average_opponent_rank",
    "average_opponent_strength",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",

    "weekly_offense_adjustment",
    "weekly_defense_adjustment",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment",

    "preseason_strength_rank",
    "preseason_team_strength",
    "preseason_baseline_team_strength",
    "preseason_personnel_adjustment",
    "preseason_personnel_strength",
    "preseason_roster_continuity",
    "preseason_roster_continuity_adjustment"
]

weekly_team_strength = (
    weekly_strength[
        final_columns
    ]
    .copy()
)

display(
    weekly_team_strength
)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change,games_in_update,average_opponent_rank,average_opponent_strength,...,weekly_defense_adjustment,cumulative_offense_adjustment,cumulative_defense_adjustment,preseason_strength_rank,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_personnel_strength,preseason_roster_continuity,preseason_roster_continuity_adjustment
0,1,SF,5.532855,1,5.115310,0.417545,0,1.0,3.0,4.618006,...,-0.546825,5.803577,3.744827,10,2.366788,1.805709,0.692939,0.461959,0.577778,0.290631
1,2,BUF,5.393291,2,5.000529,0.392762,0,1.0,4.0,4.253705,...,-1.310486,7.497441,-3.261309,1,4.816514,4.125764,0.934506,0.623004,0.573034,0.260091
2,3,SEA,4.200461,3,4.618006,-0.417545,0,1.0,1.0,5.115310,...,-0.978176,2.617435,1.758685,3,4.363421,3.515976,0.635683,0.423788,0.677419,0.932073
3,4,NE,3.901913,9,2.526854,1.375059,5,1.0,23.0,-2.021235,...,1.004204,-0.568482,3.822768,11,1.910188,1.605622,0.906186,0.604124,0.458333,-0.478291
4,5,LA,3.860944,4,4.253705,-0.392762,-1,1.0,2.0,5.000529,...,-1.732480,0.649234,-0.209516,2,4.762452,3.257133,2.100811,1.400540,0.608696,0.489665
5,6,JAX,3.774217,5,4.148852,-0.374635,-1,1.0,17.0,0.076707,...,1.082877,1.033289,7.074539,12,1.713136,1.746953,-0.223729,-0.149153,0.563830,0.200841
6,7,BAL,3.254665,7,2.696986,0.557679,0,1.0,19.0,-0.336098,...,0.167396,4.095722,-0.663028,6,3.074111,2.710864,0.636254,0.424170,0.526882,-0.037012
7,8,KC,3.165481,6,3.165481,0.000000,-2,0.0,NaN,NaN,...,0.000000,3.685027,2.166277,13,1.302244,1.484935,-0.187743,-0.125162,0.510870,-0.140090
8,9,MIN,3.140947,10,2.467510,0.673437,1,1.0,24.0,-2.264969,...,1.595064,-1.330436,7.710814,18,0.475040,0.919610,-0.620638,-0.413759,0.510204,-0.144374
9,10,DEN,2.901957,8,2.535135,0.366822,-2,1.0,21.0,-1.470386,...,1.024861,-2.507520,1.283730,5,3.569507,2.355154,0.979753,0.653169,0.727273,1.253003
10,11,DET,2.858510,12,1.527588,1.330923,1,1.0,29.0,-4.246405,...,0.320760,6.741330,-5.067420,4,4.018565,3.374644,1.041923,0.694616,0.538462,0.037533
11,12,GB,1.458414,18,0.044335,1.414080,6,1.0,11.0,2.211567,...,2.662934,-2.149116,0.442134,8,2.536317,1.718369,0.882628,0.588419,0.622222,0.576742
12,13,HOU,1.429501,16,0.155800,1.273702,3,1.0,32.0,-6.801614,...,2.924939,-1.103813,0.587437,7,2.810133,2.193179,1.173833,0.782555,0.505495,-0.174691
13,14,CHI,0.797487,11,2.211567,-1.414080,-3,1.0,18.0,0.044335,...,-1.018337,0.143731,2.884981,19,-0.051934,-0.069709,0.002783,0.001856,0.537634,0.032209
14,15,CIN,0.772808,14,0.450493,0.322315,-1,1.0,31.0,-4.993609,...,-0.157260,1.760165,1.201415,21,-0.739434,-1.268642,0.286293,0.190862,0.643678,0.714864
15,16,PIT,0.534587,20,-0.505123,1.039710,4,1.0,13.0,0.950515,...,0.365644,-0.899891,1.091359,16,0.543902,0.359049,0.304322,0.202881,0.533333,0.004521
16,17,PHI,0.451342,17,0.076707,0.374635,0,1.0,5.0,4.148852,...,0.935582,-3.737436,0.653814,9,2.451919,2.324982,0.264690,0.176460,0.522727,-0.063756
17,18,IND,-0.089195,13,0.950515,-1.039710,-5,1.0,20.0,-0.505123,...,-1.488942,1.267575,-3.041175,17,0.532226,0.543256,-0.167564,-0.111709,0.560440,0.179017
18,19,DAL,-0.585702,15,0.443958,-1.029660,-4,1.0,22.0,-1.832732,...,-0.038727,3.097513,-3.011237,20,-0.386396,-0.773189,0.640887,0.427258,0.533333,0.004521
19,20,TB,-0.803072,22,-1.832732,1.029660,2,1.0,15.0,0.443958,...,1.246648,-2.627936,0.563314,15,0.601026,0.449564,0.167912,0.111942,0.548387,0.101429
20,21,ATL,-0.893777,19,-0.336098,-0.557679,-2,1.0,7.0,2.696986,...,-0.768863,0.266266,-0.892484,22,-1.331272,-1.430617,0.664859,0.443239,0.439560,-0.599141
21,22,LAC,-1.837208,21,-1.470386,-0.366822,-1,1.0,8.0,2.535135,...,0.275068,-4.707852,-1.666602,14,0.910681,1.089525,-0.382598,-0.255065,0.548387,0.101429
22,23,NYG,-2.640440,25,-2.757233,0.116792,2,1.0,26.0,-3.164962,...,-0.538686,-1.554073,1.187177,26,-3.455862,-2.902685,-0.687303,-0.458202,0.488889,-0.281590
23,24,NO,-2.938405,24,-2.264969,-0.673437,0,1.0,10.0,2.467510,...,0.272532,0.425055,-4.933695,23,-1.556053,-1.584652,-0.112569,-0.075046,0.562500,0.192281
24,25,WAS,-3.281754,26,-3.164962,-0.116792,1,1.0,25.0,-2.757233,...,-0.523396,-0.108180,-4.716930,24,-2.001869,-1.962594,0.021167,0.014111,0.516484,-0.103950
25,26,LV,-3.396294,23,-2.021235,-1.375059,-3,1.0,9.0,2.526854,...,-3.025243,2.423625,-1.735125,30,-5.693342,-4.625655,-1.325021,-0.883347,0.447917,-0.545348
26,27,CAR,-3.513248,27,-3.513248,0.000000,0,0.0,NaN,NaN,...,0.000000,4.150041,-2.618709,29,-4.533242,-3.703033,-1.322770,-0.881847,0.521277,-0.073094
27,28,CLE,-4.119980,28,-3.639662,-0.480318,0,1.0,30.0,-4.786024,...,0.900524,-3.820292,0.420958,28,-4.150395,-3.147236,-1.385118,-0.923412,0.479167,-0.344177
28,29,NYJ,-4.305707,30,-4.786024,0.480318,1,1.0,28.0,-3.639662,...,1.693513,-3.714033,2.927217,31,-5.933726,-4.805098,-1.734836,-1.156558,0.505376,-0.175452
29,30,MIA,-5.315924,31,-4.993609,-0.322315,1,1.0,14.0,0.450493,...,-1.003107,-6.847689,-2.156439,25,-2.443254,-1.116195,-0.947865,-0.631910,0.297030,-1.516681
30,31,ARI,-5.577328,29,-4.246405,-1.330923,-2,1.0,12.0,1.527588,...,-3.062715,-1.005392,-6.514142,27,-3.678016,-2.961441,-1.166618,-0.777745,0.527473,-0.033208
31,32,TEN,-8.075316,32,-6.801614,-1.273702,0,1.0,16.0,0.155800,...,-0.264158,-8.951338,0.989912,32,-6.747344,-5.173512,-2.073057,-1.382038,0.430108,-0.659994

# Save Weekly Team Strength

This writes only to:

`data/processed/weekly/`

The original:

`data/processed/2026_team_strength.parquet`

remains untouched.

In [14]:
OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

weekly_team_strength.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("Saved:", OUTPUT_PATH)
print()
print(
    "Original preseason file remains:",
    PRESEASON_STRENGTH_PATH
)

Saved: ..\..\data\processed\weekly\week_06_sequential_team_strength.parquet

Original preseason file remains: ..\..\data\processed\2026_team_strength.parquet

# What This Means for Week 3

At the end of this notebook, every team has:

- its frozen preseason rating
- its Week 2 entering rating and rank
- its opponent adjusted Week 2 performance
- its Week 2 offensive and defensive signals
- its Week 2 → Week 3 rating movement
- its updated Week 3 team strength rating
- its updated Week 3 rank

The next stage will apply the Week 3 injury update and then use the resulting team state to generate Week 3 game projections.

The weekly ranking table is diagnostic only.

The saved weekly team strength file retains the additional information required by the projection pipeline.