# 04 — Weekly Team Strength

This notebook updates team strength sequentially using the new in season evidence created in `03_Inseason_Feature_Engineering.ipynb`.

The original preseason model remains unchanged.

The weekly model follows a sequential principle:

> The previous week's team strength is the prior. The most recently completed week provides new evidence.

For each target week, this notebook:

- Loads the frozen preseason ratings for reference
- Loads the previous week's team strength state
- Loads the target week's new in season feature table
- Applies the opponent adjusted weekly strength update
- Preserves separate offensive and defensive weekly signals
- Calculates current weekly rankings
- Compares rank and strength movement to the previous week
- Saves a separate weekly team strength file

No original preseason file or prior weekly file is overwritten.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the output from:

`03_Inseason_Feature_Engineering.ipynb`

For Week 3:

- `TARGET_WEEK = 3`
- `PRIOR_WEEK = 2`

The Week 2 team strength file becomes the entering prior for Week 3.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 4
PRIOR_WEEK = TARGET_WEEK - 1

PRESEASON_STRENGTH_PATH = (
    PROCESSED_DIR
    / "2026_team_strength.parquet"
)

PRIOR_WEEK_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

INSEASON_FEATURES_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

OUTPUT_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_sequential_team_strength.parquet"
)

print("Preseason ratings:", PRESEASON_STRENGTH_PATH)
print("Prior-week ratings:", PRIOR_WEEK_STRENGTH_PATH)
print("New in-season features:", INSEASON_FEATURES_PATH)
print("Weekly output:", OUTPUT_PATH)

Preseason ratings: ..\..\data\processed\2026_team_strength.parquet
Prior-week ratings: ..\..\data\processed\weekly\week_03_sequential_team_strength.parquet
New in-season features: ..\..\data\processed\weekly\week_04_inseason_features.parquet
Weekly output: ..\..\data\processed\weekly\week_04_sequential_team_strength.parquet

# Load Frozen Preseason Team Strength

The preseason team strength file is the final output of the original `05_Team_Strength_Model.ipynb`.

Its `team_strength` value is already expressed in point differential terms, so it can serve directly as the prior for weekly updates.

We immediately rename the important preseason columns so it is impossible to confuse the original ratings with the new weekly ratings.

In [3]:
preseason = pd.read_parquet(
    PRESEASON_STRENGTH_PATH
).copy()

required_preseason_columns = [
    "team",
    "team_strength",
    "baseline_team_strength",
    "personnel_adjustment",
    "personnel_strength",
    "roster_continuity",
    "roster_continuity_adjustment"
]

missing_preseason = [
    column
    for column in required_preseason_columns
    if column not in preseason.columns
]

if missing_preseason:
    raise KeyError(
        "Missing required preseason columns: "
        + ", ".join(missing_preseason)
    )

preseason = preseason.rename(
    columns={
        "strength_rank": "preseason_strength_rank",
        "team_strength": "preseason_team_strength",
        "baseline_team_strength": "preseason_baseline_team_strength",
        "personnel_adjustment": "preseason_personnel_adjustment",
        "personnel_strength": "preseason_personnel_strength",
        "roster_continuity": "preseason_roster_continuity",
        "roster_continuity_adjustment": "preseason_roster_continuity_adjustment"
    }
)

print("Preseason teams:", len(preseason))
print("Unique teams:", preseason["team"].nunique())

display(
    preseason[
        [
            "preseason_strength_rank",
            "team",
            "preseason_team_strength",
            "preseason_baseline_team_strength",
            "preseason_personnel_adjustment",
            "preseason_roster_continuity_adjustment"
        ]
    ].sort_values(
        "preseason_strength_rank"
    )
)

Preseason teams: 32
Unique teams: 32

,preseason_strength_rank,team,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_roster_continuity_adjustment
0,1,BUF,4.816514,4.125764,0.934506,0.260091
1,2,LA,4.762452,3.257133,2.100811,0.489665
2,3,SEA,4.363421,3.515976,0.635683,0.932073
3,4,DET,4.018565,3.374644,1.041923,0.037533
4,5,DEN,3.569507,2.355154,0.979753,1.253003
5,6,BAL,3.074111,2.710864,0.636254,-0.037012
6,7,HOU,2.810133,2.193179,1.173833,-0.174691
7,8,GB,2.536317,1.718369,0.882628,0.576742
8,9,PHI,2.451919,2.324982,0.264690,-0.063756
9,10,SF,2.366788,1.805709,0.692939,0.290631
10,11,NE,1.910188,1.605622,0.906186,-0.478291
11,12,JAX,1.713136,1.746953,-0.223729,0.200841
12,13,KC,1.302244,1.484935,-0.187743,-0.140090
13,14,LAC,0.910681,1.089525,-0.382598,0.101429
14,15,TB,0.601026,0.449564,0.167912,0.101429
15,16,PIT,0.543902,0.359049,0.304322,0.004521
16,17,IND,0.532226,0.543256,-0.167564,0.179017
17,18,MIN,0.475040,0.919610,-0.620638,-0.144374
18,19,CHI,-0.051934,-0.069709,0.002783,0.032209
19,20,DAL,-0.386396,-0.773189,0.640887,0.004521
20,21,CIN,-0.739434,-1.268642,0.286293,0.714864
21,22,ATL,-1.331272,-1.430617,0.664859,-0.599141
22,23,NO,-1.556053,-1.584652,-0.112569,0.192281
23,24,WAS,-2.001869,-1.962594,0.021167,-0.103950
24,25,MIA,-2.443254,-1.116195,-0.947865,-1.516681
25,26,NYG,-3.455862,-2.902685,-0.687303,-0.281590
26,27,ARI,-3.678016,-2.961441,-1.166618,-0.033208
27,28,CLE,-4.150395,-3.147236,-1.385118,-0.344177
28,29,CAR,-4.533242,-3.703033,-1.322770,-0.073094
29,30,LV,-5.693342,-4.625655,-1.325021,-0.545348
30,31,NYJ,-5.933726,-4.805098,-1.734836,-0.175452
31,32,TEN,-6.747344,-5.173512,-2.073057,-0.659994

# Load Prior-Week Team Strength

The previous week's team strength file is the starting point for the new weekly update.

For Week 3, the model begins with the Week 2 ratings.

This prevents older games from being counted repeatedly and creates a true sequential rating system.

In [4]:
prior_week = pd.read_parquet(
    PRIOR_WEEK_STRENGTH_PATH
).copy()

required_prior_columns = [
    "team",
    "weekly_strength_rank",
    "weekly_team_strength",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment"
]

missing_prior = [
    column
    for column in required_prior_columns
    if column not in prior_week.columns
]

if missing_prior:
    raise KeyError(
        "Missing required prior-week columns: "
        + ", ".join(missing_prior)
    )

prior_week = prior_week[
    required_prior_columns
].rename(
    columns={
        "weekly_strength_rank":
            "prior_week_strength_rank",
        "weekly_team_strength":
            "prior_week_team_strength",
        "cumulative_offense_adjustment":
            "prior_cumulative_offense_adjustment",
        "cumulative_defense_adjustment":
            "prior_cumulative_defense_adjustment"
    }
)

print(
    f"Week {PRIOR_WEEK} teams:",
    len(prior_week)
)

print(
    "Unique teams:",
    prior_week["team"].nunique()
)

display(
    prior_week.sort_values(
        "prior_week_strength_rank"
    )
)

Week 3 teams: 32
Unique teams: 32

,team,prior_week_strength_rank,prior_week_team_strength,prior_cumulative_offense_adjustment,prior_cumulative_defense_adjustment
0,BUF,1,5.941307,5.041594,-2.327156
1,SEA,2,5.532084,-0.158291,4.172959
2,SF,3,4.807611,2.601193,3.782443
3,LA,4,4.510074,-1.498756,1.782494
4,BAL,5,3.194678,1.944839,-0.323911
5,NE,6,3.153263,-2.043349,4.537901
6,DEN,7,2.823203,-2.081192,0.300058
7,DET,8,2.748511,2.700053,-3.768697
8,MIN,9,2.458757,0.602059,3.133309
9,KC,10,2.458286,2.965793,0.847043
10,JAX,11,2.328442,0.236323,2.167573
11,PHI,12,1.582449,0.088525,0.069775
12,GB,13,1.131145,-0.602571,-1.821321
13,CIN,14,1.122452,1.318883,1.900133
14,HOU,15,1.025111,-1.016442,-1.485192
15,CHI,16,0.551141,2.454678,-0.264072
16,NO,17,0.223504,1.672747,-0.146003
17,DAL,18,-0.076385,1.621160,-0.647590
18,PIT,19,-0.215758,-3.264039,1.817211
19,IND,20,-0.520573,1.424757,-4.143993
20,TB,21,-0.961835,-0.070350,-1.889100
21,LAC,22,-1.669265,-2.846899,-1.365649
22,WAS,23,-2.745448,-0.395877,-2.364627
23,ATL,24,-3.169388,-4.539745,-1.558495
24,LV,25,-3.206077,1.103276,2.584526
25,ARI,26,-3.679974,-1.597723,0.183527
26,NYG,27,-3.713683,-1.528364,-0.347114
27,CAR,28,-4.369019,3.844253,-2.624497
28,CLE,29,-4.391506,-1.725137,-1.143887
29,NYJ,30,-4.654697,-0.946024,2.035226
30,MIA,31,-4.705708,-2.913530,-2.632280
31,TEN,32,-7.456672,-2.387643,-0.456393

# Load New Weekly In-Season Features

These features contain the new evidence generated in notebook `03`.

For Week 3, they describe each team's Week 2 performance relative to its entering Week 2 expectation.

The primary values used here are:

- `weekly_strength_update`
- `weekly_offense_adjustment`
- `weekly_defense_adjustment`

The overall strength update is opponent adjusted and uses diminishing returns for extreme single game results.

In [5]:
inseason = pd.read_parquet(
    INSEASON_FEATURES_PATH
).copy()

required_inseason_columns = [
    "team",
    "games_in_update",
    "entering_team_strength",
    "entering_strength_rank",
    "average_opponent_strength",
    "average_opponent_rank",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

missing_inseason = [
    column
    for column in required_inseason_columns
    if column not in inseason.columns
]

if missing_inseason:
    raise KeyError(
        "Missing required in-season columns: "
        + ", ".join(missing_inseason)
    )

print("In-season teams:", len(inseason))
print(
    "Unique teams:",
    inseason["team"].nunique()
)

display(
    inseason[
        required_inseason_columns
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

In-season teams: 32
Unique teams: 32

,team,games_in_update,entering_team_strength,entering_strength_rank,average_opponent_strength,average_opponent_rank,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
14,JAX,1,2.328442,11,3.153263,6.0,29.0,0.675179,28.324821,1.448446,1.824497,2.761997
1,ATL,1,-3.169388,24,1.131145,13.0,21.0,-5.800533,26.800533,1.436171,1.748668,1.486168
5,CHI,1,0.551141,16,1.582449,12.0,20.0,0.468692,19.531308,1.326430,0.565592,2.553092
18,LV,1,-3.206077,25,0.223504,17.0,8.0,-4.929581,12.929581,1.091353,1.714631,-0.497869
31,WAS,1,-2.745448,23,5.532084,2.0,2.0,-6.777532,8.777532,0.833940,1.613703,-0.898797
15,KC,1,2.458286,10,-4.705708,31.0,14.0,5.663995,8.336005,0.800683,-0.120214,1.867286
20,MIN,1,2.458757,9,-0.961835,21.0,7.0,1.920592,5.079408,0.521537,-0.129819,1.107681
9,DEN,1,2.823203,7,4.510074,4.0,4.0,-0.186871,4.186871,0.435681,1.125378,-0.187122
0,ARI,1,-3.679974,26,4.807611,3.0,-6.0,-9.987585,3.987585,0.416051,1.136535,-1.675965
26,PIT,1,-0.215758,19,1.122452,14.0,3.0,0.161790,2.838210,0.299995,0.998342,-0.464158
13,IND,1,-0.520573,20,1.025111,15.0,2.0,-0.045684,2.045684,0.217634,-0.655308,1.032192
24,NYJ,1,-4.654697,30,2.748511,8.0,-7.0,-8.903207,1.903207,0.202668,0.159319,-1.003181
7,CLE,1,-4.391506,29,-4.369019,28.0,3.0,1.477513,1.522487,0.162484,-0.557588,0.679912
2,BAL,1,3.194678,5,-0.076385,18.0,3.0,1.771063,1.228937,0.131335,1.553386,-1.109114
17,LAC,1,-1.669265,22,5.941307,1.0,-8.0,-9.110572,1.110572,0.118741,-0.920951,0.166549
30,TEN,1,-7.456672,32,-3.713683,27.0,-5.0,-5.242989,0.242989,0.026032,-2.633013,1.604487
23,NYG,1,-3.713683,27,-7.456672,32.0,5.0,5.242989,-0.242989,-0.026032,-2.023375,2.214125
3,BUF,1,5.941307,1,-1.669265,22.0,8.0,9.110572,-1.110572,-0.118741,-0.006347,1.081153
8,DAL,1,-0.076385,18,3.194678,5.0,-3.0,-1.771063,-1.228937,-0.131335,1.226050,-1.436450
4,CAR,1,-4.369019,28,-4.391506,29.0,-3.0,-1.477513,-1.522487,-0.162484,-1.008431,0.229069
10,DET,1,2.748511,8,-4.654697,30.0,7.0,8.903207,-1.903207,-0.202668,0.931699,-0.230801
12,HOU,1,1.025111,15,-0.520573,20.0,-2.0,0.045684,-2.045684,-0.217634,-1.013271,0.674229
6,CIN,1,1.122452,14,-0.215758,19.0,-3.0,-0.161790,-2.838210,-0.299995,0.498159,-0.964341
28,SF,1,4.807611,3,-3.679974,26.0,6.0,9.987585,-3.987585,-0.416051,1.718251,-1.094249
16,LA,1,4.510074,4,2.823203,7.0,-4.0,0.186871,-4.186871,-0.435681,0.462120,-0.850380
29,TB,1,-0.961835,21,2.458757,9.0,-7.0,-1.920592,-5.079408,-0.521537,-1.051547,0.185953
19,MIA,1,-4.705708,31,2.458286,10.0,-14.0,-5.663995,-8.336005,-0.800683,-1.951564,0.035936
27,SEA,1,5.532084,2,-2.745448,23.0,-2.0,6.777532,-8.777532,-0.833940,1.003296,-1.509204
22,NO,1,0.223504,17,-3.206077,25.0,-8.0,4.929581,-12.929581,-1.091353,0.386022,-1.826478
25,PHI,1,1.582449,12,0.551141,16.0,-20.0,-0.468692,-19.531308,-1.326430,-2.473082,-0.485582
11,GB,1,1.131145,13,-3.169388,24.0,-21.0,5.800533,-26.800533,-1.436171,-1.562602,-1.825102
21,NE,1,3.153263,6,2.328442,11.0,-29.0,-0.675179,-28.324821,-1.448446,-2.556433,-1.618933

# Merge Prior Week State with New Evidence

The weekly model now combines three pieces of information:

1. Frozen preseason information for long term reference
2. Previous week's team strength as the current prior
3. Most recent week's opponent adjusted performance as new evidence

All 32 teams must remain in the table.

In [6]:
weekly_strength = (
    preseason
    .merge(
        prior_week,
        on="team",
        how="left",
        validate="one_to_one"
    )
    .merge(
        inseason,
        on="team",
        how="left",
        validate="one_to_one"
    )
)

weekly_fill_columns = [
    "games_in_update",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

weekly_strength[
    weekly_fill_columns
] = (
    weekly_strength[
        weekly_fill_columns
    ]
    .fillna(0.0)
)

print("Merged teams:", len(weekly_strength))
print(
    "Unique teams:",
    weekly_strength["team"].nunique()
)

print(
    "Missing prior-week strengths:",
    weekly_strength[
        "prior_week_team_strength"
    ].isna().sum()
)

Merged teams: 32
Unique teams: 32
Missing prior-week strengths: 0

# Sequential Weekly Rating Update

The previous week's team strength is the starting point.

The current week's opponent adjusted performance update is then applied:

`weekly_team_strength = prior_week_team_strength + weekly_strength_update`

Therefore, for Week 3:

`Week 3 Strength = Week 2 Strength + Week 2 Performance Update`

Older results remain embedded in the prior week rating and are not counted again.

The offensive and defensive weekly adjustments remain available separately for the weekly scoring model.

In [7]:
weekly_strength["team_strength_change"] = (
    weekly_strength["weekly_strength_update"]
)

weekly_strength["weekly_team_strength"] = (
    weekly_strength["prior_week_team_strength"]
    + weekly_strength["team_strength_change"]
)

display(
    weekly_strength[
        [
            "team",
            "prior_week_team_strength",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment",
            "team_strength_change",
            "weekly_team_strength"
        ]
    ].sort_values(
        "weekly_team_strength",
        ascending=False
    )
)

,team,prior_week_team_strength,weekly_offense_adjustment,weekly_defense_adjustment,team_strength_change,weekly_team_strength
0,BUF,5.941307,-0.006347,1.081153,-0.118741,5.822566
2,SEA,5.532084,1.003296,-1.509204,-0.833940,4.698144
9,SF,4.807611,1.718251,-1.094249,-0.416051,4.391561
1,LA,4.510074,0.462120,-0.850380,-0.435681,4.074393
11,JAX,2.328442,1.824497,2.761997,1.448446,3.776888
5,BAL,3.194678,1.553386,-1.109114,0.131335,3.326012
12,KC,2.458286,-0.120214,1.867286,0.800683,3.258970
4,DEN,2.823203,1.125378,-0.187122,0.435681,3.258884
17,MIN,2.458757,-0.129819,1.107681,0.521537,2.980293
3,DET,2.748511,0.931699,-0.230801,-0.202668,2.545843
18,CHI,0.551141,0.565592,2.553092,1.326430,1.877571
10,NE,3.153263,-2.556433,-1.618933,-1.448446,1.704818
20,CIN,1.122452,0.498159,-0.964341,-0.299995,0.822457
6,HOU,1.025111,-1.013271,0.674229,-0.217634,0.807477
8,PHI,1.582449,-2.473082,-0.485582,-1.326430,0.256019
15,PIT,-0.215758,0.998342,-0.464158,0.299995,0.084237
19,DAL,-0.076385,1.226050,-1.436450,-0.131335,-0.207720
16,IND,-0.520573,-0.655308,1.032192,0.217634,-0.302939
7,GB,1.131145,-1.562602,-1.825102,-1.436171,-0.305026
22,NO,0.223504,0.386022,-1.826478,-1.091353,-0.867849
14,TB,-0.961835,-1.051547,0.185953,-0.521537,-1.483372
13,LAC,-1.669265,-0.920951,0.166549,0.118741,-1.550525
21,ATL,-3.169388,1.748668,1.486168,1.436171,-1.733218
23,WAS,-2.745448,1.613703,-0.898797,0.833940,-1.911508
29,LV,-3.206077,1.714631,-0.497869,1.091353,-2.114724
26,ARI,-3.679974,1.136535,-1.675965,0.416051,-3.263923
25,NYG,-3.713683,-2.023375,2.214125,-0.026032,-3.739715
27,CLE,-4.391506,-0.557588,0.679912,0.162484,-4.229023
30,NYJ,-4.654697,0.159319,-1.003181,0.202668,-4.452029
28,CAR,-4.369019,-1.008431,0.229069,-0.162484,-4.531503
24,MIA,-4.705708,-1.951564,0.035936,-0.800683,-5.506392
31,TEN,-7.456672,-2.633013,1.604487,0.026032,-7.430640

In [8]:
weekly_strength["cumulative_offense_adjustment"] = (
    weekly_strength["prior_cumulative_offense_adjustment"]
    + weekly_strength["weekly_offense_adjustment"]
)

weekly_strength["cumulative_defense_adjustment"] = (
    weekly_strength["prior_cumulative_defense_adjustment"]
    + weekly_strength["weekly_defense_adjustment"]
)

assert weekly_strength[
    "cumulative_offense_adjustment"
].notna().all()

assert weekly_strength[
    "cumulative_defense_adjustment"
].notna().all()

# Updated Weekly Rankings

The current weekly rank is based on `weekly_team_strength`.

Ranking movement is now measured relative to the immediately previous week rather than the preseason ranking.

A positive `rank_change` means the team moved up.

For example:

- Week 2 rank = 8
- Week 3 rank = 5
- Rank change = +3

In [9]:
weekly_strength = weekly_strength.sort_values(
    [
        "weekly_team_strength",
        "prior_week_team_strength"
    ],
    ascending=[False, False]
).reset_index(drop=True)

weekly_strength["weekly_strength_rank"] = (
    np.arange(
        1,
        len(weekly_strength) + 1
    )
)

weekly_strength["rank_change"] = (
    weekly_strength["prior_week_strength_rank"]
    - weekly_strength["weekly_strength_rank"]
)

weekly_comparison_table = (
    weekly_strength[
        [
            "weekly_strength_rank",
            "team",
            "weekly_team_strength",
            "prior_week_strength_rank",
            "prior_week_team_strength",
            "team_strength_change",
            "rank_change"
        ]
    ]
    .copy()
)

display(weekly_comparison_table)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change
0,1,BUF,5.822566,1,5.941307,-0.118741,0
1,2,SEA,4.698144,2,5.532084,-0.833940,0
2,3,SF,4.391561,3,4.807611,-0.416051,0
3,4,LA,4.074393,4,4.510074,-0.435681,0
4,5,JAX,3.776888,11,2.328442,1.448446,6
5,6,BAL,3.326012,5,3.194678,0.131335,-1
6,7,KC,3.258970,10,2.458286,0.800683,3
7,8,DEN,3.258884,7,2.823203,0.435681,-1
8,9,MIN,2.980293,9,2.458757,0.521537,0
9,10,DET,2.545843,8,2.748511,-0.202668,-2
10,11,CHI,1.877571,16,0.551141,1.326430,5
11,12,NE,1.704818,6,3.153263,-1.448446,-6
12,13,CIN,0.822457,14,1.122452,-0.299995,1
13,14,HOU,0.807477,15,1.025111,-0.217634,1
14,15,PHI,0.256019,12,1.582449,-1.326430,-3
15,16,PIT,0.084237,19,-0.215758,0.299995,3
16,17,DAL,-0.207720,18,-0.076385,-0.131335,1
17,18,IND,-0.302939,20,-0.520573,0.217634,2
18,19,GB,-0.305026,13,1.131145,-1.436171,-6
19,20,NO,-0.867849,17,0.223504,-1.091353,-3
20,21,TB,-1.483372,21,-0.961835,-0.521537,0
21,22,LAC,-1.550525,22,-1.669265,0.118741,0
22,23,ATL,-1.733218,24,-3.169388,1.436171,1
23,24,WAS,-1.911508,23,-2.745448,0.833940,-1
24,25,LV,-2.114724,25,-3.206077,1.091353,0
25,26,ARI,-3.263923,26,-3.679974,0.416051,0
26,27,NYG,-3.739715,27,-3.713683,-0.026032,0
27,28,CLE,-4.229023,29,-4.391506,0.162484,1
28,29,NYJ,-4.452029,30,-4.654697,0.202668,1
29,30,CAR,-4.531503,28,-4.369019,-0.162484,-2
30,31,MIA,-5.506392,31,-4.705708,-0.800683,0
31,32,TEN,-7.430640,32,-7.456672,0.026032,0

# Biggest Weekly Movers

This table is diagnostic only.

It shows which teams experienced the largest overall rating changes from the previous week to the current week.

The underlying projection model still retains the full preseason, offense, defense, opponent and weekly information.

In [10]:
mover_columns = [
    "team",
    "prior_week_team_strength",
    "team_strength_change",
    "weekly_team_strength",
    "prior_week_strength_rank",
    "weekly_strength_rank",
    "rank_change"
]

biggest_risers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=False
    )
    .head(10)
)

biggest_fallers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=True
    )
    .head(10)
)

print("BIGGEST RISERS")
display(biggest_risers)

print()
print("BIGGEST FALLERS")
display(biggest_fallers)

BIGGEST RISERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
4,JAX,2.328442,1.448446,3.776888,11,5,6
22,ATL,-3.169388,1.436171,-1.733218,24,23,1
10,CHI,0.551141,1.326430,1.877571,16,11,5
24,LV,-3.206077,1.091353,-2.114724,25,25,0
23,WAS,-2.745448,0.833940,-1.911508,23,24,-1
6,KC,2.458286,0.800683,3.258970,10,7,3
8,MIN,2.458757,0.521537,2.980293,9,9,0
7,DEN,2.823203,0.435681,3.258884,7,8,-1
25,ARI,-3.679974,0.416051,-3.263923,26,26,0
15,PIT,-0.215758,0.299995,0.084237,19,16,3

BIGGEST FALLERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
11,NE,3.153263,-1.448446,1.704818,6,12,-6
18,GB,1.131145,-1.436171,-0.305026,13,19,-6
14,PHI,1.582449,-1.326430,0.256019,12,15,-3
19,NO,0.223504,-1.091353,-0.867849,17,20,-3
1,SEA,5.532084,-0.833940,4.698144,2,2,0
30,MIA,-4.705708,-0.800683,-5.506392,31,31,0
20,TB,-0.961835,-0.521537,-1.483372,21,21,0
3,LA,4.510074,-0.435681,4.074393,4,4,0
2,SF,4.807611,-0.416051,4.391561,3,3,0
12,CIN,1.122452,-0.299995,0.822457,14,13,1

# Update Diagnostics

These diagnostics check the size and distribution of the sequential weekly update.

The comparison is now:

`Prior Week Strength → Current Week Strength`

rather than:

`Preseason Strength → Current Week Strength`

In [11]:
movement = (
    weekly_strength[
        "team_strength_change"
    ].abs()
)

print(
    f"WEEK {PRIOR_WEEK} → "
    f"WEEK {TARGET_WEEK} TEAM-STRENGTH MOVEMENT"
)

print(
    weekly_strength[
        "team_strength_change"
    ]
    .describe()
    .round(3)
)

print()

print(
    "Mean absolute movement:",
    round(
        movement.mean(),
        3
    )
)

print(
    "Maximum absolute movement:",
    round(
        movement.max(),
        3
    )
)

print(
    "Team with largest movement:",
    weekly_strength.loc[
        movement.idxmax(),
        "team"
    ]
)

print()
print("RATING DISTRIBUTIONS")

distribution_check = pd.DataFrame(
    {
        "metric": [
            f"Week {PRIOR_WEEK} Team Strength",
            f"Week {TARGET_WEEK} Team Strength"
        ],
        "mean": [
            weekly_strength[
                "prior_week_team_strength"
            ].mean(),
            weekly_strength[
                "weekly_team_strength"
            ].mean()
        ],
        "std": [
            weekly_strength[
                "prior_week_team_strength"
            ].std(),
            weekly_strength[
                "weekly_team_strength"
            ].std()
        ],
        "min": [
            weekly_strength[
                "prior_week_team_strength"
            ].min(),
            weekly_strength[
                "weekly_team_strength"
            ].min()
        ],
        "max": [
            weekly_strength[
                "prior_week_team_strength"
            ].max(),
            weekly_strength[
                "weekly_team_strength"
            ].max()
        ]
    }
)

display(
    distribution_check.round(3)
)

WEEK 3 → WEEK 4 TEAM-STRENGTH MOVEMENT
count    32.000
mean      0.000
std       0.775
min      -1.448
25%      -0.421
50%       0.000
75%       0.421
max       1.448
Name: team_strength_change, dtype: float64

Mean absolute movement: 0.592
Maximum absolute movement: 1.448
Team with largest movement: JAX

RATING DISTRIBUTIONS

                 metric   mean    std    min    max
0  Week 3 Team Strength  0.002  3.436 -7.457  5.941
1  Week 4 Team Strength  0.002  3.344 -7.431  5.823

# Sanity Checks

These checks verify the sequential weekly update.

The weekly file should:

- contain exactly 32 unique teams
- preserve the frozen preseason information
- contain a valid prior week rating for every team
- contain no missing current weekly strength values
- have `team_strength_change` equal to the new opponent adjusted weekly update
- calculate current strength as prior week strength plus the weekly update
- never overwrite the preseason or prior week files

In [12]:
assert len(weekly_strength) == 32, (
    "Expected 32 teams in weekly strength table."
)

assert (
    weekly_strength["team"].nunique()
    == 32
), (
    "Expected 32 unique teams."
)

assert weekly_strength[
    "preseason_team_strength"
].notna().all(), (
    "Missing frozen preseason ratings."
)

assert weekly_strength[
    "prior_week_team_strength"
].notna().all(), (
    "Missing prior-week ratings."
)

assert weekly_strength[
    "weekly_team_strength"
].notna().all(), (
    "Missing current weekly ratings."
)

assert np.allclose(
    weekly_strength[
        "team_strength_change"
    ],
    weekly_strength[
        "weekly_strength_update"
    ]
), (
    "Team-strength change does not match "
    "the opponent-adjusted weekly update."
)

assert np.allclose(
    weekly_strength[
        "weekly_team_strength"
    ],
    (
        weekly_strength[
            "prior_week_team_strength"
        ]
        + weekly_strength[
            "team_strength_change"
        ]
    )
), (
    "Sequential weekly strength formula "
    "is inconsistent."
)

assert np.allclose(
    weekly_strength[
        "entering_team_strength"
    ],
    weekly_strength[
        "prior_week_team_strength"
    ]
), (
    "Notebook 03 entering strength does not "
    "match the prior-week team strength."
)

print(
    "All sequential weekly team-strength "
    "sanity checks passed."
)

All sequential weekly team-strength sanity checks passed.

# Final Weekly Team Strength Table

The saved file contains the full state needed by the weekly projection pipeline.

This includes:

- current weekly strength and rank
- previous week's strength and rank
- week to week movement
- frozen preseason information
- opponent adjusted performance information
- separate offensive and defensive weekly signals

The compact ranking table shown earlier is only for interpretation. The saved dataset retains the additional model information.

In [13]:
final_columns = [
    "weekly_strength_rank",
    "team",
    "weekly_team_strength",

    "prior_week_strength_rank",
    "prior_week_team_strength",
    "team_strength_change",
    "rank_change",

    "games_in_update",
    "average_opponent_rank",
    "average_opponent_strength",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",

    "weekly_offense_adjustment",
    "weekly_defense_adjustment",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment",

    "preseason_strength_rank",
    "preseason_team_strength",
    "preseason_baseline_team_strength",
    "preseason_personnel_adjustment",
    "preseason_personnel_strength",
    "preseason_roster_continuity",
    "preseason_roster_continuity_adjustment"
]

weekly_team_strength = (
    weekly_strength[
        final_columns
    ]
    .copy()
)

display(
    weekly_team_strength
)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change,games_in_update,average_opponent_rank,average_opponent_strength,...,weekly_defense_adjustment,cumulative_offense_adjustment,cumulative_defense_adjustment,preseason_strength_rank,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_personnel_strength,preseason_roster_continuity,preseason_roster_continuity_adjustment
0,1,BUF,5.822566,1,5.941307,-0.118741,0,1,22.0,-1.669265,...,1.081153,5.035246,-1.246004,1,4.816514,4.125764,0.934506,0.623004,0.573034,0.260091
1,2,SEA,4.698144,2,5.532084,-0.833940,0,1,23.0,-2.745448,...,-1.509204,0.845005,2.663755,3,4.363421,3.515976,0.635683,0.423788,0.677419,0.932073
2,3,SF,4.391561,3,4.807611,-0.416051,0,1,26.0,-3.679974,...,-1.094249,4.319443,2.688193,10,2.366788,1.805709,0.692939,0.461959,0.577778,0.290631
3,4,LA,4.074393,4,4.510074,-0.435681,0,1,7.0,2.823203,...,-0.850380,-1.036636,0.932114,2,4.762452,3.257133,2.100811,1.400540,0.608696,0.489665
4,5,JAX,3.776888,11,2.328442,1.448446,6,1,6.0,3.153263,...,2.761997,2.060820,4.929570,12,1.713136,1.746953,-0.223729,-0.149153,0.563830,0.200841
5,6,BAL,3.326012,5,3.194678,0.131335,-1,1,18.0,-0.076385,...,-1.109114,3.498225,-1.433025,6,3.074111,2.710864,0.636254,0.424170,0.526882,-0.037012
6,7,KC,3.258970,10,2.458286,0.800683,3,1,31.0,-4.705708,...,1.867286,2.845579,2.714329,13,1.302244,1.484935,-0.187743,-0.125162,0.510870,-0.140090
7,8,DEN,3.258884,7,2.823203,0.435681,-1,1,4.0,4.510074,...,-0.187122,-0.955814,0.112936,5,3.569507,2.355154,0.979753,0.653169,0.727273,1.253003
8,9,MIN,2.980293,9,2.458757,0.521537,0,1,21.0,-0.961835,...,1.107681,0.472240,4.240990,18,0.475040,0.919610,-0.620638,-0.413759,0.510204,-0.144374
9,10,DET,2.545843,8,2.748511,-0.202668,-2,1,30.0,-4.654697,...,-0.230801,3.631752,-3.999498,4,4.018565,3.374644,1.041923,0.694616,0.538462,0.037533
10,11,CHI,1.877571,16,0.551141,1.326430,5,1,12.0,1.582449,...,2.553092,3.020270,2.289020,19,-0.051934,-0.069709,0.002783,0.001856,0.537634,0.032209
11,12,NE,1.704818,6,3.153263,-1.448446,-6,1,11.0,2.328442,...,-1.618933,-4.599782,2.918968,11,1.910188,1.605622,0.906186,0.604124,0.458333,-0.478291
12,13,CIN,0.822457,14,1.122452,-0.299995,1,1,19.0,-0.215758,...,-0.964341,1.817042,0.935792,21,-0.739434,-1.268642,0.286293,0.190862,0.643678,0.714864
13,14,HOU,0.807477,15,1.025111,-0.217634,1,1,20.0,-0.520573,...,0.674229,-2.029713,-0.810963,7,2.810133,2.193179,1.173833,0.782555,0.505495,-0.174691
14,15,PHI,0.256019,12,1.582449,-1.326430,-3,1,16.0,0.551141,...,-0.485582,-2.384558,-0.415808,9,2.451919,2.324982,0.264690,0.176460,0.522727,-0.063756
15,16,PIT,0.084237,19,-0.215758,0.299995,3,1,14.0,1.122452,...,-0.464158,-2.265697,1.353053,16,0.543902,0.359049,0.304322,0.202881,0.533333,0.004521
16,17,DAL,-0.207720,18,-0.076385,-0.131335,1,1,5.0,3.194678,...,-1.436450,2.847210,-2.084040,20,-0.386396,-0.773189,0.640887,0.427258,0.533333,0.004521
17,18,IND,-0.302939,20,-0.520573,0.217634,2,1,15.0,1.025111,...,1.032192,0.769449,-3.111801,17,0.532226,0.543256,-0.167564,-0.111709,0.560440,0.179017
18,19,GB,-0.305026,13,1.131145,-1.436171,-6,1,24.0,-3.169388,...,-1.825102,-2.165173,-3.646423,8,2.536317,1.718369,0.882628,0.588419,0.622222,0.576742
19,20,NO,-0.867849,17,0.223504,-1.091353,-3,1,25.0,-3.206077,...,-1.826478,2.058769,-1.972481,23,-1.556053,-1.584652,-0.112569,-0.075046,0.562500,0.192281
20,21,TB,-1.483372,21,-0.961835,-0.521537,0,1,9.0,2.458757,...,0.185953,-1.121896,-1.703146,15,0.601026,0.449564,0.167912,0.111942,0.548387,0.101429
21,22,LAC,-1.550525,22,-1.669265,0.118741,0,1,1.0,5.941307,...,0.166549,-3.767850,-1.199100,14,0.910681,1.089525,-0.382598,-0.255065,0.548387,0.101429
22,23,ATL,-1.733218,24,-3.169388,1.436171,1,1,13.0,1.131145,...,1.486168,-2.791077,-0.072327,22,-1.331272,-1.430617,0.664859,0.443239,0.439560,-0.599141
23,24,WAS,-1.911508,23,-2.745448,0.833940,-1,1,2.0,5.532084,...,-0.898797,1.217826,-3.263424,24,-2.001869,-1.962594,0.021167,0.014111,0.516484,-0.103950
24,25,LV,-2.114724,25,-3.206077,1.091353,0,1,17.0,0.223504,...,-0.497869,2.817907,2.086657,30,-5.693342,-4.625655,-1.325021,-0.883347,0.447917,-0.545348
25,26,ARI,-3.263923,26,-3.679974,0.416051,0,1,3.0,4.807611,...,-1.675965,-0.461187,-1.492437,27,-3.678016,-2.961441,-1.166618,-0.777745,0.527473,-0.033208
26,27,NYG,-3.739715,27,-3.713683,-0.026032,0,1,32.0,-7.456672,...,2.214125,-3.551739,1.867011,26,-3.455862,-2.902685,-0.687303,-0.458202,0.488889,-0.281590
27,28,CLE,-4.229023,29,-4.391506,0.162484,1,1,28.0,-4.369019,...,0.679912,-2.282725,-0.463975,28,-4.150395,-3.147236,-1.385118,-0.923412,0.479167,-0.344177
28,29,NYJ,-4.452029,30,-4.654697,0.202668,1,1,8.0,2.748511,...,-1.003181,-0.786705,1.032045,31,-5.933726,-4.805098,-1.734836,-1.156558,0.505376,-0.175452
29,30,CAR,-4.531503,28,-4.369019,-0.162484,-2,1,29.0,-4.391506,...,0.229069,2.835822,-2.395428,29,-4.533242,-3.703033,-1.322770,-0.881847,0.521277,-0.073094
30,31,MIA,-5.506392,31,-4.705708,-0.800683,0,1,10.0,2.458286,...,0.035936,-4.865094,-2.596344,25,-2.443254,-1.116195,-0.947865,-0.631910,0.297030,-1.516681
31,32,TEN,-7.430640,32,-7.456672,0.026032,0,1,27.0,-3.713683,...,1.604487,-5.020656,1.148094,32,-6.747344,-5.173512,-2.073057,-1.382038,0.430108,-0.659994

# Save Weekly Team Strength

This writes only to:

`data/processed/weekly/`

The original:

`data/processed/2026_team_strength.parquet`

remains untouched.

In [14]:
OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

weekly_team_strength.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("Saved:", OUTPUT_PATH)
print()
print(
    "Original preseason file remains:",
    PRESEASON_STRENGTH_PATH
)

Saved: ..\..\data\processed\weekly\week_04_sequential_team_strength.parquet

Original preseason file remains: ..\..\data\processed\2026_team_strength.parquet

# What This Means for Week 3

At the end of this notebook, every team has:

- its frozen preseason rating
- its Week 2 entering rating and rank
- its opponent adjusted Week 2 performance
- its Week 2 offensive and defensive signals
- its Week 2 → Week 3 rating movement
- its updated Week 3 team strength rating
- its updated Week 3 rank

The next stage will apply the Week 3 injury update and then use the resulting team state to generate Week 3 game projections.

The weekly ranking table is diagnostic only.

The saved weekly team strength file retains the additional information required by the projection pipeline.