# 04 — Weekly Team Strength

This notebook updates team strength sequentially using the new in season evidence created in `03_Inseason_Feature_Engineering.ipynb`.

The original preseason model remains unchanged.

The weekly model follows a sequential principle:

> The previous week's team strength is the prior. The most recently completed week provides new evidence.

For each target week, this notebook:

- Loads the frozen preseason ratings for reference
- Loads the previous week's team strength state
- Loads the target week's new in season feature table
- Applies the opponent adjusted weekly strength update
- Preserves separate offensive and defensive weekly signals
- Calculates current weekly rankings
- Compares rank and strength movement to the previous week
- Saves a separate weekly team strength file

No original preseason file or prior weekly file is overwritten.

In [29]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the output from:

`03_Inseason_Feature_Engineering.ipynb`

For Week 3:

- `TARGET_WEEK = 3`
- `PRIOR_WEEK = 2`

The Week 2 team strength file becomes the entering prior for Week 3.

In [30]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 7
PRIOR_WEEK = TARGET_WEEK - 1

PRESEASON_STRENGTH_PATH = (
    PROCESSED_DIR
    / "2026_team_strength.parquet"
)

PRIOR_WEEK_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

INSEASON_FEATURES_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

OUTPUT_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_sequential_team_strength.parquet"
)

print("Preseason ratings:", PRESEASON_STRENGTH_PATH)
print("Prior-week ratings:", PRIOR_WEEK_STRENGTH_PATH)
print("New in-season features:", INSEASON_FEATURES_PATH)
print("Weekly output:", OUTPUT_PATH)

Preseason ratings: ..\..\data\processed\2026_team_strength.parquet
Prior-week ratings: ..\..\data\processed\weekly\week_06_sequential_team_strength.parquet
New in-season features: ..\..\data\processed\weekly\week_07_inseason_features.parquet
Weekly output: ..\..\data\processed\weekly\week_07_sequential_team_strength.parquet

# Load Frozen Preseason Team Strength

The preseason team strength file is the final output of the original `05_Team_Strength_Model.ipynb`.

Its `team_strength` value is already expressed in point differential terms, so it can serve directly as the prior for weekly updates.

We immediately rename the important preseason columns so it is impossible to confuse the original ratings with the new weekly ratings.

In [31]:
preseason = pd.read_parquet(
    PRESEASON_STRENGTH_PATH
).copy()

required_preseason_columns = [
    "team",
    "team_strength",
    "baseline_team_strength",
    "personnel_adjustment",
    "personnel_strength",
    "roster_continuity",
    "roster_continuity_adjustment"
]

missing_preseason = [
    column
    for column in required_preseason_columns
    if column not in preseason.columns
]

if missing_preseason:
    raise KeyError(
        "Missing required preseason columns: "
        + ", ".join(missing_preseason)
    )

preseason = preseason.rename(
    columns={
        "strength_rank": "preseason_strength_rank",
        "team_strength": "preseason_team_strength",
        "baseline_team_strength": "preseason_baseline_team_strength",
        "personnel_adjustment": "preseason_personnel_adjustment",
        "personnel_strength": "preseason_personnel_strength",
        "roster_continuity": "preseason_roster_continuity",
        "roster_continuity_adjustment": "preseason_roster_continuity_adjustment"
    }
)

print("Preseason teams:", len(preseason))
print("Unique teams:", preseason["team"].nunique())

display(
    preseason[
        [
            "preseason_strength_rank",
            "team",
            "preseason_team_strength",
            "preseason_baseline_team_strength",
            "preseason_personnel_adjustment",
            "preseason_roster_continuity_adjustment"
        ]
    ].sort_values(
        "preseason_strength_rank"
    )
)

Preseason teams: 32
Unique teams: 32

,preseason_strength_rank,team,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_roster_continuity_adjustment
0,1,BUF,4.816514,4.125764,0.934506,0.260091
1,2,LA,4.762452,3.257133,2.100811,0.489665
2,3,SEA,4.363421,3.515976,0.635683,0.932073
3,4,DET,4.018565,3.374644,1.041923,0.037533
4,5,DEN,3.569507,2.355154,0.979753,1.253003
5,6,BAL,3.074111,2.710864,0.636254,-0.037012
6,7,HOU,2.810133,2.193179,1.173833,-0.174691
7,8,GB,2.536317,1.718369,0.882628,0.576742
8,9,PHI,2.451919,2.324982,0.264690,-0.063756
9,10,SF,2.366788,1.805709,0.692939,0.290631
10,11,NE,1.910188,1.605622,0.906186,-0.478291
11,12,JAX,1.713136,1.746953,-0.223729,0.200841
12,13,KC,1.302244,1.484935,-0.187743,-0.140090
13,14,LAC,0.910681,1.089525,-0.382598,0.101429
14,15,TB,0.601026,0.449564,0.167912,0.101429
15,16,PIT,0.543902,0.359049,0.304322,0.004521
16,17,IND,0.532226,0.543256,-0.167564,0.179017
17,18,MIN,0.475040,0.919610,-0.620638,-0.144374
18,19,CHI,-0.051934,-0.069709,0.002783,0.032209
19,20,DAL,-0.386396,-0.773189,0.640887,0.004521
20,21,CIN,-0.739434,-1.268642,0.286293,0.714864
21,22,ATL,-1.331272,-1.430617,0.664859,-0.599141
22,23,NO,-1.556053,-1.584652,-0.112569,0.192281
23,24,WAS,-2.001869,-1.962594,0.021167,-0.103950
24,25,MIA,-2.443254,-1.116195,-0.947865,-1.516681
25,26,NYG,-3.455862,-2.902685,-0.687303,-0.281590
26,27,ARI,-3.678016,-2.961441,-1.166618,-0.033208
27,28,CLE,-4.150395,-3.147236,-1.385118,-0.344177
28,29,CAR,-4.533242,-3.703033,-1.322770,-0.073094
29,30,LV,-5.693342,-4.625655,-1.325021,-0.545348
30,31,NYJ,-5.933726,-4.805098,-1.734836,-0.175452
31,32,TEN,-6.747344,-5.173512,-2.073057,-0.659994

# Load Prior-Week Team Strength

The previous week's team strength file is the starting point for the new weekly update.

For Week 3, the model begins with the Week 2 ratings.

This prevents older games from being counted repeatedly and creates a true sequential rating system.

In [32]:
prior_week = pd.read_parquet(
    PRIOR_WEEK_STRENGTH_PATH
).copy()

required_prior_columns = [
    "team",
    "weekly_strength_rank",
    "weekly_team_strength",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment"
]

missing_prior = [
    column
    for column in required_prior_columns
    if column not in prior_week.columns
]

if missing_prior:
    raise KeyError(
        "Missing required prior-week columns: "
        + ", ".join(missing_prior)
    )

prior_week = prior_week[
    required_prior_columns
].rename(
    columns={
        "weekly_strength_rank":
            "prior_week_strength_rank",
        "weekly_team_strength":
            "prior_week_team_strength",
        "cumulative_offense_adjustment":
            "prior_cumulative_offense_adjustment",
        "cumulative_defense_adjustment":
            "prior_cumulative_defense_adjustment"
    }
)

print(
    f"Week {PRIOR_WEEK} teams:",
    len(prior_week)
)

print(
    "Unique teams:",
    prior_week["team"].nunique()
)

display(
    prior_week.sort_values(
        "prior_week_strength_rank"
    )
)

Week 6 teams: 32
Unique teams: 32

,team,prior_week_strength_rank,prior_week_team_strength,prior_cumulative_offense_adjustment,prior_cumulative_defense_adjustment
0,SF,1,5.532855,5.803577,3.744827
1,BUF,2,5.393291,7.497441,-3.261309
2,SEA,3,4.200461,2.617435,1.758685
3,NE,4,3.901913,-0.568482,3.822768
4,LA,5,3.860944,0.649234,-0.209516
5,JAX,6,3.774217,1.033289,7.074539
6,BAL,7,3.254665,4.095722,-0.663028
7,KC,8,3.165481,3.685027,2.166277
8,MIN,9,3.140947,-1.330436,7.710814
9,DEN,10,2.901957,-2.507520,1.283730
10,DET,11,2.858510,6.741330,-5.067420
11,GB,12,1.458414,-2.149116,0.442134
12,HOU,13,1.429501,-1.103813,0.587437
13,CHI,14,0.797487,0.143731,2.884981
14,CIN,15,0.772808,1.760165,1.201415
15,PIT,16,0.534587,-0.899891,1.091359
16,PHI,17,0.451342,-3.737436,0.653814
17,IND,18,-0.089195,1.267575,-3.041175
18,DAL,19,-0.585702,3.097513,-3.011237
19,TB,20,-0.803072,-2.627936,0.563314
20,ATL,21,-0.893777,0.266266,-0.892484
21,LAC,22,-1.837208,-4.707852,-1.666602
22,NYG,23,-2.640440,-1.554073,1.187177
23,NO,24,-2.938405,0.425055,-4.933695
24,WAS,25,-3.281754,-0.108180,-4.716930
25,LV,26,-3.396294,2.423625,-1.735125
26,CAR,27,-3.513248,4.150041,-2.618709
27,CLE,28,-4.119980,-3.820292,0.420958
28,NYJ,29,-4.305707,-3.714033,2.927217
29,MIA,30,-5.315924,-6.847689,-2.156439
30,ARI,31,-5.577328,-1.005392,-6.514142
31,TEN,32,-8.075316,-8.951338,0.989912

# Load New Weekly In-Season Features

These features contain the new evidence generated in notebook `03`.

For Week 3, they describe each team's Week 2 performance relative to its entering Week 2 expectation.

The primary values used here are:

- `weekly_strength_update`
- `weekly_offense_adjustment`
- `weekly_defense_adjustment`

The overall strength update is opponent adjusted and uses diminishing returns for extreme single game results.

In [33]:
inseason = pd.read_parquet(
    INSEASON_FEATURES_PATH
).copy()

required_inseason_columns = [
    "team",
    "games_in_update",
    "entering_team_strength",
    "entering_strength_rank",
    "average_opponent_strength",
    "average_opponent_rank",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

missing_inseason = [
    column
    for column in required_inseason_columns
    if column not in inseason.columns
]

if missing_inseason:
    raise KeyError(
        "Missing required in-season columns: "
        + ", ".join(missing_inseason)
    )

print("In-season teams:", len(inseason))
print(
    "Unique teams:",
    inseason["team"].nunique()
)

display(
    inseason[
        required_inseason_columns
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

In-season teams: 28
Unique teams: 28

,team,games_in_update,entering_team_strength,entering_strength_rank,average_opponent_strength,average_opponent_rank,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
4,CAR,1,-3.513248,27,0.451342,17.0,11.0,-5.464590,16.464590,1.239299,0.499068,1.184782
26,TEN,1,-8.075316,32,-0.089195,18.0,6.0,-9.486120,15.486120,1.204047,0.628798,0.264512
0,ARI,1,-5.577328,31,3.860944,5.0,2.0,-10.938272,12.938272,1.091791,-0.423072,1.012643
13,KC,1,3.165481,8,-1.837208,22.0,16.0,6.502689,9.497311,0.885697,-0.036752,2.298962
6,CLE,1,-4.119980,28,3.254665,7.0,3.0,-5.874645,8.874645,0.841101,-1.195807,1.889907
18,NO,1,-2.938405,24,-2.640440,23.0,7.0,-1.797965,8.797965,0.835451,1.733126,-0.881159
5,CHI,1,0.797487,14,-0.893777,21.0,8.0,0.191264,7.808736,0.759478,1.348626,-0.215659
22,PIT,1,0.534587,16,-0.803072,20.0,7.0,-0.162341,7.162341,0.706781,0.602028,0.387742
10,HOU,1,1.429501,13,3.774217,6.0,3.0,-3.844716,6.844716,0.680024,1.973676,-1.240610
9,GB,1,1.458414,12,-0.585702,19.0,10.0,3.544117,6.455883,0.646513,0.160179,1.295893
27,WAS,1,-3.281754,25,5.532855,1.0,-6.0,-10.314609,4.314609,0.448179,-0.510375,0.025339
16,LV,1,-3.396294,26,5.393291,2.0,-3.0,-7.289585,4.289585,0.445736,1.434391,-1.479894
8,DEN,1,2.901957,10,4.200461,3.0,3.0,0.201495,2.798505,0.295909,-0.560340,1.325374
20,NYJ,1,-4.305707,29,3.901913,4.0,-7.0,-9.707620,2.707620,0.286538,-0.271535,-0.485821
17,NE,1,3.901913,4,-4.305707,29.0,7.0,9.707620,-2.707620,-0.286538,0.470679,0.256393
23,SEA,1,4.200461,3,2.901957,10.0,-3.0,-0.201495,-2.798505,-0.295909,-1.059034,0.826681
3,BUF,1,5.393291,2,-3.396294,26.0,3.0,7.289585,-4.289585,-0.445736,1.554782,-1.359504
24,SF,1,5.532855,1,-3.281754,25.0,6.0,10.314609,-4.314609,-0.448179,0.059077,0.594791
7,DAL,1,-0.585702,19,1.458414,12.0,-10.0,-3.544117,-6.455883,-0.646513,-1.263167,-0.127452
12,JAX,1,3.774217,6,1.429501,13.0,-3.0,3.844716,-6.844716,-0.680024,1.435749,-1.778537
25,TB,1,-0.803072,20,0.534587,16.0,-7.0,0.162341,-7.162341,-0.706781,-0.397810,-0.612096
1,ATL,1,-0.893777,21,0.797487,14.0,-8.0,-0.191264,-7.808736,-0.759478,0.212049,-1.352237
19,NYG,1,-2.640440,23,-2.938405,24.0,-7.0,1.797965,-8.797965,-0.835451,0.671953,-1.942333
2,BAL,1,3.254665,7,-4.119980,28.0,-3.0,5.874645,-8.874645,-0.841101,-1.922356,1.163358
15,LAC,1,-1.837208,22,3.165481,8.0,-16.0,-6.502689,-9.497311,-0.885697,-2.249152,0.086563
14,LA,1,3.860944,5,-5.577328,31.0,-2.0,10.938272,-12.938272,-1.091791,-1.077007,0.358707
11,IND,1,-0.089195,18,-8.075316,32.0,-6.0,9.486120,-15.486120,-1.204047,-0.570681,-0.934967
21,PHI,1,0.451342,17,-3.513248,27.0,-11.0,5.464590,-16.464590,-1.239299,-1.299604,-0.613890

# Merge Prior Week State with New Evidence

The weekly model now combines three pieces of information:

1. Frozen preseason information for long term reference
2. Previous week's team strength as the current prior
3. Most recent week's opponent adjusted performance as new evidence

All 32 teams must remain in the table.

In [34]:
weekly_strength = (
    preseason
    .merge(
        prior_week,
        on="team",
        how="left",
        validate="one_to_one"
    )
    .merge(
        inseason,
        on="team",
        how="left",
        validate="one_to_one"
    )
)

weekly_fill_columns = [
    "games_in_update",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

weekly_strength[
    weekly_fill_columns
] = (
    weekly_strength[
        weekly_fill_columns
    ]
    .fillna(0.0)
)

print("Merged teams:", len(weekly_strength))
print(
    "Unique teams:",
    weekly_strength["team"].nunique()
)

print(
    "Missing prior-week strengths:",
    weekly_strength[
        "prior_week_team_strength"
    ].isna().sum()
)

Merged teams: 32
Unique teams: 32
Missing prior-week strengths: 0

# Sequential Weekly Rating Update

The previous week's team strength is the starting point.

The current week's opponent adjusted performance update is then applied:

`weekly_team_strength = prior_week_team_strength + weekly_strength_update`

Therefore, for Week 3:

`Week 3 Strength = Week 2 Strength + Week 2 Performance Update`

Older results remain embedded in the prior week rating and are not counted again.

The offensive and defensive weekly adjustments remain available separately for the weekly scoring model.

In [35]:
weekly_strength["team_strength_change"] = (
    weekly_strength["weekly_strength_update"]
)

weekly_strength["weekly_team_strength"] = (
    weekly_strength["prior_week_team_strength"]
    + weekly_strength["team_strength_change"]
)

display(
    weekly_strength[
        [
            "team",
            "prior_week_team_strength",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment",
            "team_strength_change",
            "weekly_team_strength"
        ]
    ].sort_values(
        "weekly_team_strength",
        ascending=False
    )
)

,team,prior_week_team_strength,weekly_offense_adjustment,weekly_defense_adjustment,team_strength_change,weekly_team_strength
9,SF,5.532855,0.059077,0.594791,-0.448179,5.084675
0,BUF,5.393291,1.554782,-1.359504,-0.445736,4.947555
12,KC,3.165481,-0.036752,2.298962,0.885697,4.051178
2,SEA,4.200461,-1.059034,0.826681,-0.295909,3.904552
10,NE,3.901913,0.470679,0.256393,-0.286538,3.615375
4,DEN,2.901957,-0.560340,1.325374,0.295909,3.197866
17,MIN,3.140947,0.000000,0.000000,0.000000,3.140947
11,JAX,3.774217,1.435749,-1.778537,-0.680024,3.094193
3,DET,2.858510,0.000000,0.000000,0.000000,2.858510
1,LA,3.860944,-1.077007,0.358707,-1.091791,2.769153
5,BAL,3.254665,-1.922356,1.163358,-0.841101,2.413564
6,HOU,1.429501,1.973676,-1.240610,0.680024,2.109526
7,GB,1.458414,0.160179,1.295893,0.646513,2.104927
18,CHI,0.797487,1.348626,-0.215659,0.759478,1.556965
15,PIT,0.534587,0.602028,0.387742,0.706781,1.241368
20,CIN,0.772808,0.000000,0.000000,0.000000,0.772808
8,PHI,0.451342,-1.299604,-0.613890,-1.239299,-0.787958
19,DAL,-0.585702,-1.263167,-0.127452,-0.646513,-1.232215
16,IND,-0.089195,-0.570681,-0.934967,-1.204047,-1.293242
14,TB,-0.803072,-0.397810,-0.612096,-0.706781,-1.509854
21,ATL,-0.893777,0.212049,-1.352237,-0.759478,-1.653255
22,NO,-2.938405,1.733126,-0.881159,0.835451,-2.102954
28,CAR,-3.513248,0.499068,1.184782,1.239299,-2.273949
13,LAC,-1.837208,-2.249152,0.086563,-0.885697,-2.722905
23,WAS,-3.281754,-0.510375,0.025339,0.448179,-2.833574
29,LV,-3.396294,1.434391,-1.479894,0.445736,-2.950558
27,CLE,-4.119980,-1.195807,1.889907,0.841101,-3.278879
25,NYG,-2.640440,0.671953,-1.942333,-0.835451,-3.475892
30,NYJ,-4.305707,-0.271535,-0.485821,0.286538,-4.019168
26,ARI,-5.577328,-0.423072,1.012643,1.091791,-4.485537
24,MIA,-5.315924,0.000000,0.000000,0.000000,-5.315924
31,TEN,-8.075316,0.628798,0.264512,1.204047,-6.871269

In [36]:
weekly_strength["cumulative_offense_adjustment"] = (
    weekly_strength["prior_cumulative_offense_adjustment"]
    + weekly_strength["weekly_offense_adjustment"]
)

weekly_strength["cumulative_defense_adjustment"] = (
    weekly_strength["prior_cumulative_defense_adjustment"]
    + weekly_strength["weekly_defense_adjustment"]
)

assert weekly_strength[
    "cumulative_offense_adjustment"
].notna().all()

assert weekly_strength[
    "cumulative_defense_adjustment"
].notna().all()

# Updated Weekly Rankings

The current weekly rank is based on `weekly_team_strength`.

Ranking movement is now measured relative to the immediately previous week rather than the preseason ranking.

A positive `rank_change` means the team moved up.

For example:

- Week 2 rank = 8
- Week 3 rank = 5
- Rank change = +3

In [37]:
weekly_strength = weekly_strength.sort_values(
    [
        "weekly_team_strength",
        "prior_week_team_strength"
    ],
    ascending=[False, False]
).reset_index(drop=True)

weekly_strength["weekly_strength_rank"] = (
    np.arange(
        1,
        len(weekly_strength) + 1
    )
)

weekly_strength["rank_change"] = (
    weekly_strength["prior_week_strength_rank"]
    - weekly_strength["weekly_strength_rank"]
)

weekly_comparison_table = (
    weekly_strength[
        [
            "weekly_strength_rank",
            "team",
            "weekly_team_strength",
            "prior_week_strength_rank",
            "prior_week_team_strength",
            "team_strength_change",
            "rank_change"
        ]
    ]
    .copy()
)

display(weekly_comparison_table)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change
0,1,SF,5.084675,1,5.532855,-0.448179,0
1,2,BUF,4.947555,2,5.393291,-0.445736,0
2,3,KC,4.051178,8,3.165481,0.885697,5
3,4,SEA,3.904552,3,4.200461,-0.295909,-1
4,5,NE,3.615375,4,3.901913,-0.286538,-1
5,6,DEN,3.197866,10,2.901957,0.295909,4
6,7,MIN,3.140947,9,3.140947,0.000000,2
7,8,JAX,3.094193,6,3.774217,-0.680024,-2
8,9,DET,2.858510,11,2.858510,0.000000,2
9,10,LA,2.769153,5,3.860944,-1.091791,-5
10,11,BAL,2.413564,7,3.254665,-0.841101,-4
11,12,HOU,2.109526,13,1.429501,0.680024,1
12,13,GB,2.104927,12,1.458414,0.646513,-1
13,14,CHI,1.556965,14,0.797487,0.759478,0
14,15,PIT,1.241368,16,0.534587,0.706781,1
15,16,CIN,0.772808,15,0.772808,0.000000,-1
16,17,PHI,-0.787958,17,0.451342,-1.239299,0
17,18,DAL,-1.232215,19,-0.585702,-0.646513,1
18,19,IND,-1.293242,18,-0.089195,-1.204047,-1
19,20,TB,-1.509854,20,-0.803072,-0.706781,0
20,21,ATL,-1.653255,21,-0.893777,-0.759478,0
21,22,NO,-2.102954,24,-2.938405,0.835451,2
22,23,CAR,-2.273949,27,-3.513248,1.239299,4
23,24,LAC,-2.722905,22,-1.837208,-0.885697,-2
24,25,WAS,-2.833574,25,-3.281754,0.448179,0
25,26,LV,-2.950558,26,-3.396294,0.445736,0
26,27,CLE,-3.278879,28,-4.119980,0.841101,1
27,28,NYG,-3.475892,23,-2.640440,-0.835451,-5
28,29,NYJ,-4.019168,29,-4.305707,0.286538,0
29,30,ARI,-4.485537,31,-5.577328,1.091791,1
30,31,MIA,-5.315924,30,-5.315924,0.000000,-1
31,32,TEN,-6.871269,32,-8.075316,1.204047,0

# Biggest Weekly Movers

This table is diagnostic only.

It shows which teams experienced the largest overall rating changes from the previous week to the current week.

The underlying projection model still retains the full preseason, offense, defense, opponent and weekly information.

In [38]:
mover_columns = [
    "team",
    "prior_week_team_strength",
    "team_strength_change",
    "weekly_team_strength",
    "prior_week_strength_rank",
    "weekly_strength_rank",
    "rank_change"
]

biggest_risers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=False
    )
    .head(10)
)

biggest_fallers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=True
    )
    .head(10)
)

print("BIGGEST RISERS")
display(biggest_risers)

print()
print("BIGGEST FALLERS")
display(biggest_fallers)

BIGGEST RISERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
22,CAR,-3.513248,1.239299,-2.273949,27,23,4
31,TEN,-8.075316,1.204047,-6.871269,32,32,0
29,ARI,-5.577328,1.091791,-4.485537,31,30,1
2,KC,3.165481,0.885697,4.051178,8,3,5
26,CLE,-4.119980,0.841101,-3.278879,28,27,1
21,NO,-2.938405,0.835451,-2.102954,24,22,2
13,CHI,0.797487,0.759478,1.556965,14,14,0
14,PIT,0.534587,0.706781,1.241368,16,15,1
11,HOU,1.429501,0.680024,2.109526,13,12,1
12,GB,1.458414,0.646513,2.104927,12,13,-1

BIGGEST FALLERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
16,PHI,0.451342,-1.239299,-0.787958,17,17,0
18,IND,-0.089195,-1.204047,-1.293242,18,19,-1
9,LA,3.860944,-1.091791,2.769153,5,10,-5
23,LAC,-1.837208,-0.885697,-2.722905,22,24,-2
10,BAL,3.254665,-0.841101,2.413564,7,11,-4
27,NYG,-2.640440,-0.835451,-3.475892,23,28,-5
20,ATL,-0.893777,-0.759478,-1.653255,21,21,0
19,TB,-0.803072,-0.706781,-1.509854,20,20,0
7,JAX,3.774217,-0.680024,3.094193,6,8,-2
17,DAL,-0.585702,-0.646513,-1.232215,19,18,1

# Update Diagnostics

These diagnostics check the size and distribution of the sequential weekly update.

The comparison is now:

`Prior Week Strength → Current Week Strength`

rather than:

`Preseason Strength → Current Week Strength`

In [39]:
movement = (
    weekly_strength[
        "team_strength_change"
    ].abs()
)

print(
    f"WEEK {PRIOR_WEEK} → "
    f"WEEK {TARGET_WEEK} TEAM-STRENGTH MOVEMENT"
)

print(
    weekly_strength[
        "team_strength_change"
    ]
    .describe()
    .round(3)
)

print()

print(
    "Mean absolute movement:",
    round(
        movement.mean(),
        3
    )
)

print(
    "Maximum absolute movement:",
    round(
        movement.max(),
        3
    )
)

print(
    "Team with largest movement:",
    weekly_strength.loc[
        movement.idxmax(),
        "team"
    ]
)

print()
print("RATING DISTRIBUTIONS")

distribution_check = pd.DataFrame(
    {
        "metric": [
            f"Week {PRIOR_WEEK} Team Strength",
            f"Week {TARGET_WEEK} Team Strength"
        ],
        "mean": [
            weekly_strength[
                "prior_week_team_strength"
            ].mean(),
            weekly_strength[
                "weekly_team_strength"
            ].mean()
        ],
        "std": [
            weekly_strength[
                "prior_week_team_strength"
            ].std(),
            weekly_strength[
                "weekly_team_strength"
            ].std()
        ],
        "min": [
            weekly_strength[
                "prior_week_team_strength"
            ].min(),
            weekly_strength[
                "weekly_team_strength"
            ].min()
        ],
        "max": [
            weekly_strength[
                "prior_week_team_strength"
            ].max(),
            weekly_strength[
                "weekly_team_strength"
            ].max()
        ]
    }
)

display(
    distribution_check.round(3)
)

WEEK 6 → WEEK 7 TEAM-STRENGTH MOVEMENT
count    32.000
mean      0.000
std       0.757
min      -1.239
25%      -0.687
50%       0.000
75%       0.687
max       1.239
Name: team_strength_change, dtype: float64

Mean absolute movement: 0.648
Maximum absolute movement: 1.239
Team with largest movement: PHI

RATING DISTRIBUTIONS

                 metric   mean    std    min    max
0  Week 6 Team Strength  0.002  3.548 -8.075  5.533
1  Week 7 Team Strength  0.002  3.297 -6.871  5.085

# Sanity Checks

These checks verify the sequential weekly update.

The weekly file should:

- contain exactly 32 unique teams
- preserve the frozen preseason information
- contain a valid prior week rating for every team
- contain no missing current weekly strength values
- have `team_strength_change` equal to the new opponent adjusted weekly update
- calculate current strength as prior week strength plus the weekly update
- never overwrite the preseason or prior week files

In [40]:
assert len(weekly_strength) == 32, (
    "Expected 32 teams in weekly strength table."
)

assert (
    weekly_strength["team"].nunique()
    == 32
), (
    "Expected 32 unique teams."
)

assert weekly_strength[
    "preseason_team_strength"
].notna().all(), (
    "Missing frozen preseason ratings."
)

assert weekly_strength[
    "prior_week_team_strength"
].notna().all(), (
    "Missing prior-week ratings."
)

assert weekly_strength[
    "weekly_team_strength"
].notna().all(), (
    "Missing current weekly ratings."
)

assert np.allclose(
    weekly_strength[
        "team_strength_change"
    ],
    weekly_strength[
        "weekly_strength_update"
    ]
), (
    "Team-strength change does not match "
    "the opponent-adjusted weekly update."
)

assert np.allclose(
    weekly_strength[
        "weekly_team_strength"
    ],
    (
        weekly_strength[
            "prior_week_team_strength"
        ]
        + weekly_strength[
            "team_strength_change"
        ]
    )
), (
    "Sequential weekly strength formula "
    "is inconsistent."
)

played_mask = weekly_strength["games_in_update"] > 0

assert np.allclose(
    weekly_strength.loc[
        played_mask, "entering_team_strength"
    ],
    weekly_strength.loc[
        played_mask, "prior_week_team_strength"
    ]
), (
    "Notebook 03 entering strength does not match "
    "the prior-week team strength."
)

bye_mask = ~played_mask

assert np.allclose(
    weekly_strength.loc[
        bye_mask, "weekly_team_strength"
    ],
    weekly_strength.loc[
        bye_mask, "prior_week_team_strength"
    ]
), "Bye-week teams did not retain their previous strength."

print(
    "All sequential weekly team-strength "
    "sanity checks passed."
)

All sequential weekly team-strength sanity checks passed.

# Final Weekly Team Strength Table

The saved file contains the full state needed by the weekly projection pipeline.

This includes:

- current weekly strength and rank
- previous week's strength and rank
- week to week movement
- frozen preseason information
- opponent adjusted performance information
- separate offensive and defensive weekly signals

The compact ranking table shown earlier is only for interpretation. The saved dataset retains the additional model information.

In [41]:
final_columns = [
    "weekly_strength_rank",
    "team",
    "weekly_team_strength",

    "prior_week_strength_rank",
    "prior_week_team_strength",
    "team_strength_change",
    "rank_change",

    "games_in_update",
    "average_opponent_rank",
    "average_opponent_strength",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",

    "weekly_offense_adjustment",
    "weekly_defense_adjustment",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment",

    "preseason_strength_rank",
    "preseason_team_strength",
    "preseason_baseline_team_strength",
    "preseason_personnel_adjustment",
    "preseason_personnel_strength",
    "preseason_roster_continuity",
    "preseason_roster_continuity_adjustment"
]

weekly_team_strength = (
    weekly_strength[
        final_columns
    ]
    .copy()
)

display(
    weekly_team_strength
)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change,games_in_update,average_opponent_rank,average_opponent_strength,...,weekly_defense_adjustment,cumulative_offense_adjustment,cumulative_defense_adjustment,preseason_strength_rank,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_personnel_strength,preseason_roster_continuity,preseason_roster_continuity_adjustment
0,1,SF,5.084675,1,5.532855,-0.448179,0,1.0,25.0,-3.281754,...,0.594791,5.862654,4.339618,10,2.366788,1.805709,0.692939,0.461959,0.577778,0.290631
1,2,BUF,4.947555,2,5.393291,-0.445736,0,1.0,26.0,-3.396294,...,-1.359504,9.052222,-4.620813,1,4.816514,4.125764,0.934506,0.623004,0.573034,0.260091
2,3,KC,4.051178,8,3.165481,0.885697,5,1.0,22.0,-1.837208,...,2.298962,3.648274,4.465239,13,1.302244,1.484935,-0.187743,-0.125162,0.510870,-0.140090
3,4,SEA,3.904552,3,4.200461,-0.295909,-1,1.0,10.0,2.901957,...,0.826681,1.558401,2.585365,3,4.363421,3.515976,0.635683,0.423788,0.677419,0.932073
4,5,NE,3.615375,4,3.901913,-0.286538,-1,1.0,29.0,-4.305707,...,0.256393,-0.097803,4.079161,11,1.910188,1.605622,0.906186,0.604124,0.458333,-0.478291
5,6,DEN,3.197866,10,2.901957,0.295909,4,1.0,3.0,4.200461,...,1.325374,-3.067860,2.609104,5,3.569507,2.355154,0.979753,0.653169,0.727273,1.253003
6,7,MIN,3.140947,9,3.140947,0.000000,2,0.0,NaN,NaN,...,0.000000,-1.330436,7.710814,18,0.475040,0.919610,-0.620638,-0.413759,0.510204,-0.144374
7,8,JAX,3.094193,6,3.774217,-0.680024,-2,1.0,13.0,1.429501,...,-1.778537,2.469038,5.296003,12,1.713136,1.746953,-0.223729,-0.149153,0.563830,0.200841
8,9,DET,2.858510,11,2.858510,0.000000,2,0.0,NaN,NaN,...,0.000000,6.741330,-5.067420,4,4.018565,3.374644,1.041923,0.694616,0.538462,0.037533
9,10,LA,2.769153,5,3.860944,-1.091791,-5,1.0,31.0,-5.577328,...,0.358707,-0.427773,0.149192,2,4.762452,3.257133,2.100811,1.400540,0.608696,0.489665
10,11,BAL,2.413564,7,3.254665,-0.841101,-4,1.0,28.0,-4.119980,...,1.163358,2.173366,0.500330,6,3.074111,2.710864,0.636254,0.424170,0.526882,-0.037012
11,12,HOU,2.109526,13,1.429501,0.680024,1,1.0,6.0,3.774217,...,-1.240610,0.869863,-0.653173,7,2.810133,2.193179,1.173833,0.782555,0.505495,-0.174691
12,13,GB,2.104927,12,1.458414,0.646513,-1,1.0,19.0,-0.585702,...,1.295893,-1.988937,1.738028,8,2.536317,1.718369,0.882628,0.588419,0.622222,0.576742
13,14,CHI,1.556965,14,0.797487,0.759478,0,1.0,21.0,-0.893777,...,-0.215659,1.492357,2.669322,19,-0.051934,-0.069709,0.002783,0.001856,0.537634,0.032209
14,15,PIT,1.241368,16,0.534587,0.706781,1,1.0,20.0,-0.803072,...,0.387742,-0.297864,1.479101,16,0.543902,0.359049,0.304322,0.202881,0.533333,0.004521
15,16,CIN,0.772808,15,0.772808,0.000000,-1,0.0,NaN,NaN,...,0.000000,1.760165,1.201415,21,-0.739434,-1.268642,0.286293,0.190862,0.643678,0.714864
16,17,PHI,-0.787958,17,0.451342,-1.239299,0,1.0,27.0,-3.513248,...,-0.613890,-5.037040,0.039924,9,2.451919,2.324982,0.264690,0.176460,0.522727,-0.063756
17,18,DAL,-1.232215,19,-0.585702,-0.646513,1,1.0,12.0,1.458414,...,-0.127452,1.834347,-3.138689,20,-0.386396,-0.773189,0.640887,0.427258,0.533333,0.004521
18,19,IND,-1.293242,18,-0.089195,-1.204047,-1,1.0,32.0,-8.075316,...,-0.934967,0.696893,-3.976142,17,0.532226,0.543256,-0.167564,-0.111709,0.560440,0.179017
19,20,TB,-1.509854,20,-0.803072,-0.706781,0,1.0,16.0,0.534587,...,-0.612096,-3.025747,-0.048782,15,0.601026,0.449564,0.167912,0.111942,0.548387,0.101429
20,21,ATL,-1.653255,21,-0.893777,-0.759478,0,1.0,14.0,0.797487,...,-1.352237,0.478315,-2.244721,22,-1.331272,-1.430617,0.664859,0.443239,0.439560,-0.599141
21,22,NO,-2.102954,24,-2.938405,0.835451,2,1.0,23.0,-2.640440,...,-0.881159,2.158182,-5.814854,23,-1.556053,-1.584652,-0.112569,-0.075046,0.562500,0.192281
22,23,CAR,-2.273949,27,-3.513248,1.239299,4,1.0,17.0,0.451342,...,1.184782,4.649109,-1.433927,29,-4.533242,-3.703033,-1.322770,-0.881847,0.521277,-0.073094
23,24,LAC,-2.722905,22,-1.837208,-0.885697,-2,1.0,8.0,3.165481,...,0.086563,-6.957003,-1.580039,14,0.910681,1.089525,-0.382598,-0.255065,0.548387,0.101429
24,25,WAS,-2.833574,25,-3.281754,0.448179,0,1.0,1.0,5.532855,...,0.025339,-0.618555,-4.691591,24,-2.001869,-1.962594,0.021167,0.014111,0.516484,-0.103950
25,26,LV,-2.950558,26,-3.396294,0.445736,0,1.0,2.0,5.393291,...,-1.479894,3.858017,-3.215019,30,-5.693342,-4.625655,-1.325021,-0.883347,0.447917,-0.545348
26,27,CLE,-3.278879,28,-4.119980,0.841101,1,1.0,7.0,3.254665,...,1.889907,-5.016099,2.310865,28,-4.150395,-3.147236,-1.385118,-0.923412,0.479167,-0.344177
27,28,NYG,-3.475892,23,-2.640440,-0.835451,-5,1.0,24.0,-2.938405,...,-1.942333,-0.882120,-0.755156,26,-3.455862,-2.902685,-0.687303,-0.458202,0.488889,-0.281590
28,29,NYJ,-4.019168,29,-4.305707,0.286538,0,1.0,4.0,3.901913,...,-0.485821,-3.985568,2.441396,31,-5.933726,-4.805098,-1.734836,-1.156558,0.505376,-0.175452
29,30,ARI,-4.485537,31,-5.577328,1.091791,1,1.0,5.0,3.860944,...,1.012643,-1.428464,-5.501499,27,-3.678016,-2.961441,-1.166618,-0.777745,0.527473,-0.033208
30,31,MIA,-5.315924,30,-5.315924,0.000000,-1,0.0,NaN,NaN,...,0.000000,-6.847689,-2.156439,25,-2.443254,-1.116195,-0.947865,-0.631910,0.297030,-1.516681
31,32,TEN,-6.871269,32,-8.075316,1.204047,0,1.0,18.0,-0.089195,...,0.264512,-8.322540,1.254424,32,-6.747344,-5.173512,-2.073057,-1.382038,0.430108,-0.659994

# Save Weekly Team Strength

This writes only to:

`data/processed/weekly/`

The original:

`data/processed/2026_team_strength.parquet`

remains untouched.

In [42]:
OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

weekly_team_strength.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("Saved:", OUTPUT_PATH)
print()
print(
    "Original preseason file remains:",
    PRESEASON_STRENGTH_PATH
)

Saved: ..\..\data\processed\weekly\week_07_sequential_team_strength.parquet

Original preseason file remains: ..\..\data\processed\2026_team_strength.parquet

# What This Means for Week 3

At the end of this notebook, every team has:

- its frozen preseason rating
- its Week 2 entering rating and rank
- its opponent adjusted Week 2 performance
- its Week 2 offensive and defensive signals
- its Week 2 → Week 3 rating movement
- its updated Week 3 team strength rating
- its updated Week 3 rank

The next stage will apply the Week 3 injury update and then use the resulting team state to generate Week 3 game projections.

The weekly ranking table is diagnostic only.

The saved weekly team strength file retains the additional information required by the projection pipeline.