# 04 — Weekly Team Strength

This notebook updates team strength sequentially using the new in season evidence created in `03_Inseason_Feature_Engineering.ipynb`.

The original preseason model remains unchanged.

The weekly model follows a sequential principle:

> The previous week's team strength is the prior. The most recently completed week provides new evidence.

For each target week, this notebook:

- Loads the frozen preseason ratings for reference
- Loads the previous week's team strength state
- Loads the target week's new in season feature table
- Applies the opponent adjusted weekly strength update
- Preserves separate offensive and defensive weekly signals
- Calculates current weekly rankings
- Compares rank and strength movement to the previous week
- Saves a separate weekly team strength file

No original preseason file or prior weekly file is overwritten.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

## Paths and Weekly Settings

This notebook expects the output from:

`03_Inseason_Feature_Engineering.ipynb`

For Week 3:

- `TARGET_WEEK = 3`
- `PRIOR_WEEK = 2`

The Week 2 team strength file becomes the entering prior for Week 3.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"

SEASON = 2026
TARGET_WEEK = 8
PRIOR_WEEK = TARGET_WEEK - 1

PRESEASON_STRENGTH_PATH = (
    PROCESSED_DIR
    / "2026_team_strength.parquet"
)

PRIOR_WEEK_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{PRIOR_WEEK:02d}_sequential_team_strength.parquet"
)

INSEASON_FEATURES_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_inseason_features.parquet"
)

OUTPUT_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_sequential_team_strength.parquet"
)

print("Preseason ratings:", PRESEASON_STRENGTH_PATH)
print("Prior-week ratings:", PRIOR_WEEK_STRENGTH_PATH)
print("New in-season features:", INSEASON_FEATURES_PATH)
print("Weekly output:", OUTPUT_PATH)

Preseason ratings: ..\..\data\processed\2026_team_strength.parquet
Prior-week ratings: ..\..\data\processed\weekly\week_07_sequential_team_strength.parquet
New in-season features: ..\..\data\processed\weekly\week_08_inseason_features.parquet
Weekly output: ..\..\data\processed\weekly\week_08_sequential_team_strength.parquet

# Load Frozen Preseason Team Strength

The preseason team strength file is the final output of the original `05_Team_Strength_Model.ipynb`.

Its `team_strength` value is already expressed in point differential terms, so it can serve directly as the prior for weekly updates.

We immediately rename the important preseason columns so it is impossible to confuse the original ratings with the new weekly ratings.

In [3]:
preseason = pd.read_parquet(
    PRESEASON_STRENGTH_PATH
).copy()

required_preseason_columns = [
    "team",
    "team_strength",
    "baseline_team_strength",
    "personnel_adjustment",
    "personnel_strength",
    "roster_continuity",
    "roster_continuity_adjustment"
]

missing_preseason = [
    column
    for column in required_preseason_columns
    if column not in preseason.columns
]

if missing_preseason:
    raise KeyError(
        "Missing required preseason columns: "
        + ", ".join(missing_preseason)
    )

preseason = preseason.rename(
    columns={
        "strength_rank": "preseason_strength_rank",
        "team_strength": "preseason_team_strength",
        "baseline_team_strength": "preseason_baseline_team_strength",
        "personnel_adjustment": "preseason_personnel_adjustment",
        "personnel_strength": "preseason_personnel_strength",
        "roster_continuity": "preseason_roster_continuity",
        "roster_continuity_adjustment": "preseason_roster_continuity_adjustment"
    }
)

print("Preseason teams:", len(preseason))
print("Unique teams:", preseason["team"].nunique())

display(
    preseason[
        [
            "preseason_strength_rank",
            "team",
            "preseason_team_strength",
            "preseason_baseline_team_strength",
            "preseason_personnel_adjustment",
            "preseason_roster_continuity_adjustment"
        ]
    ].sort_values(
        "preseason_strength_rank"
    )
)

Preseason teams: 32
Unique teams: 32

,preseason_strength_rank,team,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_roster_continuity_adjustment
0,1,BUF,4.816514,4.125764,0.934506,0.260091
1,2,LA,4.762452,3.257133,2.100811,0.489665
2,3,SEA,4.363421,3.515976,0.635683,0.932073
3,4,DET,4.018565,3.374644,1.041923,0.037533
4,5,DEN,3.569507,2.355154,0.979753,1.253003
5,6,BAL,3.074111,2.710864,0.636254,-0.037012
6,7,HOU,2.810133,2.193179,1.173833,-0.174691
7,8,GB,2.536317,1.718369,0.882628,0.576742
8,9,PHI,2.451919,2.324982,0.264690,-0.063756
9,10,SF,2.366788,1.805709,0.692939,0.290631
10,11,NE,1.910188,1.605622,0.906186,-0.478291
11,12,JAX,1.713136,1.746953,-0.223729,0.200841
12,13,KC,1.302244,1.484935,-0.187743,-0.140090
13,14,LAC,0.910681,1.089525,-0.382598,0.101429
14,15,TB,0.601026,0.449564,0.167912,0.101429
15,16,PIT,0.543902,0.359049,0.304322,0.004521
16,17,IND,0.532226,0.543256,-0.167564,0.179017
17,18,MIN,0.475040,0.919610,-0.620638,-0.144374
18,19,CHI,-0.051934,-0.069709,0.002783,0.032209
19,20,DAL,-0.386396,-0.773189,0.640887,0.004521
20,21,CIN,-0.739434,-1.268642,0.286293,0.714864
21,22,ATL,-1.331272,-1.430617,0.664859,-0.599141
22,23,NO,-1.556053,-1.584652,-0.112569,0.192281
23,24,WAS,-2.001869,-1.962594,0.021167,-0.103950
24,25,MIA,-2.443254,-1.116195,-0.947865,-1.516681
25,26,NYG,-3.455862,-2.902685,-0.687303,-0.281590
26,27,ARI,-3.678016,-2.961441,-1.166618,-0.033208
27,28,CLE,-4.150395,-3.147236,-1.385118,-0.344177
28,29,CAR,-4.533242,-3.703033,-1.322770,-0.073094
29,30,LV,-5.693342,-4.625655,-1.325021,-0.545348
30,31,NYJ,-5.933726,-4.805098,-1.734836,-0.175452
31,32,TEN,-6.747344,-5.173512,-2.073057,-0.659994

# Load Prior-Week Team Strength

The previous week's team strength file is the starting point for the new weekly update.

For Week 3, the model begins with the Week 2 ratings.

This prevents older games from being counted repeatedly and creates a true sequential rating system.

In [4]:
prior_week = pd.read_parquet(
    PRIOR_WEEK_STRENGTH_PATH
).copy()

required_prior_columns = [
    "team",
    "weekly_strength_rank",
    "weekly_team_strength",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment"
]

missing_prior = [
    column
    for column in required_prior_columns
    if column not in prior_week.columns
]

if missing_prior:
    raise KeyError(
        "Missing required prior-week columns: "
        + ", ".join(missing_prior)
    )

prior_week = prior_week[
    required_prior_columns
].rename(
    columns={
        "weekly_strength_rank":
            "prior_week_strength_rank",
        "weekly_team_strength":
            "prior_week_team_strength",
        "cumulative_offense_adjustment":
            "prior_cumulative_offense_adjustment",
        "cumulative_defense_adjustment":
            "prior_cumulative_defense_adjustment"
    }
)

print(
    f"Week {PRIOR_WEEK} teams:",
    len(prior_week)
)

print(
    "Unique teams:",
    prior_week["team"].nunique()
)

display(
    prior_week.sort_values(
        "prior_week_strength_rank"
    )
)

Week 7 teams: 32
Unique teams: 32

,team,prior_week_strength_rank,prior_week_team_strength,prior_cumulative_offense_adjustment,prior_cumulative_defense_adjustment
0,SF,1,5.084675,5.862654,4.339618
1,BUF,2,4.947555,9.052222,-4.620813
2,KC,3,4.051178,3.648274,4.465239
3,SEA,4,3.904552,1.558401,2.585365
4,NE,5,3.615375,-0.097803,4.079161
5,DEN,6,3.197866,-3.067860,2.609104
6,MIN,7,3.140947,-1.330436,7.710814
7,JAX,8,3.094193,2.469038,5.296003
8,DET,9,2.858510,6.741330,-5.067420
9,LA,10,2.769153,-0.427773,0.149192
10,BAL,11,2.413564,2.173366,0.500330
11,HOU,12,2.109526,0.869863,-0.653173
12,GB,13,2.104927,-1.988937,1.738028
13,CHI,14,1.556965,1.492357,2.669322
14,PIT,15,1.241368,-0.297864,1.479101
15,CIN,16,0.772808,1.760165,1.201415
16,PHI,17,-0.787958,-5.037040,0.039924
17,DAL,18,-1.232215,1.834347,-3.138689
18,IND,19,-1.293242,0.696893,-3.976142
19,TB,20,-1.509854,-3.025747,-0.048782
20,ATL,21,-1.653255,0.478315,-2.244721
21,NO,22,-2.102954,2.158182,-5.814854
22,CAR,23,-2.273949,4.649109,-1.433927
23,LAC,24,-2.722905,-6.957003,-1.580039
24,WAS,25,-2.833574,-0.618555,-4.691591
25,LV,26,-2.950558,3.858017,-3.215019
26,CLE,27,-3.278879,-5.016099,2.310865
27,NYG,28,-3.475892,-0.882120,-0.755156
28,NYJ,29,-4.019168,-3.985568,2.441396
29,ARI,30,-4.485537,-1.428464,-5.501499
30,MIA,31,-5.315924,-6.847689,-2.156439
31,TEN,32,-6.871269,-8.322540,1.254424

# Load New Weekly In-Season Features

These features contain the new evidence generated in notebook `03`.

For Week 3, they describe each team's Week 2 performance relative to its entering Week 2 expectation.

The primary values used here are:

- `weekly_strength_update`
- `weekly_offense_adjustment`
- `weekly_defense_adjustment`

The overall strength update is opponent adjusted and uses diminishing returns for extreme single game results.

In [5]:
inseason = pd.read_parquet(
    INSEASON_FEATURES_PATH
).copy()

required_inseason_columns = [
    "team",
    "games_in_update",
    "entering_team_strength",
    "entering_strength_rank",
    "average_opponent_strength",
    "average_opponent_rank",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

missing_inseason = [
    column
    for column in required_inseason_columns
    if column not in inseason.columns
]

if missing_inseason:
    raise KeyError(
        "Missing required in-season columns: "
        + ", ".join(missing_inseason)
    )

print("In-season teams:", len(inseason))
print(
    "Unique teams:",
    inseason["team"].nunique()
)

display(
    inseason[
        required_inseason_columns
    ].sort_values(
        "weekly_strength_update",
        ascending=False
    )
)

In-season teams: 28
Unique teams: 28

,team,games_in_update,entering_team_strength,entering_strength_rank,average_opponent_strength,average_opponent_rank,actual_margin,expected_margin,performance_residual,weekly_strength_update,weekly_offense_adjustment,weekly_defense_adjustment
26,TB,1,-1.509854,20,-2.273949,23.0,30.0,-0.735905,30.735905,1.463284,2.979013,1.350441
5,CIN,1,0.772808,16,2.413564,11.0,22.0,-3.140757,25.140757,1.419549,1.954794,1.526223
7,DAL,1,-1.232215,18,-0.787958,17.0,17.0,-1.944257,18.944257,1.312196,2.284737,0.206166
24,SEA,1,3.904552,4,4.051178,3.0,17.0,1.353374,15.646626,1.210107,-0.233795,3.087633
1,ATL,1,-1.653255,21,5.084675,1.0,9.0,-5.237930,14.237930,1.152960,1.154961,0.576390
20,NYG,1,-3.475892,28,2.109526,12.0,6.0,-7.085417,13.085417,1.099148,0.743393,0.314821
14,LA,1,2.769153,10,-2.950558,26.0,14.0,4.219711,9.780289,0.905210,1.753640,0.125068
8,DEN,1,3.197866,6,-4.485537,30.0,14.0,6.183403,7.816597,0.760104,0.946078,0.817507
4,CHI,1,1.556965,14,3.615375,5.0,6.0,-0.558410,6.558410,0.655429,1.249862,-0.078709
16,MIA,1,-5.315924,31,-4.019168,29.0,3.0,-2.796755,5.796755,0.587864,0.663567,-0.515005
23,PIT,1,1.241368,15,-2.102954,22.0,6.0,1.844322,4.155678,0.432619,-1.064575,1.806854
6,CLE,1,-3.278879,27,-6.871269,32.0,3.0,2.092390,0.907610,0.097108,0.406613,-0.471958
9,DET,1,2.858510,9,2.104927,13.0,3.0,2.253583,0.746417,0.079898,-0.306780,0.914649
17,MIN,1,3.140947,7,-1.293242,19.0,6.0,5.934189,0.065811,0.007051,-1.034211,1.837218
12,IND,1,-1.293242,19,3.140947,7.0,-6.0,-5.934189,-0.065811,-0.007051,-1.767929,1.103500
10,GB,1,2.104927,13,2.858510,9.0,-3.0,-2.253583,-0.746417,-0.079898,-0.728520,0.492908
27,TEN,1,-6.871269,32,-3.278879,27.0,-3.0,-2.092390,-0.907610,-0.097108,0.091328,-0.787244
19,NO,1,-2.102954,22,1.241368,15.0,-6.0,-1.844322,-4.155678,-0.432619,-1.839163,1.032266
21,NYJ,1,-4.019168,29,-5.315924,31.0,-3.0,2.796755,-5.796755,-0.587864,0.164939,-1.013633
18,NE,1,3.615375,5,1.556965,14.0,-6.0,0.558410,-6.558410,-0.655429,0.272672,-1.055900
0,ARI,1,-4.485537,30,3.197866,6.0,-14.0,-6.183403,-7.816597,-0.760104,-0.865794,-0.994366
15,LV,1,-2.950558,26,2.769153,10.0,-14.0,-4.219711,-9.780289,-0.905210,-0.131871,-1.760442
11,HOU,1,2.109526,12,-3.475892,28.0,-6.0,7.085417,-13.085417,-1.099148,-0.366060,-0.794632
25,SF,1,5.084675,1,-1.653255,21.0,-9.0,5.237930,-14.237930,-1.152960,-0.447711,-1.026283
13,KC,1,4.051178,3,3.904552,4.0,-17.0,-1.353374,-15.646626,-1.210107,-2.789294,0.532135
22,PHI,1,-0.787958,17,-1.232215,18.0,-17.0,1.944257,-18.944257,-1.312196,-0.281922,-2.360494
2,BAL,1,2.413564,11,0.772808,16.0,-22.0,3.140757,-25.140757,-1.419549,-1.406734,-1.835305
3,CAR,1,-2.273949,23,-1.509854,20.0,-30.0,0.735905,-30.735905,-1.463284,-1.492334,-3.120905

# Merge Prior Week State with New Evidence

The weekly model now combines three pieces of information:

1. Frozen preseason information for long term reference
2. Previous week's team strength as the current prior
3. Most recent week's opponent adjusted performance as new evidence

All 32 teams must remain in the table.

In [6]:
weekly_strength = (
    preseason
    .merge(
        prior_week,
        on="team",
        how="left",
        validate="one_to_one"
    )
    .merge(
        inseason,
        on="team",
        how="left",
        validate="one_to_one"
    )
)

weekly_fill_columns = [
    "games_in_update",
    "weekly_strength_update",
    "weekly_offense_adjustment",
    "weekly_defense_adjustment"
]

weekly_strength[
    weekly_fill_columns
] = (
    weekly_strength[
        weekly_fill_columns
    ]
    .fillna(0.0)
)

print("Merged teams:", len(weekly_strength))
print(
    "Unique teams:",
    weekly_strength["team"].nunique()
)

print(
    "Missing prior-week strengths:",
    weekly_strength[
        "prior_week_team_strength"
    ].isna().sum()
)

Merged teams: 32
Unique teams: 32
Missing prior-week strengths: 0

# Sequential Weekly Rating Update

The previous week's team strength is the starting point.

The current week's opponent adjusted performance update is then applied:

`weekly_team_strength = prior_week_team_strength + weekly_strength_update`

Therefore, for Week 3:

`Week 3 Strength = Week 2 Strength + Week 2 Performance Update`

Older results remain embedded in the prior week rating and are not counted again.

The offensive and defensive weekly adjustments remain available separately for the weekly scoring model.

In [7]:
weekly_strength["team_strength_change"] = (
    weekly_strength["weekly_strength_update"]
)

weekly_strength["weekly_team_strength"] = (
    weekly_strength["prior_week_team_strength"]
    + weekly_strength["team_strength_change"]
)

display(
    weekly_strength[
        [
            "team",
            "prior_week_team_strength",
            "weekly_offense_adjustment",
            "weekly_defense_adjustment",
            "team_strength_change",
            "weekly_team_strength"
        ]
    ].sort_values(
        "weekly_team_strength",
        ascending=False
    )
)

,team,prior_week_team_strength,weekly_offense_adjustment,weekly_defense_adjustment,team_strength_change,weekly_team_strength
2,SEA,3.904552,-0.233795,3.087633,1.210107,5.114660
0,BUF,4.947555,0.000000,0.000000,0.000000,4.947555
4,DEN,3.197866,0.946078,0.817507,0.760104,3.957970
9,SF,5.084675,-0.447711,-1.026283,-1.152960,3.931716
1,LA,2.769153,1.753640,0.125068,0.905210,3.674363
17,MIN,3.140947,-1.034211,1.837218,0.007051,3.147998
11,JAX,3.094193,0.000000,0.000000,0.000000,3.094193
10,NE,3.615375,0.272672,-1.055900,-0.655429,2.959946
3,DET,2.858510,-0.306780,0.914649,0.079898,2.938408
12,KC,4.051178,-2.789294,0.532135,-1.210107,2.841071
18,CHI,1.556965,1.249862,-0.078709,0.655429,2.212394
20,CIN,0.772808,1.954794,1.526223,1.419549,2.192357
7,GB,2.104927,-0.728520,0.492908,-0.079898,2.025029
15,PIT,1.241368,-1.064575,1.806854,0.432619,1.673987
6,HOU,2.109526,-0.366060,-0.794632,-1.099148,1.010378
5,BAL,2.413564,-1.406734,-1.835305,-1.419549,0.994015
19,DAL,-1.232215,2.284737,0.206166,1.312196,0.079981
14,TB,-1.509854,2.979013,1.350441,1.463284,-0.046570
21,ATL,-1.653255,1.154961,0.576390,1.152960,-0.500295
16,IND,-1.293242,-1.767929,1.103500,-0.007051,-1.300293
8,PHI,-0.787958,-0.281922,-2.360494,-1.312196,-2.100154
25,NYG,-3.475892,0.743393,0.314821,1.099148,-2.376744
22,NO,-2.102954,-1.839163,1.032266,-0.432619,-2.535573
13,LAC,-2.722905,0.000000,0.000000,0.000000,-2.722905
23,WAS,-2.833574,0.000000,0.000000,0.000000,-2.833574
27,CLE,-3.278879,0.406613,-0.471958,0.097108,-3.181771
28,CAR,-2.273949,-1.492334,-3.120905,-1.463284,-3.737233
29,LV,-2.950558,-0.131871,-1.760442,-0.905210,-3.855768
30,NYJ,-4.019168,0.164939,-1.013633,-0.587864,-4.607032
24,MIA,-5.315924,0.663567,-0.515005,0.587864,-4.728059
26,ARI,-4.485537,-0.865794,-0.994366,-0.760104,-5.245641
31,TEN,-6.871269,0.091328,-0.787244,-0.097108,-6.968377

In [8]:
weekly_strength["cumulative_offense_adjustment"] = (
    weekly_strength["prior_cumulative_offense_adjustment"]
    + weekly_strength["weekly_offense_adjustment"]
)

weekly_strength["cumulative_defense_adjustment"] = (
    weekly_strength["prior_cumulative_defense_adjustment"]
    + weekly_strength["weekly_defense_adjustment"]
)

assert weekly_strength[
    "cumulative_offense_adjustment"
].notna().all()

assert weekly_strength[
    "cumulative_defense_adjustment"
].notna().all()

# Updated Weekly Rankings

The current weekly rank is based on `weekly_team_strength`.

Ranking movement is now measured relative to the immediately previous week rather than the preseason ranking.

A positive `rank_change` means the team moved up.

For example:

- Week 2 rank = 8
- Week 3 rank = 5
- Rank change = +3

In [9]:
weekly_strength = weekly_strength.sort_values(
    [
        "weekly_team_strength",
        "prior_week_team_strength"
    ],
    ascending=[False, False]
).reset_index(drop=True)

weekly_strength["weekly_strength_rank"] = (
    np.arange(
        1,
        len(weekly_strength) + 1
    )
)

weekly_strength["rank_change"] = (
    weekly_strength["prior_week_strength_rank"]
    - weekly_strength["weekly_strength_rank"]
)

weekly_comparison_table = (
    weekly_strength[
        [
            "weekly_strength_rank",
            "team",
            "weekly_team_strength",
            "prior_week_strength_rank",
            "prior_week_team_strength",
            "team_strength_change",
            "rank_change"
        ]
    ]
    .copy()
)

display(weekly_comparison_table)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change
0,1,SEA,5.114660,4,3.904552,1.210107,3
1,2,BUF,4.947555,2,4.947555,0.000000,0
2,3,DEN,3.957970,6,3.197866,0.760104,3
3,4,SF,3.931716,1,5.084675,-1.152960,-3
4,5,LA,3.674363,10,2.769153,0.905210,5
5,6,MIN,3.147998,7,3.140947,0.007051,1
6,7,JAX,3.094193,8,3.094193,0.000000,1
7,8,NE,2.959946,5,3.615375,-0.655429,-3
8,9,DET,2.938408,9,2.858510,0.079898,0
9,10,KC,2.841071,3,4.051178,-1.210107,-7
10,11,CHI,2.212394,14,1.556965,0.655429,3
11,12,CIN,2.192357,16,0.772808,1.419549,4
12,13,GB,2.025029,13,2.104927,-0.079898,0
13,14,PIT,1.673987,15,1.241368,0.432619,1
14,15,HOU,1.010378,12,2.109526,-1.099148,-3
15,16,BAL,0.994015,11,2.413564,-1.419549,-5
16,17,DAL,0.079981,18,-1.232215,1.312196,1
17,18,TB,-0.046570,20,-1.509854,1.463284,2
18,19,ATL,-0.500295,21,-1.653255,1.152960,2
19,20,IND,-1.300293,19,-1.293242,-0.007051,-1
20,21,PHI,-2.100154,17,-0.787958,-1.312196,-4
21,22,NYG,-2.376744,28,-3.475892,1.099148,6
22,23,NO,-2.535573,22,-2.102954,-0.432619,-1
23,24,LAC,-2.722905,24,-2.722905,0.000000,0
24,25,WAS,-2.833574,25,-2.833574,0.000000,0
25,26,CLE,-3.181771,27,-3.278879,0.097108,1
26,27,CAR,-3.737233,23,-2.273949,-1.463284,-4
27,28,LV,-3.855768,26,-2.950558,-0.905210,-2
28,29,NYJ,-4.607032,29,-4.019168,-0.587864,0
29,30,MIA,-4.728059,31,-5.315924,0.587864,1
30,31,ARI,-5.245641,30,-4.485537,-0.760104,-1
31,32,TEN,-6.968377,32,-6.871269,-0.097108,0

# Biggest Weekly Movers

This table is diagnostic only.

It shows which teams experienced the largest overall rating changes from the previous week to the current week.

The underlying projection model still retains the full preseason, offense, defense, opponent and weekly information.

In [10]:
mover_columns = [
    "team",
    "prior_week_team_strength",
    "team_strength_change",
    "weekly_team_strength",
    "prior_week_strength_rank",
    "weekly_strength_rank",
    "rank_change"
]

biggest_risers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=False
    )
    .head(10)
)

biggest_fallers = (
    weekly_strength[
        mover_columns
    ]
    .sort_values(
        "team_strength_change",
        ascending=True
    )
    .head(10)
)

print("BIGGEST RISERS")
display(biggest_risers)

print()
print("BIGGEST FALLERS")
display(biggest_fallers)

BIGGEST RISERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
17,TB,-1.509854,1.463284,-0.046570,20,18,2
11,CIN,0.772808,1.419549,2.192357,16,12,4
16,DAL,-1.232215,1.312196,0.079981,18,17,1
0,SEA,3.904552,1.210107,5.114660,4,1,3
18,ATL,-1.653255,1.152960,-0.500295,21,19,2
21,NYG,-3.475892,1.099148,-2.376744,28,22,6
4,LA,2.769153,0.905210,3.674363,10,5,5
2,DEN,3.197866,0.760104,3.957970,6,3,3
10,CHI,1.556965,0.655429,2.212394,14,11,3
29,MIA,-5.315924,0.587864,-4.728059,31,30,1

BIGGEST FALLERS

,team,prior_week_team_strength,team_strength_change,weekly_team_strength,prior_week_strength_rank,weekly_strength_rank,rank_change
26,CAR,-2.273949,-1.463284,-3.737233,23,27,-4
15,BAL,2.413564,-1.419549,0.994015,11,16,-5
20,PHI,-0.787958,-1.312196,-2.100154,17,21,-4
9,KC,4.051178,-1.210107,2.841071,3,10,-7
3,SF,5.084675,-1.152960,3.931716,1,4,-3
14,HOU,2.109526,-1.099148,1.010378,12,15,-3
27,LV,-2.950558,-0.905210,-3.855768,26,28,-2
30,ARI,-4.485537,-0.760104,-5.245641,30,31,-1
7,NE,3.615375,-0.655429,2.959946,5,8,-3
28,NYJ,-4.019168,-0.587864,-4.607032,29,29,0

# Update Diagnostics

These diagnostics check the size and distribution of the sequential weekly update.

The comparison is now:

`Prior Week Strength → Current Week Strength`

rather than:

`Preseason Strength → Current Week Strength`

In [11]:
movement = (
    weekly_strength[
        "team_strength_change"
    ].abs()
)

print(
    f"WEEK {PRIOR_WEEK} → "
    f"WEEK {TARGET_WEEK} TEAM-STRENGTH MOVEMENT"
)

print(
    weekly_strength[
        "team_strength_change"
    ]
    .describe()
    .round(3)
)

print()

print(
    "Mean absolute movement:",
    round(
        movement.mean(),
        3
    )
)

print(
    "Maximum absolute movement:",
    round(
        movement.max(),
        3
    )
)

print(
    "Team with largest movement:",
    weekly_strength.loc[
        movement.idxmax(),
        "team"
    ]
)

print()
print("RATING DISTRIBUTIONS")

distribution_check = pd.DataFrame(
    {
        "metric": [
            f"Week {PRIOR_WEEK} Team Strength",
            f"Week {TARGET_WEEK} Team Strength"
        ],
        "mean": [
            weekly_strength[
                "prior_week_team_strength"
            ].mean(),
            weekly_strength[
                "weekly_team_strength"
            ].mean()
        ],
        "std": [
            weekly_strength[
                "prior_week_team_strength"
            ].std(),
            weekly_strength[
                "weekly_team_strength"
            ].std()
        ],
        "min": [
            weekly_strength[
                "prior_week_team_strength"
            ].min(),
            weekly_strength[
                "weekly_team_strength"
            ].min()
        ],
        "max": [
            weekly_strength[
                "prior_week_team_strength"
            ].max(),
            weekly_strength[
                "weekly_team_strength"
            ].max()
        ]
    }
)

display(
    distribution_check.round(3)
)

WEEK 7 → WEEK 8 TEAM-STRENGTH MOVEMENT
count    32.000
mean     -0.000
std       0.889
min      -1.463
25%      -0.682
50%       0.000
75%       0.682
max       1.463
Name: team_strength_change, dtype: float64

Mean absolute movement: 0.699
Maximum absolute movement: 1.463
Team with largest movement: TB

RATING DISTRIBUTIONS

                 metric   mean    std    min    max
0  Week 7 Team Strength  0.002  3.297 -6.871  5.085
1  Week 8 Team Strength  0.002  3.366 -6.968  5.115

# Sanity Checks

These checks verify the sequential weekly update.

The weekly file should:

- contain exactly 32 unique teams
- preserve the frozen preseason information
- contain a valid prior week rating for every team
- contain no missing current weekly strength values
- have `team_strength_change` equal to the new opponent adjusted weekly update
- calculate current strength as prior week strength plus the weekly update
- never overwrite the preseason or prior week files

In [12]:
assert len(weekly_strength) == 32, (
    "Expected 32 teams in weekly strength table."
)

assert (
    weekly_strength["team"].nunique()
    == 32
), (
    "Expected 32 unique teams."
)

assert weekly_strength[
    "preseason_team_strength"
].notna().all(), (
    "Missing frozen preseason ratings."
)

assert weekly_strength[
    "prior_week_team_strength"
].notna().all(), (
    "Missing prior-week ratings."
)

assert weekly_strength[
    "weekly_team_strength"
].notna().all(), (
    "Missing current weekly ratings."
)

assert np.allclose(
    weekly_strength[
        "team_strength_change"
    ],
    weekly_strength[
        "weekly_strength_update"
    ]
), (
    "Team-strength change does not match "
    "the opponent-adjusted weekly update."
)

assert np.allclose(
    weekly_strength[
        "weekly_team_strength"
    ],
    (
        weekly_strength[
            "prior_week_team_strength"
        ]
        + weekly_strength[
            "team_strength_change"
        ]
    )
), (
    "Sequential weekly strength formula "
    "is inconsistent."
)

played_mask = weekly_strength["games_in_update"] > 0

assert np.allclose(
    weekly_strength.loc[
        played_mask, "entering_team_strength"
    ],
    weekly_strength.loc[
        played_mask, "prior_week_team_strength"
    ]
), (
    "Notebook 03 entering strength does not match "
    "the prior-week team strength."
)

bye_mask = ~played_mask

assert np.allclose(
    weekly_strength.loc[
        bye_mask, "weekly_team_strength"
    ],
    weekly_strength.loc[
        bye_mask, "prior_week_team_strength"
    ]
), "Bye-week teams did not retain their previous strength."

print(
    "All sequential weekly team-strength "
    "sanity checks passed."
)

All sequential weekly team-strength sanity checks passed.

# Final Weekly Team Strength Table

The saved file contains the full state needed by the weekly projection pipeline.

This includes:

- current weekly strength and rank
- previous week's strength and rank
- week to week movement
- frozen preseason information
- opponent adjusted performance information
- separate offensive and defensive weekly signals

The compact ranking table shown earlier is only for interpretation. The saved dataset retains the additional model information.

In [13]:
final_columns = [
    "weekly_strength_rank",
    "team",
    "weekly_team_strength",

    "prior_week_strength_rank",
    "prior_week_team_strength",
    "team_strength_change",
    "rank_change",

    "games_in_update",
    "average_opponent_rank",
    "average_opponent_strength",
    "actual_margin",
    "expected_margin",
    "performance_residual",
    "weekly_strength_update",

    "weekly_offense_adjustment",
    "weekly_defense_adjustment",
    "cumulative_offense_adjustment",
    "cumulative_defense_adjustment",

    "preseason_strength_rank",
    "preseason_team_strength",
    "preseason_baseline_team_strength",
    "preseason_personnel_adjustment",
    "preseason_personnel_strength",
    "preseason_roster_continuity",
    "preseason_roster_continuity_adjustment"
]

weekly_team_strength = (
    weekly_strength[
        final_columns
    ]
    .copy()
)

display(
    weekly_team_strength
)

,weekly_strength_rank,team,weekly_team_strength,prior_week_strength_rank,prior_week_team_strength,team_strength_change,rank_change,games_in_update,average_opponent_rank,average_opponent_strength,...,weekly_defense_adjustment,cumulative_offense_adjustment,cumulative_defense_adjustment,preseason_strength_rank,preseason_team_strength,preseason_baseline_team_strength,preseason_personnel_adjustment,preseason_personnel_strength,preseason_roster_continuity,preseason_roster_continuity_adjustment
0,1,SEA,5.114660,4,3.904552,1.210107,3,1.0,3.0,4.051178,...,3.087633,1.324606,5.672999,3,4.363421,3.515976,0.635683,0.423788,0.677419,0.932073
1,2,BUF,4.947555,2,4.947555,0.000000,0,0.0,NaN,NaN,...,0.000000,9.052222,-4.620813,1,4.816514,4.125764,0.934506,0.623004,0.573034,0.260091
2,3,DEN,3.957970,6,3.197866,0.760104,3,1.0,30.0,-4.485537,...,0.817507,-2.121782,3.426611,5,3.569507,2.355154,0.979753,0.653169,0.727273,1.253003
3,4,SF,3.931716,1,5.084675,-1.152960,-3,1.0,21.0,-1.653255,...,-1.026283,5.414943,3.313336,10,2.366788,1.805709,0.692939,0.461959,0.577778,0.290631
4,5,LA,3.674363,10,2.769153,0.905210,5,1.0,26.0,-2.950558,...,0.125068,1.325867,0.274260,2,4.762452,3.257133,2.100811,1.400540,0.608696,0.489665
5,6,MIN,3.147998,7,3.140947,0.007051,1,1.0,19.0,-1.293242,...,1.837218,-2.364647,9.548032,18,0.475040,0.919610,-0.620638,-0.413759,0.510204,-0.144374
6,7,JAX,3.094193,8,3.094193,0.000000,1,0.0,NaN,NaN,...,0.000000,2.469038,5.296003,12,1.713136,1.746953,-0.223729,-0.149153,0.563830,0.200841
7,8,NE,2.959946,5,3.615375,-0.655429,-3,1.0,14.0,1.556965,...,-1.055900,0.174868,3.023261,11,1.910188,1.605622,0.906186,0.604124,0.458333,-0.478291
8,9,DET,2.938408,9,2.858510,0.079898,0,1.0,13.0,2.104927,...,0.914649,6.434550,-4.152771,4,4.018565,3.374644,1.041923,0.694616,0.538462,0.037533
9,10,KC,2.841071,3,4.051178,-1.210107,-7,1.0,4.0,3.904552,...,0.532135,0.858981,4.997374,13,1.302244,1.484935,-0.187743,-0.125162,0.510870,-0.140090
10,11,CHI,2.212394,14,1.556965,0.655429,3,1.0,5.0,3.615375,...,-0.078709,2.742220,2.590612,19,-0.051934,-0.069709,0.002783,0.001856,0.537634,0.032209
11,12,CIN,2.192357,16,0.772808,1.419549,4,1.0,11.0,2.413564,...,1.526223,3.714960,2.727638,21,-0.739434,-1.268642,0.286293,0.190862,0.643678,0.714864
12,13,GB,2.025029,13,2.104927,-0.079898,0,1.0,9.0,2.858510,...,0.492908,-2.717457,2.230936,8,2.536317,1.718369,0.882628,0.588419,0.622222,0.576742
13,14,PIT,1.673987,15,1.241368,0.432619,1,1.0,22.0,-2.102954,...,1.806854,-1.362439,3.285954,16,0.543902,0.359049,0.304322,0.202881,0.533333,0.004521
14,15,HOU,1.010378,12,2.109526,-1.099148,-3,1.0,28.0,-3.475892,...,-0.794632,0.503803,-1.447805,7,2.810133,2.193179,1.173833,0.782555,0.505495,-0.174691
15,16,BAL,0.994015,11,2.413564,-1.419549,-5,1.0,16.0,0.772808,...,-1.835305,0.766632,-1.334976,6,3.074111,2.710864,0.636254,0.424170,0.526882,-0.037012
16,17,DAL,0.079981,18,-1.232215,1.312196,1,1.0,17.0,-0.787958,...,0.206166,4.119084,-2.932523,20,-0.386396,-0.773189,0.640887,0.427258,0.533333,0.004521
17,18,TB,-0.046570,20,-1.509854,1.463284,2,1.0,23.0,-2.273949,...,1.350441,-0.046734,1.301659,15,0.601026,0.449564,0.167912,0.111942,0.548387,0.101429
18,19,ATL,-0.500295,21,-1.653255,1.152960,2,1.0,1.0,5.084675,...,0.576390,1.633276,-1.668332,22,-1.331272,-1.430617,0.664859,0.443239,0.439560,-0.599141
19,20,IND,-1.300293,19,-1.293242,-0.007051,-1,1.0,7.0,3.140947,...,1.103500,-1.071035,-2.872642,17,0.532226,0.543256,-0.167564,-0.111709,0.560440,0.179017
20,21,PHI,-2.100154,17,-0.787958,-1.312196,-4,1.0,18.0,-1.232215,...,-2.360494,-5.318962,-2.320569,9,2.451919,2.324982,0.264690,0.176460,0.522727,-0.063756
21,22,NYG,-2.376744,28,-3.475892,1.099148,6,1.0,12.0,2.109526,...,0.314821,-0.138727,-0.440334,26,-3.455862,-2.902685,-0.687303,-0.458202,0.488889,-0.281590
22,23,NO,-2.535573,22,-2.102954,-0.432619,-1,1.0,15.0,1.241368,...,1.032266,0.319019,-4.782588,23,-1.556053,-1.584652,-0.112569,-0.075046,0.562500,0.192281
23,24,LAC,-2.722905,24,-2.722905,0.000000,0,0.0,NaN,NaN,...,0.000000,-6.957003,-1.580039,14,0.910681,1.089525,-0.382598,-0.255065,0.548387,0.101429
24,25,WAS,-2.833574,25,-2.833574,0.000000,0,0.0,NaN,NaN,...,0.000000,-0.618555,-4.691591,24,-2.001869,-1.962594,0.021167,0.014111,0.516484,-0.103950
25,26,CLE,-3.181771,27,-3.278879,0.097108,1,1.0,32.0,-6.871269,...,-0.471958,-4.609486,1.838907,28,-4.150395,-3.147236,-1.385118,-0.923412,0.479167,-0.344177
26,27,CAR,-3.737233,23,-2.273949,-1.463284,-4,1.0,20.0,-1.509854,...,-3.120905,3.156775,-4.554832,29,-4.533242,-3.703033,-1.322770,-0.881847,0.521277,-0.073094
27,28,LV,-3.855768,26,-2.950558,-0.905210,-2,1.0,10.0,2.769153,...,-1.760442,3.726146,-4.975462,30,-5.693342,-4.625655,-1.325021,-0.883347,0.447917,-0.545348
28,29,NYJ,-4.607032,29,-4.019168,-0.587864,0,1.0,31.0,-5.315924,...,-1.013633,-3.820630,1.427763,31,-5.933726,-4.805098,-1.734836,-1.156558,0.505376,-0.175452
29,30,MIA,-4.728059,31,-5.315924,0.587864,1,1.0,29.0,-4.019168,...,-0.515005,-6.184122,-2.671444,25,-2.443254,-1.116195,-0.947865,-0.631910,0.297030,-1.516681
30,31,ARI,-5.245641,30,-4.485537,-0.760104,-1,1.0,6.0,3.197866,...,-0.994366,-2.294258,-6.495865,27,-3.678016,-2.961441,-1.166618,-0.777745,0.527473,-0.033208
31,32,TEN,-6.968377,32,-6.871269,-0.097108,0,1.0,27.0,-3.278879,...,-0.787244,-8.231212,0.467181,32,-6.747344,-5.173512,-2.073057,-1.382038,0.430108,-0.659994

# Save Weekly Team Strength

This writes only to:

`data/processed/weekly/`

The original:

`data/processed/2026_team_strength.parquet`

remains untouched.

In [14]:
OUTPUT_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

weekly_team_strength.to_parquet(
    OUTPUT_PATH,
    index=False
)

print("Saved:", OUTPUT_PATH)
print()
print(
    "Original preseason file remains:",
    PRESEASON_STRENGTH_PATH
)

Saved: ..\..\data\processed\weekly\week_08_sequential_team_strength.parquet

Original preseason file remains: ..\..\data\processed\2026_team_strength.parquet

# What This Means for Week 3

At the end of this notebook, every team has:

- its frozen preseason rating
- its Week 2 entering rating and rank
- its opponent adjusted Week 2 performance
- its Week 2 offensive and defensive signals
- its Week 2 → Week 3 rating movement
- its updated Week 3 team strength rating
- its updated Week 3 rank

The next stage will apply the Week 3 injury update and then use the resulting team state to generate Week 3 game projections.

The weekly ranking table is diagnostic only.

The saved weekly team strength file retains the additional information required by the projection pipeline.