# 06 — Week 2 Projections

This notebook converts the updated weekly team-strength ratings into game level projections for the selected target week.

The original preseason notebooks and preseason projections remain frozen.

For each target week matchup, this notebook:

- loads the updated weekly team strengths from Notebook 04
- preserves the original preseason Week 2 projection as a baseline
- recalculates expected margin using weekly strength, historical home field advantage, and rest
- converts expected margin into win probability using historical NFL margin variability
- carries forward the frozen preseason scoring baseline created for Week 1
- adds the new in season offensive and defensive scoring evidence
- produces projected scores, model spreads, ATS comparisons, totals comparisons, and final output tables
- saves all outputs only inside the weekly layer

The market is used only for comparison. It never enters the model projection itself.

In [11]:
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl
from scipy.stats import norm
from sklearn.linear_model import LinearRegression

## Paths and Weekly Settings

For Week 2, `TARGET_WEEK = 2`.

Future weeks use the same notebook by changing the target week after the preceding weekly notebooks have been rerun.

In [12]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"
WEEKLY_OUTPUT_DIR = PROJECT_ROOT / "weekly_projections" / "outputs"

SEASON = 2026
TARGET_WEEK = 6

WEEK_OUTPUT_DIR = (
    WEEKLY_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}"
)

WEEK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

WEEKLY_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_sequential_team_strength.parquet"
)

INJURY_ADJUSTED_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_injury_adjusted_team_strength.parquet"
)

TARGET_SCHEDULE_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_schedule.parquet"
)

PRESEASON_BASELINE_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_preseason_baseline.parquet"
)

WEEK1_PROJECTIONS_PATH = (
    WEEKLY_DATA_DIR
    / "week_01_projections.parquet"
)

# Load Weekly Inputs

Notebook 04 supplies the updated ratings. Notebook 02 supplies the target week schedule and frozen preseason comparison.

In [13]:
weekly_strength = pd.read_parquet(WEEKLY_STRENGTH_PATH)

injury_adjusted_strength = pd.read_parquet(
    INJURY_ADJUSTED_STRENGTH_PATH
)

target_schedule = pd.read_parquet(
    TARGET_SCHEDULE_PATH
)

preseason_baseline = pd.read_parquet(
    PRESEASON_BASELINE_PATH
)

target_schedule = target_schedule[
    target_schedule["home_score"].isna()
    & target_schedule["away_score"].isna()
].copy()


preseason_baseline = preseason_baseline[
    preseason_baseline["game_id"].isin(
        target_schedule["game_id"]
    )
].copy()


print(
    "Sequential weekly strengths:",
    weekly_strength.shape
)

print(
    "Injury-adjusted strengths:",
    injury_adjusted_strength.shape
)

print(
    "Remaining target-week games:",
    target_schedule.shape
)

print(
    "Frozen preseason games:",
    preseason_baseline.shape
)

assert len(weekly_strength) == 32
assert weekly_strength["team"].nunique() == 32

assert len(injury_adjusted_strength) == 32
assert injury_adjusted_strength["team"].nunique() == 32

assert len(target_schedule) == len(
    preseason_baseline
)

required_injury_columns = [
    "team",
    "weekly_team_strength",
    "injury_adjustment",
    "injury_adjusted_team_strength"
]

missing_injury_columns = [
    col
    for col in required_injury_columns
    if col not in injury_adjusted_strength.columns
]

assert not missing_injury_columns, (
    "Missing injury-adjusted columns: "
    + ", ".join(missing_injury_columns)
)


print(
    "Using sequential ratings as the pre-injury baseline "
    "and injury-adjusted ratings for Week "
    f"{TARGET_WEEK} projections."
)

Sequential weekly strengths: (32, 25)
Injury-adjusted strengths: (32, 30)
Remaining target-week games: (14, 46)
Frozen preseason games: (14, 16)
Using sequential ratings as the pre-injury baseline and injury-adjusted ratings for Week 6 projections.

### Injury adjusted game strength

For Week 2, the `home_weekly_team_strength` and `away_weekly_team_strength` values now include the conservative injury adjustment from Notebook 05.

The injury adjustment remains visible separately in the saved team strength file, so we can distinguish:

**preseason → performance update → injury update → final Week 2 rating**

# Attach Updated Team Strength

The matchup calculation is identical in structure to the original preseason game prediction model. The only change is the source of team strength:

`preseason team_strength` → `weekly_team_strength`

This isolates the in season update without changing the original model.

In [14]:
strength_lookup = injury_adjusted_strength[
    [
        "team",
        "weekly_team_strength",
        "injury_adjustment",
        "injury_adjusted_team_strength",
        "preseason_team_strength",
        "team_strength_change",
        "cumulative_offense_adjustment",
        "cumulative_defense_adjustment"
    ]
].copy()


games = target_schedule.copy()

home_lookup = strength_lookup.rename(
    columns={
        "team": "home_team",

        "weekly_team_strength":
            "home_pre_injury_team_strength",

        "injury_adjustment":
            "home_injury_adjustment",

        "injury_adjusted_team_strength":
            "home_weekly_team_strength",

        "preseason_team_strength":
            "home_preseason_team_strength",

        "team_strength_change":
            "home_strength_change",

        "cumulative_offense_adjustment":
            "home_offense_adjustment",

        "cumulative_defense_adjustment":
            "home_defense_adjustment"
    }
)

away_lookup = strength_lookup.rename(
    columns={
        "team": "away_team",

        "weekly_team_strength":
            "away_pre_injury_team_strength",

        "injury_adjustment":
            "away_injury_adjustment",

        "injury_adjusted_team_strength":
            "away_weekly_team_strength",

        "preseason_team_strength":
            "away_preseason_team_strength",

        "team_strength_change":
            "away_strength_change",

        "cumulative_offense_adjustment":
            "away_offense_adjustment",

        "cumulative_defense_adjustment":
            "away_defense_adjustment"
    }
)


games = (
    games
    .merge(
        home_lookup,
        on="home_team",
        how="left",
        validate="many_to_one"
    )
    .merge(
        away_lookup,
        on="away_team",
        how="left",
        validate="many_to_one"
    )
)

games["weekly_neutral_strength_diff"] = (
    games["home_weekly_team_strength"]
    - games["away_weekly_team_strength"]
)

games["pre_injury_neutral_strength_diff"] = (
    games["home_pre_injury_team_strength"]
    - games["away_pre_injury_team_strength"]
)


games["preseason_neutral_strength_diff"] = (
    games["home_preseason_team_strength"]
    - games["away_preseason_team_strength"]
)

assert games[
    "home_weekly_team_strength"
].notna().all()

assert games[
    "away_weekly_team_strength"
].notna().all()

assert games[
    "home_injury_adjustment"
].notna().all()

assert games[
    "away_injury_adjustment"
].notna().all()

# Home Field and Rest

These effects are recalculated using the same historical 2015–2025 methodology as the frozen preseason game prediction notebook.

They are not retuned using Week 1.

In [15]:
schedule_clean = pl.read_parquet(
    PROCESSED_DIR / "schedule_clean.parquet"
)

historical_home = (
    schedule_clean
    .filter(
        (pl.col("season") >= 2015)
        & (pl.col("season") <= 2025)
        & (pl.col("location") == "Home")
        & pl.col("result").is_not_null()
    )
)

HOME_FIELD_ADVANTAGE = (
    historical_home
    .select(pl.col("result").mean())
    .item()
)

historical_rest = (
    schedule_clean
    .filter(
        (pl.col("season") >= 2015)
        & (pl.col("season") <= 2025)
        & pl.col("result").is_not_null()
        & pl.col("home_rest").is_not_null()
        & pl.col("away_rest").is_not_null()
    )
    .select(["result", "home_rest", "away_rest", "location"])
    .to_pandas()
)

historical_rest["rest_diff"] = (
    historical_rest["home_rest"]
    - historical_rest["away_rest"]
).clip(-7, 7)

historical_rest["home_field"] = (
    historical_rest["location"] == "Home"
).astype(int)

rest_model = LinearRegression()
rest_model.fit(
    historical_rest[["home_field", "rest_diff"]],
    historical_rest["result"]
)

REST_POINT_VALUE = rest_model.coef_[1]

print("Historical HFA:", round(HOME_FIELD_ADVANTAGE, 3))
print("Rest points/day:", round(REST_POINT_VALUE, 3))

Historical HFA: 1.764
Rest points/day: 0.181

In [16]:
games["home_field_adjustment"] = np.where(
    games["location"] == "Home",
    HOME_FIELD_ADVANTAGE,
    0.0
)

games["rest_diff"] = (
    games["home_rest"]
    - games["away_rest"]
).clip(-7, 7)

games["rest_adjustment"] = (
    games["rest_diff"]
    * REST_POINT_VALUE
)

games["expected_home_margin"] = (
    games["weekly_neutral_strength_diff"]
    + games["home_field_adjustment"]
    + games["rest_adjustment"]
)

# Win Probabilities

Historical 2015–2025 game-margin variability is retained exactly as the uncertainty scale. Week 1 is not used to recalibrate probability confidence.

In [17]:
historical_margin_std = (
    schedule_clean
    .filter(
        (pl.col("season") >= 2015)
        & (pl.col("season") <= 2025)
        & pl.col("result").is_not_null()
    )
    .select(pl.col("result").std())
    .item()
)

games["home_win_probability"] = norm.cdf(
    games["expected_home_margin"]
    / historical_margin_std
)

games["away_win_probability"] = (
    1 - games["home_win_probability"]
)

games["predicted_winner"] = np.where(
    games["home_win_probability"] >= 0.50,
    games["home_team"],
    games["away_team"]
)

games["predicted_win_probability"] = np.maximum(
    games["home_win_probability"],
    games["away_win_probability"]
)

print("Historical margin SD:", round(historical_margin_std, 3))

Historical margin SD: 14.201

# Preseason vs Weekly Margin Movement

The frozen preseason Week 2 projection is attached for diagnostics only.

This makes it possible to see exactly how much the Week 1 evidence changed each Week 2 matchup.

In [18]:
preseason_compare = preseason_baseline[
    [
        "game_id",
        "expected_home_margin",
        "predicted_winner",
        "predicted_win_probability"
    ]
].rename(columns={
    "expected_home_margin": "preseason_expected_home_margin",
    "predicted_winner": "preseason_predicted_winner",
    "predicted_win_probability": "preseason_predicted_win_probability"
})

games = games.merge(
    preseason_compare,
    on="game_id",
    how="left",
    validate="one_to_one"
)

games["margin_change_from_preseason"] = (
    games["expected_home_margin"]
    - games["preseason_expected_home_margin"]
)

display(
    games[
        [
            "away_team",
            "home_team",
            "preseason_expected_home_margin",
            "expected_home_margin",
            "margin_change_from_preseason",
            "preseason_predicted_winner",
            "predicted_winner",
            "predicted_win_probability"
        ]
    ].round(3)
)

,away_team,home_team,preseason_expected_home_margin,expected_home_margin,margin_change_from_preseason,preseason_predicted_winner,predicted_winner,predicted_win_probability
0,SEA,DEN,0.970,0.465,-0.505,DEN,DEN,0.513
1,ARI,LA,10.023,11.021,0.998,LA,LA,0.781
2,BAL,CLE,-5.461,-5.611,-0.150,BAL,BAL,0.654
3,BUF,LV,-8.565,-6.845,1.720,BUF,BUF,0.685
4,CAR,PHI,7.482,4.461,-3.021,PHI,PHI,0.623
5,CHI,ATL,0.484,0.072,-0.412,ATL,ATL,0.502
6,DAL,GB,4.143,3.265,-0.879,GB,GB,0.591
7,HOU,JAX,-1.097,2.345,3.442,HOU,JAX,0.566
8,LAC,KC,3.422,8.033,4.611,KC,KC,0.714
9,NO,NYG,-0.136,2.061,2.198,NO,NYG,0.558
10,NYJ,NE,9.607,9.971,0.364,NE,NE,0.759
11,PIT,TB,2.364,0.969,-1.395,TB,TB,0.527
12,TEN,IND,9.043,9.750,0.707,IND,IND,0.754
13,WAS,SF,6.132,10.578,4.446,SF,SF,0.772

# Frozen Preseason Scoring Ratings

Week 1's saved projection artifact contains the preseason offensive/defensive scoring ratings and personnel scoring adjustments for all 32 teams.

Those values were created before the season and are reused here as the frozen scoring prior. We do not rebuild or modify the preseason notebooks.

The new weekly offense/defense signals are added separately afterward.

In [19]:
week1_frozen = pd.read_parquet(
    WEEK1_PROJECTIONS_PATH
)

home_scoring = week1_frozen[
    [
        "home_team",
        "home_projected_off_ppg",
        "home_projected_def_ppg",
        "home_off_personnel_z",
        "home_def_personnel_z"
    ]
].rename(columns={
    "home_team": "team",
    "home_projected_off_ppg": "preseason_projected_off_ppg",
    "home_projected_def_ppg": "preseason_projected_def_ppg",
    "home_off_personnel_z": "off_personnel_z",
    "home_def_personnel_z": "def_personnel_z"
})

away_scoring = week1_frozen[
    [
        "away_team",
        "away_projected_off_ppg",
        "away_projected_def_ppg",
        "away_off_personnel_z",
        "away_def_personnel_z"
    ]
].rename(columns={
    "away_team": "team",
    "away_projected_off_ppg": "preseason_projected_off_ppg",
    "away_projected_def_ppg": "preseason_projected_def_ppg",
    "away_off_personnel_z": "off_personnel_z",
    "away_def_personnel_z": "def_personnel_z"
})

scoring_prior = (
    pd.concat([home_scoring, away_scoring], ignore_index=True)
    .groupby("team", as_index=False)
    .agg(
        preseason_projected_off_ppg=("preseason_projected_off_ppg", "mean"),
        preseason_projected_def_ppg=("preseason_projected_def_ppg", "mean"),
        off_personnel_z=("off_personnel_z", "mean"),
        def_personnel_z=("def_personnel_z", "mean")
    )
)

assert len(scoring_prior) == 32
display(scoring_prior.head())

,team,preseason_projected_off_ppg,preseason_projected_def_ppg,off_personnel_z,def_personnel_z
0,ARI,22.191473,24.425844,-0.763765,-1.345326
1,ATL,22.032425,23.261103,0.507936,0.513715
2,BAL,25.007820,22.580763,0.442967,0.969729
3,BUF,25.942602,22.289034,1.060099,0.231615
4,CAR,20.533474,23.731353,-1.506345,-0.346889

In [20]:
completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

completed_games = pd.read_parquet(
    completed_games_path
).copy()

completed_games = completed_games[
    completed_games["week"] < TARGET_WEEK
].copy()

home_scoring_actual = completed_games[
    [
        "home_team",
        "home_score",
        "away_score"
    ]
].rename(
    columns={
        "home_team": "team",
        "home_score": "points_for",
        "away_score": "points_against"
    }
)

away_scoring_actual = completed_games[
    [
        "away_team",
        "away_score",
        "home_score"
    ]
].rename(
    columns={
        "away_team": "team",
        "away_score": "points_for",
        "home_score": "points_against"
    }
)

team_scoring_actual = pd.concat(
    [
        home_scoring_actual,
        away_scoring_actual
    ],
    ignore_index=True
)

inseason_scoring = (
    team_scoring_actual
    .groupby("team", as_index=False)
    .agg(
        games_played=("points_for", "size"),
        actual_off_ppg=("points_for", "mean"),
        actual_def_ppg=("points_against", "mean")
    )
)

assert len(inseason_scoring) == 32

assert (
    inseason_scoring["games_played"] > 0
).all(), "Some teams have no completed games."

assert (
    inseason_scoring["games_played"] <= TARGET_WEEK - 1
).all(), "A team has more completed games than expected."

print("Games played distribution:")
print(
    inseason_scoring["games_played"]
    .value_counts()
    .sort_index()
)

print("\nTeams with fewer completed games:")
display(
    inseason_scoring.loc[
        inseason_scoring["games_played"] < TARGET_WEEK - 1,
        ["team", "games_played"]
    ].sort_values("games_played")
)

display(
    inseason_scoring
    .sort_values("actual_off_ppg", ascending=False)
    .round(2)
)

Games played distribution:
games_played
4     2
5    30
Name: count, dtype: int64

Teams with fewer completed games:

   team  games_played
4   CAR             4
15   KC             4

   team  games_played  actual_off_ppg  actual_def_ppg
3   BUF             5           32.80           28.20
10  DET             5           32.80           29.60
28   SF             5           30.80           18.60
4   CAR             4           30.25           27.25
15   KC             4           29.50           19.25
2   BAL             5           29.20           23.80
8   DAL             5           27.60           27.20
27  SEA             5           26.80           21.00
18   LV             5           26.40           25.80
6   CIN             5           25.60           21.80
13  IND             5           24.80           27.60
14  JAX             5           24.60           14.00
16   LA             5           23.80           24.00
5   CHI             5           23.80           19.20
1   ATL             5           23.80           24.40
22   NO             5           23.60           30.20
31  WAS             5           23.00           29.80
26  PIT             5           22.20           21.80
12  HOU             5           22.00           22.40
21   NE             5           22.00           18.80
23  NYG             5           21.80           21.20
20  MIN             5           21.80           12.80
0   ARI             5           21.60           32.40
11   GB             5           20.80           22.40
29   TB             5           20.00           22.40
9   DEN             5           19.40           22.20
7   CLE             5           18.60           22.40
24  NYJ             5           18.60           19.20
25  PHI             5           18.40           22.40
17  LAC             5           16.80           25.80
19  MIA             5           14.00           26.40
30  TEN             5           11.60           21.80

In [21]:
scoring_expectations = scoring_prior[
    [
        "team",
        "preseason_projected_off_ppg",
        "preseason_projected_def_ppg"
    ]
].copy()

home_games = completed_games[
    [
        "week",
        "home_team",
        "away_team",
        "home_score",
        "away_score"
    ]
].copy()

home_games = home_games.rename(
    columns={
        "home_team": "team",
        "away_team": "opponent",
        "home_score": "points_for",
        "away_score": "points_against"
    }
)

away_games = completed_games[
    [
        "week",
        "away_team",
        "home_team",
        "away_score",
        "home_score"
    ]
].copy()

away_games = away_games.rename(
    columns={
        "away_team": "team",
        "home_team": "opponent",
        "away_score": "points_for",
        "home_score": "points_against"
    }
)

team_games = pd.concat(
    [home_games, away_games],
    ignore_index=True
)

opponent_defense = scoring_expectations[
    [
        "team",
        "preseason_projected_def_ppg"
    ]
].rename(
    columns={
        "team": "opponent",
        "preseason_projected_def_ppg":
            "opponent_expected_def_ppg"
    }
)

opponent_offense = scoring_expectations[
    [
        "team",
        "preseason_projected_off_ppg"
    ]
].rename(
    columns={
        "team": "opponent",
        "preseason_projected_off_ppg":
            "opponent_expected_off_ppg"
    }
)

team_games = (
    team_games
    .merge(
        opponent_defense,
        on="opponent",
        how="left",
        validate="many_to_one"
    )
    .merge(
        opponent_offense,
        on="opponent",
        how="left",
        validate="many_to_one"
    )
)

league_preseason_off_ppg = (
    scoring_prior[
        "preseason_projected_off_ppg"
    ].mean()
)

league_preseason_def_ppg = (
    scoring_prior[
        "preseason_projected_def_ppg"
    ].mean()
)

team_games["adjusted_points_for"] = (
    team_games["points_for"]
    + (
        league_preseason_def_ppg
        - team_games["opponent_expected_def_ppg"]
    )
)

team_games["adjusted_points_against"] = (
    team_games["points_against"]
    + (
        league_preseason_off_ppg
        - team_games["opponent_expected_off_ppg"]
    )
)

inseason_scoring_adjusted = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_played=("points_for", "size"),
        actual_off_ppg=("points_for", "mean"),
        actual_def_ppg=("points_against", "mean"),
        adjusted_off_ppg=(
            "adjusted_points_for",
            "mean"
        ),
        adjusted_def_ppg=(
            "adjusted_points_against",
            "mean"
        )
    )
)

assert len(inseason_scoring_adjusted) == 32

display(
    inseason_scoring_adjusted[
        [
            "team",
            "actual_off_ppg",
            "adjusted_off_ppg",
            "actual_def_ppg",
            "adjusted_def_ppg"
        ]
    ]
    .sort_values(
        "adjusted_off_ppg",
        ascending=False
    )
    .round(2)
)

   team  actual_off_ppg  adjusted_off_ppg  actual_def_ppg  adjusted_def_ppg
3   BUF           32.80             33.55           28.20             27.06
10  DET           32.80             32.22           29.60             30.49
28   SF           30.80             31.08           18.60             18.03
4   CAR           30.25             30.07           27.25             27.30
15   KC           29.50             29.43           19.25             19.82
2   BAL           29.20             28.39           23.80             24.27
8   DAL           27.60             27.51           27.20             26.98
18   LV           26.40             27.02           25.80             26.38
27  SEA           26.80             26.67           21.00             20.90
6   CIN           25.60             25.97           21.80             21.63
13  IND           24.80             25.27           27.60             27.35
14  JAX           24.60             24.92           14.00             14.09
16   LA           23.80             24.30           24.00             23.23
1   ATL           23.80             23.99           24.40             24.76
5   CHI           23.80             23.94           19.20             20.07
22   NO           23.60             23.68           30.20             30.13
31  WAS           23.00             22.83           29.80             29.05
21   NE           22.00             22.44           18.80             18.45
0   ARI           21.60             21.92           32.40             31.55
20  MIN           21.80             21.86           12.80             12.99
26  PIT           22.20             21.84           21.80             22.00
12  HOU           22.00             21.02           22.40             21.53
23  NYG           21.80             20.70           21.20             21.13
11   GB           20.80             20.59           22.40             23.05
9   DEN           19.40             20.16           22.20             21.47
29   TB           20.00             19.68           22.40             22.44
24  NYJ           18.60             18.37           19.20             19.51
7   CLE           18.60             18.31           22.40             23.12
25  PHI           18.40             18.01           22.40             22.28
17  LAC           16.80             17.03           25.80             25.67
19  MIA           14.00             14.10           26.40             26.86
30  TEN           11.60             11.71           21.80             22.04

In [22]:
scoring_model = scoring_prior.merge(
    inseason_scoring_adjusted,
    on="team",
    how="left",
    validate="one_to_one"
)

PRESEASON_EQUIVALENT_GAMES = 5.0

scoring_model["preseason_weight"] = (
    PRESEASON_EQUIVALENT_GAMES
    / (
        PRESEASON_EQUIVALENT_GAMES
        + scoring_model["games_played"]
    )
)

scoring_model["inseason_weight"] = (
    1.0
    - scoring_model["preseason_weight"]
)

scoring_model["current_off_ppg"] = (
    scoring_model["preseason_weight"]
    * scoring_model["preseason_projected_off_ppg"]
    +
    scoring_model["inseason_weight"]
    * scoring_model["adjusted_off_ppg"]
)

scoring_model["current_def_ppg"] = (
    scoring_model["preseason_weight"]
    * scoring_model["preseason_projected_def_ppg"]
    +
    scoring_model["inseason_weight"]
    * scoring_model["adjusted_def_ppg"]
)

assert len(scoring_model) == 32

assert scoring_model[
    [
        "current_off_ppg",
        "current_def_ppg"
    ]
].notna().all().all()

display(
    scoring_model[
        [
            "team",
            "preseason_projected_off_ppg",
            "adjusted_off_ppg",
            "current_off_ppg",
            "preseason_projected_def_ppg",
            "adjusted_def_ppg",
            "current_def_ppg",
            "preseason_weight",
            "inseason_weight"
        ]
    ]
    .sort_values(
        "current_off_ppg",
        ascending=False
    )
    .round(2)
)

,team,preseason_projected_off_ppg,adjusted_off_ppg,current_off_ppg,preseason_projected_def_ppg,adjusted_def_ppg,current_def_ppg,preseason_weight,inseason_weight
3,BUF,25.94,33.55,29.75,22.29,27.06,24.67,0.50,0.50
10,DET,26.28,32.22,29.25,23.05,30.49,26.77,0.50,0.50
28,SF,24.31,31.08,27.69,22.70,18.03,20.36,0.50,0.50
2,BAL,25.01,28.39,26.70,22.58,24.27,23.43,0.50,0.50
8,DAL,24.71,27.51,26.11,24.75,26.98,25.87,0.50,0.50
27,SEA,24.46,26.67,25.57,21.63,20.90,21.27,0.50,0.50
15,KC,22.39,29.43,25.52,21.52,19.82,20.77,0.56,0.44
6,CIN,23.96,25.97,24.97,24.55,21.63,23.09,0.50,0.50
13,IND,24.31,25.27,24.79,23.56,27.35,25.45,0.50,0.50
4,CAR,20.53,30.07,24.77,23.73,27.30,25.32,0.56,0.44
16,LA,25.21,24.30,24.76,22.35,23.23,22.79,0.50,0.50
14,JAX,23.95,24.92,24.43,22.47,14.09,18.28,0.50,0.50
5,CHI,23.20,23.94,23.57,23.18,20.07,21.62,0.50,0.50
18,LV,19.47,27.02,23.24,23.59,26.38,24.99,0.50,0.50
1,ATL,22.03,23.99,23.01,23.26,24.76,24.01,0.50,0.50
21,NE,23.37,22.44,22.91,22.15,18.45,20.30,0.50,0.50
31,WAS,22.84,22.83,22.84,24.21,29.05,26.63,0.50,0.50
22,NO,21.17,23.68,22.42,22.74,30.13,26.43,0.50,0.50
26,PIT,22.68,21.84,22.26,22.50,22.00,22.25,0.50,0.50
20,MIN,22.30,21.86,22.08,21.84,12.99,17.42,0.50,0.50
11,GB,23.53,20.59,22.06,22.19,23.05,22.62,0.50,0.50
0,ARI,22.19,21.92,22.06,24.43,31.55,27.99,0.50,0.50
12,HOU,23.08,21.02,22.05,21.53,21.53,21.53,0.50,0.50
9,DEN,23.33,20.16,21.74,21.61,21.47,21.54,0.50,0.50
29,TB,23.49,19.68,21.58,23.03,22.44,22.73,0.50,0.50
23,NYG,21.42,20.70,21.06,23.82,21.13,22.48,0.50,0.50
25,PHI,23.56,18.01,20.78,21.79,22.28,22.04,0.50,0.50
17,LAC,22.51,17.03,19.77,21.88,25.67,23.77,0.50,0.50
24,NYJ,20.46,18.37,19.41,24.43,19.51,21.97,0.50,0.50
7,CLE,20.05,18.31,19.18,23.00,23.12,23.06,0.50,0.50
19,MIA,22.38,14.10,18.24,23.30,26.86,25.08,0.50,0.50
30,TEN,20.13,11.71,15.92,24.45,22.04,23.25,0.50,0.50

# Weekly Scoring Update

The in-season offensive and defensive adjustments from Notebook 04 are already shrunk for sample size.

They are added to the frozen scoring prior:

- positive offensive adjustment raises expected scoring
- positive defensive adjustment represents points saved, so it lowers projected points allowed

This keeps the Week 1 scoring evidence separate and interpretable.

In [23]:
scoring_update = scoring_model[
    [
        "team",
        "current_off_ppg",
        "current_def_ppg"
    ]
].copy()

assert len(scoring_update) == 32
assert scoring_update["team"].nunique() == 32

display(
    scoring_update
    .sort_values(
        "current_off_ppg",
        ascending=False
    )
    .round(2)
)

   team  current_off_ppg  current_def_ppg
3   BUF            29.75            24.67
10  DET            29.25            26.77
28   SF            27.69            20.36
2   BAL            26.70            23.43
8   DAL            26.11            25.87
27  SEA            25.57            21.27
15   KC            25.52            20.77
6   CIN            24.97            23.09
13  IND            24.79            25.45
4   CAR            24.77            25.32
16   LA            24.76            22.79
14  JAX            24.43            18.28
5   CHI            23.57            21.62
18   LV            23.24            24.99
1   ATL            23.01            24.01
21   NE            22.91            20.30
31  WAS            22.84            26.63
22   NO            22.42            26.43
26  PIT            22.26            22.25
20  MIN            22.08            17.42
11   GB            22.06            22.62
0   ARI            22.06            27.99
12  HOU            22.05            21.53
9   DEN            21.74            21.54
29   TB            21.58            22.73
23  NYG            21.06            22.48
25  PHI            20.78            22.04
17  LAC            19.77            23.77
24  NYJ            19.41            21.97
7   CLE            19.18            23.06
19  MIA            18.24            25.08
30  TEN            15.92            23.25

# Weekly Projected Total

The matchup total uses the same basic preseason scoring concept: each offense is paired with the opposing defense.

Because the weekly offense/defense inputs are already heavily shrunk, no additional Week 1 multiplier is applied here.

The final projected scores are forced to satisfy both:

- projected score difference = weekly expected margin
- projected score sum = weekly projected total

In [24]:
home_scoring_update = scoring_update.rename(
    columns={
        "team": "home_team",
        "current_off_ppg":
            "home_current_off_ppg",
        "current_def_ppg":
            "home_current_def_ppg"
    }
)

away_scoring_update = scoring_update.rename(
    columns={
        "team": "away_team",
        "current_off_ppg":
            "away_current_off_ppg",
        "current_def_ppg":
            "away_current_def_ppg"
    }
)

In [25]:
games = (
    games
    .merge(
        home_scoring_update,
        on="home_team",
        how="left",
        validate="many_to_one"
    )
    .merge(
        away_scoring_update,
        on="away_team",
        how="left",
        validate="many_to_one"
    )
)

required_scoring_columns = [
    "home_current_off_ppg",
    "home_current_def_ppg",
    "away_current_off_ppg",
    "away_current_def_ppg"
]

assert games[
    required_scoring_columns
].notna().all().all()

games["raw_home_score"] = (
    games["home_current_off_ppg"]
    + games["away_current_def_ppg"]
) / 2

games["raw_away_score"] = (
    games["away_current_off_ppg"]
    + games["home_current_def_ppg"]
) / 2

games["projected_total"] = (
    games["raw_home_score"]
    + games["raw_away_score"]
)

games["projected_home_score"] = (
    games["projected_total"]
    + games["expected_home_margin"]
) / 2

games["projected_away_score"] = (
    games["projected_total"]
    - games["expected_home_margin"]
) / 2


assert games["projected_total"].notna().all()

assert np.allclose(
    games["projected_home_score"]
    - games["projected_away_score"],
    games["expected_home_margin"]
)

assert np.allclose(
    games["projected_home_score"]
    + games["projected_away_score"],
    games["projected_total"]
)


display(
    games[
        [
            "away_team",
            "home_team",
            "away_current_off_ppg",
            "home_current_def_ppg",
            "home_current_off_ppg",
            "away_current_def_ppg",
            "projected_away_score",
            "projected_home_score",
            "projected_total",
            "expected_home_margin"
        ]
    ].round(2)
)

,away_team,home_team,away_current_off_ppg,home_current_def_ppg,home_current_off_ppg,away_current_def_ppg,projected_away_score,projected_home_score,projected_total,expected_home_margin
0,SEA,DEN,25.57,21.54,21.74,21.27,22.30,22.76,45.06,0.47
1,ARI,LA,22.06,22.79,24.76,27.99,18.89,29.91,48.80,11.02
2,BAL,CLE,26.70,23.06,19.18,23.43,25.90,20.29,46.19,-5.61
3,BUF,LV,29.75,24.99,23.24,24.67,29.08,22.24,51.32,-6.85
4,CAR,PHI,24.77,22.04,20.78,25.32,21.00,25.46,46.46,4.46
5,CHI,ATL,23.57,24.01,23.01,21.62,23.02,23.09,46.11,0.07
6,DAL,GB,26.11,22.62,22.06,25.87,22.53,25.80,48.33,3.26
7,HOU,JAX,22.05,18.28,24.43,21.53,20.40,22.75,43.15,2.34
8,LAC,KC,19.77,20.77,25.52,23.77,18.44,26.47,44.92,8.03
9,NO,NYG,22.42,22.48,21.06,26.43,22.07,24.13,46.20,2.06
10,NYJ,NE,19.41,20.30,22.91,21.97,16.16,26.13,42.29,9.97
11,PIT,TB,22.26,22.73,21.58,22.25,21.72,22.69,44.41,0.97
12,TEN,IND,15.92,25.45,24.79,23.25,17.48,27.23,44.71,9.75
13,WAS,SF,22.84,20.36,27.69,26.63,19.09,29.67,48.76,10.58

# Market Comparison

nflverse uses positive `spread_line` for a home favorite and negative for an away favorite. The values below are converted to standard sportsbook notation.

Market information is used only after the model projections have been completed.

In [26]:
games["home_spread"] = -games["spread_line"]
games["away_spread"] = games["spread_line"]

games["model_home_spread"] = -games["expected_home_margin"]
games["model_away_spread"] = games["expected_home_margin"]

games["home_ats_edge"] = (
    games["home_spread"]
    - games["model_home_spread"]
)

games["away_ats_edge"] = (
    games["away_spread"]
    - games["model_away_spread"]
)

games["ats_pick"] = np.where(
    games["home_ats_edge"] > games["away_ats_edge"],
    games["home_team"],
    np.where(
        games["away_ats_edge"] > games["home_ats_edge"],
        games["away_team"],
        "PUSH"
    )
)

games["ats_difference"] = (
    games[["home_ats_edge", "away_ats_edge"]]
    .max(axis=1)
)

games["total_difference_signed"] = (
    games["projected_total"]
    - games["total_line"]
)

games["total_difference"] = (
    games["total_difference_signed"].abs()
)

games["total_pick"] = np.where(
    games["total_difference_signed"] > 0,
    "OVER",
    np.where(
        games["total_difference_signed"] < 0,
        "UNDER",
        "PUSH"
    )
)

## Unit Sizing

Unit sizes are assigned from the model's edge over the market.

ATS and totals use separate thresholds because the totals model is newer and requires a larger edge before qualifying as a play.

These units do not change any projections or picks. They provide a consistent way to track performance by model confidence.

In [27]:
def assign_ats_units(edge):
    if pd.isna(edge) or edge < 1.0:
        return 0.0
    elif edge < 2.0:
        return 0.5
    elif edge < 3.0:
        return 1.0
    elif edge < 4.0:
        return 1.5
    else:
        return 2.0


def assign_total_units(edge):
    if pd.isna(edge) or edge < 2.0:
        return 0.0
    elif edge < 3.5:
        return 0.5
    elif edge < 5.0:
        return 1.0
    elif edge < 7.0:
        return 1.5
    else:
        return 2.0


games["ats_units"] = games["ats_difference"].apply(assign_ats_units)

games["total_units"] = games["total_difference"].apply(assign_total_units)


games[
    [
        "away_team",
        "home_team",
        "ats_pick",
        "ats_difference",
        "ats_units",
        "total_pick",
        "total_difference",
        "total_units"
    ]
]

,away_team,home_team,ats_pick,ats_difference,ats_units,total_pick,total_difference,total_units
0,SEA,DEN,DEN,2.965023,1.0,OVER,4.556676,1.0
1,ARI,LA,ARI,2.479195,1.0,UNDER,3.702688,1.0
2,BAL,CLE,BAL,1.111118,0.5,OVER,5.685118,1.5
3,BUF,LV,BUF,0.845063,0.0,UNDER,2.176375,0.5
4,CAR,PHI,PHI,2.961155,1.0,OVER,4.955844,1.0
5,CHI,ATL,ATL,3.072264,1.5,UNDER,3.390844,0.5
6,DAL,GB,GB,1.764660,0.5,UNDER,4.172820,1.0
7,HOU,JAX,HOU,0.655284,0.0,OVER,0.648537,0.0
8,LAC,KC,LAC,0.466820,0.0,OVER,2.415489,0.5
9,NO,NYG,NYG,0.561493,0.0,OVER,0.696742,0.0
10,NYJ,NE,NE,2.471148,1.0,UNDER,1.208236,0.0
11,PIT,TB,TB,3.968852,1.5,OVER,3.912424,1.0
12,TEN,IND,IND,2.749648,1.0,OVER,0.206559,0.0
13,WAS,SF,SF,3.078136,1.5,UNDER,1.737840,0.0

# Display Helpers

In [28]:
def format_spread(team, line):
    if pd.isna(line):
        return "N/A"
    if line > 0:
        return f"{team} +{line:.1f}"
    return f"{team} {line:.1f}"

def model_spread_display(row):
    if row["model_home_spread"] < 0:
        return format_spread(row["home_team"], row["model_home_spread"])
    if row["model_away_spread"] < 0:
        return format_spread(row["away_team"], row["model_away_spread"])
    return "PICK"

def market_spread_display(row):
    if pd.isna(row["spread_line"]):
        return "N/A"
    if row["home_spread"] < 0:
        return format_spread(row["home_team"], row["home_spread"])
    if row["away_spread"] < 0:
        return format_spread(row["away_team"], row["away_spread"])
    return "PICK"

def ats_pick_display(row):
    if row["ats_pick"] == "PUSH":
        return "PUSH"
    if row["ats_pick"] == row["home_team"]:
        return format_spread(row["home_team"], row["home_spread"])
    return format_spread(row["away_team"], row["away_spread"])

games["projected_score"] = (
    games["away_team"]
    + " "
    + games["projected_away_score"].round(1).astype(str)
    + " - "
    + games["home_team"]
    + " "
    + games["projected_home_score"].round(1).astype(str)
)

games["model_spread_display"] = games.apply(
    model_spread_display, axis=1
)

games["market_spread_display"] = games.apply(
    market_spread_display, axis=1
)

games["ats_pick_display"] = games.apply(
    ats_pick_display, axis=1
)

# Final Week Projection Board

In [29]:
projection_board = pd.DataFrame({
    "Matchup": games["away_team"] + " @ " + games["home_team"],
    "Projected Score": games["projected_score"],
    "SU Pick": games["predicted_winner"],
    "Win Prob": games["predicted_win_probability"],
    "Model Spread": games["model_spread_display"],
    "Market Spread": games["market_spread_display"],
    "ATS Pick": games["ats_pick_display"],
    "ATS Diff": games["ats_difference"],
    "ATS Units": games["ats_units"].map(lambda x: f"{x:.1f}"),
    "Model Total": games["projected_total"],
    "Market Total": games["total_line"],
    "O/U Pick": games["total_pick"],
    "Total Diff": games["total_difference"],
    "Total Units": games["total_units"].map(lambda x: f"{x:.1f}"),
    "Preseason Margin": games["preseason_expected_home_margin"],
    "Weekly Margin": games["expected_home_margin"],
    "Margin Change": games["margin_change_from_preseason"]
})

display(
    projection_board.style.format({
        "Win Prob": "{:.3f}",
        "ATS Diff": "{:.2f}",
        "Model Total": "{:.1f}",
        "Market Total": "{:.1f}",
        "Total Diff": "{:.1f}",
        "Preseason Margin": "{:.2f}",
        "Weekly Margin": "{:.2f}",
        "Margin Change": "{:+.2f}"
    }).hide(axis="index")
)

# Biggest Model vs Market Differences

In [30]:
biggest_ats_differences = (
    projection_board[
        [
            "Matchup",
            "Projected Score",
            "Model Spread",
            "Market Spread",
            "ATS Pick",
            "ATS Diff"
        ]
    ]
    .sort_values("ATS Diff", ascending=False)
    .head(5)
    .copy()
)

biggest_total_differences = (
    projection_board[
        [
            "Matchup",
            "Projected Score",
            "Model Total",
            "Market Total",
            "O/U Pick",
            "Total Diff"
        ]
    ]
    .sort_values("Total Diff", ascending=False)
    .head(5)
    .copy()
)

print("BIGGEST ATS DIFFERENCES")
display(biggest_ats_differences.round(2))

print()
print("BIGGEST TOTAL DIFFERENCES")
display(biggest_total_differences.round(2))

BIGGEST ATS DIFFERENCES

,Matchup,Projected Score,Model Spread,Market Spread,ATS Pick,ATS Diff
11,PIT @ TB,PIT 21.7 - TB 22.7,TB -1.0,PIT -3.0,TB +3.0,3.97
13,WAS @ SF,WAS 19.1 - SF 29.7,SF -10.6,SF -7.5,SF -7.5,3.08
5,CHI @ ATL,CHI 23.0 - ATL 23.1,ATL -0.1,CHI -3.0,ATL +3.0,3.07
0,SEA @ DEN,SEA 22.3 - DEN 22.8,DEN -0.5,SEA -2.5,DEN +2.5,2.97
4,CAR @ PHI,CAR 21.0 - PHI 25.5,PHI -4.5,PHI -1.5,PHI -1.5,2.96

BIGGEST TOTAL DIFFERENCES

,Matchup,Projected Score,Model Total,Market Total,O/U Pick,Total Diff
2,BAL @ CLE,BAL 25.9 - CLE 20.3,46.19,40.5,OVER,5.69
4,CAR @ PHI,CAR 21.0 - PHI 25.5,46.46,41.5,OVER,4.96
0,SEA @ DEN,SEA 22.3 - DEN 22.8,45.06,40.5,OVER,4.56
6,DAL @ GB,DAL 22.5 - GB 25.8,48.33,52.5,UNDER,4.17
11,PIT @ TB,PIT 21.7 - TB 22.7,44.41,40.5,OVER,3.91

In [31]:
biggest_ats_differences["ATS Diff"] = (
    biggest_ats_differences["ATS Diff"].round(2)
)

biggest_total_differences["Model Total"] = (
    biggest_total_differences["Model Total"].round(1)
)

biggest_total_differences["Market Total"] = (
    biggest_total_differences["Market Total"].round(1)
)

biggest_total_differences["Total Diff"] = (
    biggest_total_differences["Total Diff"].round(1)
)

# Biggest Changes from the Preseason Projection

This is one of the most important weekly diagnostics. It shows which games changed most because of new in season information.

In [32]:
biggest_projection_changes = (
    projection_board[
        [
            "Matchup",
            "Preseason Margin",
            "Weekly Margin",
            "Margin Change",
            "SU Pick",
            "Win Prob"
        ]
    ]
    .assign(
        Absolute_Change=lambda x: x["Margin Change"].abs()
    )
    .sort_values("Absolute_Change", ascending=False)
    .drop(columns="Absolute_Change")
)

display(biggest_projection_changes.round(3))

,Matchup,Preseason Margin,Weekly Margin,Margin Change,SU Pick,Win Prob
8,LAC @ KC,3.422,8.033,4.611,KC,0.714
13,WAS @ SF,6.132,10.578,4.446,SF,0.772
7,HOU @ JAX,-1.097,2.345,3.442,JAX,0.566
4,CAR @ PHI,7.482,4.461,-3.021,PHI,0.623
9,NO @ NYG,-0.136,2.061,2.198,NYG,0.558
3,BUF @ LV,-8.565,-6.845,1.720,BUF,0.685
11,PIT @ TB,2.364,0.969,-1.395,TB,0.527
1,ARI @ LA,10.023,11.021,0.998,LA,0.781
6,DAL @ GB,4.143,3.265,-0.879,GB,0.591
12,TEN @ IND,9.043,9.750,0.707,IND,0.754
0,SEA @ DEN,0.970,0.465,-0.505,DEN,0.513
5,CHI @ ATL,0.484,0.072,-0.412,ATL,0.502
10,NYJ @ NE,9.607,9.971,0.364,NE,0.759
2,BAL @ CLE,-5.461,-5.611,-0.150,BAL,0.654

In [33]:
biggest_projection_changes["Preseason Margin"] = (
    biggest_projection_changes["Preseason Margin"].round(2)
)

biggest_projection_changes["Weekly Margin"] = (
    biggest_projection_changes["Weekly Margin"].round(2)
)

biggest_projection_changes["Margin Change"] = (
    biggest_projection_changes["Margin Change"].round(2)
)

biggest_projection_changes["Win Prob"] = (
    biggest_projection_changes["Win Prob"].round(3)
)

# Sanity Checks

In [34]:
assert len(games) == len(target_schedule)
assert games["weekly_neutral_strength_diff"].notna().all()
assert games["expected_home_margin"].notna().all()
assert games["predicted_win_probability"].between(0.5, 1.0).all()
assert games["projected_total"].notna().all()

score_margin_check = (
    games["projected_home_score"]
    - games["projected_away_score"]
)

score_total_check = (
    games["projected_home_score"]
    + games["projected_away_score"]
)

assert np.allclose(
    score_margin_check,
    games["expected_home_margin"]
)

assert np.allclose(
    score_total_check,
    games["projected_total"]
)

print("All weekly game prediction sanity checks passed.")

All weekly game prediction sanity checks passed.

# Save Week Outputs

Everything is written only to the weekly layer.

The detailed parquet preserves all modeling fields for later evaluation. The CSV files provide the clean weekly projection board and largest model versus market differences.

In [35]:
detailed_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_projections.parquet"
)

current_games = games.copy()

if detailed_path.exists():

    previous_games = pd.read_parquet(
        detailed_path
    )

    current_game_ids = set(
        current_games["game_id"]
    )

    frozen_games = previous_games[
        ~previous_games["game_id"].isin(
            current_game_ids
        )
    ].copy()

    detailed_save = pd.concat(
        [
            frozen_games,
            current_games
        ],
        ignore_index=True
    )

else:

    detailed_save = current_games.copy()


detailed_save.to_parquet(
    detailed_path,
    index=False
)

projection_save = projection_board.copy()

projection_save["ATS Units"] = games["ats_units"].values
projection_save["Total Units"] = games["total_units"].values

projection_save["Win Prob"] = (
    projection_save["Win Prob"].round(3)
)

projection_save["ATS Diff"] = (
    projection_save["ATS Diff"].round(2)
)

projection_save["ATS Units"] = (
    projection_save["ATS Units"].round(1)
)

projection_save["Model Total"] = (
    projection_save["Model Total"].round(1)
)

projection_save["Market Total"] = (
    projection_save["Market Total"].round(1)
)

projection_save["Total Diff"] = (
    projection_save["Total Diff"].round(1)
)

projection_save["Total Units"] = (
    projection_save["Total Units"].round(1)
)

projection_save["Preseason Margin"] = (
    projection_save["Preseason Margin"].round(2)
)

projection_save["Weekly Margin"] = (
    projection_save["Weekly Margin"].round(2)
)

projection_save["Margin Change"] = (
    projection_save["Margin Change"].round(2)
)

projection_csv_path = (
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_projections.csv"
)

if projection_csv_path.exists():

    previous_projections = pd.read_csv(
        projection_csv_path
    )

    current_matchups = set(
        projection_save["Matchup"]
    )

    frozen_projections = previous_projections[
        ~previous_projections["Matchup"].isin(
            current_matchups
        )
    ].copy()

    projection_save = pd.concat(
        [
            frozen_projections,
            projection_save
        ],
        ignore_index=True
    )

projection_save.to_csv(
    projection_csv_path,
    index=False
)

biggest_ats_differences.to_csv(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_ats_differences.csv",
    index=False
)

biggest_total_differences.to_csv(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_total_differences.csv",
    index=False
)

biggest_projection_changes.to_csv(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_projection_changes.csv",
    index=False
)


print("Saved:")
print(detailed_path)
print(projection_csv_path)

print(
    f"\nTotal saved Week {TARGET_WEEK} projections: "
    f"{len(projection_save)}"
)

print(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_ats_differences.csv"
)

print(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_total_differences.csv"
)

print(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_projection_changes.csv"
)

Saved:
..\..\data\processed\weekly\week_06_projections.parquet
..\..\weekly_projections\outputs\week_06\week_06_projections.csv

Total saved Week 6 projections: 14
..\..\weekly_projections\outputs\week_06\week_06_biggest_ats_differences.csv
..\..\weekly_projections\outputs\week_06\week_06_biggest_total_differences.csv
..\..\weekly_projections\outputs\week_06\week_06_biggest_projection_changes.csv

# Weekly Pipeline

For each future week, the intended order is:

`02_Weekly_Data_Update`  
→ `03_Inseason_Feature_Engineering`  
→ `04_Weekly_Team_Strength`  
→ `06_Week2_Projections`

The original preseason notebooks remain frozen throughout the season.

The next notebook will be `06_Weekly_Evaluation.ipynb`, which will compare locked weekly predictions against actual results after each week is complete.