# 06 — Week 2 Projections

This notebook converts the updated weekly team-strength ratings into game level projections for the selected target week.

The original preseason notebooks and preseason projections remain frozen.

For each target week matchup, this notebook:

- loads the updated weekly team strengths from Notebook 04
- preserves the original preseason Week 2 projection as a baseline
- recalculates expected margin using weekly strength, historical home field advantage, and rest
- converts expected margin into win probability using historical NFL margin variability
- carries forward the frozen preseason scoring baseline created for Week 1
- adds the new in season offensive and defensive scoring evidence
- produces projected scores, model spreads, ATS comparisons, totals comparisons, and final output tables
- saves all outputs only inside the weekly layer

The market is used only for comparison. It never enters the model projection itself.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import polars as pl
from scipy.stats import norm
from sklearn.linear_model import LinearRegression

## Paths and Weekly Settings

For Week 2, `TARGET_WEEK = 2`.

Future weeks use the same notebook by changing the target week after the preceding weekly notebooks have been rerun.

In [2]:
PROJECT_ROOT = Path("../..")

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
WEEKLY_DATA_DIR = PROCESSED_DIR / "weekly"
WEEKLY_OUTPUT_DIR = PROJECT_ROOT / "weekly_projections" / "outputs"

SEASON = 2026
TARGET_WEEK = 7

WEEK_OUTPUT_DIR = (
    WEEKLY_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}"
)

WEEK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

WEEKLY_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_sequential_team_strength.parquet"
)

INJURY_ADJUSTED_STRENGTH_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_injury_adjusted_team_strength.parquet"
)

TARGET_SCHEDULE_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_schedule.parquet"
)

PRESEASON_BASELINE_PATH = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_preseason_baseline.parquet"
)

WEEK1_PROJECTIONS_PATH = (
    WEEKLY_DATA_DIR
    / "week_01_projections.parquet"
)

# Load Weekly Inputs

Notebook 04 supplies the updated ratings. Notebook 02 supplies the target week schedule and frozen preseason comparison.

In [3]:
weekly_strength = pd.read_parquet(WEEKLY_STRENGTH_PATH)

injury_adjusted_strength = pd.read_parquet(
    INJURY_ADJUSTED_STRENGTH_PATH
)

target_schedule = pd.read_parquet(
    TARGET_SCHEDULE_PATH
)

preseason_baseline = pd.read_parquet(
    PRESEASON_BASELINE_PATH
)

target_schedule = target_schedule[
    target_schedule["home_score"].isna()
    & target_schedule["away_score"].isna()
].copy()


preseason_baseline = preseason_baseline[
    preseason_baseline["game_id"].isin(
        target_schedule["game_id"]
    )
].copy()


print(
    "Sequential weekly strengths:",
    weekly_strength.shape
)

print(
    "Injury-adjusted strengths:",
    injury_adjusted_strength.shape
)

print(
    "Remaining target-week games:",
    target_schedule.shape
)

print(
    "Frozen preseason games:",
    preseason_baseline.shape
)

assert len(weekly_strength) == 32
assert weekly_strength["team"].nunique() == 32

assert len(injury_adjusted_strength) == 32
assert injury_adjusted_strength["team"].nunique() == 32

assert len(target_schedule) == len(
    preseason_baseline
)

required_injury_columns = [
    "team",
    "weekly_team_strength",
    "injury_adjustment",
    "injury_adjusted_team_strength"
]

missing_injury_columns = [
    col
    for col in required_injury_columns
    if col not in injury_adjusted_strength.columns
]

assert not missing_injury_columns, (
    "Missing injury-adjusted columns: "
    + ", ".join(missing_injury_columns)
)


print(
    "Using sequential ratings as the pre-injury baseline "
    "and injury-adjusted ratings for Week "
    f"{TARGET_WEEK} projections."
)

Sequential weekly strengths: (32, 25)
Injury-adjusted strengths: (32, 30)
Remaining target-week games: (14, 46)
Frozen preseason games: (14, 16)
Using sequential ratings as the pre-injury baseline and injury-adjusted ratings for Week 7 projections.

### Injury adjusted game strength

For Week 2, the `home_weekly_team_strength` and `away_weekly_team_strength` values now include the conservative injury adjustment from Notebook 05.

The injury adjustment remains visible separately in the saved team strength file, so we can distinguish:

**preseason → performance update → injury update → final Week 2 rating**

# Attach Updated Team Strength

The matchup calculation is identical in structure to the original preseason game prediction model. The only change is the source of team strength:

`preseason team_strength` → `weekly_team_strength`

This isolates the in season update without changing the original model.

In [4]:
strength_lookup = injury_adjusted_strength[
    [
        "team",
        "weekly_team_strength",
        "injury_adjustment",
        "injury_adjusted_team_strength",
        "preseason_team_strength",
        "team_strength_change",
        "cumulative_offense_adjustment",
        "cumulative_defense_adjustment"
    ]
].copy()


games = target_schedule.copy()

home_lookup = strength_lookup.rename(
    columns={
        "team": "home_team",

        "weekly_team_strength":
            "home_pre_injury_team_strength",

        "injury_adjustment":
            "home_injury_adjustment",

        "injury_adjusted_team_strength":
            "home_weekly_team_strength",

        "preseason_team_strength":
            "home_preseason_team_strength",

        "team_strength_change":
            "home_strength_change",

        "cumulative_offense_adjustment":
            "home_offense_adjustment",

        "cumulative_defense_adjustment":
            "home_defense_adjustment"
    }
)

away_lookup = strength_lookup.rename(
    columns={
        "team": "away_team",

        "weekly_team_strength":
            "away_pre_injury_team_strength",

        "injury_adjustment":
            "away_injury_adjustment",

        "injury_adjusted_team_strength":
            "away_weekly_team_strength",

        "preseason_team_strength":
            "away_preseason_team_strength",

        "team_strength_change":
            "away_strength_change",

        "cumulative_offense_adjustment":
            "away_offense_adjustment",

        "cumulative_defense_adjustment":
            "away_defense_adjustment"
    }
)


games = (
    games
    .merge(
        home_lookup,
        on="home_team",
        how="left",
        validate="many_to_one"
    )
    .merge(
        away_lookup,
        on="away_team",
        how="left",
        validate="many_to_one"
    )
)

games["weekly_neutral_strength_diff"] = (
    games["home_weekly_team_strength"]
    - games["away_weekly_team_strength"]
)

games["pre_injury_neutral_strength_diff"] = (
    games["home_pre_injury_team_strength"]
    - games["away_pre_injury_team_strength"]
)


games["preseason_neutral_strength_diff"] = (
    games["home_preseason_team_strength"]
    - games["away_preseason_team_strength"]
)

assert games[
    "home_weekly_team_strength"
].notna().all()

assert games[
    "away_weekly_team_strength"
].notna().all()

assert games[
    "home_injury_adjustment"
].notna().all()

assert games[
    "away_injury_adjustment"
].notna().all()

# Home Field and Rest

These effects are recalculated using the same historical 2015–2025 methodology as the frozen preseason game prediction notebook.

They are not retuned using Week 1.

In [5]:
schedule_clean = pl.read_parquet(
    PROCESSED_DIR / "schedule_clean.parquet"
)

historical_home = (
    schedule_clean
    .filter(
        (pl.col("season") >= 2015)
        & (pl.col("season") <= 2025)
        & (pl.col("location") == "Home")
        & pl.col("result").is_not_null()
    )
)

HOME_FIELD_ADVANTAGE = (
    historical_home
    .select(pl.col("result").mean())
    .item()
)

historical_rest = (
    schedule_clean
    .filter(
        (pl.col("season") >= 2015)
        & (pl.col("season") <= 2025)
        & pl.col("result").is_not_null()
        & pl.col("home_rest").is_not_null()
        & pl.col("away_rest").is_not_null()
    )
    .select(["result", "home_rest", "away_rest", "location"])
    .to_pandas()
)

historical_rest["rest_diff"] = (
    historical_rest["home_rest"]
    - historical_rest["away_rest"]
).clip(-7, 7)

historical_rest["home_field"] = (
    historical_rest["location"] == "Home"
).astype(int)

rest_model = LinearRegression()
rest_model.fit(
    historical_rest[["home_field", "rest_diff"]],
    historical_rest["result"]
)

REST_POINT_VALUE = rest_model.coef_[1]

print("Historical HFA:", round(HOME_FIELD_ADVANTAGE, 3))
print("Rest points/day:", round(REST_POINT_VALUE, 3))

Historical HFA: 1.764
Rest points/day: 0.181

In [6]:
games["home_field_adjustment"] = np.where(
    games["location"] == "Home",
    HOME_FIELD_ADVANTAGE,
    0.0
)

games["rest_diff"] = (
    games["home_rest"]
    - games["away_rest"]
).clip(-7, 7)

games["rest_adjustment"] = (
    games["rest_diff"]
    * REST_POINT_VALUE
)

games["expected_home_margin"] = (
    games["weekly_neutral_strength_diff"]
    + games["home_field_adjustment"]
    + games["rest_adjustment"]
)

# Win Probabilities

Historical 2015–2025 game-margin variability is retained exactly as the uncertainty scale. Week 1 is not used to recalibrate probability confidence.

In [7]:
historical_margin_std = (
    schedule_clean
    .filter(
        (pl.col("season") >= 2015)
        & (pl.col("season") <= 2025)
        & pl.col("result").is_not_null()
    )
    .select(pl.col("result").std())
    .item()
)

games["home_win_probability"] = norm.cdf(
    games["expected_home_margin"]
    / historical_margin_std
)

games["away_win_probability"] = (
    1 - games["home_win_probability"]
)

games["predicted_winner"] = np.where(
    games["home_win_probability"] >= 0.50,
    games["home_team"],
    games["away_team"]
)

games["predicted_win_probability"] = np.maximum(
    games["home_win_probability"],
    games["away_win_probability"]
)

print("Historical margin SD:", round(historical_margin_std, 3))

Historical margin SD: 14.201

# Preseason vs Weekly Margin Movement

The frozen preseason Week 2 projection is attached for diagnostics only.

This makes it possible to see exactly how much the Week 1 evidence changed each Week 2 matchup.

In [8]:
preseason_compare = preseason_baseline[
    [
        "game_id",
        "expected_home_margin",
        "predicted_winner",
        "predicted_win_probability"
    ]
].rename(columns={
    "expected_home_margin": "preseason_expected_home_margin",
    "predicted_winner": "preseason_predicted_winner",
    "predicted_win_probability": "preseason_predicted_win_probability"
})

games = games.merge(
    preseason_compare,
    on="game_id",
    how="left",
    validate="one_to_one"
)

games["margin_change_from_preseason"] = (
    games["expected_home_margin"]
    - games["preseason_expected_home_margin"]
)

display(
    games[
        [
            "away_team",
            "home_team",
            "preseason_expected_home_margin",
            "expected_home_margin",
            "margin_change_from_preseason",
            "preseason_predicted_winner",
            "predicted_winner",
            "predicted_win_probability"
        ]
    ].round(3)
)

,away_team,home_team,preseason_expected_home_margin,expected_home_margin,margin_change_from_preseason,preseason_predicted_winner,predicted_winner,predicted_win_probability
0,NE,CHI,-0.199,0.019,0.218,NE,CHI,0.501
1,CIN,BAL,4.310,1.831,-2.479,BAL,BAL,0.551
2,CLE,TEN,-0.833,-1.982,-1.148,CLE,CLE,0.555
3,DEN,ARI,-6.027,-6.982,-0.955,DEN,DEN,0.689
4,GB,DET,4.513,3.717,-0.796,DET,DET,0.603
5,IND,MIN,2.973,7.819,4.846,MIN,MIN,0.709
6,KC,SEA,5.368,1.920,-3.448,SEA,SEA,0.554
7,LA,LV,-8.692,-3.847,4.846,LA,LA,0.607
8,MIA,NYJ,-2.994,1.774,4.768,MIA,NYJ,0.550
9,NYG,HOU,8.030,9.729,1.700,HOU,HOU,0.753
10,PIT,NO,-2.100,-3.222,-1.122,PIT,PIT,0.590
11,SF,ATL,-1.754,-4.463,-2.710,SF,SF,0.623
12,TB,CAR,-3.371,0.460,3.831,TB,CAR,0.513
13,DAL,PHI,4.602,0.094,-4.507,PHI,PHI,0.503

# Frozen Preseason Scoring Ratings

Week 1's saved projection artifact contains the preseason offensive/defensive scoring ratings and personnel scoring adjustments for all 32 teams.

Those values were created before the season and are reused here as the frozen scoring prior. We do not rebuild or modify the preseason notebooks.

The new weekly offense/defense signals are added separately afterward.

In [9]:
week1_frozen = pd.read_parquet(
    WEEK1_PROJECTIONS_PATH
)

home_scoring = week1_frozen[
    [
        "home_team",
        "home_projected_off_ppg",
        "home_projected_def_ppg",
        "home_off_personnel_z",
        "home_def_personnel_z"
    ]
].rename(columns={
    "home_team": "team",
    "home_projected_off_ppg": "preseason_projected_off_ppg",
    "home_projected_def_ppg": "preseason_projected_def_ppg",
    "home_off_personnel_z": "off_personnel_z",
    "home_def_personnel_z": "def_personnel_z"
})

away_scoring = week1_frozen[
    [
        "away_team",
        "away_projected_off_ppg",
        "away_projected_def_ppg",
        "away_off_personnel_z",
        "away_def_personnel_z"
    ]
].rename(columns={
    "away_team": "team",
    "away_projected_off_ppg": "preseason_projected_off_ppg",
    "away_projected_def_ppg": "preseason_projected_def_ppg",
    "away_off_personnel_z": "off_personnel_z",
    "away_def_personnel_z": "def_personnel_z"
})

scoring_prior = (
    pd.concat([home_scoring, away_scoring], ignore_index=True)
    .groupby("team", as_index=False)
    .agg(
        preseason_projected_off_ppg=("preseason_projected_off_ppg", "mean"),
        preseason_projected_def_ppg=("preseason_projected_def_ppg", "mean"),
        off_personnel_z=("off_personnel_z", "mean"),
        def_personnel_z=("def_personnel_z", "mean")
    )
)

assert len(scoring_prior) == 32
display(scoring_prior.head())

,team,preseason_projected_off_ppg,preseason_projected_def_ppg,off_personnel_z,def_personnel_z
0,ARI,22.191473,24.425844,-0.763765,-1.345326
1,ATL,22.032425,23.261103,0.507936,0.513715
2,BAL,25.007820,22.580763,0.442967,0.969729
3,BUF,25.942602,22.289034,1.060099,0.231615
4,CAR,20.533474,23.731353,-1.506345,-0.346889

In [10]:
completed_games_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_completed_games.parquet"
)

completed_games = pd.read_parquet(
    completed_games_path
).copy()

completed_games = completed_games[
    completed_games["week"] < TARGET_WEEK
].copy()

home_scoring_actual = completed_games[
    [
        "home_team",
        "home_score",
        "away_score"
    ]
].rename(
    columns={
        "home_team": "team",
        "home_score": "points_for",
        "away_score": "points_against"
    }
)

away_scoring_actual = completed_games[
    [
        "away_team",
        "away_score",
        "home_score"
    ]
].rename(
    columns={
        "away_team": "team",
        "away_score": "points_for",
        "home_score": "points_against"
    }
)

team_scoring_actual = pd.concat(
    [
        home_scoring_actual,
        away_scoring_actual
    ],
    ignore_index=True
)

inseason_scoring = (
    team_scoring_actual
    .groupby("team", as_index=False)
    .agg(
        games_played=("points_for", "size"),
        actual_off_ppg=("points_for", "mean"),
        actual_def_ppg=("points_against", "mean")
    )
)

assert len(inseason_scoring) == 32

assert (
    inseason_scoring["games_played"] > 0
).all(), "Some teams have no completed games."

assert (
    inseason_scoring["games_played"] <= TARGET_WEEK - 1
).all(), "A team has more completed games than expected."

print("Games played distribution:")
print(
    inseason_scoring["games_played"]
    .value_counts()
    .sort_index()
)

print("\nTeams with fewer completed games:")
display(
    inseason_scoring.loc[
        inseason_scoring["games_played"] < TARGET_WEEK - 1,
        ["team", "games_played"]
    ].sort_values("games_played")
)

display(
    inseason_scoring
    .sort_values("actual_off_ppg", ascending=False)
    .round(2)
)

Games played distribution:
games_played
5     6
6    26
Name: count, dtype: int64

Teams with fewer completed games:

   team  games_played
4   CAR             5
6   CIN             5
10  DET             5
15   KC             5
19  MIA             5
20  MIN             5

   team  games_played  actual_off_ppg  actual_def_ppg
3   BUF             6           32.83           28.50
10  DET             5           32.80           29.60
28   SF             6           29.50           18.33
4   CAR             5           29.20           24.60
15   KC             5           28.00           16.60
18   LV             6           27.00           27.00
2   BAL             6           26.00           22.00
14  JAX             6           25.67           17.33
6   CIN             5           25.60           21.80
22   NO             6           25.33           29.67
8   DAL             6           25.17           26.50
5   CHI             6           25.00           19.83
27  SEA             6           24.67           20.33
13  IND             6           24.00           27.33
12  HOU             6           24.00           23.83
1   ATL             6           23.67           25.50
26  PIT             6           22.83           21.33
21   NE             6           22.67           18.83
23  NYG             6           22.67           23.33
16   LA             6           22.50           23.00
31  WAS             6           22.00           28.67
20  MIN             5           21.80           12.80
11   GB             6           21.17           20.83
0   ARI             6           21.00           29.67
29   TB             6           19.83           23.00
9   DEN             6           19.00           20.83
24  NYJ             6           18.67           20.33
7   CLE             6           17.67           20.33
25  PHI             6           17.67           22.83
17  LAC             6           15.00           25.17
19  MIA             5           14.00           26.40
30  TEN             6           14.00           21.50

In [11]:
scoring_expectations = scoring_prior[
    [
        "team",
        "preseason_projected_off_ppg",
        "preseason_projected_def_ppg"
    ]
].copy()

home_games = completed_games[
    [
        "week",
        "home_team",
        "away_team",
        "home_score",
        "away_score"
    ]
].copy()

home_games = home_games.rename(
    columns={
        "home_team": "team",
        "away_team": "opponent",
        "home_score": "points_for",
        "away_score": "points_against"
    }
)

away_games = completed_games[
    [
        "week",
        "away_team",
        "home_team",
        "away_score",
        "home_score"
    ]
].copy()

away_games = away_games.rename(
    columns={
        "away_team": "team",
        "home_team": "opponent",
        "away_score": "points_for",
        "home_score": "points_against"
    }
)

team_games = pd.concat(
    [home_games, away_games],
    ignore_index=True
)

opponent_defense = scoring_expectations[
    [
        "team",
        "preseason_projected_def_ppg"
    ]
].rename(
    columns={
        "team": "opponent",
        "preseason_projected_def_ppg":
            "opponent_expected_def_ppg"
    }
)

opponent_offense = scoring_expectations[
    [
        "team",
        "preseason_projected_off_ppg"
    ]
].rename(
    columns={
        "team": "opponent",
        "preseason_projected_off_ppg":
            "opponent_expected_off_ppg"
    }
)

team_games = (
    team_games
    .merge(
        opponent_defense,
        on="opponent",
        how="left",
        validate="many_to_one"
    )
    .merge(
        opponent_offense,
        on="opponent",
        how="left",
        validate="many_to_one"
    )
)

league_preseason_off_ppg = (
    scoring_prior[
        "preseason_projected_off_ppg"
    ].mean()
)

league_preseason_def_ppg = (
    scoring_prior[
        "preseason_projected_def_ppg"
    ].mean()
)

team_games["adjusted_points_for"] = (
    team_games["points_for"]
    + (
        league_preseason_def_ppg
        - team_games["opponent_expected_def_ppg"]
    )
)

team_games["adjusted_points_against"] = (
    team_games["points_against"]
    + (
        league_preseason_off_ppg
        - team_games["opponent_expected_off_ppg"]
    )
)

inseason_scoring_adjusted = (
    team_games
    .groupby("team", as_index=False)
    .agg(
        games_played=("points_for", "size"),
        actual_off_ppg=("points_for", "mean"),
        actual_def_ppg=("points_against", "mean"),
        adjusted_off_ppg=(
            "adjusted_points_for",
            "mean"
        ),
        adjusted_def_ppg=(
            "adjusted_points_against",
            "mean"
        )
    )
)

assert len(inseason_scoring_adjusted) == 32

display(
    inseason_scoring_adjusted[
        [
            "team",
            "actual_off_ppg",
            "adjusted_off_ppg",
            "actual_def_ppg",
            "adjusted_def_ppg"
        ]
    ]
    .sort_values(
        "adjusted_off_ppg",
        ascending=False
    )
    .round(2)
)

   team  actual_off_ppg  adjusted_off_ppg  actual_def_ppg  adjusted_def_ppg
3   BUF           32.83             33.35           28.50             28.13
10  DET           32.80             32.22           29.60             30.49
28   SF           29.50             29.52           18.33             17.88
4   CAR           29.20             29.28           24.60             24.52
15   KC           28.00             28.15           16.60             17.14
18   LV           27.00             27.63           27.00             26.98
14  JAX           25.67             26.17           17.33             17.39
6   CIN           25.60             25.97           21.80             21.63
2   BAL           26.00             25.31           22.00             22.88
22   NO           25.33             25.25           29.67             29.86
8   DAL           25.17             25.21           26.50             26.22
5   CHI           25.00             25.07           19.83             20.71
27  SEA           24.67             24.78           20.33             20.19
13  IND           24.00             24.14           27.33             27.59
1   ATL           23.67             23.79           25.50             25.76
12  HOU           24.00             23.26           23.83             22.94
21   NE           22.67             22.79           18.83             18.95
16   LA           22.50             22.67           23.00             22.49
26  PIT           22.83             22.52           21.33             21.41
31  WAS           22.00             21.90           28.67             27.82
20  MIN           21.80             21.86           12.80             12.99
23  NYG           22.67             21.79           23.33             23.57
0   ARI           21.00             21.37           29.67             28.58
11   GB           21.17             20.69           20.83             21.08
9   DEN           19.00             19.85           20.83             19.97
29   TB           19.83             19.64           23.00             23.07
24  NYJ           18.67             18.61           20.33             20.52
7   CLE           17.67             17.48           20.33             20.59
25  PHI           17.67             17.21           22.83             23.13
17  LAC           15.00             15.43           25.17             25.15
19  MIA           14.00             14.10           26.40             26.86
30  TEN           14.00             13.99           21.50             21.47

In [12]:
scoring_model = scoring_prior.merge(
    inseason_scoring_adjusted,
    on="team",
    how="left",
    validate="one_to_one"
)

PRESEASON_EQUIVALENT_GAMES = 5.0

scoring_model["preseason_weight"] = (
    PRESEASON_EQUIVALENT_GAMES
    / (
        PRESEASON_EQUIVALENT_GAMES
        + scoring_model["games_played"]
    )
)

scoring_model["inseason_weight"] = (
    1.0
    - scoring_model["preseason_weight"]
)

scoring_model["current_off_ppg"] = (
    scoring_model["preseason_weight"]
    * scoring_model["preseason_projected_off_ppg"]
    +
    scoring_model["inseason_weight"]
    * scoring_model["adjusted_off_ppg"]
)

scoring_model["current_def_ppg"] = (
    scoring_model["preseason_weight"]
    * scoring_model["preseason_projected_def_ppg"]
    +
    scoring_model["inseason_weight"]
    * scoring_model["adjusted_def_ppg"]
)

assert len(scoring_model) == 32

assert scoring_model[
    [
        "current_off_ppg",
        "current_def_ppg"
    ]
].notna().all().all()

display(
    scoring_model[
        [
            "team",
            "preseason_projected_off_ppg",
            "adjusted_off_ppg",
            "current_off_ppg",
            "preseason_projected_def_ppg",
            "adjusted_def_ppg",
            "current_def_ppg",
            "preseason_weight",
            "inseason_weight"
        ]
    ]
    .sort_values(
        "current_off_ppg",
        ascending=False
    )
    .round(2)
)

,team,preseason_projected_off_ppg,adjusted_off_ppg,current_off_ppg,preseason_projected_def_ppg,adjusted_def_ppg,current_def_ppg,preseason_weight,inseason_weight
3,BUF,25.94,33.35,29.98,22.29,28.13,25.47,0.45,0.55
10,DET,26.28,32.22,29.25,23.05,30.49,26.77,0.50,0.50
28,SF,24.31,29.52,27.15,22.70,17.88,20.07,0.45,0.55
15,KC,22.39,28.15,25.27,21.52,17.14,19.33,0.50,0.50
2,BAL,25.01,25.31,25.17,22.58,22.88,22.74,0.45,0.55
14,JAX,23.95,26.17,25.16,22.47,17.39,19.70,0.45,0.55
8,DAL,24.71,25.21,24.98,24.75,26.22,25.55,0.45,0.55
6,CIN,23.96,25.97,24.97,24.55,21.63,23.09,0.50,0.50
4,CAR,20.53,29.28,24.91,23.73,24.52,24.13,0.50,0.50
27,SEA,24.46,24.78,24.64,21.63,20.19,20.84,0.45,0.55
13,IND,24.31,24.14,24.22,23.56,27.59,25.76,0.45,0.55
5,CHI,23.20,25.07,24.22,23.18,20.71,21.83,0.45,0.55
18,LV,19.47,27.63,23.92,23.59,26.98,25.44,0.45,0.55
16,LA,25.21,22.67,23.82,22.35,22.49,22.43,0.45,0.55
22,NO,21.17,25.25,23.39,22.74,29.86,26.62,0.45,0.55
12,HOU,23.08,23.26,23.18,21.53,22.94,22.30,0.45,0.55
21,NE,23.37,22.79,23.05,22.15,18.95,20.41,0.45,0.55
1,ATL,22.03,23.79,22.99,23.26,25.76,24.62,0.45,0.55
26,PIT,22.68,22.52,22.59,22.50,21.41,21.91,0.45,0.55
31,WAS,22.84,21.90,22.33,24.21,27.82,26.18,0.45,0.55
20,MIN,22.30,21.86,22.08,21.84,12.99,17.42,0.50,0.50
11,GB,23.53,20.69,21.98,22.19,21.08,21.58,0.45,0.55
0,ARI,22.19,21.37,21.74,24.43,28.58,26.69,0.45,0.55
23,NYG,21.42,21.79,21.62,23.82,23.57,23.69,0.45,0.55
9,DEN,23.33,19.85,21.43,21.61,19.97,20.72,0.45,0.55
29,TB,23.49,19.64,21.39,23.03,23.07,23.05,0.45,0.55
25,PHI,23.56,17.21,20.10,21.79,23.13,22.53,0.45,0.55
24,NYJ,20.46,18.61,19.45,24.43,20.52,22.30,0.45,0.55
7,CLE,20.05,17.48,18.65,23.00,20.59,21.69,0.45,0.55
17,LAC,22.51,15.43,18.65,21.88,25.15,23.66,0.45,0.55
19,MIA,22.38,14.10,18.24,23.30,26.86,25.08,0.50,0.50
30,TEN,20.13,13.99,16.78,24.45,21.47,22.83,0.45,0.55

# Weekly Scoring Update

The in-season offensive and defensive adjustments from Notebook 04 are already shrunk for sample size.

They are added to the frozen scoring prior:

- positive offensive adjustment raises expected scoring
- positive defensive adjustment represents points saved, so it lowers projected points allowed

This keeps the Week 1 scoring evidence separate and interpretable.

In [13]:
scoring_update = scoring_model[
    [
        "team",
        "current_off_ppg",
        "current_def_ppg"
    ]
].copy()

assert len(scoring_update) == 32
assert scoring_update["team"].nunique() == 32

display(
    scoring_update
    .sort_values(
        "current_off_ppg",
        ascending=False
    )
    .round(2)
)

   team  current_off_ppg  current_def_ppg
3   BUF            29.98            25.47
10  DET            29.25            26.77
28   SF            27.15            20.07
15   KC            25.27            19.33
2   BAL            25.17            22.74
14  JAX            25.16            19.70
8   DAL            24.98            25.55
6   CIN            24.97            23.09
4   CAR            24.91            24.13
27  SEA            24.64            20.84
13  IND            24.22            25.76
5   CHI            24.22            21.83
18   LV            23.92            25.44
16   LA            23.82            22.43
22   NO            23.39            26.62
12  HOU            23.18            22.30
21   NE            23.05            20.41
1   ATL            22.99            24.62
26  PIT            22.59            21.91
31  WAS            22.33            26.18
20  MIN            22.08            17.42
11   GB            21.98            21.58
0   ARI            21.74            26.69
23  NYG            21.62            23.69
9   DEN            21.43            20.72
29   TB            21.39            23.05
25  PHI            20.10            22.53
24  NYJ            19.45            22.30
7   CLE            18.65            21.69
17  LAC            18.65            23.66
19  MIA            18.24            25.08
30  TEN            16.78            22.83

# Weekly Projected Total

The matchup total uses the same basic preseason scoring concept: each offense is paired with the opposing defense.

Because the weekly offense/defense inputs are already heavily shrunk, no additional Week 1 multiplier is applied here.

The final projected scores are forced to satisfy both:

- projected score difference = weekly expected margin
- projected score sum = weekly projected total

In [14]:
home_scoring_update = scoring_update.rename(
    columns={
        "team": "home_team",
        "current_off_ppg":
            "home_current_off_ppg",
        "current_def_ppg":
            "home_current_def_ppg"
    }
)

away_scoring_update = scoring_update.rename(
    columns={
        "team": "away_team",
        "current_off_ppg":
            "away_current_off_ppg",
        "current_def_ppg":
            "away_current_def_ppg"
    }
)

In [15]:
games = (
    games
    .merge(
        home_scoring_update,
        on="home_team",
        how="left",
        validate="many_to_one"
    )
    .merge(
        away_scoring_update,
        on="away_team",
        how="left",
        validate="many_to_one"
    )
)

required_scoring_columns = [
    "home_current_off_ppg",
    "home_current_def_ppg",
    "away_current_off_ppg",
    "away_current_def_ppg"
]

assert games[
    required_scoring_columns
].notna().all().all()

games["raw_home_score"] = (
    games["home_current_off_ppg"]
    + games["away_current_def_ppg"]
) / 2

games["raw_away_score"] = (
    games["away_current_off_ppg"]
    + games["home_current_def_ppg"]
) / 2

games["projected_total"] = (
    games["raw_home_score"]
    + games["raw_away_score"]
)

games["projected_home_score"] = (
    games["projected_total"]
    + games["expected_home_margin"]
) / 2

games["projected_away_score"] = (
    games["projected_total"]
    - games["expected_home_margin"]
) / 2


assert games["projected_total"].notna().all()

assert np.allclose(
    games["projected_home_score"]
    - games["projected_away_score"],
    games["expected_home_margin"]
)

assert np.allclose(
    games["projected_home_score"]
    + games["projected_away_score"],
    games["projected_total"]
)


display(
    games[
        [
            "away_team",
            "home_team",
            "away_current_off_ppg",
            "home_current_def_ppg",
            "home_current_off_ppg",
            "away_current_def_ppg",
            "projected_away_score",
            "projected_home_score",
            "projected_total",
            "expected_home_margin"
        ]
    ].round(2)
)

,away_team,home_team,away_current_off_ppg,home_current_def_ppg,home_current_off_ppg,away_current_def_ppg,projected_away_score,projected_home_score,projected_total,expected_home_margin
0,NE,CHI,23.05,21.83,24.22,20.41,22.37,22.39,44.75,0.02
1,CIN,BAL,24.97,22.74,25.17,23.09,23.08,24.91,47.98,1.83
2,CLE,TEN,18.65,22.83,16.78,21.69,20.98,19.00,39.97,-1.98
3,DEN,ARI,21.43,26.69,21.74,20.72,26.14,19.15,45.29,-6.98
4,GB,DET,21.98,26.77,29.25,21.58,23.04,26.75,49.79,3.72
5,IND,MIN,24.22,17.42,22.08,25.76,18.46,26.28,44.74,7.82
6,KC,SEA,25.27,20.84,24.64,19.33,21.56,23.48,45.04,1.92
7,LA,LV,23.82,25.44,23.92,22.43,25.83,21.98,47.81,-3.85
8,MIA,NYJ,18.24,22.30,19.45,25.08,20.38,22.15,42.53,1.77
9,NYG,HOU,21.62,22.30,23.18,23.69,17.83,27.56,45.39,9.73
10,PIT,NO,22.59,26.62,23.39,21.91,25.24,22.02,47.26,-3.22
11,SF,ATL,27.15,24.62,22.99,20.07,25.94,21.48,47.42,-4.46
12,TB,CAR,21.39,24.13,24.91,23.05,23.14,23.60,46.74,0.46
13,DAL,PHI,24.98,22.53,20.10,25.55,23.24,23.34,46.58,0.09

# Market Comparison

nflverse uses positive `spread_line` for a home favorite and negative for an away favorite. The values below are converted to standard sportsbook notation.

Market information is used only after the model projections have been completed.

In [16]:
games["home_spread"] = -games["spread_line"]
games["away_spread"] = games["spread_line"]

games["model_home_spread"] = -games["expected_home_margin"]
games["model_away_spread"] = games["expected_home_margin"]

games["home_ats_edge"] = (
    games["home_spread"]
    - games["model_home_spread"]
)

games["away_ats_edge"] = (
    games["away_spread"]
    - games["model_away_spread"]
)

games["ats_pick"] = np.where(
    games["home_ats_edge"] > games["away_ats_edge"],
    games["home_team"],
    np.where(
        games["away_ats_edge"] > games["home_ats_edge"],
        games["away_team"],
        "PUSH"
    )
)

games["ats_difference"] = (
    games[["home_ats_edge", "away_ats_edge"]]
    .max(axis=1)
)

games["total_difference_signed"] = (
    games["projected_total"]
    - games["total_line"]
)

games["total_difference"] = (
    games["total_difference_signed"].abs()
)

games["total_pick"] = np.where(
    games["total_difference_signed"] > 0,
    "OVER",
    np.where(
        games["total_difference_signed"] < 0,
        "UNDER",
        "PUSH"
    )
)

## Unit Sizing

Unit sizes are assigned from the model's edge over the market.

ATS and totals use separate thresholds because the totals model is newer and requires a larger edge before qualifying as a play.

These units do not change any projections or picks. They provide a consistent way to track performance by model confidence.

In [17]:
def assign_ats_units(edge):
    if pd.isna(edge) or edge < 1.0:
        return 0.0
    elif edge < 2.0:
        return 0.5
    elif edge < 3.0:
        return 1.0
    elif edge < 4.0:
        return 1.5
    else:
        return 2.0


def assign_total_units(edge):
    if pd.isna(edge) or edge < 2.0:
        return 0.0
    elif edge < 3.5:
        return 0.5
    elif edge < 5.0:
        return 1.0
    elif edge < 7.0:
        return 1.5
    else:
        return 2.0


games["ats_units"] = games["ats_difference"].apply(assign_ats_units)

games["total_units"] = games["total_difference"].apply(assign_total_units)


games[
    [
        "away_team",
        "home_team",
        "ats_pick",
        "ats_difference",
        "ats_units",
        "total_pick",
        "total_difference",
        "total_units"
    ]
]

,away_team,home_team,ats_pick,ats_difference,ats_units,total_pick,total_difference,total_units
0,NE,CHI,NE,2.980857,1.0,UNDER,5.747391,1.5
1,CIN,BAL,CIN,1.168978,0.5,UNDER,3.515203,1.0
2,CLE,TEN,CLE,0.481862,0.0,OVER,1.473405,0.0
3,DEN,ARI,DEN,2.482459,1.0,OVER,1.790074,0.0
4,GB,DET,DET,0.717024,0.0,UNDER,3.708620,1.0
5,IND,MIN,MIN,1.319130,0.5,OVER,3.236355,0.5
6,KC,SEA,KC,0.579814,0.0,OVER,2.541746,0.5
7,LA,LV,LV,0.653317,0.0,OVER,0.305070,0.0
8,MIA,NYJ,MIA,2.725805,1.0,OVER,4.033601,1.0
9,NYG,HOU,NYG,0.270630,0.0,OVER,2.892479,0.5
10,PIT,NO,NO,0.277853,0.0,OVER,2.758908,0.5
11,SF,ATL,SF,0.963408,0.0,UNDER,3.084351,0.5
12,TB,CAR,TB,3.039742,1.5,OVER,2.237177,0.5
13,DAL,PHI,PHI,4.594435,2.0,OVER,2.079276,0.5

# Display Helpers

In [18]:
def format_spread(team, line):
    if pd.isna(line):
        return "N/A"
    if line > 0:
        return f"{team} +{line:.1f}"
    return f"{team} {line:.1f}"

def model_spread_display(row):
    if row["model_home_spread"] < 0:
        return format_spread(row["home_team"], row["model_home_spread"])
    if row["model_away_spread"] < 0:
        return format_spread(row["away_team"], row["model_away_spread"])
    return "PICK"

def market_spread_display(row):
    if pd.isna(row["spread_line"]):
        return "N/A"
    if row["home_spread"] < 0:
        return format_spread(row["home_team"], row["home_spread"])
    if row["away_spread"] < 0:
        return format_spread(row["away_team"], row["away_spread"])
    return "PICK"

def ats_pick_display(row):
    if row["ats_pick"] == "PUSH":
        return "PUSH"
    if row["ats_pick"] == row["home_team"]:
        return format_spread(row["home_team"], row["home_spread"])
    return format_spread(row["away_team"], row["away_spread"])

games["projected_score"] = (
    games["away_team"]
    + " "
    + games["projected_away_score"].round(1).astype(str)
    + " - "
    + games["home_team"]
    + " "
    + games["projected_home_score"].round(1).astype(str)
)

games["model_spread_display"] = games.apply(
    model_spread_display, axis=1
)

games["market_spread_display"] = games.apply(
    market_spread_display, axis=1
)

games["ats_pick_display"] = games.apply(
    ats_pick_display, axis=1
)

# Final Week Projection Board

In [ ]:
projection_board = pd.DataFrame({
    "Matchup": games["away_team"] + " @ " + games["home_team"],
    "Projected Score": games["projected_score"],
    "SU Pick": games["predicted_winner"],
    "Win Prob": games["predicted_win_probability"],
    "Model Spread": games["model_spread_display"],
    "Market Spread": games["market_spread_display"],
    "ATS Pick": games["ats_pick_display"],
    "ATS Diff": games["ats_difference"],
    "ATS Units": games["ats_units"].map(lambda x: f"{x:.1f}"),
    "Model Total": games["projected_total"],
    "Market Total": games["total_line"],
    "O/U Pick": games["total_pick"],
    "Total Diff": games["total_difference"],
    "Total Units": games["total_units"].map(lambda x: f"{x:.1f}"),
    "Preseason Margin": games["preseason_expected_home_margin"],
    "Weekly Margin": games["expected_home_margin"],
    "Margin Change": games["margin_change_from_preseason"]
})

projection_display = projection_board.copy()

projection_csv_path = (
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_projections.csv"
)

if projection_csv_path.exists():
    previous_board = pd.read_csv(projection_csv_path)

    current_matchups = set(projection_display["Matchup"])

    frozen_board = previous_board.loc[
        ~previous_board["Matchup"].isin(current_matchups)
    ].copy()

    projection_display = pd.concat(
        [frozen_board, projection_display],
        ignore_index=True
    )

assert projection_display["Matchup"].is_unique, (
    "Duplicate matchups found in projection board."
)

display_board = projection_display.copy()

numeric_columns = [
    "Win Prob",
    "ATS Diff",
    "ATS Units",
    "Model Total",
    "Market Total",
    "Total Diff",
    "Total Units",
    "Preseason Margin",
    "Weekly Margin",
    "Margin Change"
]

for col in numeric_columns:
    display_board[col] = pd.to_numeric(
        display_board[col],
        errors="raise"
    )


PUBLIC_EXCLUSIONS = {
    6: ["CAR @ PHI"]
}

excluded_matchups = PUBLIC_EXCLUSIONS.get(
    TARGET_WEEK, []
)

public_display_board = display_board.loc[
    ~display_board["Matchup"].isin(excluded_matchups)
].copy()

print(
    f"Week {TARGET_WEEK} Public Projection Board "
    f"({len(public_display_board)} displayed games)"
)

display(
    public_display_board.style.format({
        "Win Prob": "{:.3f}",
        "ATS Diff": "{:.2f}",
        "ATS Units": "{:.1f}",
        "Model Total": "{:.1f}",
        "Market Total": "{:.1f}",
        "Total Diff": "{:.1f}",
        "Total Units": "{:.1f}",
        "Preseason Margin": "{:.2f}",
        "Weekly Margin": "{:.2f}",
        "Margin Change": "{:+.2f}"
    }).hide(axis="index")
)

Week 7 Public Projection Board (14 displayed games)

# Biggest Model vs Market Differences

In [20]:
biggest_ats_differences = (
    projection_board[
        [
            "Matchup",
            "Projected Score",
            "Model Spread",
            "Market Spread",
            "ATS Pick",
            "ATS Diff"
        ]
    ]
    .sort_values("ATS Diff", ascending=False)
    .head(5)
    .copy()
)

biggest_total_differences = (
    projection_board[
        [
            "Matchup",
            "Projected Score",
            "Model Total",
            "Market Total",
            "O/U Pick",
            "Total Diff"
        ]
    ]
    .sort_values("Total Diff", ascending=False)
    .head(5)
    .copy()
)

print("BIGGEST ATS DIFFERENCES")
display(biggest_ats_differences.round(2))

print()
print("BIGGEST TOTAL DIFFERENCES")
display(biggest_total_differences.round(2))

BIGGEST ATS DIFFERENCES

,Matchup,Projected Score,Model Spread,Market Spread,ATS Pick,ATS Diff
13,DAL @ PHI,DAL 23.2 - PHI 23.3,PHI -0.1,DAL -4.5,PHI +4.5,4.59
12,TB @ CAR,TB 23.1 - CAR 23.6,CAR -0.5,CAR -3.5,TB +3.5,3.04
0,NE @ CHI,NE 22.4 - CHI 22.4,CHI -0.0,CHI -3.0,NE +3.0,2.98
8,MIA @ NYJ,MIA 20.4 - NYJ 22.2,NYJ -1.8,NYJ -4.5,MIA +4.5,2.73
3,DEN @ ARI,DEN 26.1 - ARI 19.2,DEN -7.0,DEN -4.5,DEN -4.5,2.48

BIGGEST TOTAL DIFFERENCES

,Matchup,Projected Score,Model Total,Market Total,O/U Pick,Total Diff
0,NE @ CHI,NE 22.4 - CHI 22.4,44.75,50.5,UNDER,5.75
8,MIA @ NYJ,MIA 20.4 - NYJ 22.2,42.53,38.5,OVER,4.03
4,GB @ DET,GB 23.0 - DET 26.8,49.79,53.5,UNDER,3.71
1,CIN @ BAL,CIN 23.1 - BAL 24.9,47.98,51.5,UNDER,3.52
5,IND @ MIN,IND 18.5 - MIN 26.3,44.74,41.5,OVER,3.24

In [21]:
biggest_ats_differences["ATS Diff"] = (
    biggest_ats_differences["ATS Diff"].round(2)
)

biggest_total_differences["Model Total"] = (
    biggest_total_differences["Model Total"].round(1)
)

biggest_total_differences["Market Total"] = (
    biggest_total_differences["Market Total"].round(1)
)

biggest_total_differences["Total Diff"] = (
    biggest_total_differences["Total Diff"].round(1)
)

# Biggest Changes from the Preseason Projection

This is one of the most important weekly diagnostics. It shows which games changed most because of new in season information.

In [22]:
biggest_projection_changes = (
    projection_board[
        [
            "Matchup",
            "Preseason Margin",
            "Weekly Margin",
            "Margin Change",
            "SU Pick",
            "Win Prob"
        ]
    ]
    .assign(
        Absolute_Change=lambda x: x["Margin Change"].abs()
    )
    .sort_values("Absolute_Change", ascending=False)
    .drop(columns="Absolute_Change")
)

display(biggest_projection_changes.round(3))

,Matchup,Preseason Margin,Weekly Margin,Margin Change,SU Pick,Win Prob
5,IND @ MIN,2.973,7.819,4.846,MIN,0.709
7,LA @ LV,-8.692,-3.847,4.846,LA,0.607
8,MIA @ NYJ,-2.994,1.774,4.768,NYJ,0.550
13,DAL @ PHI,4.602,0.094,-4.507,PHI,0.503
12,TB @ CAR,-3.371,0.460,3.831,CAR,0.513
6,KC @ SEA,5.368,1.920,-3.448,SEA,0.554
11,SF @ ATL,-1.754,-4.463,-2.710,SF,0.623
1,CIN @ BAL,4.310,1.831,-2.479,BAL,0.551
9,NYG @ HOU,8.030,9.729,1.700,HOU,0.753
2,CLE @ TEN,-0.833,-1.982,-1.148,CLE,0.555
10,PIT @ NO,-2.100,-3.222,-1.122,PIT,0.590
3,DEN @ ARI,-6.027,-6.982,-0.955,DEN,0.689
4,GB @ DET,4.513,3.717,-0.796,DET,0.603
0,NE @ CHI,-0.199,0.019,0.218,CHI,0.501

In [23]:
biggest_projection_changes["Preseason Margin"] = (
    biggest_projection_changes["Preseason Margin"].round(2)
)

biggest_projection_changes["Weekly Margin"] = (
    biggest_projection_changes["Weekly Margin"].round(2)
)

biggest_projection_changes["Margin Change"] = (
    biggest_projection_changes["Margin Change"].round(2)
)

biggest_projection_changes["Win Prob"] = (
    biggest_projection_changes["Win Prob"].round(3)
)

# Sanity Checks

In [24]:
assert len(games) == len(target_schedule)
assert games["weekly_neutral_strength_diff"].notna().all()
assert games["expected_home_margin"].notna().all()
assert games["predicted_win_probability"].between(0.5, 1.0).all()
assert games["projected_total"].notna().all()

score_margin_check = (
    games["projected_home_score"]
    - games["projected_away_score"]
)

score_total_check = (
    games["projected_home_score"]
    + games["projected_away_score"]
)

assert np.allclose(
    score_margin_check,
    games["expected_home_margin"]
)

assert np.allclose(
    score_total_check,
    games["projected_total"]
)

print("All weekly game prediction sanity checks passed.")

All weekly game prediction sanity checks passed.

# Save Week Outputs

Everything is written only to the weekly layer.

The detailed parquet preserves all modeling fields for later evaluation. The CSV files provide the clean weekly projection board and largest model versus market differences.

In [25]:
detailed_path = (
    WEEKLY_DATA_DIR
    / f"week_{TARGET_WEEK:02d}_projections.parquet"
)

current_games = games.copy()

if detailed_path.exists():

    previous_games = pd.read_parquet(
        detailed_path
    )

    current_game_ids = set(
        current_games["game_id"]
    )

    frozen_games = previous_games[
        ~previous_games["game_id"].isin(
            current_game_ids
        )
    ].copy()

    detailed_save = pd.concat(
        [
            frozen_games,
            current_games
        ],
        ignore_index=True
    )

else:

    detailed_save = current_games.copy()


detailed_save.to_parquet(
    detailed_path,
    index=False
)

projection_save = projection_board.copy()

projection_save["ATS Units"] = games["ats_units"].values
projection_save["Total Units"] = games["total_units"].values

projection_save["Win Prob"] = (
    projection_save["Win Prob"].round(3)
)

projection_save["ATS Diff"] = (
    projection_save["ATS Diff"].round(2)
)

projection_save["ATS Units"] = (
    projection_save["ATS Units"].round(1)
)

projection_save["Model Total"] = (
    projection_save["Model Total"].round(1)
)

projection_save["Market Total"] = (
    projection_save["Market Total"].round(1)
)

projection_save["Total Diff"] = (
    projection_save["Total Diff"].round(1)
)

projection_save["Total Units"] = (
    projection_save["Total Units"].round(1)
)

projection_save["Preseason Margin"] = (
    projection_save["Preseason Margin"].round(2)
)

projection_save["Weekly Margin"] = (
    projection_save["Weekly Margin"].round(2)
)

projection_save["Margin Change"] = (
    projection_save["Margin Change"].round(2)
)

projection_csv_path = (
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_projections.csv"
)

if projection_csv_path.exists():

    previous_projections = pd.read_csv(
        projection_csv_path
    )

    current_matchups = set(
        projection_save["Matchup"]
    )

    frozen_projections = previous_projections[
        ~previous_projections["Matchup"].isin(
            current_matchups
        )
    ].copy()

    projection_save = pd.concat(
        [
            frozen_projections,
            projection_save
        ],
        ignore_index=True
    )

projection_save.to_csv(
    projection_csv_path,
    index=False
)

PUBLIC_EXCLUSIONS = {
    6: ["CAR @ PHI"]
}

excluded_matchups = PUBLIC_EXCLUSIONS.get(
    TARGET_WEEK, []
)

public_projection_save = projection_save.loc[
    ~projection_save["Matchup"].isin(excluded_matchups)
].copy()

public_projection_path = (
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_public_projections.csv"
)

public_projection_save.to_csv(
    public_projection_path,
    index=False
)

print("Public projections saved:", public_projection_path)
print("Public games:", len(public_projection_save))
print("Internal games:", len(projection_save))


biggest_ats_differences.to_csv(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_ats_differences.csv",
    index=False
)

biggest_total_differences.to_csv(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_total_differences.csv",
    index=False
)

biggest_projection_changes.to_csv(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_projection_changes.csv",
    index=False
)


print("Saved:")
print(detailed_path)
print(projection_csv_path)

print(
    f"\nTotal saved Week {TARGET_WEEK} projections: "
    f"{len(projection_save)}"
)

print(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_ats_differences.csv"
)

print(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_total_differences.csv"
)

print(
    WEEK_OUTPUT_DIR
    / f"week_{TARGET_WEEK:02d}_biggest_projection_changes.csv"
)

Public projections saved: ..\..\weekly_projections\outputs\week_07\week_07_public_projections.csv
Public games: 14
Internal games: 14
Saved:
..\..\data\processed\weekly\week_07_projections.parquet
..\..\weekly_projections\outputs\week_07\week_07_projections.csv

Total saved Week 7 projections: 14
..\..\weekly_projections\outputs\week_07\week_07_biggest_ats_differences.csv
..\..\weekly_projections\outputs\week_07\week_07_biggest_total_differences.csv
..\..\weekly_projections\outputs\week_07\week_07_biggest_projection_changes.csv

# Weekly Pipeline

For each future week, the intended order is:

`02_Weekly_Data_Update`  
→ `03_Inseason_Feature_Engineering`  
→ `04_Weekly_Team_Strength`  
→ `06_Week2_Projections`

The original preseason notebooks remain frozen throughout the season.

The next notebook will be `06_Weekly_Evaluation.ipynb`, which will compare locked weekly predictions against actual results after each week is complete.